cover:
  - platform: mqtt
    name: "Master Blinds"
    device_class: blind
    command_topic: "habc/master/command/set/state"
    set_position_topic: "habc/master/command/set/positionpct"
    position_topic: "habc/master/tele/currentpct"
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    position_open: 100
    position_closed: 0

sensor:
  platform: average
  name: Master Blinds Average Light Level
  entities:
    - sensor.left_master_blind_light_level
    - sensor.center_master_blind_light_level
    - sensor.right_master_blind_light_level
    - sensor.west_master_blind_light_level