sensor.daily_bike_distance:
  title: Daily Rides
  card:
    type: entities
    entities:
      - entity: sensor.daily_bike_distance
        name: Distance
        icon: 'mdi:map-marker-distance'
      - entity: sensor.daily_bike_duration_calc
        name: Duration
        icon: 'mdi:timer'
      - entity: sensor.daily_bike_calories
        name: Calories
        icon: 'mdi:fire'
      - entity: sensor.daily_bike_climb
        name: Climb
        icon: 'mdi:slope-uphill'
      - entity: sensor.daily_bike_rides
        name: Rides
        icon: 'mdi:bicycle'

sensor.weekly_bike_distance:
  title: Weekly Rides
  card:
    type: entities
    entities:
      - entity: sensor.weekly_bike_distance
        name: Distance
        icon: 'mdi:map-marker-distance'
      - entity: sensor.weekly_bike_duration_calc
        name: Duration
        icon: 'mdi:timer'
      - entity: sensor.weekly_bike_calories
        name: Calories
        icon: 'mdi:fire'
      - entity: sensor.weekly_bike_climb
        name: Climb
        icon: 'mdi:slope-uphill'
      - entity: sensor.weekly_bike_rides
        name: Rides
        icon: 'mdi:bicycle'

sensor.monthly_bike_distance:
  title: Monthly Rides
  card:
    type: entities
    entities:
      - entity: sensor.monthly_bike_distance
        name: Distance
        icon: 'mdi:map-marker-distance'
      - entity: sensor.monthly_bike_duration_calc
        name: Duration
        icon: 'mdi:timer'
      - entity: sensor.monthly_bike_calories
        name: Calories
        icon: 'mdi:fire'
      - entity: sensor.monthly_bike_climb
        name: Climb
        icon: 'mdi:slope-uphill'
      - entity: sensor.monthly_bike_rides
        name: Rides
        icon: 'mdi:bicycle'

sensor.yearly_bike_distance:
  title: Yearly Rides
  card:
    type: entities
    entities:
      - entity: sensor.yearly_bike_distance
        name: Distance
        icon: 'mdi:map-marker-distance'
      - entity: sensor.yearly_bike_duration_calc
        name: Duration
        icon: 'mdi:timer'
      - entity: sensor.yearly_bike_calories
        name: Calories
        icon: 'mdi:fire'
      - entity: sensor.yearly_bike_climb
        name: Climb
        icon: 'mdi:slope-uphill'
      - entity: sensor.yearly_bike_rides
        name: Rides
        icon: 'mdi:bicycle'

sensor.career_bike_distance:
  title: Career Rides
  card:
    type: entities
    entities:
      - entity: sensor.career_bike_distance
        name: Distance
        icon: 'mdi:map-marker-distance'
      - entity: sensor.career_bike_duration_calc
        name: Duration
        icon: 'mdi:timer'
      - entity: sensor.career_bike_calories
        name: Calories
        icon: 'mdi:fire'
      - entity: sensor.career_bike_climb
        name: Climb
        icon: 'mdi:slope-uphill'
      - entity: sensor.career_bike_rides
        name: Rides
        icon: 'mdi:bicycle'