sensor:
  - platform: mqtt
    name: AcuRite WS Temperature
    state_topic: rtl_433/2381/temperature_F
    unit_of_measurement: "°F"

  - platform: mqtt
    name: AcuRite WS Humidity
    state_topic: rtl_433/2381/humidity
    unit_of_measurement: "%"

  - platform: mqtt
    name: AcuRite WS Wind Direction
    state_topic: rtl_433/2381/wind_dir_deg
    unit_of_measurement: "°"

  - platform: mqtt
    name: AcuRite WS Wind Speed
    state_topic: rtl_433/2381/wind_avg_km_h
    value_template: "{{ (value | float * 0.621371) | round (1) }}"
    unit_of_measurement: "mi/h"

  - platform: mqtt
    name: AcuRite WS Cumulative Rainfall
    state_topic: rtl_433/2381/rain_in
    unit_of_measurement: "in"

  - platform: mqtt
    name: AcuRite Outside Temperature
    state_topic: rtl_433/8860/temperature_C
    unit_of_measurement: "°C"

  - platform: mqtt
    name: AcuRite Outside Humidity
    state_topic: rtl_433/8860/humidity
    unit_of_measurement: "%"

  - platform: statistics
    name: AcuRite WS Hourly Total Rain Statistics
    entity_id: sensor.acurite_ws_cumulative_rainfall
    sampling_size: 4000
    max_age:
      minutes: 60
  
  - platform: template
    sensors:
      acurite_ws_rain_last_60_minutes:
        value_template: "{{ state_attr('sensor.acurite_ws_hourly_total_rain_statistics','change') }}"

utility_meter:

  acurite_ws_rain_daily:
    source: sensor.acurite_ws_cumulative_rainfall
    cycle: daily

  acurite_ws_rain_weekly:
    source: sensor.acurite_ws_cumulative_rainfall
    cycle: weekly

  acurite_ws_rain_monthly:
    source: sensor.acurite_ws_cumulative_rainfall
    cycle: monthly

  acurite_ws_rain_yearly:
    source: sensor.acurite_ws_cumulative_rainfall
    cycle: yearly    