sensor:
  - platform: mqtt
    name: AcuRite Temperature
    state_topic: rtl_433/2381/temperature_F
    unit_of_measurement: "°F"

  - platform: mqtt
    name: AcuRite Humidity
    state_topic: rtl_433/2381/humidity
    unit_of_measurement: "%"

  - platform: mqtt
    name: AcuRite Wind Direction
    state_topic: rtl_433/2381/wind_dir_deg
    unit_of_measurement: "°"

  - platform: mqtt
    name: AcuRite Wind Speed
    state_topic: rtl_433/2381/wind_avg_km_h
    value_template: "{{ (value | float * 0.621371) | round (1) }}"
    unit_of_measurement: "mi/h"

  - platform: mqtt
    name: AcuRite Cumulative Rainfall
    state_topic: rtl_433/2381/rain_in
    unit_of_measurement: "in"

  - platform: statistics
    name: AcuRite Hourly Total Rain Statistics
    entity_id: sensor.acurite_cumulative_rainfall
    sampling_size: 4000
    max_age:
      minutes: 60
  
  - platform: template
    sensors:
      acurite_rain_last_60_minutes:
        value_template: "{{ state_attr('sensor.acurite_hourly_total_rain_statistics','change') }}"

utility_meter:

  acurite_rain_daily:
    source: sensor.acurite_cumulative_rainfall
    cycle: daily

  acurite_rain_weekly:
    source: sensor.acurite_cumulative_rainfall
    cycle: weekly

  acurite_rain_monthly:
    source: sensor.acurite_cumulative_rainfall
    cycle: monthly

  acurite_rain_yearly:
    source: sensor.acurite_cumulative_rainfall
    cycle: yearly    