sensor:
  - platform: dewpoint
    sensors:
      dewpoint_outside:
        temperature: sensor.acurite_outside_temperature
        rel_hum: sensor.acurite_outside_humidity

  - platform: template
    sensors:
      pws_url:
        value_template: !secret pws_url

      press_in:
        unit_of_measurement: in
        value_template: "{{ (states('sensor.aquara_den_pressure') | float * 0.02953) | round(2) }}"

      sunlight_pct:
        value_template: >-
          {%- set elevation = state_attr('sun.sun','elevation') | float %}
          {%- set cloud_coverage = states('sensor.dark_sky_cloud_coverage') | float %}
          {%- set cloud_factor = (1 - (0.75 * ( cloud_coverage / 100) ** 3 )) %}
          {%- set min_elevation = -6 %}
          {%- set max_elevation = 90 %}
          {%- set adjusted_elevation = elevation - min_elevation %}
          {%- set adjusted_elevation = [adjusted_elevation,0] | max %}
          {%- set adjusted_elevation = [adjusted_elevation,max_elevation - min_elevation] | min %}
          {%- set adjusted_elevation = adjusted_elevation / (max_elevation - min_elevation) %}
          {%- set adjusted_elevation = adjusted_elevation %}
          {%- set adjusted_elevation = adjusted_elevation * 100 %}
          {%- set brightness = adjusted_elevation * cloud_factor %}
          {{ brightness | round }}
        unit_of_measurement: "%"
        device_class: "illuminance"

      weather_description:
        value_template: >-
          {% if is_state('input_boolean.is_raining','on') -%}
            Rain now.  {{ states('sensor.dark_sky_daily_summary') }}
          {% else -%}
            {{ states('sensor.dark_sky_daily_summary') }}
          {% endif -%}

      clean_precip_intensity:
        value_template: "{{ states('sensor.dark_sky_precip_intensity') | round(2) }}"

  # Darksky
  - platform: darksky
    api_key: !secret ds_key
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility

  - platform: mqtt
    name: Bear Creek Elevation
    state_topic: "hcfws/elevation"
    unit_of_measurement: "ft"
  - platform: mqtt
    name: Bear Creek Rain This Hour
    state_topic: "hcfws/rain/current"
    unit_of_measurement: "in"
  - platform: mqtt
    name: Bear Creek Rain Last Hour
    state_topic: "hcfws/rain/last"
    unit_of_measurement: "in"

  #OpenWeatherMap
  - platform: mqtt
    name: OpenWeatherMap Current Icon
    state_topic: openweathermap
    value_template: "{{value_json['current'].icon }}"
  - platform: mqtt
    name: OpenWeatherMap Current Summary
    state_topic: openweathermap
    value_template: "{{value_json['current'].summary }}"
  - platform: mqtt
    name: OpenWeatherMap Current Temperature
    state_topic: openweathermap
    value_template: "{{value_json['current'].temperature }}"
    unit_of_measurement: "°F"
  - platform: mqtt
    name: OpenWeatherMap Current Visibility
    state_topic: openweathermap
    value_template: "{{value_json['current'].visibility }}"
    unit_of_measurement: "mi"
  - platform: mqtt
    name: OpenWeatherMap Current Maximum Temperature
    state_topic: openweathermap
    value_template: "{{value_json['current'].maxtemp }}"
    unit_of_measurement: "°F"
  - platform: mqtt
    name: OpenWeatherMap Current Minimum Temperature
    state_topic: openweathermap
    value_template: "{{value_json['current'].mintemp }}"
    unit_of_measurement: "°F"  
  - platform: mqtt
    name: OpenWeatherMap Current Wind Bearing
    state_topic: openweathermap
    value_template: "{{value_json['current'].wind_dir }}"
    unit_of_measurement: "°"
  - platform: mqtt
    name: OpenWeatherMap Current Wind Speed
    state_topic: openweathermap
    value_template: "{{value_json['current'].wind_spd }}"
    unit_of_measurement: "mi/h"
  - platform: mqtt
    name: OpenWeatherMap Current Wind Gust
    state_topic: openweathermap
    value_template: "{{value_json['current'].wind_gust }}"
    unit_of_measurement: "mi/h"
  - platform: mqtt
    name: OpenWeatherMap Current Humidity
    state_topic: openweathermap
    value_template: "{{value_json['current'].humidity }}"
    unit_of_measurement: "%"
  - platform: mqtt
    name: OpenWeatherMap Current Pressure
    state_topic: openweathermap
    value_template: "{{value_json['current'].pressure }}"
    unit_of_measurement: "hPa"
  - platform: mqtt
    name: OpenWeatherMap Current Apparent Temperature
    state_topic: openweathermap
    value_template: "{{value_json['current'].apparent }}"
    unit_of_measurement: "°F"
  - platform: mqtt
    name: OpenWeatherMap Current POP
    state_topic: openweathermap
    value_template: "{{value_json['current'].precip_chance }}"
    unit_of_measurement: "%"
  - platform: mqtt
    name: OpenWeatherMap Current Precip Forecast
    state_topic: openweathermap
    value_template: "{{value_json['current'].precip_forecast }}"
    unit_of_measurement: "in"
  - platform: mqtt
    name: OpenWeatherMap Current UV Index
    state_topic: openweathermap
    value_template: "{{value_json['current'].uv_index }}"
  - platform: mqtt
    name: OpenWeatherMap Day 1 Icon
    state_topic: openweathermap
    value_template: "{{value_json['day_1'].icon }}"
  - platform: mqtt
    name: OpenWeatherMap Day 1 Summary
    state_topic: openweathermap
    value_template: "{{value_json['day_1'].summary }}"
  - platform: mqtt
    name: OpenWeatherMap Day 1 Maximum Temperature
    state_topic: openweathermap
    value_template: "{{value_json['day_1'].maxtemp }}"
    unit_of_measurement: "°F"
  - platform: mqtt
    name: OpenWeatherMap Day 1 Minimum Temperature
    state_topic: openweathermap
    value_template: "{{value_json['day_1'].mintemp }}"
    unit_of_measurement: "°F"  
  - platform: mqtt
    name: OpenWeatherMap Day 1 POP
    state_topic: openweathermap
    value_template: "{{value_json['day_1'].precip_chance }}"
    unit_of_measurement: "%"
  - platform: mqtt
    name: OpenWeatherMap Day 1 Precip Forecast
    state_topic: openweathermap
    value_template: "{{value_json['day_1'].precip_forecast }}"
    unit_of_measurement: "in"
  - platform: mqtt
    name: OpenWeatherMap Day 2 Icon
    state_topic: openweathermap
    value_template: "{{value_json['day_2'].icon }}"
  - platform: mqtt
    name: OpenWeatherMap Day 2 Summary
    state_topic: openweathermap
    value_template: "{{value_json['day_2'].summary }}"
  - platform: mqtt
    name: OpenWeatherMap Day 2 Maximum Temperature
    state_topic: openweathermap
    value_template: "{{value_json['day_2'].maxtemp }}"
    unit_of_measurement: "°F"
  - platform: mqtt
    name: OpenWeatherMap Day 2 Minimum Temperature
    state_topic: openweathermap
    value_template: "{{value_json['day_2'].mintemp }}"
    unit_of_measurement: "°F"  
  - platform: mqtt
    name: OpenWeatherMap Day 2 POP
    state_topic: openweathermap
    value_template: "{{value_json['day_2'].precip_chance }}"
    unit_of_measurement: "%"
  - platform: mqtt
    name: OpenWeatherMap Day 2 Precip Forecast
    state_topic: openweathermap
    value_template: "{{value_json['day_2'].precip_forecast }}"
    unit_of_measurement: "in"
  - platform: mqtt
    name: OpenWeatherMap Day 3 Icon
    state_topic: openweathermap
    value_template: "{{value_json['day_3'].icon }}"
  - platform: mqtt
    name: OpenWeatherMap Day 3 Summary
    state_topic: openweathermap
    value_template: "{{value_json['day_3'].summary }}"
  - platform: mqtt
    name: OpenWeatherMap Day 3 Maximum Temperature
    state_topic: openweathermap
    value_template: "{{value_json['day_3'].maxtemp }}"
    unit_of_measurement: "°F"
  - platform: mqtt
    name: OpenWeatherMap Day 3 Minimum Temperature
    state_topic: openweathermap
    value_template: "{{value_json['day_3'].mintemp }}"
    unit_of_measurement: "°F"  
  - platform: mqtt
    name: OpenWeatherMap Day 3 POP
    state_topic: openweathermap
    value_template: "{{value_json['day_3'].precip_chance }}"
    unit_of_measurement: "%"
  - platform: mqtt
    name: OpenWeatherMap Day 3 Precip Forecast
    state_topic: openweathermap
    value_template: "{{value_json['day_3'].precip_forecast }}"
    unit_of_measurement: "in"
  - platform: mqtt
    name: OpenWeatherMap Day 4 Icon
    state_topic: openweathermap
    value_template: "{{value_json['day_4'].icon }}"
  - platform: mqtt
    name: OpenWeatherMap Day 4 Summary
    state_topic: openweathermap
    value_template: "{{value_json['day_4'].summary }}"
  - platform: mqtt
    name: OpenWeatherMap Day 4 Maximum Temperature
    state_topic: openweathermap
    value_template: "{{value_json['day_4'].maxtemp }}"
    unit_of_measurement: "°F"
  - platform: mqtt
    name: OpenWeatherMap Day 4 Minimum Temperature
    state_topic: openweathermap
    value_template: "{{value_json['day_4'].mintemp }}"
    unit_of_measurement: "°F"  
  - platform: mqtt
    name: OpenWeatherMap Day 4 POP
    state_topic: openweathermap
    value_template: "{{value_json['day_4'].precip_chance }}"
    unit_of_measurement: "%"
  - platform: mqtt
    name: OpenWeatherMap Day 4 Precip Forecast
    state_topic: openweathermap
    value_template: "{{value_json['day_4'].precip_forecast }}"
    unit_of_measurement: "in"
  - platform: mqtt
    name: OpenWeatherMap Day 5 Icon
    state_topic: openweathermap
    value_template: "{{value_json['day_5'].icon }}"
  - platform: mqtt
    name: OpenWeatherMap Day 5 Summary
    state_topic: openweathermap
    value_template: "{{value_json['day_5'].summary }}"
  - platform: mqtt
    name: OpenWeatherMap Day 5 Maximum Temperature
    state_topic: openweathermap
    value_template: "{{value_json['day_5'].maxtemp }}"
    unit_of_measurement: "°F"
  - platform: mqtt
    name: OpenWeatherMap Day 5 Minimum Temperature
    state_topic: openweathermap
    value_template: "{{value_json['day_5'].mintemp }}"
    unit_of_measurement: "°F"  
  - platform: mqtt
    name: OpenWeatherMap Day 5 POP
    state_topic: openweathermap
    value_template: "{{value_json['day_5'].precip_chance }}"
    unit_of_measurement: "%"
  - platform: mqtt
    name: OpenWeatherMap Day 5 Precip Forecast
    state_topic: openweathermap
    value_template: "{{value_json['day_5'].precip_forecast }}"
    unit_of_measurement: "in"

rest_command:
  update_wunderground:
    url: "{{ states('sensor.pws_url') }}tempf={{ states('sensor.acurite_outside_temperature') }}&humidity={{ states('sensor.acurite_outside_humidity') }}&dewptf={{ states('sensor.dewpoint_outside') }}&baromin={{ states('sensor.press_in') }}&rainin={{ states('sensor.rain_rate') }}&dailyrainin={{ states('sensor.rain_day') }}&action=updateraw"

input_boolean:
  is_raining:
    name: Currently Raining
