counter:
  rain_minute:
    step: 1
  rain_hour:
    step: 1
  rain_day:
    step: 1
  rain_week:
    step: 1
  rain_month:
    step: 1
  rain_year:
    step: 1
  rain_total:
    step: 1
  rain_month_1:
    step: 1
  rain_month_2:
    step: 1
  rain_month_3:
    step: 1
  rain_month_4:
    step: 1
  rain_month_5:
    step: 1
  rain_month_6:
    step: 1
  rain_month_7:
    step: 1
  rain_month_8:
    step: 1
  rain_month_9:
    step: 1
  rain_month_10:
    step: 1
  rain_month_11:
    step: 1
  rain_month_12:
    step: 1

sensor:
  - platform: template
    sensors:
      rain_minute:
        value_template: "{{ (states('counter.rain_minute') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_hour:
        value_template: "{{ (states('counter.rain_hour') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_day:
        value_template: "{{ (states('counter.rain_day') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_week:
        value_template: "{{ (states('counter.rain_week') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_month:
        value_template: "{{ (states('counter.rain_month') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_month_1:
        value_template: "{{ (states('counter.rain_month_1') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_month_2:
        value_template: "{{ (states('counter.rain_month_2') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_month_3:
        value_template: "{{ (states('counter.rain_month_3') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_month_4:
        value_template: "{{ (states('counter.rain_month_4') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_month_5:
        value_template: "{{ (states('counter.rain_month_5') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_month_6:
        value_template: "{{ (states('counter.rain_month_6') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_month_7:
        value_template: "{{ (states('counter.rain_month_7') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_month_8:
        value_template: "{{ (states('counter.rain_month_8') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_month_9:
        value_template: "{{ (states('counter.rain_month_9') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_month_10:
        value_template: "{{ (states('counter.rain_month_10') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_month_11:
        value_template: "{{ (states('counter.rain_month_11') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_month_12:
        value_template: "{{ (states('counter.rain_month_12') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_year:
        value_template: "{{ (states('counter.rain_year') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_total:
        value_template: "{{ (states('counter.rain_total') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_minute:
        value_template: "{{ (states('input_number.rain_last_minute') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_hour:
        value_template: "{{ (states('input_number.rain_last_hour') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_day:
        value_template: "{{ (states('input_number.rain_last_day') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_week:
        value_template: "{{ (states('input_number.rain_last_week') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_month:
        value_template: "{{ (states('input_number.rain_last_month') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_month_1:
        value_template: "{{ (states('input_number.rain_last_month_1') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_month_2:
        value_template: "{{ (states('input_number.rain_last_month_2') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_month_3:
        value_template: "{{ (states('input_number.rain_last_month_3') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_month_4:
        value_template: "{{ (states('input_number.rain_last_month_4') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_month_5:
        value_template: "{{ (states('input_number.rain_last_month_5') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_month_6:
        value_template: "{{ (states('input_number.rain_last_month_6') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_month_7:
        value_template: "{{ (states('input_number.rain_last_month_7') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_month_8:
        value_template: "{{ (states('input_number.rain_last_month_8') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_month_9:
        value_template: "{{ (states('input_number.rain_last_month_9') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_month_10:
        value_template: "{{ (states('input_number.rain_last_month_10') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_month_11:
        value_template: "{{ (states('input_number.rain_last_month_11') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_month_12:
        value_template: "{{ (states('input_number.rain_last_month_12') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"

      rain_last_year:
        value_template: "{{ (states('input_number.rain_last_year') |int(none) / 100) | round(2, default=none) }}"
        unit_of_measurement: "in"


      rain_rate:
        value_template: >
          {{ (states('input_number.rain_minute_00') | float(none) +
             states('input_number.rain_minute_01') | float(none) +
             states('input_number.rain_minute_02') | float(none) +
             states('input_number.rain_minute_03') | float(none) +
             states('input_number.rain_minute_04') | float(none) +
             states('input_number.rain_minute_05') | float(none) +
             states('input_number.rain_minute_06') | float(none) +
             states('input_number.rain_minute_07') | float(none) +
             states('input_number.rain_minute_08') | float(none) +
             states('input_number.rain_minute_09') | float(none) +
             states('input_number.rain_minute_10') | float(none) +
             states('input_number.rain_minute_11') | float(none) +
             states('input_number.rain_minute_12') | float(none) +
             states('input_number.rain_minute_13') | float(none) +
             states('input_number.rain_minute_14') | float(none) +
             states('input_number.rain_minute_15') | float(none) +
             states('input_number.rain_minute_16') | float(none) +
             states('input_number.rain_minute_17') | float(none) +
             states('input_number.rain_minute_18') | float(none) +
             states('input_number.rain_minute_19') | float(none) +
             states('input_number.rain_minute_20') | float(none) +
             states('input_number.rain_minute_21') | float(none) +
             states('input_number.rain_minute_22') | float(none) +
             states('input_number.rain_minute_23') | float(none) +
             states('input_number.rain_minute_24') | float(none) +
             states('input_number.rain_minute_25') | float(none) +
             states('input_number.rain_minute_26') | float(none) +
             states('input_number.rain_minute_27') | float(none) +
             states('input_number.rain_minute_28') | float(none) +
             states('input_number.rain_minute_29') | float(none) +
             states('input_number.rain_minute_30') | float(none) +
             states('input_number.rain_minute_31') | float(none) +
             states('input_number.rain_minute_32') | float(none) +
             states('input_number.rain_minute_33') | float(none) +
             states('input_number.rain_minute_34') | float(none) +
             states('input_number.rain_minute_35') | float(none) +
             states('input_number.rain_minute_36') | float(none) +
             states('input_number.rain_minute_37') | float(none) +
             states('input_number.rain_minute_38') | float(none) +
             states('input_number.rain_minute_39') | float(none) +
             states('input_number.rain_minute_40') | float(none) +
             states('input_number.rain_minute_41') | float(none) +
             states('input_number.rain_minute_42') | float(none) +
             states('input_number.rain_minute_43') | float(none) +
             states('input_number.rain_minute_44') | float(none) +
             states('input_number.rain_minute_45') | float(none) +
             states('input_number.rain_minute_46') | float(none) +
             states('input_number.rain_minute_47') | float(none) +
             states('input_number.rain_minute_48') | float(none) +
             states('input_number.rain_minute_49') | float(none) +
             states('input_number.rain_minute_50') | float(none) +
             states('input_number.rain_minute_51') | float(none) +
             states('input_number.rain_minute_52') | float(none) +
             states('input_number.rain_minute_53') | float(none) +
             states('input_number.rain_minute_54') | float(none) +
             states('input_number.rain_minute_55') | float(none) +
             states('input_number.rain_minute_56') | float(none) +
             states('input_number.rain_minute_57') | float(none) +
             states('input_number.rain_minute_58') | float(none) +
             states('input_number.rain_minute_59') | float) | round(2, default=none) }}
        unit_of_measurement: "in/hr"

input_number:
  rain_minute_00:
    min: 0
    max: 100
    mode: box

  rain_minute_01:
    min: 0
    max: 100
    mode: box

  rain_minute_02:
    min: 0
    max: 100
    mode: box

  rain_minute_03:
    min: 0
    max: 100
    mode: box

  rain_minute_04:
    min: 0
    max: 100
    mode: box

  rain_minute_05:
    min: 0
    max: 100
    mode: box

  rain_minute_06:
    min: 0
    max: 100
    mode: box

  rain_minute_07:
    min: 0
    max: 100
    mode: box

  rain_minute_08:
    min: 0
    max: 100
    mode: box

  rain_minute_09:
    min: 0
    max: 100
    mode: box

  rain_minute_10:
    min: 0
    max: 100
    mode: box

  rain_minute_11:
    min: 0
    max: 100
    mode: box

  rain_minute_12:
    min: 0
    max: 100
    mode: box

  rain_minute_13:
    min: 0
    max: 100
    mode: box

  rain_minute_14:
    min: 0
    max: 100
    mode: box

  rain_minute_15:
    min: 0
    max: 100
    mode: box

  rain_minute_16:
    min: 0
    max: 100
    mode: box

  rain_minute_17:
    min: 0
    max: 100
    mode: box

  rain_minute_18:
    min: 0
    max: 100
    mode: box

  rain_minute_19:
    min: 0
    max: 100
    mode: box

  rain_minute_20:
    min: 0
    max: 100
    mode: box

  rain_minute_21:
    min: 0
    max: 100
    mode: box

  rain_minute_22:
    min: 0
    max: 100
    mode: box

  rain_minute_23:
    min: 0
    max: 100
    mode: box

  rain_minute_24:
    min: 0
    max: 100
    mode: box

  rain_minute_25:
    min: 0
    max: 100
    mode: box

  rain_minute_26:
    min: 0
    max: 100
    mode: box

  rain_minute_27:
    min: 0
    max: 100
    mode: box

  rain_minute_28:
    min: 0
    max: 100
    mode: box

  rain_minute_29:
    min: 0
    max: 100
    mode: box

  rain_minute_30:
    min: 0
    max: 100
    mode: box

  rain_minute_31:
    min: 0
    max: 100
    mode: box

  rain_minute_32:
    min: 0
    max: 100
    mode: box

  rain_minute_33:
    min: 0
    max: 100
    mode: box

  rain_minute_34:
    min: 0
    max: 100
    mode: box

  rain_minute_35:
    min: 0
    max: 100
    mode: box

  rain_minute_36:
    min: 0
    max: 100
    mode: box

  rain_minute_37:
    min: 0
    max: 100
    mode: box

  rain_minute_38:
    min: 0
    max: 100
    mode: box

  rain_minute_39:
    min: 0
    max: 100
    mode: box

  rain_minute_40:
    min: 0
    max: 100
    mode: box

  rain_minute_41:
    min: 0
    max: 100
    mode: box

  rain_minute_42:
    min: 0
    max: 100
    mode: box

  rain_minute_43:
    min: 0
    max: 100
    mode: box

  rain_minute_44:
    min: 0
    max: 100
    mode: box

  rain_minute_45:
    min: 0
    max: 100
    mode: box

  rain_minute_46:
    min: 0
    max: 100
    mode: box

  rain_minute_47:
    min: 0
    max: 100
    mode: box

  rain_minute_48:
    min: 0
    max: 100
    mode: box

  rain_minute_49:
    min: 0
    max: 100
    mode: box

  rain_minute_50:
    min: 0
    max: 100
    mode: box

  rain_minute_51:
    min: 0
    max: 100
    mode: box

  rain_minute_52:
    min: 0
    max: 100
    mode: box

  rain_minute_53:
    min: 0
    max: 100
    mode: box

  rain_minute_54:
    min: 0
    max: 100
    mode: box

  rain_minute_55:
    min: 0
    max: 100
    mode: box

  rain_minute_56:
    min: 0
    max: 100
    mode: box

  rain_minute_57:
    min: 0
    max: 100
    mode: box

  rain_minute_58:
    min: 0
    max: 100
    mode: box

  rain_minute_59:
    min: 0
    max: 100
    mode: box

  rain_last_minute:
    min: 0
    max: 100000
    mode: box
  rain_last_hour:
    min: 0
    max: 100000
    mode: box
  rain_last_day:
    min: 0
    max: 100000
    mode: box
  rain_last_week:
    min: 0
    max: 100000
    mode: box
  rain_last_month:
    min: 0
    max: 100000
    mode: box
  rain_last_year:
    min: 0
    max: 100000
    mode: box
  rain_last_month_1:
    min: 0
    max: 100000
    mode: box
  rain_last_month_2:
    min: 0
    max: 100000
    mode: box
  rain_last_month_3:
    min: 0
    max: 100000
    mode: box
  rain_last_month_4:
    min: 0
    max: 100000
    mode: box
  rain_last_month_5:
    min: 0
    max: 100000
    mode: box
  rain_last_month_6:
    min: 0
    max: 100000
    mode: box
  rain_last_month_7:
    min: 0
    max: 100000
    mode: box
  rain_last_month_8:
    min: 0
    max: 100000
    mode: box
  rain_last_month_9:
    min: 0
    max: 100000
    mode: box
  rain_last_month_10:
    min: 0
    max: 100000
    mode: box
  rain_last_month_11:
    min: 0
    max: 100000
    mode: box
  rain_last_month_12:
    min: 0
    max: 100000
    mode: box

input_text:
  last_rain:
    name: Last Rain Date