- alias: Close Blinds When Away, Going to Bed, or at Dusk
  id: d569ad60-eb9e-413c-b39b-f2e84f15ec36
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      from: arming
      to: armed_night
    - platform: state
      entity_id: alarm_control_panel.house
      from: 
        - disarmed
        - armed_home
      to: armed_night
      for: "00:01:00"
    - platform: state
      entity_id: alarm_control_panel.house
      from: arming
      to: armed_away
    - platform: state
      entity_id: alarm_control_panel.house
      from: 
        - disarmed
        - armed_home
      to: armed_away
      for: "00:01:00"
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      below: -2.5
  action:
    - service: cover.close_cover
      entity_id: cover.house_blinds
    - service: input_boolean.turn_off
      entity_id: input_boolean.blinds_manual

- alias: Open Blinds When Awake and Sun Up
  id: c2acc359-cb48-461a-bc5b-a5c6cdcd1a75
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      to: disarmed
    - platform: state
      entity_id: alarm_control_panel.house
      to: armed_home
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      above: 0
  condition:
    - condition: state
      entity_id: switch.shower_light_and_fan
      state: "off"
    - condition: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      above: 0
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: "off"
    - condition: state
      entity_id: input_boolean.blinds_manual
      state: "off"
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
  action:
    - service: cover.open_cover
      entity_id: cover.house_blinds
    - service: input_boolean.turn_on
      entity_id: input_boolean.blinds_manual

- alias: Open Blinds When Awake and Sun Up Taking Shower
  id: b8e38b8e-542b-4814-af4f-dbe145d903d2
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      to: disarmed
    - platform: state
      entity_id: alarm_control_panel.house
      to: armed_home
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      above: 0
  condition:
    - condition: state
      entity_id: switch.shower_light_and_fan
      state: "on"
    - condition: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      above: 0
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: "off"
    - condition: state
      entity_id: input_boolean.blinds_manual
      state: "off"
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
  action:
    - service: cover.open_cover
      entity_id:
        - cover.office_blinds
        - cover.guest_blind
        - cover.server_room_blind
        - cover.den_blinds
        - cover.kitchen_blinds
        - cover.shack_blinds
    - service: input_boolean.turn_on
      entity_id: input_boolean.blinds_manual

- alias: All Windows Same Position
  id: c3f72e8a-a0d0-4947-841c-c83b8ad28310
  trigger:
    - platform: state
      entity_id:
        - cover.office_blinds
        - cover.den_blinds
        - cover.kitchen_blinds
        - cover.shack_blinds
        - cover.master_blinds
        - cover.server_room_blind
        - cover.guest_blind
      from: "closed"
      to: "open"
    - platform: state
      entity_id:
        - cover.office_blinds
        - cover.den_blinds
        - cover.kitchen_blinds
        - cover.shack_blinds
        - cover.master_blinds
        - cover.server_room_blind
        - cover.guest_blind
      from: "open"
      to: "closed"
  condition:
    - condition: template
      value_template: "{{ states('cover.office_blinds') == states('cover.den_blinds') == states('cover.kitchen_blinds') == states('cover.guest_blind') == states('cover.server_room_blind') == states('cover.shack_blinds') == states('cover.master_blinds') }}"
    - condition: template
      value_template: "{{ not is_state('cover.guest_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.server_room_blind', 'unavailable') }}"
  action:
    - service: mqtt.publish
      data:
        payload_template: "{{ state_attr('cover.center_office_blind', 'current_position') }}"
        topic: habc/all/tele/currentpct
        retain: "true"

- alias: All Windows Various Positions
  id: affdddae-bb97-44fa-bc4c-821ad73b6b5e
  trigger:
    - platform: state
      entity_id:
        - cover.office_blinds
        - cover.den_blinds
        - cover.kitchen_blinds
        - cover.shack_blinds
        - cover.master_blinds
        - cover.server_room_blind
        - cover.guest_blind
      from: "closed"
      to: "open"
    - platform: state
      entity_id:
        - cover.office_blinds
        - cover.den_blinds
        - cover.kitchen_blinds
        - cover.shack_blinds
        - cover.master_blinds
        - cover.server_room_blind
        - cover.guest_blind
      from: "open"
      to: "closed"
  condition:
    - condition: template
      value_template: "{{ not states('cover.office_blinds') == states('cover.den_blinds') == states('cover.kitchen_blinds') == states('cover.guest_blind') == states('cover.server_room_blind') == states('cover.shack_blinds') == states('cover.master_blinds') }}"
    - condition: template
      value_template: "{{ not is_state('cover.guest_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.server_room_blind', 'unavailable') }}"
  action:
    - service: mqtt.publish
      data:
        payload: 95
        topic: habc/all/tele/currentpct
        retain: "true"

- alias: Open House Blinds
  id: 6be62fc0-7975-40d9-812f-3b989e7e3abf
  trigger:
    - platform: state
      entity_id: switch.house_blinds
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: cover.house_blinds
      state: "closed"
  action:
    - service: cover.open_cover
      entity_id: cover.house_blinds

- alias: Close House Blinds
  id: 9d284723-232b-4cbd-b6e2-075499825dff
  trigger:
    - platform: state
      entity_id: switch.house_blinds
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: cover.house_blinds
      state: "open"
  action:
    - service: cover.close_cover
      entity_id: cover.house_blinds

- alias: House Blinds Keypad on if any Open
  id: ea85574a-7031-4e89-b9cd-c8d36df50ad6
  trigger:
    - platform: state
      entity_id: cover.house_blinds
      from: "closed"
      to: "open"
  condition:
    - condition: state
      entity_id: switch.house_blinds
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.house_blinds

- alias: House Blinds Keypad off if all Closed
  id: 4bf53edf-1ced-49ef-ada8-f10b3c6d0139
  trigger:
    - platform: state
      entity_id: cover.house_blinds
      from: "open"
      to: "closed"
  condition:
    - condition: state
      entity_id: switch.house_blinds
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.house_blinds
