- alias: Open Den Blinds
  trigger:
    - platform: state
      entity_id: switch.den_blinds
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: cover.den_blinds
      state: 'closed'
  action:
    - service: cover.open_cover
      entity_id: cover.den_blinds

- alias: Close Den Blinds
  trigger:
    - platform: state
      entity_id: switch.den_blinds
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: cover.den_blinds
      state: 'open'
  action:
    - service: cover.close_cover
      entity_id: cover.den_blinds

- alias: Den Blind Keypad on if any Open
  trigger:
    - platform: state
      entity_id: cover.den_blinds
      from: 'closed'
      to: 'open'
  condition:
    - condition: state
      entity_id: switch.den_blinds
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.den_blinds
    

- alias: Den Blind Keypad off if all Closed
  trigger:
    - platform: state
      entity_id: cover.den_blinds
      from: 'open'
      to: 'closed'
  condition:
    - condition: state
      entity_id: switch.den_blinds
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.den_blinds

- alias: Den Windows Same Position
  trigger:
    - platform: state
      entity_id:
        - cover.center_den_blind
        - cover.right_den_blind
        - cover.left_den_blind
      from: 'closed'
      to: 'open'
    - platform: state
      entity_id:
        - cover.center_den_blind
        - cover.right_den_blind
        - cover.left_den_blind
      from: 'open'
      to: 'closed'
  condition:
    - condition: template
      value_template: "{{ states('cover.center_den_blind') == states('cover.right_den_blind') == states('cover.left_den_blind') }}"
    - condition: template
      value_template: "{{ not is_state('cover.center_den_blind', 'unavailable') }}"
    - condition: template
      value_template:  "{{ not is_state('cover.left_den_blind', 'unavailable') }}"
    - condition: template
      value_template:  "{{ not is_state('cover.right_den_blind', 'unavailable') }}"
  action:
    - service: mqtt.publish
      data:
        payload_template: "{{ state_attr('cover.center_den_blind', 'current_position') }}"
        topic: habc/den/tele/currentpct
        retain: 'true'

- alias: Den Windows Various Positions
  trigger:
    - platform: state
      entity_id:
        - cover.center_den_blind
        - cover.right_den_blind
        - cover.left_den_blind
      from: 'closed'
      to: 'open'
    - platform: state
      entity_id:
        - cover.center_den_blind
        - cover.right_den_blind
        - cover.left_den_blind
      from: 'open'
      to: 'closed'
  condition:
    - condition: template
      value_template: "{{ not states('cover.center_den_blind') == states('cover.right_den_blind') == states('cover.left_den_blind') }}"
    - condition: template
      value_template: "{{ not is_state('cover.center_den_blind', 'unavailable') }}"
    - condition: template
      value_template:  "{{ not is_state('cover.left_den_blind', 'unavailable') }}"
    - condition: template
      value_template:  "{{ not is_state('cover.right_den_blind', 'unavailable') }}"
  action:
    - service: mqtt.publish
      data:
        payload: 95
        topic: habc/den/tele/currentpct
        retain: 'true'