- alias: Open Guest Blinds
  id: a07de380-2a55-413d-ae75-f245f3868548
  trigger:
    - platform: state
      entity_id: switch.guest_blinds
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: cover.guest_blind
      state: "closed"
  action:
    - service: cover.open_cover
      entity_id: cover.guest_blind

- alias: Close Guest Blinds
  id: 7853e322-9f87-42bb-a0d4-deaa557782fd
  trigger:
    - platform: state
      entity_id: switch.guest_blinds
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: cover.guest_blind
      state: "open"
  action:
    - service: cover.close_cover
      entity_id: cover.guest_blind

- alias: Guest Blind Keypad on if any Open
  id: 2c2e9135-c29d-42a4-a2b0-ce410517a1bd
  trigger:
    - platform: state
      entity_id: cover.guest_blind
      from: "closed"
      to: "open"
  condition:
    - condition: state
      entity_id: switch.guest_blinds
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.guest_blinds

- alias: Guest Blind Keypad off if all Closed
  id: 7a5aaa66-f8c9-448f-9045-945900968a05
  trigger:
    - platform: state
      entity_id: cover.guest_blind
      from: "open"
      to: "closed"
  condition:
    - condition: state
      entity_id: switch.guest_blinds
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.guest_blinds
