- alias: Open Kitchen Blinds
  id: 16eda4ed-8827-42cf-bbd5-96882d53aebb
  trigger:
    - platform: state
      entity_id:
        - switch.kitchen_blinds
        - switch.dining_room_blinds
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: cover.kitchen_blinds
      state: "closed"
  action:
    - service: cover.open_cover
      entity_id: cover.kitchen_blinds

- alias: Close Kitchen Blinds
  id: 7feb5816-0fb0-4766-b887-041477d7a4fc
  trigger:
    - platform: state
      entity_id:
        - switch.kitchen_blinds
        - switch.dining_room_blinds
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: cover.kitchen_blinds
      state: "open"
  action:
    - service: cover.close_cover
      entity_id: cover.kitchen_blinds

- alias: Kitchen Blind Keypad on if any Open
  id: 7c2bc1f0-d7c6-4d24-9041-cf96ff29adc0
  trigger:
    - platform: state
      entity_id: cover.kitchen_blinds
      from: "closed"
      to: "open"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: switch.kitchen_blinds
          state: "off"
        - condition: state
          entity_id: switch.dining_room_blinds
          state: "off"
  action:
    - service: switch.turn_on
      entity_id:
        - switch.kitchen_blinds
        - switch.dining_room_blinds

- alias: Kitchen Blind Keypad off if all Closed
  id: aa78f13f-4081-47db-853d-6d9c49f3a018
  trigger:
    - platform: state
      entity_id: cover.kitchen_blinds
      from: "open"
      to: "closed"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: switch.kitchen_blinds
          state: "on"
        - condition: state
          entity_id: switch.dining_room_blinds
          state: "on"
  action:
    - service: switch.turn_off
      entity_id:
        - switch.kitchen_blinds
        - switch.dining_room_blinds

- alias: Kitchen Windows Same Position
  id: 2e26e804-8298-4c9d-a106-278fd6323812
  trigger:
    - platform: state
      entity_id:
        - cover.east_kitchen_blind
        - cover.right_kitchen_blind
        - cover.left_kitchen_blind
      from: "closed"
      to: "open"
    - platform: state
      entity_id:
        - cover.east_kitchen_blind
        - cover.right_kitchen_blind
        - cover.left_kitchen_blind
      from: "open"
      to: "closed"
  condition:
    - condition: template
      value_template: "{{ states('cover.east_kitchen_blind') == states('cover.right_kitchen_blind') == states('cover.left_kitchen_blind') }}"
    - condition: template
      value_template: "{{ not is_state('cover.east_kitchen_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.left_kitchen_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.right_kitchen_blind', 'unavailable') }}"
  action:
    - service: mqtt.publish
      data:
        payload_template: "{{ state_attr('cover.east_kitchen_blind', 'current_position') }}"
        topic: habc/kitchen/tele/currentpct
        retain: "true"

- alias: Kitchen Windows Various Positions
  id: 18fd4528-7036-423b-8068-ff7237c78313
  trigger:
    - platform: state
      entity_id:
        - cover.east_kitchen_blind
        - cover.right_kitchen_blind
        - cover.left_kitchen_blind
      from: "closed"
      to: "open"
    - platform: state
      entity_id:
        - cover.east_kitchen_blind
        - cover.right_kitchen_blind
        - cover.left_kitchen_blind
      from: "open"
      to: "closed"
  condition:
    - condition: template
      value_template: "{{ not states('cover.east_kitchen_blind') == states('cover.right_kitchen_blind') == states('cover.left_kitchen_blind') }}"
    - condition: template
      value_template: "{{ not is_state('cover.east_kitchen_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.left_kitchen_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.right_kitchen_blind', 'unavailable') }}"
  action:
    - service: mqtt.publish
      data:
        payload: 95
        topic: habc/kitchen/tele/currentpct
        retain: "true"
