- alias: Open Kitchen Blinds
  trigger:
    - platform: state
      entity_id: 
        - switch.kitchen_blinds
        - switch.dining_room_blinds
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: cover.kitchen_blinds
      state: 'closed'
  action:
    - service: cover.open_cover
      entity_id: cover.kitchen_blinds

- alias: Close Kitchen Blinds
  trigger:
    - platform: state
      entity_id: 
        - switch.kitchen_blinds
        - switch.dining_room_blinds
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: cover.kitchen_blinds
      state: 'open'
  action:
    - service: cover.close_cover
      entity_id: cover.kitchen_blinds

- alias: Kitchen Blind Keypad on if any Open
  trigger:
    - platform: state
      entity_id: cover.kitchen_blinds
      from: 'closed'
      to: 'open'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: switch.kitchen_blinds
        state: 'off'
      - condition: state
        entity_id: switch.dining_room_blinds
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.kitchen_blinds
        - switch.dining_room_blinds
    

- alias: Kitchen Blind Keypad off if all Closed
  trigger:
    - platform: state
      entity_id: cover.kitchen_blinds
      from: 'open'
      to: 'closed'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: switch.kitchen_blinds
        state: 'on'
      - condition: state
        entity_id: switch.dining_room_blinds
        state: 'on'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.kitchen_blinds
        - switch.dining_room_blinds

- alias: Kitchen Windows Same Position
  trigger:
    - platform: state
      entity_id:
        - cover.east_kitchen_blind
        - cover.right_kitchen_blind
        - cover.left_kitchen_blind
      from: 'closed'
      to: 'open'
    - platform: state
      entity_id:
        - cover.east_kitchen_blind
        - cover.right_kitchen_blind
        - cover.left_kitchen_blind
      from: 'open'
      to: 'closed'
  condition:
    - condition: template
      value_template: "{{ states('cover.east_kitchen_blind') == states('cover.right_kitchen_blind') == states('cover.left_kitchen_blind') }}"
    - condition: template
      value_template: "{{ not is_state('cover.east_kitchen_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.left_kitchen_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.right_kitchen_blind', 'unavailable') }}"
  action:
    - service: mqtt.publish
      data:
        payload_template: "{{ state_attr('cover.east_kitchen_blind', 'current_position') }}"
        topic: habc/kitchen/tele/currentpct
        retain: 'true'

- alias: Kitchen Windows Various Positions
  trigger:
    - platform: state
      entity_id:
        - cover.east_kitchen_blind
        - cover.right_kitchen_blind
        - cover.left_kitchen_blind
      from: 'closed'
      to: 'open'
    - platform: state
      entity_id:
        - cover.east_kitchen_blind
        - cover.right_kitchen_blind
        - cover.left_kitchen_blind
      from: 'open'
      to: 'closed'
  condition:
    - condition: template
      value_template: "{{ not states('cover.east_kitchen_blind') == states('cover.right_kitchen_blind') == states('cover.left_kitchen_blind') }}"
    - condition: template
      value_template: "{{ not is_state('cover.east_kitchen_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.left_kitchen_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.right_kitchen_blind', 'unavailable') }}"
  action:
    - service: mqtt.publish
      data:
        payload: 95
        topic: habc/kitchen/tele/currentpct
        retain: 'true'