- alias: Open Master Blinds
  trigger:
    - platform: state
      entity_id: 
        - switch.master_bedroom_blinds
        - switch.master_bathroom_blinds
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: cover.master_blinds
      state: 'closed'
  action:
    - service: cover.open_cover
      entity_id: cover.master_blinds

- alias: Close Master Blinds
  trigger:
    - platform: state
      entity_id: 
        - switch.master_bedroom_blinds
        - switch.master_bathroom_blinds
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: cover.master_blinds
      state: 'open'
  action:
    - service: cover.close_cover
      entity_id: cover.master_blinds

- alias: Master Blind Keypad on if any Open
  trigger:
    - platform: state
      entity_id: cover.master_blinds
      from: 'closed'
      to: 'open'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: switch.master_bedroom_blinds
          state: 'off'
        - condition: state
          entity_id: switch.master_bathroom_blinds
          state: 'off'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.master_bedroom_blinds
        - switch.master_bathroom_blinds
    

- alias: Master Blind Keypad off if all Closed
  trigger:
    - platform: state
      entity_id: cover.master_blinds
      from: 'open'
      to: 'closed'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: switch.master_bedroom_blinds
          state: 'on'
        - condition: state
          entity_id: switch.master_bathroom_blinds
          state: 'on'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.master_bedroom_blinds
        - switch.master_bathroom_blinds

- alias: Alexa Open Master Blinds
  trigger:
    - platform: state
      entity_id: input_boolean.master_blinds_open
      to: 'on'
  action:
    - service: cover.open_cover
      entity_id: cover.master_blinds
    - service: input_boolean.turn_off
      entity_id: input_boolean.master_blinds_open

- alias: Alexa Close Master Blinds
  trigger:
    - platform: state
      entity_id: input_boolean.master_blinds_close
      to: 'on'
  action:
    - service: cover.close_cover
      entity_id: cover.master_blinds
    - service: input_boolean.turn_off
      entity_id: input_boolean.master_blinds_close

- alias: Master Windows Same Position
  trigger:
    - platform: state
      entity_id:
        - cover.center_master_blind
        - cover.right_master_blind
        - cover.left_master_blind
        - cover.west_master_blind
      from: 'closed'
      to: 'open'
    - platform: state
      entity_id:
        - cover.center_master_blind
        - cover.right_master_blind
        - cover.left_master_blind
        - cover.west_master_blind
      from: 'open'
      to: 'closed'
  condition:
    - condition: template
      value_template: "{{ states('cover.center_master_blind') == states('cover.right_master_blind') == states('cover.left_master_blind') == states('cover.west_master_blind') }}"
    - condition: template
      value_template: "{{ not is_state('cover.center_master_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.left_master_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.right_master_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.west_master_blind', 'unavailable') }}"
  action:
    - service: mqtt.publish
      data:
        payload_template: "{{ state_attr('cover.center_master_blind', 'current_position') }}"
        topic: habc/master/tele/currentpct
        retain: 'true'

- alias: Master Windows Various Positions
  trigger:
    - platform: state
      entity_id:
        - cover.center_master_blind
        - cover.right_master_blind
        - cover.left_master_blind
        - cover.west_master_blind
      from: 'closed'
      to: 'open'
    - platform: state
      entity_id:
        - cover.center_master_blind
        - cover.right_master_blind
        - cover.left_master_blind
        - cover.west_master_blind
      from: 'open'
      to: 'closed'
  condition:
    - condition: template
      value_template: "{{ not states('cover.center_master_blind') == states('cover.right_master_blind') == states('cover.left_master_blind') == states('cover.west_master_blind') }}"
    - condition: template
      value_template: "{{ not is_state('cover.center_master_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.left_master_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.right_master_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.west_master_blind', 'unavailable') }}"
  action:
    - service: mqtt.publish
      data:
        payload: 95
        topic: habc/master/tele/currentpct
        retain: 'true'