- alias: Open Office Blinds
  trigger:
    - platform: state
      entity_id: switch.office_blinds
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: cover.office_blinds
      state: "closed"
  action:
    - service: cover.open_cover
      entity_id: cover.office_blinds

- alias: Close Office Blinds
  trigger:
    - platform: state
      entity_id: switch.office_blinds
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: cover.office_blinds
      state: "open"
  action:
    - service: cover.close_cover
      entity_id: cover.office_blinds

- alias: Office Blind Keypad on if any Open
  trigger:
    - platform: state
      entity_id: cover.office_blinds
      from: "closed"
      to: "open"
  condition:
    - condition: state
      entity_id: switch.office_blinds
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.office_blinds

- alias: Office Blind Keypad off if all Closed
  trigger:
    - platform: state
      entity_id: cover.office_blinds
      from: "open"
      to: "closed"
  condition:
    - condition: state
      entity_id: switch.office_blinds
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.office_blinds

- alias: Office Windows Same Position
  trigger:
    - platform: state
      entity_id:
        - cover.center_office_blind
        - cover.right_office_blind
        - cover.left_office_blind
      from: "closed"
      to: "open"
    - platform: state
      entity_id:
        - cover.center_office_blind
        - cover.right_office_blind
        - cover.left_office_blind
      from: "open"
      to: "closed"
  condition:
    - condition: template
      value_template: "{{ states('cover.center_office_blind') == states('cover.right_office_blind') == states('cover.left_office_blind') }}"
    - condition: template
      value_template: "{{ not is_state('cover.center_office_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.left_office_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.right_office_blind', 'unavailable') }}"
  action:
    - service: mqtt.publish
      data:
        payload_template: "{{ state_attr('cover.center_office_blind', 'current_position') }}"
        topic: habc/office/tele/currentpct
        retain: "true"

- alias: Office Windows Various Positions
  trigger:
    - platform: state
      entity_id:
        - cover.center_office_blind
        - cover.right_office_blind
        - cover.left_office_blind
      from: "closed"
      to: "open"
    - platform: state
      entity_id:
        - cover.center_office_blind
        - cover.right_office_blind
        - cover.left_office_blind
      from: "open"
      to: "closed"
  condition:
    - condition: template
      value_template: "{{ not states('cover.center_office_blind') == states('cover.right_office_blind') == states('cover.left_office_blind') }}"
    - condition: template
      value_template: "{{ not is_state('cover.center_office_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.left_office_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.right_office_blind', 'unavailable') }}"
  action:
    - service: mqtt.publish
      data:
        payload: 95
        topic: habc/office/tele/currentpct
        retain: "true"
