- alias: Open Server Blinds
  id: a0221682-6fd2-45bb-98e4-25a8cd24d96e
  trigger:
    - platform: state
      entity_id: switch.server_blinds
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: cover.server_room_blind
      state: "closed"
  action:
    - service: cover.open_cover
      entity_id: cover.server_room_blind

- alias: Close Server Blinds
  id: 1cf36418-aa86-4e84-9115-fec35478bf1d
  trigger:
    - platform: state
      entity_id: switch.server_blinds
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: cover.server_room_blind
      state: "open"
  action:
    - service: cover.close_cover
      entity_id: cover.server_room_blind

- alias: Server Blind Keypad on if any Open
  id: c9986927-13a4-467a-9fc2-5ced6642ef03
  trigger:
    - platform: state
      entity_id: cover.server_room_blind
      from: "closed"
      to: "open"
  condition:
    - condition: state
      entity_id: switch.server_blinds
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.server_blinds

- alias: Server Blind Keypad off if all Closed
  id: b211d035-1cc2-4fd1-a6a1-c6c74208c1f6
  trigger:
    - platform: state
      entity_id: cover.server_room_blind
      from: "open"
      to: "closed"
  condition:
    - condition: state
      entity_id: switch.server_blinds
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.server_blinds
