- alias: Open Server Blinds
  trigger:
    - platform: state
      entity_id: switch.server_blinds
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: cover.server_room_blind
      state: 'closed'
  action:
    - service: cover.open_cover
      entity_id: cover.server_room_blind

- alias: Close Server Blinds
  trigger:
    - platform: state
      entity_id: switch.server_blinds
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: cover.server_room_blind
      state: 'open'
  action:
    - service: cover.close_cover
      entity_id: cover.server_room_blind

- alias: Server Blind Keypad on if any Open
  trigger:
    - platform: state
      entity_id: cover.server_room_blind
      from: 'closed'
      to: 'open'
  condition:
    - condition: state
      entity_id: switch.server_room_blinds
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.server_room_blinds

- alias: Server Blind Keypad off if all Closed
  trigger:
    - platform: state
      entity_id: cover.server_room_blind
      from: 'open'
      to: 'closed'
  condition:
    - condition: state
      entity_id: switch.server_room_blinds
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.server_room_blinds