- alias: Open Shack Blinds
  id: 56f11665-d3ef-4b05-b84f-cffd21179fab
  trigger:
    - platform: state
      entity_id: switch.shack_blinds
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: cover.shack_blinds
      state: "closed"
  action:
    - service: cover.open_cover
      entity_id: cover.shack_blinds

- alias: Close Shack Blinds
  id: 7aeb2fcf-7486-4c8e-89be-79e974609d61
  trigger:
    - platform: state
      entity_id: switch.shack_blinds
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: cover.shack_blinds
      state: "open"
  action:
    - service: cover.close_cover
      entity_id: cover.shack_blinds

- alias: Shack Blind Keypad on if any Open
  id: acd1edc7-914d-488c-b477-80b588ef6d5e
  trigger:
    - platform: state
      entity_id: cover.shack_blinds
      from: "closed"
      to: "open"
  condition:
    - condition: state
      entity_id: switch.shack_blinds
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.shack_blinds

- alias: Shack Blind Keypad off if all Closed
  id: ad298385-90a6-42ad-8093-af1c5347e926
  trigger:
    - platform: state
      entity_id: cover.shack_blinds
      from: "open"
      to: "closed"
  condition:
    - condition: state
      entity_id: switch.shack_blinds
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.shack_blinds

- alias: Shack Windows Same Position
  id: e14a7ef9-4a2e-403f-a9c4-d269e585e144
  trigger:
    - platform: state
      entity_id:
        - cover.center_shack_blind
        - cover.right_shack_blind
        - cover.left_shack_blind
      from: "closed"
      to: "open"
    - platform: state
      entity_id:
        - cover.center_shack_blind
        - cover.right_shack_blind
        - cover.left_shack_blind
      from: "open"
      to: "closed"
  condition:
    - condition: template
      value_template: "{{ states('cover.center_shack_blind') == states('cover.right_shack_blind') == states('cover.left_shack_blind') }}"
    - condition: template
      value_template: "{{ not is_state('cover.center_shack_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.left_shack_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.right_shack_blind', 'unavailable') }}"
  action:
    - service: mqtt.publish
      data:
        payload_template: "{{ state_attr('cover.center_shack_blind', 'current_position') }}"
        topic: habc/shack/tele/currentpct
        retain: "true"

- alias: Shack Windows Various Positions
  id: a6ee8cb1-7ad3-4e16-b0ee-43f721359543
  trigger:
    - platform: state
      entity_id:
        - cover.center_shack_blind
        - cover.right_shack_blind
        - cover.left_shack_blind
      from: "closed"
      to: "open"
    - platform: state
      entity_id:
        - cover.center_shack_blind
        - cover.right_shack_blind
        - cover.left_shack_blind
      from: "open"
      to: "closed"
  condition:
    - condition: template
      value_template: "{{ not states('cover.center_shack_blind') == states('cover.right_shack_blind') == states('cover.left_shack_blind') }}"
    - condition: template
      value_template: "{{ not is_state('cover.center_shack_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.left_shack_blind', 'unavailable') }}"
    - condition: template
      value_template: "{{ not is_state('cover.right_shack_blind', 'unavailable') }}"
  action:
    - service: mqtt.publish
      data:
        payload: 95
        topic: habc/shack/tele/currentpct
        retain: "true"
