homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # URLs:
  internal_url: !secret internal_url
  external_url: !secret external_url
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - !secret proxy_ip

frontend:
  themes: !include_dir_merge_named themes

# Enable Lovelace yaml mode
lovelace:
  mode: yaml
  dashboards:
    lovelace-kitchen:
      mode: yaml
      filename: lovelace-kitchen.yaml
      title: Kitchen Tablet
      show_in_sidebar: false
    lovelace-office:
      mode: yaml
      filename: lovelace-office.yaml
      title: Office Tablet
      show_in_sidebar: false
    lovelace-shack:
      mode: yaml
      filename: lovelace-shack.yaml
      title: Shack Tablet
      show_in_sidebar: false
    lovelace-den:
      mode: yaml
      filename: lovelace-den.yaml
      title: Den Tablet
      show_in_sidebar: false
    lovelace-master:
      mode: yaml
      filename: lovelace-master.yaml
      title: Master Bedroom Tablet
      show_in_sidebar: false
    lovelace-mobile:
      mode: yaml
      filename: lovelace-mobile.yaml
      title: Mobile Interface
      show_in_sidebar: false
    lovelace-entry:
      mode: yaml
      filename: lovelace-entry.yaml
      title: Entry Tablet
      show_in_sidebar: false
    lovelace-server:
      mode: yaml
      filename: lovelace-server.yaml
      title: Server Tablet
      show_in_sidebar: false
  resources:
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/bignumber-card/bignumber-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/circle-sensor-card/circle-sensor-card.js
      type: module
    - url: /hacsfiles/dark-sky-weather-card/dark-sky-weather-card.js
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-gap-card/gap-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /local/custom_ui/moment.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/text-divider-row/text-divider-row.js
      type: module
    - url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/waze-card/waze-card.js
      type: module
    - url: /hacsfiles/config-template-card/config-template-card.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/flex-horseshoe-card/flex-horseshoe-card.js
      type: module
    - url: /hacsfiles/list-card/list-card.js
      type: module
    - url: /hacsfiles/text-element/text-element.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/restriction-card/restriction-card.js
      type: module
    - url: /hacsfiles/lovelace-card-preloader/lovelace-card-preloader.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-time-picker-card/time-picker-card.js
      type: module
    - url: /hacsfiles/roku-card/roku-card.js
      type: module
    - url: /local/custom_ui/mm2-clock-card.js
      type: module
    - url: /hacsfiles/bom-weather-card/bom-weather-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module    
    - url: /hacsfiles/our-groceries-card/our-groceries-card.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    

# Discover some devices automatically
discovery:

# Sensors
sensor:

  #Template Sensors
  - platform: template
    sensors:
      #Blank
      blank:
        value_template: ""
        friendly_name: ""

      external_url:
        value_template: !secret ext_url

binary_sensor:
  - platform: template
    sensors:
      is_dst:
        value_template: "{{ now().timetuple().tm_isdst > 0 }}"

input_boolean:
  guest_mode:
    name: Guest Mode
    icon: mdi:timer-outline

  timer_lights:
    name: Timer Lights
    icon: mdi:lightbulb

  outside_timer_lights:
    name: Outside Timer Lights
    icon: mdi:timer-outline

  master_lamp_timer:
    name: Master Lamp Timer
    icon: mdi:timer-outline

mqtt:
  light:
    - schema: json
      name: "Hall Lamp"
      state_topic: "esps/hall"
      command_topic: "esps/hall/set"
      brightness: true
      rgb: true
      effect: true
      effect_list:
        - Solid
        - Blink
        - Flash
        - Rainbow
        - Chase
        - Fire flicker
        - Lightning
        - Breathe
  switch:
    - name: "Fireplace"
      state_topic: "stat/fireplace/POWER"
      command_topic: "cmnd/fireplace/POWER"
      availability_topic: "tele/fireplace/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Wax Warmer"
      state_topic: "warmer/stat/POWER"
      command_topic: "warmer/cmnd/POWER"
      availability_topic: "warmer/tele/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"
  sensor:
    #Fireplace

    - state_topic: "tele/fireplace/STATE"
      name: "Fireplace Signal"
      unit_of_measurement: "%"
      value_template: "{{value_json['Wifi'].RSSI }}"
      availability_topic: "tele/fireplace/LWT"
      qos: 1
      payload_available: "Online"
      payload_not_available: "Offline"

    #Wax Warmer

    - state_topic: "warmer/tele/STATE"
      name: "Fireplace Signal"
      unit_of_measurement: "%"
      value_template: "{{value_json['Wifi'].RSSI }}"
      availability_topic: "warmer/tele/LWT"
      qos: 1
      payload_available: "Online"
      payload_not_available: "Offline"

# Timers
timer:
  laundry_room:
    name: Laundry Room Light Timer
    duration: "00:02:00"

  master_closet:
    name: Master Closet Light Timer
    duration: "00:02:00"

  garage_light:
    name: Garage Lighting Timer
    duration: "00:10:00"

  doorbell_popup:
    name: Garage Lighting Timer
    duration: "00:01:00"

  blinds_after_shower_repeat:
    name: Repeat Prompt to Open Blinds After Shower
    duration: "00:05:00"

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

group: !include groups.yaml

automation: !include_dir_merge_list automation

script: !include_dir_merge_named scripts

scene: !include_dir_merge_named scenes

zone: !include zones.yaml

#Elk M1 Integration
elkm1:
  host: !secret elk_host
  username: !secret elk_user
  password: !secret elk_pass
  area:
    exclude: [3-8]
  counter:
    enabled: false
  keypad:
    enabled: false
  output:
    include: [3, 7, 9-16, 17-19, 177-180, 182-185, 197]
  setting:
    enabled: false
  task:
    enabled: false
  thermostat:
    enabled: false
  plc:
    enabled: false
  zone:
    exclude: [16, 35-36, 38-39, 54-64, 73-78, 81-196, 198-207]

# Alexa Integration
api:
alexa: !include alexa.yaml

#Google Calendar
google:
  client_id: !secret gcal_client_id
  client_secret: !secret gcal_client_secret

#Browser Mod
browser_mod:
  devices:
    !secret kitchen_tablet_browser:
      name: kitchen_tablet
    !secret shawn_chromebook_browser:
      name: shawn_chromebook
    !secret shawn_office_browser:
      name: shawn_office
    !secret shawn_n6_browser:
      name: shawn_n6
    !secret office_tablet_browser:
      name: office_tablet
    !secret shack_tablet_browser:
      name: shack_tablet
  disable:
    - all

input_select:
  doorbell_tone:
    name: Doorbell Sound
    options:
      - Alexa Speak
      - Wish Upon A Star
      - Christmas
    icon: mdi:music


device_tracker:
  - platform: aruba
    host: !secret aruba_host
    username: !secret aruba_user
    password: !secret aruba_pass

ourgroceries:
  username: !secret our_groceries_username
  password: !secret our_groceries_password