homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

# Enable Lovelace yaml mode
lovelace:
  mode: yaml

lovelace_gen:

# Discover some devices automatically
discovery:

#Blinds
cover:
  #MyQ
  - platform: myq
    username: !secret myq_user
    password: !secret myq_pass
    type: chamberlain

# Sensors
sensor:

  #Fireplace

  - platform: mqtt
    state_topic: "tele/fireplace/STATE"
    name: "Fireplace Signal"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "tele/fireplace/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"

  #Wax Warmer

  - platform: mqtt
    state_topic: "warmer/tele/STATE"
    name: "Fireplace Signal"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "warmer/tele/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"    

#Template Sensors
  - platform: template
    sensors:
      
      #Blank
      blank:
        value_template: ''
        friendly_name: ''

      external_url:
        value_template: !secret ext_url

binary_sensor:

  - platform: wyzesense
    device: "/dev/hidraw0"
  - platform: template
    sensors:
      is_dst:
        entity_id: sensor.date
        value_template: "{{ now().timetuple().tm_isdst > 0 }}"
    
switch:

  - platform: template
    switches:
      irrigation_program:
        friendly_name: "Irrigation Program Enabled"
        value_template: "{{ not is_state('switch.every_3_days', 'unavailable') }}"
        turn_on:
          service: rainmachine.enable_program
          data:
            program_id: 1
        turn_off:
          service: rainmachine.disable_program
          data:
            program_id: 1

      irrigation_run_program:
        friendly_name: "Run Irrigation Program"
        value_template: "{{ is_state('switch.every_3_days', 'on') }}"
        turn_on:
          service: rainmachine.start_program
          data:
            program_id: 1
        turn_off:
          service: rainmachine.stop_program
          data:
            program_id: 1

  - platform: mqtt
    name: "Fireplace"
    state_topic: "stat/fireplace/POWER"
    command_topic: "cmnd/fireplace/POWER"
    availability_topic: "tele/fireplace/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Wax Warmer"
    state_topic: "warmer/stat/POWER"
    command_topic: "warmer/cmnd/POWER"
    availability_topic: "warmer/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"    

input_boolean:

  guest_mode:
    name: Guest Mode
    icon: mdi:timer

  timer_lights:
    name: Timer Lights
    icon: mdi:lightbulb

  goodnight_trigger:
    name: Alexa Good Night Trigger
    initial: off
    icon: mdi:amazon-alexa

  bedtime_trigger:
    name: Alexa Bedtime Trigger
    initial: off
    icon: mdi:amazon-alexa

  morning_trigger:
    name: Alexa Morning Trigger
    initial: off
    icon: mdi:amazon-alexa    

  outside_timer_lights:
    name: Outside Timer Lights
    icon: mdi:timer
  
  master_lamp_timer:
    name: Master Lamp Timer
    icon: mdi:timer

  vacation_mode:
    name: Vacation Mode
    icon: mdi:airplane

  elk_night_on:
    name: Elk Night Mode On Trigger
    icon: mdi:alarm-bell

  elk_night_off:
    name: Elk Night Mode Off Trigger
    icon: mdi:alarm-bell  

  elk_stay_on:
    name: Elk Stay Mode On Trigger
    icon: mdi:alarm-bell

  elk_stay_off:
    name: Elk Stay Mode Off Trigger
    icon: mdi:alarm-bell

  elk_away_on:
    name: Elk Away Mode On Trigger
    icon: mdi:alarm-bell

light:

  - platform: mqtt
    schema: json
    name: "Hall Lamp"
    state_topic: "esps/hall"
    command_topic: "esps/hall/set"
    brightness: true
    rgb: true
    effect: true
    effect_list:
      - Solid
      - Blink
      - Flash
      - Rainbow
      - Chase
      - Fire flicker
      - Lightning
      - Breathe

  - platform: flux_led
    devices:
      192.168.6.3:
        name: build_light
# Timers
timer:

  garage:
    name: Garage Light Timer
    duration: '00:10:00'

  front_door:
    name: Front Door Lock Timer
    duration: '00:05:00'

  back_door:
    name: Back Door Lock Timer
    duration: '00:05:00'

  laundry_room:
    name: Laundry Room Light Timer
    duration: '00:02:00'

  master_closet:
    name: Master Closet Light Timer
    duration: '00:02:00'

  garage_entry:
    name: Garage Entry Lock Timer
    duration: '00:05:00'

  garage_light:
    name: Garage Lighting Timer
    duration: '00:10:00'

  doorbell_popup:
    name: Garage Lighting Timer
    duration: '00:01:00'

# Text to speech
tts:

  - platform: google_translate
    service_name: google_say

group: !include groups.yaml

automation: !include_dir_merge_list automation

script: !include_dir_merge_named scripts

scene: !include_dir_merge_named scenes

zone: !include zones.yaml



#Elk M1 Integration
elkm1:
  host: !secret elk_host
  username: !secret elk_user
  password: !secret elk_pass
  area:
    exclude: [3-8]
  counter:
    enabled: false
  keypad:
    enabled: false
  output:
    include: [3, 7, 9-16, 177-180, 182-183, 197]
  setting:
    enabled: false
  task:
    enabled: false
  thermostat:
    enabled: false
  plc:
    enabled: false
  zone:
    exclude: [16, 35-36, 38-39, 54-64, 73-78, 81-196, 198-207]


# Alexa Integration
api:
alexa: !include alexa.yaml

#Device Tracking
device_tracker:
  - platform: aprs
    username: !secret my_callsign
    callsigns:
      - !secret truck_callsign

#Counters
counter:
  dryer_alert:
    initial: 0
    step: 1
  washer_alert:
    initial: 0
    step: 1

#Kodi Media Player
media_player:
  - name: den_kodi
    platform: kodi
    host: !secret den_kodi_host
  - name: master_kodi
    platform: kodi
    host: !secret master_kodi_host
      
#Google Calendar
google:
  client_id: !secret gcal_client_id
  client_secret: !secret gcal_client_secret

#HACS
hacs:
  token: !secret hacs_git

#Alexa Media Player
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com

#Browser Mod
browser_mod:
  devices:
    !secret kitchen_tablet_browser:
      name: kitchen_tablet
    !secret shawn_chromebook_browser:
      name: shawn_chromebook
    !secret shawn_office_browser:
      name: shawn_office
    !secret shawn_n6_browser:
      name: shawn_n6
  disable: 
    - all
    
input_select:
  doorbell_tone:
    name: Doorbell Sound
    options:
      - Alexa Speak
      - Wish Upon A Star    
      - Christmas
    icon: mdi:music