title: The Geek House

# Preload Cards

# preload_cards:
#   - picture-elements
#   - picture-entity
#   - conditional

button_card_templates:
  !include /config/lovelace/resources/button_card_templates.yaml
decluttering_templates:
  !include /config/lovelace/resources/decluttering_card_templates.yaml

background: center / cover no-repeat url("/local/lovelace/background_19.png") fixed
views:
  - !include /config/lovelace/views/panels/crestron-kitchen.yaml
