title: The Geek House

# Preload Cards

preload_cards:
  - picture-elements
  - picture-entity
  - conditional

#############################################################################################################################################
#                                                                                                                                           #
#                                                                BEGIN VIEWS                                                                #
#                                                                                                                                           #
#############################################################################################################################################

views:
  - !include /config/lovelace/views/home.yaml
  - !include /config/lovelace/views/rooms.yaml
  - !include /config/lovelace/views/hvac.yaml
  - !include /config/lovelace/views/media.yaml
  - !include /config/lovelace/views/utilities.yaml
  - !include /config/lovelace/views/system.yaml
  - !include /config/lovelace/views/settings.yaml
