title: The Geek House

# Preload Cards

preload_cards:
  - picture-elements
  - picture-entity
  - conditional

decluttering_templates:
  !include /config/lovelace/resources/decluttering_card_templates.yaml

#############################################################################################################################################
#                                                                                                                                           #
#                                                                BEGIN VIEWS                                                                #
#                                                                                                                                           #
#############################################################################################################################################

background: center / cover no-repeat url("/local/lovelace/background_19.png") fixed
views:
  - !include /config/lovelace/views/home.yaml
  - !include /config/lovelace/views/rooms.yaml
  - !include /config/lovelace/views/hvac.yaml
  - !include /config/lovelace/views/media.yaml
  - !include /config/lovelace/views/weather.yaml
  - !include /config/lovelace/views/utilities.yaml
  - !include /config/lovelace/views/system.yaml
  - !include /config/lovelace/views/settings.yaml
