title: The Geek House

resources: !include /config/lovelace/resources/resources.yaml

#################################################################
#                                                               #
#                    Compact Header Config                      #
#                                                               #
################################################################# 

custom_header:
  background: 'rgba(150, 150, 150, 0.2)'
  compact_mode: true
  hide_config: true
  hide_unused: true
  hide_help: true
  button_text:
    options: '{{ time }}<br>{{ date }}'
  hide_tabs: '8'
  default_tab: '0'
  exceptions:
    - conditions:
        user_agent: fully-kitchen
      config:
        menu_dropdown: true
        hide_tabs: '0 to 7'
        default_tab: '8'
    - conditions:
        user_agent: Android
      config:
        options_hide: true
        hide_tabs: '3'

#############################################################################################################################################
#                                                                                                                                           # 
#                                                                BEGIN VIEWS                                                                #
#                                                                                                                                           #
#############################################################################################################################################  
 
background: center / cover no-repeat url("/local/lovelace/background_19.png") fixed
views: 

  - !include /config/lovelace/views/home.yaml
  - !include /config/lovelace/views/rooms.yaml  
  - !include /config/lovelace/views/hvac.yaml
  - !include /config/lovelace/views/laundry.yaml
  - !include /config/lovelace/views/blinds.yaml
  - !include /config/lovelace/views/media.yaml
  - !include /config/lovelace/views/irrigation.yaml
  - !include /config/lovelace/views/system.yaml        
  - !include /config/lovelace/views/panels/kitchen.yaml
