cover:
  - platform: mqtt
    name: "Center Shack Blind"
    device_class: blind
    command_topic: "habc/shack_c/command/set/state"
    set_position_topic: "habc/shack_c/command/set/positionpct"
    position_topic: "habc/shack_c/tele/currentpct"
    availability_topic: "habc/shack_c/tele/LWT"
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    position_open: 100
    position_closed: 0
    payload_available: "Online"
    payload_not_available: "Offline"

sensor:
  - platform: mqtt
    name: "Center Shack Blind Version"
    state_topic: "habc/shack_c/tele/status"
    value_template: "{{value_json['espVersion']}}"
    availability_topic: "habc/shack_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Center Shack Blind Uptime"
    state_topic: "habc/shack_c/tele/status"
    value_template: "{{value_json['espUptime']}}"
    availability_topic: "habc/shack_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Center Shack Blind RSSI"
    state_topic: "habc/shack_c/tele/status"
    value_template: "{{value_json['signalStrength']}}"
    availability_topic: "habc/shack_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Center Shack Blind IP"
    state_topic: "habc/shack_c/tele/status"
    value_template: "{{value_json['bridgeIP']}}"
    availability_topic: "habc/shack_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Center Shack Blind Free Heap"
    state_topic: "habc/shack_c/tele/status"
    value_template: "{{value_json['heapFree']}}"
    availability_topic: "habc/office_l/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Center Shack Blind Heap Fragmentation"
    state_topic: "habc/shack_c/tele/status"
    value_template: "{{value_json['heapFragmentation']}}"
    availability_topic: "habc/shack_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Center Shack Blind Core Version"
    state_topic: "habc/shack_c/tele/status"
    value_template: "{{value_json['espCore']}}"
    availability_topic: "habc/shack_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Center Shack Blind Light Level"
    state_topic: "habc/shack_c/tele/light"
    unit_of_measurement: "%"
    availability_topic: "habc/shack_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
