# Handle All Off message
- alias: Nuvo Zone 1 All Off
  id: 2d3f8f36-b0f6-4e52-a0ae-f7bccae77dc3
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_1_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/1/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 2 All Off
  id: 72f12f79-846e-4696-848c-8da4467c337d
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_2_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/2/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 3 All Off
  id: 33dcb675-932e-4915-9cc7-f602674dd160
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_3_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/3/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 4 All Off
  id: f1200f51-43e9-4a96-ab5a-63bfe79082bb
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_4_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/4/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 5 All Off
  id: 89960997-7fbc-408b-97a9-13b41cc182c5
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_5_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/5/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 6 All Off
  id: fc71788c-3a38-4868-a77b-918e4a2b041e
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_6_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/6/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 7 All Off
  id: f84c3162-3f1c-404c-9ee4-f388f638bfa0
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_7_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/7/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 8 All Off
  id: 62b75e7a-c3ea-4252-8120-d1dba06da806
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_8_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/8/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 9 All Off
  id: 98d72ec7-b2ec-46e4-9fc6-3a11019d77d6
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_9_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/9/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 10 All Off
  id: 53ecb9b5-9f45-44b7-bc49-de0dee202b82
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_10_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/10/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 11 All Off
  id: 01368aaa-d5a7-4a45-ab06-b7d450fc573d
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_11_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/11/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 12 All Off
  id: 726db890-633d-4c55-aef6-96b2a4c3d926
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_12_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/12/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 13 All Off
  id: 35a4a72e-bcd8-4fd1-bed5-e70d43bc19cc
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_13_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/13/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 14 All Off
  id: fae68aaf-0f21-4928-8de5-aae00f873922
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_14_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/14/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 15 All Off
  id: c66897ee-e3c9-47e9-982b-05becc5ee9ea
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_15_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/15/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 16 All Off
  id: 76d38124-5b02-4766-863d-3a80a1ac8498
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_16_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/16/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 17 All Off
  id: e6c91548-91c3-4feb-9067-8f9195c40a98
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_17_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/17/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 18 All Off
  id: 63c94d5e-93fa-4422-9eec-10854adf8f04
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_18_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/18/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 19 All Off
  id: adeb3432-4a47-41c3-be67-919ec5be63af
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_19_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/19/power
        payload: "OFF"
        retain: true

- alias: Nuvo Zone 20 All Off
  id: 3aa29c86-86d7-4cf5-bb76-cffb21205d5a
  trigger:
    - platform: mqtt
      topic: nuvo/tele/system/alloff
  condition:
    - condition: state
      entity_id: switch.nuvo_zone_20_power
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/tele/zone/20/power
        payload: "OFF"
        retain: true

- alias: Update GC Clock
  id: e982da51-ec5f-40b9-8b6c-da3ea88dded6
  trigger:
    - platform: time
      at: "00:00:00"
    - platform: state
      entity_id: binary_sensor.is_dst
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/command/set/system/time
        payload_template: >-
          {% set year = now().year %}
          {% set month = now().month %}
          {% set day = now().day %}
          {% set hour = now().hour %}
          {% set minute = now().minute %}
            {{ year }},     
            {%- if month < 10 -%}
              0{{ month }},
            {%- else -%}
              {{ month }},
            {%- endif -%}
            {%- if day < 10 -%}
              0{{ day }},
            {%- else -%}
              {{ day }},
            {%- endif -%}
            {%- if hour == 0 -%}
              00,
            {%- endif -%}
            {%- if hour > 0 -%}        
              {%- if hour < 10 -%}
                0{{ hour }},
              {%- else -%}
                {{ hour }},
              {%- endif -%}
            {%- endif -%}
            {%- if minute == 0 -%}
              00
            {%- endif -%}
            {%- if minute > 0 -%}
              {%- if minute < 10 -%}
                0{{ minute }}
              {%- else -%}
                {{ minute }}
              {%- endif -%}
            {%- endif -%}
