cover:
  - platform: mqtt
    name: "Center Office Blind"
    command_topic: "habc/office_c/command/set/state"
    set_position_topic: "habc/office_c/command/set/positionpct"
    position_topic: "habc/office_c/tele/currentpct"
    availability_topic: "habc/office_c/tele/LWT"
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    position_open: 100
    position_closed: 0
    payload_available: "Online"
    payload_not_available: "Offline"

sensor:
  - platform: mqtt
    name: "Center Office Blind Version"
    state_topic: "habc/office_c/tele/status"
    value_template: "{{value_json['espVersion']}}"
    availability_topic: "habc/office_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    
  - platform: mqtt
    name: "Center Office Blind Uptime"
    state_topic: "habc/office_c/tele/status"
    value_template: "{{value_json['espUptime']}}"
    availability_topic: "habc/office_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Center Office Blind RSSI"
    state_topic: "habc/office_c/tele/status"
    value_template: "{{value_json['signalStrength']}}"
    availability_topic: "habc/office_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Center Office Blind IP"
    state_topic: "habc/office_c/tele/status"
    value_template: "{{value_json['bridgeIP']}}"
    availability_topic: "habc/office_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Center Office Blind Free Heap"
    state_topic: "habc/office_c/tele/status"
    value_template: "{{value_json['heapFree']}}"
    availability_topic: "habc/office_l/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Center Office Blind Heap Fragmentation"
    state_topic: "habc/office_c/tele/status"
    value_template: "{{value_json['heapFragmentation']}}"
    availability_topic: "habc/office_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Center Office Blind Core Version"
    state_topic: "habc/office_c/tele/status"
    value_template: "{{value_json['espCore']}}" 
    availability_topic: "habc/office_c/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
