cover:
  - platform: mqtt
    name: "Office Blinds"
    device_class: blind
    command_topic: "habc/office/command/set/state"
    set_position_topic: "habc/office/command/set/positionpct"
    position_topic: "habc/office/tele/currentpct"
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    position_open: 100
    position_closed: 0

sensor:
  platform: average
  name: Office Blinds Average Light Level
  entities:
    - sensor.left_office_blind_light_level
    - sensor.center_office_blind_light_level
    - sensor.right_office_blind_light_level