

## Google Music Media Player
## Use this 'package.yaml' file to configure "gmusic_player"
media_player:
  - platform: gmusic_player
    username: !secret gmusic_user
    password: !secret gmusic_password
    device_id: !secret gmusic_device_id
      
    ## Add your media_players below
    speakers: # Example media_players
      - whole_house_audio
      - living_room_chromecast
      
    ## Optional: enable streaming from gmusicproxy (Workaround for issue #6)
    ## https://github.com/tprelog/homeassistant-gmusic_player/issues/6
    gmusicproxy: !secret gmusicproxy_ip