mqtt:
  cover:
    - name: "Kitchen Blinds"
      device_class: blind
      command_topic: "habc/kitchen/command/set/state"
      set_position_topic: "habc/kitchen/command/set/positionpct"
      position_topic: "habc/kitchen/tele/currentpct"
      payload_open: "OPEN"
      payload_close: "CLOSE"
      payload_stop: "STOP"
      position_open: 100
      position_closed: 0

sensor:
  - platform: average
    name: Kitchen Blinds Average Light Level
    entities:
      - sensor.left_kitchen_blind_light_level
      - sensor.east_kitchen_blind_light_level
      - sensor.right_kitchen_blind_light_level
