cover:
  - platform: mqtt
    name: "East Kitchen Blind"
    device_class: blind
    command_topic: "habc/kitchen_e/command/set/state"
    set_position_topic: "habc/kitchen_e/command/set/positionpct"
    position_topic: "habc/kitchen_e/tele/currentpct"
    availability_topic: "habc/kitchen_e/tele/LWT"
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    position_open: 100
    position_closed: 0
    payload_available: "Online"
    payload_not_available: "Offline"

sensor:
  - platform: mqtt
    name: "East Kitchen Blind Version"
    state_topic: "habc/kitchen_e/tele/status"
    value_template: "{{value_json['espVersion']}}"
    availability_topic: "habc/kitchen_e/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    
  - platform: mqtt
    name: "East Kitchen Blind Uptime"
    state_topic: "habc/kitchen_e/tele/status"
    value_template: "{{value_json['espUptime']}}"
    availability_topic: "habc/kitchen_e/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "East Kitchen Blind RSSI"
    state_topic: "habc/kitchen_e/tele/status"
    value_template: "{{value_json['signalStrength']}}"
    availability_topic: "habc/kitchen_e/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "East Kitchen Blind IP"
    state_topic: "habc/kitchen_e/tele/status"
    value_template: "{{value_json['bridgeIP']}}"
    availability_topic: "habc/kitchen_e/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "East Kitchen Blind Free Heap"
    state_topic: "habc/kitchen_e/tele/status"
    value_template: "{{value_json['heapFree']}}"
    availability_topic: "habc/office_l/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "East Kitchen Blind Heap Fragmentation"
    state_topic: "habc/kitchen_e/tele/status"
    value_template: "{{value_json['heapFragmentation']}}"
    availability_topic: "habc/kitchen_e/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "East Kitchen Blind Core Version"
    state_topic: "habc/kitchen_e/tele/status"
    value_template: "{{value_json['espCore']}}" 
    availability_topic: "habc/kitchen_e/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "East Kitchen Blind Light Level"
    state_topic: "habc/kitchen_e/tele/light"
    unit_of_measurement: '%'
    availability_topic: "habc/kitchen_e/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"