light:
  - platform: mqtt
    name: "Kitchen Toekick LEDs RGB"
    state_topic: "h801/k_toekick/ha/state"
    command_topic: "h801/k_toekick/command/set/rgb/power"
    brightness_state_topic: "h801/k_toekick/tele/current"
    brightness_command_topic: "h801/k_toekick/command/set/rgb/brightness"
    rgb_state_topic: "h801/k_toekick/tele/current"
    rgb_command_topic: "h801/k_toekick/command/set/rgb/color"
    brightness_value_template: "{{value_json['rgb_brightness']}}"
    rgb_value_template: "{{value_json['rgb_r']}},{{value_json['rgb_g']}},{{value_json['rgb_b']}}"
    qos: 0
    retain: false
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false

automation:
  - alias: k_toekick_gr report on
    id: 0dc6e9c8-9552-4e71-adfb-0785a5cb266e
    trigger:
      - platform: state
        entity_id: light.kitchen_led_1_rgb
        to: "on"
      - platform: state
        entity_id: light.kitchen_led_2_rgb
        to: "on"
      - platform: state
        entity_id: light.kitchen_led_3_rgb
        to: "on"
    action:
      - service: mqtt.publish
        data:
          topic: h801/k_toekick/ha/state
          payload_template: "ON"
          retain: true

  - alias: k_toekick_gr report off
    id: a24baf76-ca79-4318-837a-bae17ecf8e74
    trigger:
      - platform: state
        entity_id: light.kitchen_led_1_rgb
        to: "off"
      - platform: state
        entity_id: light.kitchen_led_2_rgb
        to: "off"
      - platform: state
        entity_id: light.kitchen_led_3_rgb
        to: "off"
    condition:
      - condition: state
        entity_id: light.kitchen_led_1_rgb
        state: "off"
      - condition: state
        entity_id: light.kitchen_led_2_rgb
        state: "off"
      - condition: state
        entity_id: light.kitchen_led_3_rgb
        state: "off"
    action:
      - service: mqtt.publish
        data:
          topic: h801/k_toekick/ha/state
          payload_template: "OFF"
          retain: true
