mqtt:
  light:
    - name: "Kitchen Upper LEDs RGB"
      unique_id: 1bac6be4-c208-4a7f-bfdf-2f0f19482d06
      state_topic: "h801/k_upper/ha/state"
      command_topic: "h801/k_upper/command/set/rgb/power"
      brightness_state_topic: "h801/k_upper/tele/current"
      brightness_command_topic: "h801/k_upper/command/set/rgb/brightness"
      rgb_state_topic: "h801/k_upper/tele/current"
      rgb_command_topic: "h801/k_upper/command/set/rgb/color"
      brightness_value_template: "{{value_json['rgb_brightness']}}"
      rgb_value_template: "{{value_json['rgb_r']}},{{value_json['rgb_g']}},{{value_json['rgb_b']}}"
      qos: 0
      retain: false
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false

automation:
  - alias: k_upper_gr report on
    id: eaf5e0a7-b2e9-497c-8b4e-a0622f4baf54
    trigger:
      - platform: state
        entity_id: light.kitchen_led_7_rgb
        to: "on"
      - platform: state
        entity_id: light.kitchen_led_8_rgb
        to: "on"
    action:
      - service: mqtt.publish
        data:
          topic: h801/k_upper/ha/state
          payload_template: "ON"
          retain: true

  - alias: k_upper_gr report off
    id: 147be7c7-4843-47f2-9753-99dc708f8315
    trigger:
      - platform: state
        entity_id: light.kitchen_led_7_rgb
        to: "off"
      - platform: state
        entity_id: light.kitchen_led_8_rgb
        to: "off"
    condition:
      - condition: state
        entity_id: light.kitchen_led_7_rgb
        state: "off"
      - condition: state
        entity_id: light.kitchen_led_8_rgb
        state: "off"
    action:
      - service: mqtt.publish
        data:
          topic: h801/k_upper/ha/state
          payload_template: "OFF"
          retain: true
