light:
  - platform: mqtt
    name: "Kitchen LED 5 RGB"
    state_topic: "h801/kitchen_5/tele/current"
    command_topic: "h801/kitchen_5/command/set/rgb/power"
    brightness_state_topic: "h801/kitchen_5/tele/current"
    brightness_command_topic: "h801/kitchen_5/command/set/rgb/brightness"
    rgb_state_topic: "h801/kitchen_5/tele/current"
    rgb_command_topic: "h801/kitchen_5/command/set/rgb/color"
    state_value_template: "{{value_json['rgb_power']}}"
    brightness_value_template: "{{value_json['rgb_brightness']}}"
    rgb_value_template: "{{value_json['rgb_r']}},{{value_json['rgb_g']}},{{value_json['rgb_b']}}"
    availability_topic: "h801/kitchen_5/tele/LWT"
    qos: 0
    retain: false
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Kitchen LED 5 W2"
    state_topic: "h801/kitchen_5/tele/current"
    command_topic: "h801/kitchen_5/command/set/w2/power"
    brightness_state_topic: "h801/kitchen_5/tele/current"
    brightness_command_topic: "h801/kitchen_5/command/set/w2/brightness"
    state_value_template: "{{value_json['w2_power']}}"
    brightness_value_template: "{{value_json['w2_brightness']}}"
    availability_topic: "h801/kitchen_5/tele/LWT"
    qos: 0
    retain: false
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    payload_available: "Online"
    payload_not_available: "Offline"

sensor:
  #Driver Status Messages

  - platform: mqtt
    name: "Kitchen LED 5 Version"
    state_topic: "h801/kitchen_5/tele/status"
    value_template: "{{value_json['espVersion']}}"
    availability_topic: "h801/kitchen_5/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Kitchen LED 5 Uptime"
    state_topic: "h801/kitchen_5/tele/status"
    value_template: "{{value_json['espUptime']}}"
    availability_topic: "h801/kitchen_5/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Kitchen LED 5 RSSI"
    state_topic: "h801/kitchen_5/tele/status"
    value_template: "{{value_json['signalStrength']}}"
    availability_topic: "h801/kitchen_5/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Kitchen LED 5 IP"
    state_topic: "h801/kitchen_5/tele/status"
    value_template: "{{value_json['bridgeIP']}}"
    availability_topic: "h801/kitchen_5/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Kitchen LED 5 Free Heap"
    state_topic: "h801/kitchen_5/tele/status"
    value_template: "{{value_json['heapFree']}}"
    availability_topic: "h801/kitchen_5/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Kitchen LED 5 Heap Fragmentation"
    state_topic: "h801/kitchen_5/tele/status"
    value_template: "{{value_json['heapFragmentation']}}"
    availability_topic: "h801/kitchen_5/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Kitchen LED 5 Core Version"
    state_topic: "h801/kitchen_5/tele/status"
    value_template: "{{value_json['espCore']}}"
    availability_topic: "h801/kitchen_5/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
