light:
  - platform: mqtt
    name: "Kitchen LEDs RGB"
    state_topic: "h801/kitchen/ha/state"
    command_topic: "h801/kitchen/command/set/rgb/power"
    brightness_state_topic: "h801/kitchen/tele/current"
    brightness_command_topic: "h801/kitchen/command/set/rgb/brightness"
    rgb_state_topic: "h801/kitchen/tele/current"
    rgb_command_topic: "h801/kitchen/command/set/rgb/color"
    brightness_value_template: "{{value_json['rgb_brightness']}}"
    rgb_value_template: "{{value_json['rgb_r']}},{{value_json['rgb_g']}},{{value_json['rgb_b']}}"
    qos: 0
    retain: false
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
automation:
  - alias: kitchen_gr report on
    id: 7c8086cb-f198-418f-b303-ae58f057f48a
    trigger:
      - platform: state
        entity_id: light.kitchen_led_1_rgb
        to: "on"
      - platform: state
        entity_id: light.kitchen_led_2_rgb
        to: "on"
      - platform: state
        entity_id: light.kitchen_led_3_rgb
        to: "on"
      - platform: state
        entity_id: light.kitchen_led_4_rgb
        to: "on"
      - platform: state
        entity_id: light.kitchen_led_5_rgb
        to: "on"
      - platform: state
        entity_id: light.kitchen_led_6_rgb
        to: "on"
      - platform: state
        entity_id: light.kitchen_led_7_rgb
        to: "on"
      - platform: state
        entity_id: light.kitchen_led_8_rgb
        to: "on"
    action:
      - service: mqtt.publish
        data:
          topic: h801/kitchen/ha/state
          payload_template: "ON"
  - alias: kitchen_gr report off
    id: e3109bde-b15c-4758-9d25-3791d041fa22
    trigger:
      - platform: state
        entity_id: light.kitchen_led_1_rgb
        to: "off"
      - platform: state
        entity_id: light.kitchen_led_2_rgb
        to: "off"
      - platform: state
        entity_id: light.kitchen_led_3_rgb
        to: "off"
      - platform: state
        entity_id: light.kitchen_led_4_rgb
        to: "off"
      - platform: state
        entity_id: light.kitchen_led_5_rgb
        to: "off"
      - platform: state
        entity_id: light.kitchen_led_6_rgb
        to: "off"
      - platform: state
        entity_id: light.kitchen_led_7_rgb
        to: "off"
      - platform: state
        entity_id: light.kitchen_led_8_rgb
        to: "off"
    condition:
      - condition: state
        entity_id: light.kitchen_led_1_rgb
        state: "off"
      - condition: state
        entity_id: light.kitchen_led_2_rgb
        state: "off"
      - condition: state
        entity_id: light.kitchen_led_3_rgb
        state: "off"
      - condition: state
        entity_id: light.kitchen_led_4_rgb
        state: "off"
      - condition: state
        entity_id: light.kitchen_led_5_rgb
        state: "off"
      - condition: state
        entity_id: light.kitchen_led_6_rgb
        state: "off"
      - condition: state
        entity_id: light.kitchen_led_7_rgb
        state: "off"
      - condition: state
        entity_id: light.kitchen_led_8_rgb
        state: "off"
    action:
      - service: mqtt.publish
        data:
          topic: h801/kitchen/ha/state
          payload_template: "OFF"
