sensor:
    
  - platform: template
    sensors:

      smt_electricity_cost_this_hour:
        unique_id: 1a4dd41a-3f5e-4e74-bb9e-6372236690f1
        friendly_name: Electricity Cost This Hour
        unit_of_measurement: '$'
        value_template: "{{ (states('sensor.smt_energy_hourly') | float(none) * states('input_number.smt_energy_cost') | float(none)) | round (2, default=none) }}"

      smt_electricity_cost_last_hour:
        unique_id: 5b240de3-aae0-4c9d-beaf-3ee0fd0f477e
        friendly_name: Electricity Cost Last Hour
        unit_of_measurement: '$'
        value_template: "{{ (state_attr('sensor.smt_energy_hourly','last_period') | float(none) * states('input_number.smt_energy_cost') | float(none)) | round (2, default=none) }}"

      smt_electricity_cost_today:
        unique_id: b5e868c8-9ab1-48b5-bbb2-32bd2e168934
        friendly_name: Electricity Cost Today
        unit_of_measurement: '$'
        value_template: "{{ (states('sensor.smt_energy_daily') | float(none) * states('input_number.smt_energy_cost') | float(none)) | round (2, default=none) }}"

      smt_electricity_cost_yesterday:
        unique_id: 691c6627-cc18-4cdf-9933-6de6c5dc782d
        friendly_name: Electricity Cost Yesterday
        unit_of_measurement: '$'
        value_template: "{{ (state_attr('sensor.smt_energy_daily','last_period') | float(none) * states('input_number.smt_energy_cost') | float(none)) | round (2, default=none) }}"

      smt_electricity_cost_this_week:
        unique_id: e310290d-a2e9-48de-bd63-6735b082c59f
        friendly_name: Electricity Cost This Week
        unit_of_measurement: '$'
        value_template: "{{ (states('sensor.smt_energy_weekly') | float(none) * states('input_number.smt_energy_cost') | float(none)) | round (2, default=none) }}"

      smt_electricity_cost_last_week:
        unique_id: e67b69df-dbf7-4dbe-88c9-df41097fc974
        friendly_name: Electricity Cost Last Week
        unit_of_measurement: '$'
        value_template: "{{ (state_attr('sensor.smt_energy_weekly','last_period') | float(none) * states('input_number.smt_energy_cost') | float(none)) | round (2, default=none) }}"

      smt_electricity_cost_this_month:
        unique_id: a2ecda2b-fdf4-4b26-bd71-9f9b552ede16
        friendly_name: Electricity Cost This Month
        unit_of_measurement: '$'
        value_template: "{{ (states('sensor.smt_energy_monthly') | float(none) * states('input_number.smt_energy_cost') | float(none)) | round (2, default=none) }}"

      smt_electricity_cost_last_month:
        unique_id: 9ac19983-7a4e-4e2a-902e-a6b7daa21ef7
        friendly_name: Electricity Cost Last Month
        unit_of_measurement: '$'
        value_template: "{{ (state_attr('sensor.smt_energy_monthly','last_period') | float(none) * states('input_number.smt_energy_cost') | float(none)) | round (2, default=none) }}"

      smt_electricity_cost_this_year:
        unique_id: 2261f6f9-eafa-4c9c-b7c3-5f48c26fab87
        friendly_name: Electricity Cost This Year
        unit_of_measurement: '$'
        value_template: "{{ (states('sensor.smt_energy_yearly') | float(none) * states('input_number.smt_energy_cost') | float(none)) | round (2, default=none) }}"

      smt_electricity_cost_last_year:
        unique_id: 26ae00b9-32c3-4e0e-9c24-ec6e4367742c
        friendly_name: Electricity Cost Last Year
        unit_of_measurement: '$'
        value_template: "{{ (state_attr('sensor.smt_energy_yearly','last_period') | float(none) * states('input_number.smt_energy_cost') | float(none)) | round (2, default=none) }}"

      smt_energy_last_hour:
        unique_id: 1c59ecfc-ae31-4600-8df2-714fd75fcc15
        friendly_name: Energy Last Hour
        unit_of_measurement: 'kWh'
        value_template: "{{ state_attr('sensor.smt_energy_hourly','last_period') }}"

    
utility_meter:

  smt_energy_hourly:
    source: sensor.smt_current_reading
    cycle: hourly

  smt_energy_daily:
    source: sensor.smt_current_reading
    cycle: daily
    
  smt_energy_weekly:
    source: sensor.smt_current_reading
    cycle: weekly

  smt_energy_monthly:
    source: sensor.smt_current_reading
    cycle: monthly

  smt_energy_yearly:
    source: sensor.smt_current_reading
    cycle: yearly    
    
input_number:

  smt_energy_cost:
    name: Electricity Cost
    mode: box
    min: 0
    max: 2.50
    step: .001
    unit_of_measurement: "$/kWh"
