sensor:
  - platform: mqtt
    name: "Eagle Current Power"
    state_topic: "power/elec/Home/power"
    value_template: "{{value_json['power']}}"
    unit_of_measurement: W

  - platform: integration
    source: sensor.eagle_current_power
    name: energy_used
    unit_prefix: k
    round: 2

  - platform: template
    sensors:
      electricity_cost_this_hour:
        friendly_name: Electricity Cost This Hour
        unit_of_measurement: "$"
        value_template: "{{ (states('sensor.energy_hourly') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_this_hour_unit:
        friendly_name: Electricity Cost This Hour
        value_template: "${{ (states('sensor.energy_hourly') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_last_hour:
        friendly_name: Electricity Cost Last Hour
        unit_of_measurement: "$"
        value_template: "{{ (state_attr('sensor.energy_hourly','last_period') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_last_hour_unit:
        friendly_name: Electricity Cost Last Hour
        value_template: "${{ (state_attr('sensor.energy_hourly','last_period') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_today:
        friendly_name: Electricity Cost Today
        unit_of_measurement: "$"
        value_template: "{{ (states('sensor.energy_daily') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_today_unit:
        friendly_name: Electricity Cost Today
        value_template: "${{ (states('sensor.energy_daily') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_yesterday:
        friendly_name: Electricity Cost Yesterday
        unit_of_measurement: "$"
        value_template: "{{ (state_attr('sensor.energy_daily','last_period') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_yesterday_unit:
        friendly_name: Electricity Cost Yesterday
        value_template: "${{ (state_attr('sensor.energy_daily','last_period') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_this_week:
        friendly_name: Electricity Cost This Week
        unit_of_measurement: "$"
        value_template: "{{ (states('sensor.energy_weekly') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_this_week_unit:
        friendly_name: Electricity Cost This Week
        value_template: "${{ (states('sensor.energy_weekly') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_last_week:
        friendly_name: Electricity Cost Last Week
        unit_of_measurement: "$"
        value_template: "{{ (state_attr('sensor.energy_weekly','last_period') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_last_week_unit:
        friendly_name: Electricity Cost Last Week
        value_template: "${{ (state_attr('sensor.energy_weekly','last_period') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_this_month:
        friendly_name: Electricity Cost This Month
        unit_of_measurement: "$"
        value_template: "{{ (states('sensor.energy_monthly') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_this_month_unit:
        friendly_name: Electricity Cost This Month
        value_template: "${{ (states('sensor.energy_monthly') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_last_month:
        friendly_name: Electricity Cost Last Month
        unit_of_measurement: "$"
        value_template: "{{ (state_attr('sensor.energy_monthly','last_period') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_last_month_unit:
        friendly_name: Electricity Cost Last Month
        value_template: "${{ (state_attr('sensor.energy_monthly','last_period') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_this_year:
        friendly_name: Electricity Cost This Year
        unit_of_measurement: "$"
        value_template: "{{ (states('sensor.energy_yearly') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_this_year_unit:
        friendly_name: Electricity Cost This Year
        value_template: "${{ (states('sensor.energy_yearly') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_last_year:
        friendly_name: Electricity Cost Last Year
        unit_of_measurement: "$"
        value_template: "{{ (state_attr('sensor.energy_yearly','last_period') | float * states('input_number.energy_cost') | float) | round (2) }}"

      electricity_cost_last_year_unit:
        friendly_name: Electricity Cost Last Year
        value_template: "${{ (state_attr('sensor.energy_yearly','last_period') | float * states('input_number.energy_cost') | float) | round (2) }}"

utility_meter:
  energy_hourly:
    source: sensor.energy_used
    cycle: hourly

  energy_daily:
    source: sensor.energy_used
    cycle: daily

  energy_weekly:
    source: sensor.energy_used
    cycle: weekly

  energy_monthly:
    source: sensor.energy_used
    cycle: monthly

  energy_yearly:
    source: sensor.energy_used
    cycle: yearly

input_number:
  energy_cost:
    name: Electricity Cost
    mode: box
    min: 0
    max: 2.50
    step: .001
    unit_of_measurement: "$/kWh"
