mqtt:
  switch:
    - name: Houston METAR Map Power
      unique_id: efdc9f30-f178-4873-be6c-6a93f8e6174b
      state_topic: metar/hou/tele/current
      command_topic: metar/hou/command/set/power
      availability_topic: metar/hou/tele/LWT
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      optimistic: false
      payload_available: "Online"
      payload_not_available: "Offline"

  sensor:
    #Driver Status Messages

    - name: "Houston METAR Map Version"
      unique_id: 6fd1946b-0dbd-48bc-a89f-7c7c0d0a3ca5
      state_topic: "metar/hou/tele/status"
      value_template: "{{value_json['espVersion']}}"
      availability_topic: "metar/hou/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Houston METAR Map Uptime"
      unique_id: 9ced0f61-1fcc-4e23-a115-3176109e6e53
      state_topic: "metar/hou/tele/status"
      value_template: "{{value_json['espUptime']}}"
      availability_topic: "metar/hou/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Houston METAR Map RSSI"
      unique_id: 686e2bdc-0314-433f-818b-623fa096a6c0
      state_topic: "metar/hou/tele/status"
      value_template: "{{value_json['signalStrength']}}"
      availability_topic: "metar/hou/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Houston METAR Map IP"
      unique_id: f41a0ce8-bf2d-412b-bee8-cb78328fc55f
      state_topic: "metar/hou/tele/status"
      value_template: "{{value_json['mapIP']}}"
      availability_topic: "metar/hou/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Houston METAR Map Free Heap"
      unique_id: f2aadb13-84bb-419e-bc84-3b0ed63bf686
      state_topic: "metar/hou/tele/status"
      value_template: "{{value_json['heapFree']}}"
      availability_topic: "metar/hou/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Houston METAR Map Heap Fragmentation"
      unique_id: 40f5ad64-6ebe-4297-8719-59e996a0c94a
      state_topic: "metar/hou/tele/status"
      value_template: "{{value_json['heapFragmentation']}}"
      availability_topic: "metar/hou/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Houston METAR Map Core Version"
      unique_id: c353cbcf-eabc-4508-8625-3fa3fe1b90c8
      state_topic: "metar/hou/tele/status"
      value_template: "{{value_json['espCore']}}"
      availability_topic: "metar/hou/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: HOU METAR Mode
      unique_id: 067e4e78-8d41-4077-8616-02cbb848455e
      state_topic: "metar/hou/tele/mode"
      availability_topic: "metar/hou/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"

input_boolean:
  hou_metar_mode: #Off is METAR and on is temperature...
    name: Houston METAR Map Display Mode

sensor:
  - platform: template
    sensors:
      hou_metar_mode_clean:
        unique_id: c6d01a93-7a94-44b1-930c-428886df1858
        friendly_name: HOU METAR Mode Clean Name
        value_template: >-
          {% if is_state('sensor.hou_metar_mode', 'TEMP') -%}
            Temperature
          {% elif is_state('sensor.hou_metar_mode', 'METAR') -%}
            METAR
          {% endif -%}

automation:
  - alias: Update Houston METAR Map Display Mode
    id: 988861e6-36d6-40c8-96bf-d504c96cec44
    trigger:
      - platform: state
        entity_id: input_boolean.hou_metar_mode
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.hou_metar_mode
                state: "on"
            sequence:
              - service: mqtt.publish
                data:
                  topic: metar/hou/command/set/mode
                  payload: TEMP
                  retain: true
          - conditions:
              - condition: state
                entity_id: input_boolean.hou_metar_mode
                state: "off"
            sequence:
              - service: mqtt.publish
                data:
                  topic: metar/hou/command/set/mode
                  payload: METAR
                  retain: true

  - alias: Houston Map On When Home and Awake
    id: 82d352fc-ce44-4e17-8a9c-fcbf8676ab25
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        to: disarmed
      - platform: state
        entity_id: alarm_control_panel.house
        to: armed_home
    action:
      - service: switch.turn_on
        entity_id: switch.houston_metar_map_power

  - alias: Houston Map Off When Not Home or Awake
    id: ceab912c-e825-4798-8fa0-ade314881bd5
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        to: 
          - armed_away
          - armed_vacation
          - armed_night
    action:
      - service: switch.turn_off
        entity_id: switch.houston_metar_map_power
