switch:
  - platform: mqtt
    name: Texas Cell METAR Map Power
    state_topic: metar/tx-cell/tele/current
    command_topic: metar/tx-cell/command/set/power
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    retain: true
    optimistic: false

input_boolean:
  tx_cell_metar_mode: #Off is METAR and on is temperature...
    name: Texas Cell METAR Map Display Mode

sensor:

  - platform: mqtt
    name: TX Cell METAR Mode
    state_topic: "metar/tx-cell/tele/mode"

  - platform: template
    sensors:
      tx_cell_metar_mode_clean:
        friendly_name: TX Cell METAR Mode Clean Name
        value_template: >-
          {% if is_state('sensor.tx_cell_metar_mode', 'TEMP') -%}
            Temperature
          {% elif is_state('sensor.tx_cell_metar_mode', 'METAR') -%}
            METAR
          {% endif -%}

automation:
  - alias: Update Texas Cell METAR Map Display Mode
    id: 7a37e5a9-a5b9-40c4-8312-a33a4f3bf75e
    trigger:
      - platform: state
        entity_id: input_boolean.tx_cell_metar_mode
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.tx_cell_metar_mode
                state: "on"
            sequence:
              - service: mqtt.publish
                data:
                  topic: metar/tx-cell/command/set/mode
                  payload: TEMP
                  retain: true
          - conditions:
              - condition: state
                entity_id: input_boolean.tx_cell_metar_mode
                state: "off"
            sequence:
              - service: mqtt.publish
                data:
                  topic: metar/tx-cell/command/set/mode
                  payload: METAR
                  retain: true

  - alias: Texas Cell Map On When at work
    id: caec31c4-7d2c-42cc-ad0a-e7eda7d34d53
    trigger:
      - platform: state
        entity_id: person.shawn_mccoy
        to: "work"
    action:
      - service: switch.turn_on
        entity_id: switch.texas_cell_metar_map_power

  - alias: Texas Cell Map Off When at work
    id: 16dda682-e1e6-4190-90c3-b41d392d3a02
    trigger:
      - platform: state
        entity_id: person.shawn_mccoy
        from: "work"
        to: "not_home"
        for:
            minutes: 5
    action:
      - service: switch.turn_off
        entity_id: switch.texas_cell_metar_map_power
