switch:
  - platform: mqtt
    name: US METAR Map Power
    state_topic: metar/usa/tele/current
    command_topic: metar/usa/command/set/power
    availability_topic: metar/usa/tele/LWT
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    optimistic: false
    payload_available: "Online"
    payload_not_available: "Offline"

input_boolean:
  us_metar_mode: #Off is METAR and on is temperature...
    name: US METAR Map Display Mode

sensor:
  #Driver Status Messages

  - platform: mqtt
    name: "US METAR Map Version"
    state_topic: "metar/usa/tele/status"
    value_template: "{{value_json['espVersion']}}"
    availability_topic: "metar/usa/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "US METAR Map Uptime"
    state_topic: "metar/usa/tele/status"
    value_template: "{{value_json['espUptime']}}"
    availability_topic: "metar/usa/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "US METAR Map RSSI"
    state_topic: "metar/usa/tele/status"
    value_template: "{{value_json['signalStrength']}}"
    availability_topic: "metar/usa/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "US METAR Map IP"
    state_topic: "metar/usa/tele/status"
    value_template: "{{value_json['mapIP']}}"
    availability_topic: "metar/usa/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "US METAR Map Free Heap"
    state_topic: "metar/usa/tele/status"
    value_template: "{{value_json['heapFree']}}"
    availability_topic: "metar/usa/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "US METAR Map Heap Fragmentation"
    state_topic: "metar/usa/tele/status"
    value_template: "{{value_json['heapFragmentation']}}"
    availability_topic: "metar/usa/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "US METAR Map Core Version"
    state_topic: "metar/usa/tele/status"
    value_template: "{{value_json['espCore']}}"
    availability_topic: "metar/usa/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: US METAR Mode
    state_topic: "metar/usa/tele/mode"
    availability_topic: "metar/usa/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: template
    sensors:
      us_metar_mode_clean:
        friendly_name: US METAR Mode Clean Name
        value_template: >-
          {% if is_state('sensor.us_metar_mode', 'TEMP') -%}
            Temperature
          {% elif is_state('sensor.us_metar_mode', 'METAR') -%}
            METAR
          {% endif -%}

automation:
  - alias: Update US METAR Map Display Mode
    id: 63265124-5428-4754-9d4f-83626782f6b4
    trigger:
      - platform: state
        entity_id: input_boolean.us_metar_mode
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.us_metar_mode
                state: "on"
            sequence:
              - service: mqtt.publish
                data:
                  topic: metar/usa/command/set/mode
                  payload: TEMP
                  retain: true
          - conditions:
              - condition: state
                entity_id: input_boolean.us_metar_mode
                state: "off"
            sequence:
              - service: mqtt.publish
                data:
                  topic: metar/usa/command/set/mode
                  payload: METAR
                  retain: true

  - alias: US Map On When Home and Awake
    id: fcb8c569-08fb-4904-a38e-70a5446cd21a
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        to: disarmed
      - platform: state
        entity_id: alarm_control_panel.house
        to: armed_home
    action:
      - service: switch.turn_on
        entity_id: switch.us_metar_map_power

  - alias: US Map Off When Home and Awake
    id: abfd17a1-651d-4f18-846c-8f0a9fb854e3
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        to: armed_away
      - platform: state
        entity_id: alarm_control_panel.house
        to: armed_night
    action:
      - service: switch.turn_off
        entity_id: switch.us_metar_map_power
