mqtt:
  switch:
    - name: HOU Cell METAR Map Power
      unique_id: 21b744b6-b398-4c03-9d26-0cad209be288
      state_topic: metar/hou-cell/tele/current
      command_topic: metar/hou-cell/command/set/power
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      retain: true
      optimistic: false

  sensor:
    - name: HOU Cell METAR Mode
      state_topic: "metar/hou-cell/tele/mode"

input_boolean:
  hou_cell_metar_mode: #Off is METAR and on is temperature...
    name: HOU Cell METAR Map Display Mode

sensor:
  - platform: template
    sensors:
      hou_cell_metar_mode_clean:
        unique_id: 8fa725a8-e6b9-4105-a89d-ed2e3ebe0f0d
        friendly_name: HOU Cell METAR Mode Clean Name
        value_template: >-
          {% if is_state('sensor.hou_cell_metar_mode', 'TEMP') -%}
            Temperature
          {% elif is_state('sensor.hou_cell_metar_mode', 'METAR') -%}
            METAR
          {% endif -%}

automation:
  - alias: Update HOU Cell METAR Map Display Mode
    id: ed5950ba-9d38-4d35-b5be-83883a03a3d5
    trigger:
      - platform: state
        entity_id: input_boolean.hou_cell_metar_mode
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.hou_cell_metar_mode
                state: "on"
            sequence:
              - service: mqtt.publish
                data:
                  topic: metar/hou-cell/command/set/mode
                  payload: TEMP
                  retain: true
          - conditions:
              - condition: state
                entity_id: input_boolean.hou_cell_metar_mode
                state: "off"
            sequence:
              - service: mqtt.publish
                data:
                  topic: metar/hou-cell/command/set/mode
                  payload: METAR
                  retain: true

  - alias: HOU Cell Map On When at work
    id: c7bef6b1-9f32-49d3-b624-7e5c7ac3f98c
    trigger:
      - platform: state
        entity_id: person.shawn_mccoy
        to: "work"
    action:
      - service: switch.turn_on
        entity_id: switch.hou_cell_metar_map_power

  - alias: HOU Cell Map Off When at work
    id: 4f491d21-7a6a-41eb-b8f5-3a258a7acd82
    trigger:
      - platform: state
        entity_id: person.shawn_mccoy
        from: "work"
        to: "not_home"
        for:
            minutes: 5
    action:
      - service: switch.turn_off
        entity_id: switch.hou_cell_metar_map_power
