- alias: Garage Light Auto On
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('sensor.elk_garage_entry', 'physical_status', 'open') }}"
    - platform: state
      entity_id: sensor.elk_garage_motion
      from: Normal
      to: Violated
    - platform: state
      entity_id: sensor.elk_garage_door
      from: Normal
      to: Violated
  condition:
    - condition: state
      entity_id: switch.garage_light
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.garage_lights
    - service: timer.start
      entity_id: timer.garage_light

- alias: Garage Light Timer Reset
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('sensor.elk_garage_entry', 'physical_status', 'open') }}"
    - platform: state
      entity_id: sensor.elk_garage_motion
      from: Normal
      to: Violated
    - platform: state
      entity_id: sensor.elk_garage_door
      from: Normal
      to: Violated
  condition:
    - condition: state
      entity_id: switch.garage_lights
      state: "on"
  action:
    - service: timer.start
      entity_id: timer.garage_light

- alias: Garage Light Auto Off
  trigger:
    - event_data:
        entity_id: timer.garage_light
      event_type: timer.finished
      platform: event
  action:
    - service: switch.turn_off
      entity_id: switch.garage_lights

- alias: Auto Attic Light
  trigger:
    - entity_id: sensor.elk_attic_door
      platform: state
      to: Violated
    - entity_id: sensor.elk_attic_door
      platform: state
      to: Normal
  action:
    - service_template: >
        {% if states('sensor.elk_attic_door') == "Violated" %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      entity_id: light.attic_light

- alias: Auto Guest Closet Light
  trigger:
    - entity_id: sensor.elk_guest_closet_door
      platform: state
      to: Violated
    - entity_id: sensor.elk_guest_closet_door
      platform: state
      to: Normal
  action:
    - service_template: >
        {% if states('sensor.elk_guest_closet_door') == "Violated" %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
      entity_id: switch.guest_closet_light

- alias: Auto Pantry Light
  trigger:
    - entity_id: sensor.elk_pantry_door
      platform: state
      to: Violated
    - entity_id: sensor.elk_pantry_door
      platform: state
      to: Normal
  action:
    - service_template: >
        {% if states('sensor.elk_pantry_door') == "Violated" %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      entity_id: light.pantry_light

- alias: Auto Server Closet Light
  trigger:
    - entity_id: sensor.elk_server_closet_door
      platform: state
      to: Violated
    - entity_id: sensor.elk_server_closet_door
      platform: state
      to: Normal
  action:
    - service_template: >
        {% if states('sensor.elk_server_closet_door') == "Violated" %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
      entity_id: switch.server_closet_light

- alias: Auto Shed Light
  trigger:
    - entity_id: sensor.elk_shed_door
      platform: state
      to: Violated
    - entity_id: sensor.elk_shed_door
      platform: state
      to: Normal
  action:
    - service_template: >
        {% if states('sensor.elk_shed_door') == "Violated" %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
      entity_id: switch.shed_inside_light

- alias: Master Closet Light Auto On
  trigger:
    - entity_id: sensor.elk_master_closet_motion
      platform: state
      to: Violated
  action:
    - service: switch.turn_on
      entity_id: switch.master_closet_light

- alias: Master Closet Light Auto Off
  trigger:
    - entity_id: sensor.elk_master_closet_motion
      platform: state
      to: Normal
      for:
        minutes: 2
  action:
    - service: switch.turn_off
      entity_id: switch.master_closet_light

- alias: Utility Room Light Auto On
  trigger:
    - entity_id: sensor.elk_utility_motion
      platform: state
      to: Violated
  action:
    - service: light.turn_on
      entity_id: light.utility_room_light

- alias: Uitlity Room Light Auto Off
  trigger:
    - entity_id: sensor.elk_utility_motion
      platform: state
      to: Normal
      for:
        minutes: 1
  action:
    - service: light.turn_off
      entity_id: light.utility_room_light

- alias: Auto Entry Closet Light On
  trigger:
    - entity_id: sensor.elk_entry_closet_door
      platform: state
      to: Violated
  action:
    - service: scene.create
      data:
        scene_id: entry_closet_restore
        snapshot_entities:
          - light.entry_light
    - service: light.turn_on
      entity_id: light.entry_light

- alias: Auto Entry Closet Light Off
  trigger:
    - entity_id: sensor.elk_entry_closet_door
      platform: state
      to: Normal
  action:
    - service: scene.turn_on
      entity_id: scene.entry_closet_restore

- alias: Auto Hall Closet Light On
  trigger:
    - entity_id: sensor.elk_hall_closet_door
      platform: state
      to: Violated
  action:
    - service: scene.create
      data:
        scene_id: hall_closet_restore
        snapshot_entities:
          - light.hallway_light
    - service: light.turn_on
      entity_id: light.hallway_light

- alias: Auto Hall Closet Light Off
  trigger:
    - entity_id: sensor.elk_hall_closet_door
      platform: state
      to: Normal
  action:
    - service: scene.turn_on
      entity_id: scene.hall_closet_restore
