#################################################################
#                                                               #
#                    Packages/climate_hvac                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                            Climate                            #
#                                                               #
#################################################################

climate:
  - platform: honeywell
    username: !secret tcc_user
    password: !secret tcc_pass
    scan_interval: 600

#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:
  ####################################################
  #                                                  #
  #            Binary Sensor - Template              #
  #                                                  #
  ####################################################

  - platform: template
    sensors:
      hvac_system_fan:
        friendly_name: "HVAC System Fan Call"
        value_template: "{{ is_state('sensor.hvac_system_state', 'Fan') }}"

      hvac_system_heat:
        friendly_name: "HVAC System Heat Call"
        value_template: "{{ is_state('sensor.hvac_system_state', 'Heat') }}"

      hvac_system_cool:
        friendly_name: "HVAC System Cool Call"
        value_template: "{{ is_state('sensor.hvac_system_state', 'Cool') }}"

      hvac_zone_1_fan:
        friendly_name: "HVAC Zone 1 Fan Call"
        value_template: "{{ is_state('sensor.hvac_zone_1_state', 'Fan') }}"

      hvac_zone_1_heat:
        friendly_name: "HVAC Zone 1 Heat Call"
        value_template: "{{ is_state('sensor.hvac_zone_1_state', 'Heat') }}"

      hvac_zone_1_cool:
        friendly_name: "HVAC Zone 1 Cool Call"
        value_template: "{{ is_state('sensor.hvac_zone_1_state', 'Cool') }}"

      hvac_zone_2_fan:
        friendly_name: "HVAC Zone 2 Fan Call"
        value_template: "{{ is_state('sensor.hvac_zone_2_state', 'Fan') }}"

      hvac_zone_2_heat:
        friendly_name: "HVAC Zone 2 Heat Call"
        value_template: "{{ is_state('sensor.hvac_zone_2_state', 'Heat') }}"

      hvac_zone_2_cool:
        friendly_name: "HVAC Zone 2 Cool Call"
        value_template: "{{ is_state('sensor.hvac_zone_2_state', 'Cool') }}"

      hvac_zone_3_fan:
        friendly_name: "HVAC Zone 3 Fan Call"
        value_template: "{{ is_state('sensor.hvac_zone_3_state', 'Fan') }}"

      hvac_zone_3_heat:
        friendly_name: "HVAC Zone 3 Heat Call"
        value_template: "{{ is_state('sensor.hvac_zone_3_state', 'Heat') }}"

      hvac_zone_3_cool:
        friendly_name: "HVAC Zone 3 Cool Call"
        value_template: "{{ is_state('sensor.hvac_zone_3_state', 'Cool') }}"
  
  - platform: mqtt
    name: HVAC Leak Detector 1
    state_topic: "hvac/tele/system"
    value_template: "{{value_json['Leak1']}}"
    availability_topic: "hvac/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: moisture

  - platform: mqtt
    name: HVAC Leak Detector 2
    state_topic: "hvac/tele/system"
    value_template: "{{value_json['Leak2']}}"
    availability_topic: "hvac/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: moisture

#################################################################
#                                                               #
#                            Sensors                            #
#                                                               #
#################################################################

sensor:
  - platform: mqtt
    name: HVAC System State
    state_topic: "hvac/tele/system"
    value_template: "{{value_json['System']}}"
    availability_topic: "hvac/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: HVAC Zone 1 State
    state_topic: "hvac/tele/system"
    value_template: "{{value_json['Zone1']}}"
    availability_topic: "hvac/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: HVAC Zone 2 State
    state_topic: "hvac/tele/system"
    value_template: "{{value_json['Zone2']}}"
    availability_topic: "hvac/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: HVAC Zone 3 State
    state_topic: "hvac/tele/system"
    value_template: "{{value_json['Zone3']}}"
    availability_topic: "hvac/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: HVAC Zone 1 Damper Position
    state_topic: "hvac/tele/system"
    value_template: "{{value_json['Damper1']}}"
    availability_topic: "hvac/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: HVAC Zone 2 Damper Position
    state_topic: "hvac/tele/system"
    value_template: "{{value_json['Damper2']}}"
    availability_topic: "hvac/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: HVAC Zone 3 Damper Position
    state_topic: "hvac/tele/system"
    value_template: "{{value_json['Damper3']}}"
    availability_topic: "hvac/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: HVAC Zone 4 Damper Position
    state_topic: "hvac/tele/system"
    value_template: "{{value_json['Damper4']}}"
    availability_topic: "hvac/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: HVAC Fan Current
    state_topic: "hvac/tele/system"
    value_template: "{{value_json['FanCurrent']}}"
    availability_topic: "hvac/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unit_of_measurement: "A"
  - platform: mqtt
    name: HVAC Fan Differential Pressure
    state_topic: "hvac/tele/system"
    value_template: "{{value_json['FanDP']}}"
    availability_topic: "hvac/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unit_of_measurement: "Pa"
  - platform: mqtt
    name: HVAC Fan Differential Pressure Temperature
    state_topic: "hvac/tele/system"
    value_template: "{{value_json['FanDPTemp']}}"
    availability_topic: "hvac/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unit_of_measurement: "°C"
    device_class: temperature
  - platform: mqtt
    name: HVAC Filter Differential Pressure
    state_topic: "hvac/tele/system"
    value_template: "{{value_json['FilterDP']}}"
    availability_topic: "hvac/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unit_of_measurement: "Pa"
  - platform: mqtt
    name: HVAC Filter Differential Pressure Temperature
    state_topic: "hvac/tele/system"
    value_template: "{{value_json['FilterDPTemp']}}"
    availability_topic: "hvac/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unit_of_measurement: "°C"
    device_class: temperature
  - platform: mqtt
    name: HVAC Manager Ambient Temperature
    state_topic: "hvac/tele/system"
    value_template: "{{value_json['BoardTemp']}}"
    availability_topic: "hvac/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    unit_of_measurement: "°C"
    device_class: temperature





  ####################################################
  #                                                  #
  #                Sensor - Template                 #
  #                                                  #
  ####################################################

  - platform: template
    sensors:
      
      hvac_system_runtime:
        friendly_name: "HVAC Total System Runtime"
        unit_of_measurement: "h"
        value_template: >-
          {{ ((states('sensor.hvac_system_fan_runtime') | float(none)) +
          (states('sensor.hvac_system_heat_runtime') | float(none)) +
          (states('sensor.hvac_system_cool_runtime') | float(none))) | round(2) }}

      hvac_zone_1_runtime:
        friendly_name: "HVAC Zone 1 Total Runtime"
        unit_of_measurement: "h"
        value_template: >-
          {{ ((states('sensor.hvac_zone_1_fan_runtime') | float(none)) +
          (states('sensor.hvac_zone_1_heat_runtime') | float(none)) +
          (states('sensor.hvac_zone_1_cool_runtime') | float(none))) | round(2) }}

      hvac_zone_2_runtime:
        friendly_name: "HVAC Zone 2 Total Runtime"
        unit_of_measurement: "h"
        value_template: >-
          {{ ((states('sensor.hvac_zone_2_fan_runtime') | float(none)) +
          (states('sensor.hvac_zone_2_heat_runtime') | float(none)) +
          (states('sensor.hvac_zone_2_cool_runtime') | float(none))) | round(2) }}

      hvac_zone_3_runtime:
        friendly_name: "HVAC Zone 3 Total Runtime"
        unit_of_measurement: "h"
        value_template: >-
          {{ ((states('sensor.hvac_zone_3_fan_runtime') | float(none)) +
          (states('sensor.hvac_zone_3_heat_runtime') | float(none)) +
          (states('sensor.hvac_zone_3_cool_runtime') | float(none))) | round(2) }}

  ####################################################
  #                                                  #
  #                Sensor - History                  #
  #                                                  #
  ####################################################

  - platform: history_stats
    name: HVAC System Fan Runtime
    entity_id: binary_sensor.hvac_system_fan
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: HVAC System Heat Runtime
    entity_id: binary_sensor.hvac_system_heat
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: HVAC System Cool Runtime
    entity_id: binary_sensor.hvac_system_cool
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: HVAC Zone 1 Fan Runtime
    entity_id: binary_sensor.hvac_zone_1_fan
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: HVAC Zone 1 Heat Runtime
    entity_id: binary_sensor.hvac_zone_1_heat
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: HVAC Zone 1 Cool Runtime
    entity_id: binary_sensor.hvac_zone_1_cool
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: HVAC Zone 2 Fan Runtime
    entity_id: binary_sensor.hvac_zone_2_fan
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: HVAC Zone 2 Heat Runtime
    entity_id: binary_sensor.hvac_zone_2_heat
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: HVAC Zone 2 Cool Runtime
    entity_id: binary_sensor.hvac_zone_2_cool
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: HVAC Zone 3 Fan Runtime
    entity_id: binary_sensor.hvac_zone_3_fan
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: HVAC Zone 3 Heat Runtime
    entity_id: binary_sensor.hvac_zone_3_heat
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: HVAC Zone 3 Cool Runtime
    entity_id: binary_sensor.hvac_zone_3_cool
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

#################################################################
#                                                               #
#                         Input_Boolean                         #
#                                                               #
#################################################################

input_boolean:
  hvac_geofence:
    name: In HVAC Geofence
    icon: mdi:crosshairs-gps
