#################################################################
#                                                               #
#                    Packages/climate_hvac                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                            Climate                            #
#                                                               #
#################################################################

climate:
  - platform: honeywell
    username: !secret tcc_user
    password: !secret tcc_pass
    scan_interval: 600

#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#            Binary Sensor - Template              #
#                                                  #
####################################################

  - platform: template
    sensors:

      hvac_system_fan:
        friendly_name: "HVAC System Fan Call"
        value_template: "{{ is_state('sensor.elk_hvac_fan_call', 'Violated') and is_state('sensor.elk_hvac_heat_call', 'Normal') and is_state('sensor.elk_hvac_cool_call', 'Normal') }}"

      hvac_system_heat:
        friendly_name: "HVAC System Heat Call"
        value_template: "{{ is_state('sensor.elk_hvac_heat_call', 'Violated') }}"

      hvac_system_cool:
        friendly_name: "HVAC System Cool Call"
        value_template: "{{ is_state('sensor.elk_hvac_cool_call', 'Violated') }}"

      hvac_zone_1_fan:
        friendly_name: "HVAC Zone 1 Fan Call"
        value_template: "{{ is_state('sensor.elk_hvac_fan_call', 'Violated') and is_state('sensor.elk_hvac_heat_call', 'Normal') and is_state('sensor.elk_hvac_cool_call', 'Normal') and is_state('sensor.elk_hvac_zone_1_closed', 'Normal') }}"
      
      hvac_zone_1_heat:
        friendly_name: "HVAC Zone 1 Heat Call"
        value_template: "{{ is_state('sensor.elk_hvac_heat_call', 'Violated') and is_state('sensor.elk_hvac_zone_1_closed', 'Normal') }}"

      hvac_zone_1_cool:
        friendly_name: "HVAC Zone 1 Cool Call"
        value_template: "{{ is_state('sensor.elk_hvac_cool_call', 'Violated') and is_state('sensor.elk_hvac_zone_1_closed', 'Normal') }}"

      hvac_zone_2_fan:
        friendly_name: "HVAC Zone 2 Fan Call"
        value_template: "{{ is_state('sensor.elk_hvac_fan_call', 'Violated') and is_state('sensor.elk_hvac_heat_call', 'Normal') and is_state('sensor.elk_hvac_cool_call', 'Normal') and is_state('sensor.elk_hvac_zone_2_closed', 'Normal') }}"
      
      hvac_zone_2_heat:
        friendly_name: "HVAC Zone 2 Heat Call"
        value_template: "{{ is_state('sensor.elk_hvac_heat_call', 'Violated') and is_state('sensor.elk_hvac_zone_2_closed', 'Normal') }}"

      hvac_zone_2_cool:
        friendly_name: "HVAC Zone 2 Cool Call"
        value_template: "{{ is_state('sensor.elk_hvac_cool_call', 'Violated') and is_state('sensor.elk_hvac_zone_2_closed', 'Normal') }}"
      
      hvac_zone_3_fan:
        friendly_name: "HVAC Zone 3 Fan Call"
        value_template: "{{ is_state('sensor.elk_hvac_fan_call', 'Violated') and is_state('sensor.elk_hvac_heat_call', 'Normal') and is_state('sensor.elk_hvac_cool_call', 'Normal') and is_state('sensor.elk_hvac_zone_3_closed', 'Normal') }}"
      
      hvac_zone_3_heat:
        friendly_name: "HVAC Zone 3 Heat Call"
        value_template: "{{ is_state('sensor.elk_hvac_heat_call', 'Violated') and is_state('sensor.elk_hvac_zone_3_closed', 'Normal') }}"

      hvac_zone_3_cool:
        friendly_name: "HVAC Zone 3 Cool Call"
        value_template: "{{ is_state('sensor.elk_hvac_cool_call', 'Violated') and is_state('sensor.elk_hvac_zone_3_closed', 'Normal') }}"

#################################################################
#                                                               #
#                            Sensors                            #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                Sensor - Template                 #
#                                                  #
####################################################

  - platform: template
    sensors:

      hvac_system_state:
        friendly_name: "HVAC System Current State"
        value_template: >-
          {% if is_state("binary_sensor.hvac_system_cool", 'on') -%}
            Cool
          {% elif is_state("binary_sensor.hvac_system_heat", 'on') -%}
            Heat
          {% elif is_state("binary_sensor.hvac_system_fan", 'on') -%}
            Fan
          {%- else -%}
            Idle
          {%- endif %}

      hvac_zone_1_state:
        friendly_name: "HVAC Zone 1 Current State"
        value_template: >-
          {% if is_state("binary_sensor.hvac_zone_1_cool", 'on') -%}
            Cool
          {% elif is_state("binary_sensor.hvac_zone_1_heat", 'on') -%}
            Heat
          {% elif is_state("binary_sensor.hvac_zone_1_fan", 'on') -%}
            Fan
          {%- else -%}
            Idle
          {%- endif %}

      hvac_zone_2_state:
        friendly_name: "HVAC Zone 2 Current State"
        value_template: >-
          {% if is_state("binary_sensor.hvac_zone_2_cool", 'on') -%}
            Cool
          {% elif is_state("binary_sensor.hvac_zone_2_heat", 'on') -%}
            Heat
          {% elif is_state("binary_sensor.hvac_zone_2_fan", 'on') -%}
            Fan
          {%- else -%}
            Idle
          {%- endif %}
      
      hvac_zone_3_state:
        friendly_name: "HVAC Zone 3 Current State"
        value_template: >-
          {% if is_state("binary_sensor.hvac_zone_3_cool", 'on') -%}
            Cool
          {% elif is_state("binary_sensor.hvac_zone_3_heat", 'on') -%}
            Heat
          {% elif is_state("binary_sensor.hvac_zone_3_fan", 'on') -%}
            Fan
          {%- else -%}
            Idle
          {%- endif %}

      hvac_system_runtime:
        friendly_name: "HVAC Total System Runtime"
        unit_of_measurement: 'h'
        value_template: >-
          {{ ((states('sensor.hvac_system_fan_runtime') | float) +
          (states('sensor.hvac_system_heat_runtime') | float) +
          (states('sensor.hvac_system_cool_runtime') | float)) | round(2) }}
      
      hvac_zone_1_runtime:
        friendly_name: "HVAC Zone 1 Total Runtime"
        unit_of_measurement: 'h'
        value_template: >-
          {{ ((states('sensor.hvac_zone_1_fan_runtime') | float) +
          (states('sensor.hvac_zone_1_heat_runtime') | float) +
          (states('sensor.hvac_zone_1_cool_runtime') | float)) | round(2) }}

      hvac_zone_2_runtime:
        friendly_name: "HVAC Zone 2 Total Runtime"
        unit_of_measurement: 'h'
        value_template: >-
          {{ ((states('sensor.hvac_zone_2_fan_runtime') | float) +
          (states('sensor.hvac_zone_2_heat_runtime') | float) +
          (states('sensor.hvac_zone_2_cool_runtime') | float)) | round(2) }}

      hvac_zone_3_runtime:
        friendly_name: "HVAC Zone 3 Total Runtime"
        unit_of_measurement: 'h'
        value_template: >-
          {{ ((states('sensor.hvac_zone_3_fan_runtime') | float) +
          (states('sensor.hvac_zone_3_heat_runtime') | float) +
          (states('sensor.hvac_zone_3_cool_runtime') | float)) | round(2) }}

      hvac_zone_1_damper_position:
        friendly_name: "HVAC Zone 1 Damper Position"
        value_template: >-
          {% if is_state("switch.elk_hvac_zone_1_dump", 'on') and is_state("sensor.elk_hvac_zone_1_closed", 'Normal') -%}
            Open Bypass
          {% elif is_state("switch.elk_hvac_zone_1_dump", 'on') and is_state("sensor.elk_hvac_zone_1_closed", 'Violated') -%}
            Closed Bypass
          {% elif is_state("switch.elk_hvac_zone_1_dump", 'off') and is_state("sensor.elk_hvac_zone_1_closed", 'Normal') -%}
            Open
          {% elif is_state("switch.elk_hvac_zone_1_dump", 'off') and is_state("sensor.elk_hvac_zone_1_closed", 'Violated') -%}
            Closed
          {%- endif %}
      
      hvac_zone_2_damper_position:
        friendly_name: "HVAC Zone 2 Damper Position"
        value_template: >-
          {% if is_state("switch.elk_hvac_zone_2_dump", 'on') and is_state("sensor.elk_hvac_zone_2_closed", 'Normal') -%}
            Open Bypass
          {% elif is_state("switch.elk_hvac_zone_2_dump", 'on') and is_state("sensor.elk_hvac_zone_2_closed", 'Violated') -%}
            Closed Bypass
          {% elif is_state("switch.elk_hvac_zone_2_dump", 'off') and is_state("sensor.elk_hvac_zone_2_closed", 'Normal') -%}
            Open
          {% elif is_state("switch.elk_hvac_zone_2_dump", 'off') and is_state("sensor.elk_hvac_zone_2_closed", 'Violated') -%}
            Closed
          {%- endif %}

      hvac_zone_3_damper_position:
        friendly_name: "HVAC Zone 3 Damper Position"
        value_template: >-
          {% if is_state("switch.elk_hvac_zone_3_dump", 'on') and is_state("sensor.elk_hvac_zone_3_closed", 'Normal') -%}
            Open Bypass
          {% elif is_state("switch.elk_hvac_zone_3_dump", 'on') and is_state("sensor.elk_hvac_zone_3_closed", 'Violated') -%}
            Closed Bypass
          {% elif is_state("switch.elk_hvac_zone_3_dump", 'off') and is_state("sensor.elk_hvac_zone_3_closed", 'Normal') -%}
            Open
          {% elif is_state("switch.elk_hvac_zone_3_dump", 'off') and is_state("sensor.elk_hvac_zone_3_closed", 'Violated') -%}
            Closed
          {%- endif %}

####################################################
#                                                  #
#                Sensor - History                  #
#                                                  #
####################################################

  - platform: history_stats
    name: HVAC System Fan Runtime
    entity_id: binary_sensor.hvac_system_fan
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: HVAC System Heat Runtime
    entity_id: binary_sensor.hvac_system_heat
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: HVAC System Cool Runtime
    entity_id: binary_sensor.hvac_system_cool
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: HVAC Zone 1 Fan Runtime
    entity_id: binary_sensor.hvac_zone_1_fan
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: HVAC Zone 1 Heat Runtime
    entity_id: binary_sensor.hvac_zone_1_heat
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: HVAC Zone 1 Cool Runtime
    entity_id: binary_sensor.hvac_zone_1_cool
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: HVAC Zone 2 Fan Runtime
    entity_id: binary_sensor.hvac_zone_2_fan
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: HVAC Zone 2 Heat Runtime
    entity_id: binary_sensor.hvac_zone_2_heat
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: HVAC Zone 2 Cool Runtime
    entity_id: binary_sensor.hvac_zone_2_cool
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: HVAC Zone 3 Fan Runtime
    entity_id: binary_sensor.hvac_zone_3_fan
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: HVAC Zone 3 Heat Runtime
    entity_id: binary_sensor.hvac_zone_3_heat
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: HVAC Zone 3 Cool Runtime
    entity_id: binary_sensor.hvac_zone_3_cool
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

#################################################################
#                                                               #
#                         Input_Boolean                         #
#                                                               #
#################################################################

input_boolean:
  hvac_geofence:
    name: In HVAC Geofence
    icon: mdi:crosshairs-gps