automation:
  # Add previous day's runtime to input_number each night
  - alias: Store HVAC runtime nightly
    initial_state: "on"
    trigger:
      - platform: time
        at: "00:00:01"
    action:
      - service: homeassistant.update_entity
        entity_id:
          - sensor.hvac_runtime_yesterday
          - sensor.hvac_runtime_today
      - service: input_number.set_value
        entity_id: input_number.hvac_runtime
        data_template:
          value: "{{ ((states('sensor.furnace_filter_life') | float) + (states('sensor.hvac_runtime_yesterday') | float)) | round(1) }}"

  - alias: Reset Filter Timer From NFC
    trigger:
      - platform: event
        event_type: tag_scanned
        event_data:
          tag_id: !secret hvac_filter_nfc
    action:
      - service: script.furnace_filter_date

  - alias: Reset Bleach Timer From NFC
    trigger:
      - platform: event
        event_type: tag_scanned
        event_data:
          tag_id: !secret hvac_bleach_nfc
    action:
      - service: script.furnace_bleach_date
  - alias: Record Last HVAC Cool Cycle
    trigger:
      - platform: state
        entity_id: binary_sensor.hvac_system_cool
        to: "on"
    action:
      - service: input_text.set_value
        entity_id: input_text.furnace_last_cool
        data_template:
          value: "{{ now() }}"

  - alias: Record Beginning Filter DP
    trigger:
      - platform: state
        entity_id: binary_sensor.hvac_running
        to: "on"
        for: 
          seconds: 20
    condition:
      - condition: state
        entity_id: input_boolean.record_beginning_dp
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.record_beginning_dp
      - service: input_number.set_value
        entity_id: input_number.beginning_filter_dp
        data_template:
          value: "{{ states('sensor.hvac_filter_differential_pressure') }}"

  - alias: Record Maximum Filter DP
    trigger:
      - platform: template
        value_template: "{{ states('sensor.hvac_filter_differential_pressure') | float > states('input_number.maximum_filter_dp') | float }}"
    action:
      - service: input_number.set_value
        entity_id: input_number.maximum_filter_dp
        data_template:
          value: "{{ states('sensor.hvac_filter_differential_pressure') }}"

binary_sensor:
  - platform: template
    sensors:
      hvac_running:
        friendly_name: HVAC Running
        value_template: "{{ not is_state('sensor.hvac_system_state', 'Idle') }}"

      hvac_filter_needs_replacement:
        friendly_name: HVAC Filter Needs Replacement
        value_template: "{{ states('sensor.furnace_filter_life') | int > states('input_number.replacement_threshold') | int }}"

      hvac_needs_bleach:
        friendly_name: HVAC Needs Bleach
        value_template: >
          {% set x = states('sensor.time') %}
          {{ ((((as_timestamp(now()) - (as_timestamp(states.input_text.furnace_bleach.state))) | int /60/1440) | round(0)) > 30) and ( (((as_timestamp(now()) - (as_timestamp(states.input_text.furnace_last_cool.state))) | int /60/1440) | round(0)) <= 30 )}}

sensor:
  # Runtime yesterday (for use in storing runtime each night)
  - platform: history_stats
    name: HVAC runtime yesterday
    entity_id: binary_sensor.hvac_running
    state: "on"
    type: time
    duration:
      hours: 24
    end: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"

  # Runtime current day before filter change script is called
  - platform: history_stats
    name: HVAC runtime before last filter change
    entity_id: binary_sensor.hvac_running
    state: "on"
    type: time
    start: "{{ as_timestamp(now().replace(hour=0).replace(minute=0).replace(second=0)) }}"
    end: "{{ as_timestamp(states('input_text.furnace_filter')) }}"

  # Today's Runtime
  - platform: history_stats
    name: HVAC runtime today
    entity_id: binary_sensor.hvac_running
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

  # Runtime last 7 days (for use in calculating rolling runtime average)
  - platform: history_stats
    name: HVAC runtime last 7 days
    entity_id: binary_sensor.hvac_running
    state: "on"
    type: time
    end: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    duration:
      days: 7

  - platform: template
    sensors:
      # Used to display current total runtime in frontend
      furnace_filter_life:
        friendly_name: "Filter runtime"
        value_template: >
          {% set active = states('sensor.hvac_runtime_today') | float %}
          {% set runtime = states('input_number.hvac_runtime') | float %}
          {{ (runtime + active) | round(1) }}
        unit_of_measurement: "h"

      # Calculate average runtime in the last 7 days
      average_total_runtime_week:
        friendly_name: "Average total runtime last 7 days"
        value_template: "{{ ((states('sensor.hvac_runtime_last_7_days') | float) / 7) | round(2) }}"
        unit_of_measurement: "h"

      # Calculate number of days until filter will need to be changed based on replacement threshold and rolling average
      furnace_filter_days_remaining:
        friendly_name: "Furnace filter days remaining"
        value_template: >
          {% if (states('sensor.average_total_runtime_week') | float) == 0 %}
            > 30
          {% elif ((((states('input_number.replacement_threshold') | float) - (states('sensor.furnace_filter_life') | float)) / (states('sensor.average_total_runtime_week') | float)) | round(0)) > 30 %}
            > 30
          {% else %}
            {{ (((states('input_number.replacement_threshold') | float) - (states('sensor.furnace_filter_life') | float)) / (states('sensor.average_total_runtime_week') | float)) | round(0) }}
          {% endif %}
        unit_of_measurement: "d"

      furnace_filter_last_replaced:
        friendly_name: Last Replaced
        value_template: "{{ states('input_text.furnace_filter')[:10] }}"

      furnace_last_bleached:
        friendly_name: Last Bleached
        value_template: "{{ states('input_text.furnace_bleach')[:10] }}"

      furnace_service_required:
        friendly_name: HVAC Service Required
        value_template: >-
          {% if is_state('binary_sensor.hvac_needs_bleach', 'on') -%}
            Bleach
          {% elif is_state('binary_sensor.hvac_filter_needs_replacement', 'on') -%}
            Filter
          {% else -%}
            OK
          {% endif -%}

      beginning_filter_dp:
        friendly_name: Beginning Filter Differential Pressure
        value_template: "{{ states('input_number.beginning_filter_dp') }}"
        unit_of_measurement: "Pa"

      maximum_filter_dp:
        friendly_name: Maximum Filter Differential Pressure
        value_template: "{{ states('input_number.maximum_filter_dp') }}"
        unit_of_measurement: "Pa"

      filter_dp_increase:
        friendly_name: Filter Differential Pressure Increase
        value_template: >-
          {% if (states('sensor.beginning_filter_dp') | float) > 0 %}
            {{ (((states('sensor.maximum_filter_dp') | float - states('sensor.beginning_filter_dp') | float) / states('sensor.beginning_filter_dp') | float) * 100) | round(2) }}
          {% else -%}
            0
          {% endif -%}
        unit_of_measurement: "%"

script:
  # Reset filter change date and set total runtime to zero
  furnace_filter_date:
    alias: Furnace filter change date
    sequence:
      - service: input_text.set_value
        entity_id: input_text.furnace_filter
        data_template:
          value: "{{ now() }}"
      - service: homeassistant.update_entity
        entity_id: sensor.hvac_runtime_before_last_filter_change
      - service: input_number.set_value
        entity_id: input_number.hvac_runtime
        data_template:
          value: >
            {% set active = (states('sensor.hvac_runtime_before_last_filter_change') | float) %}
            {{ 0 - active }}
      - service: input_number.set_value
        entity_id: input_number.beginning_filter_dp
        data:
          value: 0
      - service: input_number.set_value
        entity_id: input_number.maximum_filter_dp
        data:
          value: 0
      - service: input_boolean.turn_on
        entity_id: input_boolean.record_beginning_dp

  furnace_bleach_date:
    alias: Furnace filter change date
    sequence:
      - service: input_text.set_value
        entity_id: input_text.furnace_bleach
        data_template:
          value: "{{ now() }}"

input_text:
  # Store furnace filter change date
  furnace_filter:
    name: Furnace Filter Change Date

  furnace_bleach:
    name: Furnace Last Bleach

  furnace_last_cool:
    name: Furnace Last Cooling

input_number:
  # Used to store runtime nightly to reduce reliance on history
  hvac_runtime:
    name: Runtime
    icon: mdi:clock-outline
    mode: box
    min: -1000
    max: 10000
    unit_of_measurement: "h"

  # Used to set max number of hours of filter runtime to calculate days until filter change required
  replacement_threshold:
    name: Threshold
    min: 0
    max: 10000
    mode: box
    unit_of_measurement: "h"

  beginning_filter_dp:
    name: Beginning Filter Differential
    min: 0
    max: 500
    mode: box
    unit_of_measurement: "Pa"

  maximum_filter_dp:
    name: Maximum Filter Differential
    min: 0
    max: 500
    mode: box
    unit_of_measurement: "Pa"

input_boolean:
  record_beginning_dp:
    name: Record Initial Filter Pressure