- alias: Update Alexa Outside Temperature
  id: 982e4c6c-e1dc-4827-bbb4-81f0edf0e726
  trigger:
    - platform: state
      entity_id: sensor.acurite_ws_temperature
  action:
    - service: rest_command.update_alexa_outside_temp

- alias: Update Alexa Outside Humidity
  id: 10e55f92-803d-4218-9a6a-df2577065336
  trigger:
    - platform: state
      entity_id: sensor.acurite_ws_humidity
  action:
    - service: rest_command.update_alexa_outside_humidity

- alias: Update Alexa Attic Temperature
  id: 7adbcd7d-fc18-4730-af97-44576e8ac865
  trigger:
    - platform: state
      entity_id: sensor.attic_temperature_owfs
  action:
    - service: rest_command.update_alexa_attic_temp

- alias: Update Alexa Den Temperature
  id: d316607a-f06f-48f6-90cf-c74edf986c68
  trigger:
    - platform: state
      entity_id: sensor.aquara_den_temperature
  action:
    - service: rest_command.update_alexa_den_temp

- alias: Update Alexa Den Humidity
  id: 95e72fec-e0aa-49f1-9387-d660d421484e
  trigger:
    - platform: state
      entity_id: sensor.aquara_den_humidity
  action:
    - service: rest_command.update_alexa_den_humidity

- alias: Update Alexa Dining Room Temperature
  id: be9e6b25-1ee1-4247-9edd-b320ccc6c396
  trigger:
    - platform: state
      entity_id: sensor.dining_room_temperature_owfs
  action:
    - service: rest_command.update_alexa_dining_temp

- alias: Update Alexa Garage Temperature
  id: 45ab2369-88d1-4450-8778-d8dc10c644c9
  trigger:
    - platform: state
      entity_id: sensor.garage_temperature_owfs
  action:
    - service: rest_command.update_alexa_garage_temp

- alias: Update Alexa Guest Room Temperature
  id: e17480bb-20c2-44ce-a989-7f4866203934
  trigger:
    - platform: state
      entity_id: sensor.guest_bedroom_temperature_owfs
  action:
    - service: rest_command.update_alexa_guest_temp

- alias: Update Alexa Master Bedroom Temperature
  id: 868f69d5-5bc3-48db-98f3-561c1a303f93
  trigger:
    - platform: state
      entity_id: sensor.aquara_master_bedroom_temperature
  action:
    - service: rest_command.update_alexa_master_temp

- alias: Update Alexa Master Bedroom Humidity
  id: 4ef25000-b6a0-4405-9e82-44d13a52e429
  trigger:
    - platform: state
      entity_id: sensor.aquara_master_bedroom_humidity
  action:
    - service: rest_command.update_alexa_master_humidity

- alias: Update Alexa Office Temperature
  id: 21011031-11dc-47f4-b88d-37b0aab9548b
  trigger:
    - platform: state
      entity_id: sensor.aquara_office_temperature
  action:
    - service: rest_command.update_alexa_office_temp

- alias: Update Alexa Office Humidity
  id: 13e8bf6b-134c-4ed4-bddd-d1b9229b2c6c
  trigger:
    - platform: state
      entity_id: sensor.aquara_office_humidity
  action:
    - service: rest_command.update_alexa_office_humidity

- alias: Update Alexa Server Closet Temperature
  id: 3800c437-3fc4-4a87-a503-2a1b9acffab5
  trigger:
    - platform: state
      entity_id: sensor.aquara_server_closet_temperature
  action:
    - service: rest_command.update_alexa_server_temp

- alias: Update Alexa Server Closet Humidity
  id: d7887102-5754-45c0-b8ed-de89a0d5c01b
  trigger:
    - platform: state
      entity_id: sensor.aquara_server_closet_humidity
  action:
    - service: rest_command.update_alexa_server_humidity

- alias: Update Alexa Work Room Temperature
  id: d0deaa59-59bc-44ed-9ac6-d12cc4a3c7ad
  trigger:
    - platform: state
      entity_id: sensor.work_room_temperature_owfs
  action:
    - service: rest_command.update_alexa_workroom_temp

- alias: Update Alexa When Rain Starts
  id: 04d7e909-b7b7-4fc5-92b2-969695a41594
  trigger:
    - platform: state
      entity_id: input_boolean.is_raining
      to: "on"
  action:
    - service: rest_command.update_alexa_is_raining

- alias: Update Alexa When Rain Stops
  id: 0d9e64c8-f8ca-4ad0-b376-39fe4b8ae83d
  trigger:
    - platform: state
      entity_id: input_boolean.is_raining
      to: "off"
  action:
    - service: rest_command.update_alexa_not_raining

- alias: Update Alexa Daily Rain
  id: 2dffcac3-2234-40cc-b90c-cfa7aa5f84f0
  trigger:
    - platform: state
      entity_id: sensor.rain_day
  action:
    - service: rest_command.update_alexa_daily_rain

- alias: Update Alexa Monthly Rain
  id: 397c9ee4-2f7a-4d42-9fa9-9468d90fa791
  trigger:
    - platform: state
      entity_id: sensor.rain_month
  action:
    - service: rest_command.update_alexa_monthly_rain

- alias: Update Alexa Yearly Rain
  id: eda6e50a-0938-4732-81ab-22822c18788a
  trigger:
    - platform: state
      entity_id: sensor.rain_year
  action:
    - service: rest_command.update_alexa_yearly_rain

- alias: Update Alexa Rain Rate
  id: e6b27b0c-145e-4a1c-90d3-a8b2e19e34c8
  trigger:
    - platform: state
      entity_id: sensor.rain_rate
  action:
    - service: rest_command.update_alexa_rain_rate

- alias: Update Alexa Power Usage
  id: 6eeb84e6-4465-4f69-9e18-b0226012adfe
  trigger:
    - platform: time_pattern
      minutes: "*"
      seconds: "0"
  action:
    - service: rest_command.update_alexa_power_usage

- alias: Update Alexa When Garage Open
  id: 716f02b3-f142-45ca-bc9a-fd253f2b887e
  trigger:
    - platform: state
      entity_id: sensor.elk_garage_door
      to: Violated
  action:
    - service: rest_command.update_alexa_garage_open

- alias: Update Alexa When Garage Closed
  id: f0656133-6461-4f00-90aa-5288793ecc9b
  trigger:
    - platform: state
      entity_id: sensor.elk_garage_door
      to: Normal
  action:
    - service: rest_command.update_alexa_garage_closed

- alias: Update Alexa When Alarm Armed Night
  id: 198ff4ad-16d3-4c0c-bd4d-c3f001d174ec
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      to: armed_night
  action:
    - service: rest_command.update_alexa_alarm_night

- alias: Update Alexa When Alarm Armed Stay
  id: f37cd846-baf8-424f-99b6-fc39ca29813c
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      to: armed_home
  action:
    - service: rest_command.update_alexa_alarm_stay

- alias: Update Alexa When Alarm Disarmed
  id: 2852b374-f0fb-4b96-82d4-27588d0f1cc5
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      to: disarmed
  action:
    - service: rest_command.update_alexa_alarm_disarmed
