- alias: Alexa Good Night Armed Night
  trigger:
    - platform: state
      entity_id: input_boolean.goodnight_trigger
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.area_001
          state: armed_night
        - condition: state
          entity_id: alarm_control_panel.area_001
          state: arming
  action:
    - service: light.turn_off
      entity_id: light.master_suite_leds_rgb
    - service: switch.turn_off
      entity_id: switch.master_bedroom_lamps_keypad
    - service: input_boolean.turn_off
      entity_id: input_boolean.goodnight_trigger

- alias: Alexa Good Night Not Armed Night
  trigger:
    - platform: state
      entity_id: input_boolean.goodnight_trigger
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.area_001
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.area_001
          state: disarmed
  action:
    - service: light.turn_off
      entity_id: light.master_suite_leds_rgb
    - service: switch.turn_off
      entity_id: switch.master_bedroom_lamps_keypad
    - service: switch.turn_on
      entity_id: switch.output_178
    - service: input_boolean.turn_off
      entity_id: input_boolean.goodnight_trigger

- alias: Alexa Bedtime
  trigger:
    - platform: state
      entity_id: input_boolean.bedtime_trigger
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.output_178
        - switch.master_bedroom_fan
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedtime_trigger

- alias: Alexa Good Morning
  trigger:
    - platform: state
      entity_id: input_boolean.morning_trigger
      to: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.master_bedroom_fan
    - service: input_boolean.turn_on
      entity_id: input_boolean.elk_night_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.morning_trigger      