- alias: Alexa Den Timer Announcement
  id: d6e6f0b3-6f8b-4123-8c1c-44c0d0bd0a97
  mode: parallel
  trigger:
    - platform: state
      entity_id: sensor.alexa_den_next_timer
  condition:
    - condition: template
      value_template:
        "{{ trigger.to_state.state not in ['None', 'unknown', 'unavailable']
        and trigger.from_state.state != trigger.to_state.state }}"
  action:
    - service: script.alexa_den_timer_announce
      data_template:
        duration:
          "{{ (as_timestamp(trigger.to_state.state, 0) - now().timestamp() + 2)
          | timestamp_custom('%H:%M:%S', false, 0) }}"

- alias: Alexa Entry Timer Announcement
  id: b1302296-1f3d-4626-bf4a-d983201254db
  mode: parallel
  trigger:
    - platform: state
      entity_id: sensor.alexa_entry_next_timer
  condition:
    - condition: template
      value_template:
        "{{ trigger.to_state.state not in ['None', 'unknown', 'unavailable']
        and trigger.from_state.state != trigger.to_state.state }}"
  action:
    - service: script.alexa_entry_timer_announce
      data_template:
        duration:
          "{{ (as_timestamp(trigger.to_state.state, 0) - now().timestamp() + 2)
          | timestamp_custom('%H:%M:%S', false, 0) }}"

- alias: Alexa Guest Timer Announcement
  id: 73a962b7-958d-4a06-9bc2-cd39fda44354
  mode: parallel
  trigger:
    - platform: state
      entity_id: sensor.alexa_guest_room_next_timer
  condition:
    - condition: template
      value_template:
        "{{ trigger.to_state.state not in ['None', 'unknown', 'unavailable']
        and trigger.from_state.state != trigger.to_state.state }}"
  action:
    - service: script.alexa_guest_timer_announce
      data_template:
        duration:
          "{{ (as_timestamp(trigger.to_state.state, 0) - now().timestamp() + 2)
          | timestamp_custom('%H:%M:%S', false, 0) }}"

- alias: Alexa Master Timer Announcement
  id: f73bf3c4-d083-40e1-9674-6e77536683b6
  mode: parallel
  trigger:
    - platform: state
      entity_id: sensor.alexa_master_bedroom_next_timer
  condition:
    - condition: template
      value_template:
        "{{ trigger.to_state.state not in ['None', 'unknown', 'unavailable']
        and trigger.from_state.state != trigger.to_state.state }}"
  action:
    - service: script.alexa_master_timer_announce
      data_template:
        duration:
          "{{ (as_timestamp(trigger.to_state.state, 0) - now().timestamp() + 2)
          | timestamp_custom('%H:%M:%S', false, 0) }}"

- alias: Alexa Office Timer Announcement
  id: 977de87a-18b8-4966-a7d6-bc1bcbf9ff71
  mode: parallel
  trigger:
    - platform: state
      entity_id: sensor.alexa_office_next_timer
  condition:
    - condition: template
      value_template:
        "{{ trigger.to_state.state not in ['None', 'unknown', 'unavailable']
        and trigger.from_state.state != trigger.to_state.state }}"
  action:
    - service: script.alexa_office_timer_announce
      data_template:
        duration:
          "{{ (as_timestamp(trigger.to_state.state, 0) - now().timestamp() + 2)
          | timestamp_custom('%H:%M:%S', false, 0) }}"

- alias: Alexa Server Timer Announcement
  id: 56adc461-f7f0-41a4-98e5-98beb6188219
  mode: parallel
  trigger:
    - platform: state
      entity_id: sensor.alexa_server_room_next_timer
  condition:
    - condition: template
      value_template:
        "{{ trigger.to_state.state not in ['None', 'unknown', 'unavailable']
        and trigger.from_state.state != trigger.to_state.state }}"
  action:
    - service: script.alexa_server_timer_announce
      data_template:
        duration:
          "{{ (as_timestamp(trigger.to_state.state, 0) - now().timestamp() + 2)
          | timestamp_custom('%H:%M:%S', false, 0) }}"
