- alias: Alexa Good Night Armed Night
  trigger:
    - platform: state
      entity_id: input_boolean.goodnight_trigger
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_night
        - condition: state
          entity_id: alarm_control_panel.house
          state: arming
  action:
    - service: light.turn_off
      entity_id: light.master_suite_leds_rgb
    - service: switch.turn_off
      entity_id: switch.master_bedroom_lamps
    - service: input_boolean.turn_off
      entity_id: input_boolean.goodnight_trigger

- alias: Alexa Good Night Not Armed Night
  trigger:
    - platform: state
      entity_id: input_boolean.goodnight_trigger
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
  action:
    - service: light.turn_off
      entity_id: light.master_suite_leds_rgb
    - service: switch.turn_off
      entity_id: switch.master_bedroom_lamps
    - service: switch.turn_on
      entity_id: switch.elk_night_mode_on
    - service: input_boolean.turn_off
      entity_id: input_boolean.goodnight_trigger

- alias: Alexa Bedtime
  trigger:
    - platform: state
      entity_id: input_boolean.bedtime_trigger
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.elk_night_mode_on
        - switch.master_bedroom_fan
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedtime_trigger
    - service: rest_command.load_audiobook

- alias: Alexa Good Morning
  trigger:
    - platform: state
      entity_id: input_boolean.morning_trigger
      to: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.master_bedroom_fan
    - service: light.turn_off
      entity_id: light.master_bedroom_light
    - service: input_boolean.turn_on
      entity_id: input_boolean.elk_night_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.morning_trigger      

- alias: Alexa Leaving House
  trigger:
    - platform: state
      entity_id: input_boolean.leaving_trigger
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
  action:
    - service: rest_command.unlock_truck
    - service: lock.unlock
      entity_id: lock.front_door
    - service: input_boolean.turn_on
      entity_id: input_boolean.elk_away_on
    - service: input_boolean.turn_off
      entity_id: input_boolean.leaving_trigger  

- alias: Alexa Unlock Truck
  trigger:
    - platform: state
      entity_id: input_boolean.unlock_truck
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
  action:
    - service: rest_command.unlock_truck
    - service: input_boolean.turn_off
      entity_id: input_boolean.unlock_truck

- alias: Alexa Lock Truck
  trigger:
    - platform: state
      entity_id: input_boolean.lock_truck
      to: 'on'
  action:
    - service: rest_command.lock_truck
    - service: input_boolean.turn_off
      entity_id: input_boolean.lock_truck

- alias: Alexa Start Truck
  trigger:
    - platform: state
      entity_id: input_boolean.start_truck
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
  action:
    - service: rest_command.start_truck
    - service: input_boolean.turn_off
      entity_id: input_boolean.start_truck

- alias: Alexa Stop Truck
  trigger:
    - platform: state
      entity_id: input_boolean.stop_truck
      to: 'on'
  action:
    - service: rest_command.stop_truck
    - service: input_boolean.turn_off
      entity_id: input_boolean.stop_truck