- alias: Alexa Good Night Armed Night
  id: 8e432e90-8f2c-459e-824a-6c8fa934bb19
  trigger:
    - platform: state
      entity_id: input_boolean.goodnight_trigger
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_night
        - condition: state
          entity_id: alarm_control_panel.house
          state: arming
  action:
    - service: light.turn_off
      entity_id: light.master_suite_leds_rgb
    - service: switch.turn_off
      entity_id: switch.master_bedroom_lamps
    - service: input_boolean.turn_off
      entity_id: input_boolean.goodnight_trigger

- alias: Alexa Good Night Not Armed Night
  id: 1c503272-fe54-4cc0-a26d-436bbcf600b1
  trigger:
    - platform: state
      entity_id: input_boolean.goodnight_trigger
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
  action:
    - service: light.turn_off
      entity_id: light.master_suite_leds_rgb
    - service: switch.turn_off
      entity_id: switch.master_bedroom_lamps
    - service: switch.turn_on
      entity_id: switch.elk_night_mode_on
    - service: input_boolean.turn_off
      entity_id: input_boolean.goodnight_trigger

- alias: Alexa Bedtime
  id: 45e4c19f-a346-4d77-aa0c-f6ccc7f15d4e
  trigger:
    - platform: state
      entity_id: input_boolean.bedtime_trigger
      to: "on"
  action:
    - service: switch.turn_on
      entity_id:
        - switch.elk_night_mode_on
        - switch.master_bedroom_fan
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedtime_trigger
    - service: rest_command.load_audiobook

- alias: Alexa Good Morning
  id: 3b90e15b-6f41-493a-84ed-0a489068547b
  trigger:
    - platform: state
      entity_id: input_boolean.morning_trigger
      to: "on"
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/command/set/zone/vol
        payload: 4,60
    - service: switch.turn_off
      entity_id: switch.master_bedroom_fan
    - service: light.turn_off
      entity_id: light.master_bedroom_light
    - service: input_boolean.turn_on
      entity_id: input_boolean.elk_night_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.morning_trigger

- alias: Alexa Leaving House
  id: c6344618-9ac5-41a4-85e9-11bbe1fc0e60
  trigger:
    - platform: state
      entity_id: input_boolean.leaving_trigger
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
  action:
    - service: rest_command.unlock_truck
    - service: lock.unlock
      entity_id: lock.front_door
    - service: input_boolean.turn_on
      entity_id: input_boolean.elk_away_on
    - service: input_boolean.turn_off
      entity_id: input_boolean.leaving_trigger

- alias: Leaving Clear Trigger if State Disallowed
  id: 806a265d-db9c-4df7-ae86-c982d822bb24
  trigger:
    - platform: state
      entity_id: input_boolean.leaving_trigger
      to: "on"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.leaving_trigger

- alias: Alexa Returning Home
  id: befc51a4-a93f-42cf-b3a6-14fcb3897cbb
  trigger:
    - platform: state
      entity_id: input_boolean.returning_trigger
      to: "on"
  condition:
    - condition: state
      entity_id: device_tracker.shawn_7t
      state: home
    - condition: state
      entity_id: alarm_control_panel.house
      state: pending
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: "off"
    - condition: state
      entity_id: input_boolean.returning_door_unlocked
      state: "on"
  action:
    - service: switch.turn_on
      entity_id: switch.elk_stay_mode_off
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.returning_trigger
        - input_boolean.returning_door_unlocked

- alias: Arrriving Clear Trigger if Disallowed
  id: 595f2462-747b-44d7-ae2e-b89dffb9af8f
  trigger:
    - platform: state
      entity_id: input_boolean.returning_trigger
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: device_tracker.shawn_7t
          state: not_home
        - condition: not
          conditions:
            - condition: state
              entity_id: alarm_control_panel.house
              state: pending
        - condition: state
          entity_id: input_boolean.vacation_mode
          state: "on"
        - condition: state
          entity_id: input_boolean.returning_door_unlocked
          state: "off"
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.returning_trigger
        - input_boolean.returning_door_unlocked

- alias: Returning Home Lock Trigger
  id: 4badea44-bbf6-4661-8b01-bc5fcab00dd6
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('lock.front_door', 'lock_status', 'Unlocked with Keypad by user 1') }}"
    - platform: template
      value_template: "{{ is_state_attr('lock.front_door', 'lock_status', 'Unlocked by RF') }}"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: pending
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_away
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.returning_door_unlocked

- alias: Clear Returning Home Lock Trigger
  id: 0f130f21-faa4-43e1-af43-8b4cb0e1c113
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      to: disarmed
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.returning_door_unlocked
