- alias: Alexa Good Night Armed Night
  trigger:
    - platform: state
      entity_id: input_boolean.goodnight_trigger
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_night
        - condition: state
          entity_id: alarm_control_panel.house
          state: arming
  action:
    - service: light.turn_off
      entity_id: light.master_suite_leds_rgb
    - service: switch.turn_off
      entity_id: switch.master_bedroom_lamps
    - service: input_boolean.turn_off
      entity_id: input_boolean.goodnight_trigger

- alias: Alexa Good Night Not Armed Night
  trigger:
    - platform: state
      entity_id: input_boolean.goodnight_trigger
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
  action:
    - service: light.turn_off
      entity_id: light.master_suite_leds_rgb
    - service: switch.turn_off
      entity_id: switch.master_bedroom_lamps
    - service: switch.turn_on
      entity_id: switch.elk_night_mode_on
    - service: input_boolean.turn_off
      entity_id: input_boolean.goodnight_trigger

- alias: Alexa Bedtime
  trigger:
    - platform: state
      entity_id: input_boolean.bedtime_trigger
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.elk_night_mode_on
        - switch.master_bedroom_fan
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedtime_trigger
    - service: rest_command.load_audiobook

- alias: Alexa Good Morning
  trigger:
    - platform: state
      entity_id: input_boolean.morning_trigger
      to: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.master_bedroom_fan
    - service: light.turn_off
      entity_id: light.master_bedroom_light
    - service: input_boolean.turn_on
      entity_id: input_boolean.elk_night_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.morning_trigger      

- alias: Alexa Leaving House
  trigger:
    - platform: state
      entity_id: input_boolean.leaving_trigger
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
  action:
    - service: rest_command.unlock_truck
    - service: lock.unlock
      entity_id: lock.front_door
    - service: input_boolean.turn_on
      entity_id: input_boolean.elk_away_on
    - service: input_boolean.turn_off
      entity_id: input_boolean.leaving_trigger

- alias: Leaving Clear Trigger if State Disallowed
  trigger:
    - platform: state
      entity_id: input_boolean.leaving_trigger
      to: 'on'
  condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: alarm_control_panel.house
        state: armed_home
      - condition: state
        entity_id: alarm_control_panel.house
        state: disarmed
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.leaving_trigger

- alias: Alexa Returning Home
  trigger:
    - platform: state
      entity_id: input_boolean.returning_trigger
      to: 'on'
  condition:
    - condition: state
      entity_id: sensor.shawn_7t_wifi_connection
      state: !secret home_wifi_ssid
    - condition: state
      entity_id: alarm_control_panel.house
      state: pending
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ is_state_attr('lock.front_door', 'lock_status', 'Unlocked with Keypad by user 1') }}"
        - condition: template
          value_template: "{{ is_state_attr('lock.front_door', 'lock_status', 'Unlocked by RF') }}"
  action:
    - service: switch.turn_on
      entity_id: switch.elk_stay_mode_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.returning_trigger      

- alias: Arrriving Clear Trigger if Disallowed
  trigger:
    - platform: state
      entity_id: input_boolean.returning_trigger
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: not
          conditions:
            - condition: state
              entity_id: sensor.shawn_7t_wifi_connection
              state: !secret home_wifi_ssid
        - condition: not
          conditions:
            - condition: state
              entity_id: alarm_control_panel.house
              state: pending
        - condition: state
          entity_id: input_boolean.vacation_mode
          state: 'on'
        - condition: not
          conditions:
            - condition: template
              value_template: "{{ is_state_attr('lock.front_door', 'lock_status', 'Unlocked with Keypad by user 1') }}"
            - condition: template
              value_template: "{{ is_state_attr('lock.front_door', 'lock_status', 'Unlocked by RF') }}"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.returning_trigger            