- alias: All Off NuVo Away
  trigger:
    - platform: state
      entity_id: alarm_control_panel.area_001
      from: arming
      to: armed_away
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/command/set/system/alloff

- alias: All Off Main
  trigger:
    - platform: state
      entity_id: alarm_control_panel.area_001
      from: arming
      to: armed_away
    - platform: state
      entity_id: alarm_control_panel.area_001
      from: armed_home
      to: armed_night
    - platform: state
      entity_id: alarm_control_panel.area_001
      from: disarmed
      to: armed_night
  action:
    - service: light.turn_off
      entity_id: 
        - light.dining_room_light
        - light.entry_light
        - light.foyer_light
        - light.attic_light
        - light.kitchen_sink_light
        - light.kitchen_light
        - light.pantry_light
        - light.office_light
        - light.server_room_light
        - light.utility_room_light
        - light.den_light
        - light.shack_desk_light
    - service: switch.turn_off
      entity_id: 
        - switch.den_fireplace
        - switch.den_fan
        - switch.warmer
        - switch.office_fan
        - switch.server_room_fan
        - switch.back_porch_fan
        - switch.garage_lights
        - switch.garage_fan
        - switch.guest_closet_light
        - switch.server_closet_light
        - switch.master_closet_light
        - switch.shed_inside_light
        - switch.lava_lamp
        - switch.popper
        - switch.shack_fan
        - switch.back_porch_light  
        - switch.shack_light
        - switch.office_peripherals

- alias: All Off Away
  trigger:
    - platform: state
      entity_id: alarm_control_panel.area_001
      from: arming
      to: armed_away
  action:
    - service: light.turn_off
      entity_id: 
        - light.guest_bedroom_light
        - light.guest_bathroom_light
        - light.master_bedroom_light
        - light.master_shower_light
        - light.hallway_light
    - service: switch.turn_off
      entity_id:
        - switch.master_bathroom_lights
        - switch.master_bathroom_fan
        - switch.master_toilet_fan
        - switch.guest_bathroom_fan
        - switch.guest_bedroom_fan
        - switch.master_bedroom_fan
        - switch.water_projector
  
- alias: All Off Timer Lights
  trigger:
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.all_off_main
  condition:
    - condition: state
      entity_id: input_boolean.timer_lights
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.kitchen_lamp
        - switch.server_room_lamp
        - switch.office_lamps
        - switch.den_lamps
        - switch.shack_lamp
        - switch.entry_lamp

- alias: All Off Guest Lights
  trigger:
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.all_off_main
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: 
        - light.guest_bedroom_light
        - light.guest_bathroom_light
        - light.hall_light
    - service: switch.turn_off
      entity_id: 
        - switch.guest_bedroom_fan
        - switch.guest_bathroom_fan

- alias: All Off Guest NuVo
  trigger:
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.all_off_main
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.nuvo_zone_2_power

- alias: All Off NuVo Night
  trigger:
    - platform: state
      entity_id: alarm_control_panel.area_001
      from: disarmed
      to: armed_night
    - platform: state
      entity_id: alarm_control_panel.area_001
      from: armed_home
      to: armed_night
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.nuvo_zone_1_power
        - switch.nuvo_zone_3_power
        - switch.nuvo_zone_6_power
        - switch.nuvo_zone_7_power
        - switch.nuvo_zone_9_power
        - switch.nuvo_zone_10_power
        - switch.nuvo_zone_11_power
        - switch.nuvo_zone_12_power

- alias: All Off Outside Lights
  trigger:
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.all_off_main
  condition:
    - condition: state
      entity_id: input_boolean.outside_timer_lights
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.outside_lights
        - switch.shed_outside_light

- alias: All Off Timer Lights Master
  trigger:
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.all_off_main
  condition:
    - condition: state
      entity_id: input_boolean.master_lamp_timer
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.master_bedroom_lamps