- alias: Arm from Biometrics
  id: 04ce0603-a32f-447b-b963-abc994e90eaf
  trigger:
    - platform: state
      entity_id: switch.elk_biometric_trigger
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.house
      state: disarmed
  action:
    - service: lock.lock
      entity_id: lock.garage_entry
    - service: switch.turn_on
      entity_id: switch.elk_away_mode_on
    - service: switch.turn_off
      entity_id: switch.elk_biometric_trigger

- alias: Disarm from Biometrics
  id: 1244ea8c-745c-47ab-b2a3-dd52e7cc73ce
  trigger:
    - platform: state
      entity_id: switch.elk_biometric_trigger
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_away
        - condition: state
          entity_id: alarm_control_panel.house
          state: arming
  action:
    - service: lock.unlock
      entity_id: lock.garage_entry
    - service: switch.turn_on
      entity_id: switch.elk_stay_mode_off
    - service: switch.turn_off
      entity_id: switch.elk_biometric_trigger
