- alias: GitHub Build Created
  id: 365b6a29-1553-41b8-afc0-a057c1b01e20
  trigger:
    - platform: webhook
      webhook_id: !secret webhook_build_pending
      local_only: false
  action:
    - service: light.turn_on
      data:
        entity_id: light.build_light
        rgbw_color: [0, 0, 0, 255]

- alias: GitHub Build Started
  id: 11f895f2-b7fb-4362-bc94-a072c9419c21
  trigger:
    - platform: webhook
      webhook_id: !secret webhook_build_running
      local_only: false
  action:
    - service: light.turn_on
      data:
        entity_id: light.build_light
        rgbw_color: [0, 255, 0, 0]

- alias: GitHub Build Failed
  id: 781bb3c0-b9e4-419a-9754-f065d08fa135
  trigger:
    - platform: webhook
      webhook_id: !secret webhook_build_failing
      local_only: false
  action:
    - service: light.turn_on
      data:
        entity_id: light.build_light
        rgbw_color: [255, 0, 0, 0]

- alias: GitHub Build Passed
  id: 98a61d5c-b97a-47d2-b8c1-1aeecee2aa4b
  trigger:
    - platform: webhook
      webhook_id: !secret webhook_build_passing
      local_only: false
  action:
    - service: light.turn_on
      data:
        entity_id: light.build_light
        rgbw_color: [0, 0, 255, 0]
