- alias: CCTV West Front Person Detected
  id: 222aba6c-afa4-4226-b39e-de3f71662a9a
  trigger:
    - platform: state
      entity_id: binary_sensor.west_front_person
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.frigate_enabled
      state: "on"
    - condition: state
      entity_id: input_boolean.frigate_enabled_front
      state: "on"
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.west_front
        filename: /config/www/cctv/west_front_full.jpg
    - service: camera.snapshot
      data:
        entity_id: camera.west_front_last_person
        filename: /config/www/cctv/west_front_person.jpg
    - service: notify.cctv_email
      data:
        title: "CCTV Alarm: West Front - Person Detected {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
        message: "A person was detected on the west front camera at {{now().strftime('%H:%M:%S') }}."
        data:
          images:
            - /config/www/cctv/west_front_person.jpg
            - /config/www/cctv/west_front_full.jpg

- alias: CCTV East Front Person Detected
  id: 0575e725-ee28-48b4-a16d-c1abd1d5df62
  trigger:
    - platform: state
      entity_id: binary_sensor.east_front_person
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.frigate_enabled
      state: "on"
    - condition: state
      entity_id: input_boolean.frigate_enabled_front
      state: "on"
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.east_front
        filename: /config/www/cctv/east_front_full.jpg
    - service: camera.snapshot
      data:
        entity_id: camera.east_front_last_person
        filename: /config/www/cctv/east_front_person.jpg
    - service: notify.cctv_email
      data:
        title: "CCTV Alarm: East Front - Person Detected {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
        message: "A person was detected on the east front camera at {{now().strftime('%H:%M:%S') }}."
        data:
          images:
            - /config/www/cctv/east_front_person.jpg
            - /config/www/cctv/east_front_full.jpg

- alias: CCTV West Side Person Detected
  id: 4be4a812-c669-4bb4-a93d-61c838953e73
  trigger:
    - platform: state
      entity_id: binary_sensor.west_side_person
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.frigate_enabled
      state: "on"
    - condition: state
      entity_id: input_boolean.frigate_enabled_front
      state: "on"
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.west_side
        filename: /config/www/cctv/west_side_full.jpg
    - service: camera.snapshot
      data:
        entity_id: camera.west_side_last_person
        filename: /config/www/cctv/west_side_person.jpg
    - service: notify.cctv_email
      data:
        title: "CCTV Alarm: West Side - Person Detected {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
        message: "A person was detected on the west side camera at {{now().strftime('%H:%M:%S') }}."
        data:
          images:
            - /config/www/cctv/west_side_person.jpg
            - /config/www/cctv/west_side_full.jpg

- alias: CCTV East Side Person Detected
  id: d6ba9ca2-2ec0-4ef4-8b6a-d8af97842a3f
  trigger:
    - platform: state
      entity_id: binary_sensor.east_side_person
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.frigate_enabled
      state: "on"
    - condition: state
      entity_id: input_boolean.frigate_enabled_back
      state: "on"
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.east_side
        filename: /config/www/cctv/east_side_full.jpg
    - service: camera.snapshot
      data:
        entity_id: camera.east_side_last_person
        filename: /config/www/cctv/east_side_person.jpg
    - service: notify.cctv_email
      data:
        title: "CCTV Alarm: East Side - Person Detected {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
        message: "A person was detected on the east side camera at {{now().strftime('%H:%M:%S') }}."
        data:
          images:
            - /config/www/cctv/east_side_person.jpg
            - /config/www/cctv/east_side_full.jpg

- alias: CCTV Back Yard Person Detected
  id: 8fb6c7cd-2915-45b3-83e2-3b12724ca6da
  trigger:
    - platform: state
      entity_id: binary_sensor.back_yard_person
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.frigate_enabled
      state: "on"
    - condition: state
      entity_id: input_boolean.frigate_enabled_back
      state: "on"
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.back_yard
        filename: /config/www/cctv/back_yard_full.jpg
    - service: camera.snapshot
      data:
        entity_id: camera.back_yard_last_person
        filename: /config/www/cctv/back_yard_person.jpg
    - service: notify.cctv_email
      data:
        title: "CCTV Alarm: Back Yard - Person Detected {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
        message: "A person was detected on the back yard camera at {{now().strftime('%H:%M:%S') }}."
        data:
          images:
            - /config/www/cctv/back_yard_person.jpg
            - /config/www/cctv/back_yard_full.jpg

- alias: CCTV Back Porch Person Detected
  id: 74430858-a2a9-45d7-b247-7f604ca3ecc6
  trigger:
    - platform: state
      entity_id: binary_sensor.back_porch_person
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.frigate_enabled
      state: "on"
    - condition: state
      entity_id: input_boolean.frigate_enabled_back
      state: "on"
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.back_porch
        filename: /config/www/cctv/back_porch_full.jpg
    - service: camera.snapshot
      data:
        entity_id: camera.back_porch_last_person
        filename: /config/www/cctv/back_porch_person.jpg
    - service: notify.cctv_email
      data:
        title: "CCTV Alarm: Back Porch - Person Detected {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
        message: "A person was detected on the back porch camera at {{now().strftime('%H:%M:%S') }}."
        data:
          images:
            - /config/www/cctv/back_porch_person.jpg
            - /config/www/cctv/back_porch_full.jpg

- alias: CCTV Front Porch Person Detected
  id: 391c6db8-6e13-4650-a53c-374b69cccaa8
  trigger:
    - platform: state
      entity_id: binary_sensor.front_porch_person
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.frigate_enabled
      state: "on"
    - condition: state
      entity_id: input_boolean.frigate_enabled_front
      state: "on"
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.front_porch
        filename: /config/www/cctv/front_porch_full.jpg
    - service: camera.snapshot
      data:
        entity_id: camera.front_porch_last_person
        filename: /config/www/cctv/front_porch_person.jpg
    - service: notify.cctv_email
      data:
        title: "CCTV Alarm: Front Porch - Person Detected {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
        message: "A person was detected on the front porch camera at {{now().strftime('%H:%M:%S') }}."
        data:
          images:
            - /config/www/cctv/front_porch_person.jpg
            - /config/www/cctv/front_porch_full.jpg

- alias: Start Reset Timer When Frigate Disabled
  id: 891a2380-a10a-43bc-ab05-2a490d6f4f61
  trigger:
    - platform: state
      entity_id: input_boolean.frigate_enabled
      to: "off"
  action:
    - service: timer.start
      data_template:
        entity_id: timer.frigate_disable
        duration: "{{ states('input_number.frigate_disable_time') | int(none) * 3600}}"

- alias: Restart Frigate When Restart Timer Expires
  id: 09dab8b7-8a8e-4c40-95ad-006fba733abd
  trigger:
    - event_data:
        entity_id: timer.frigate_disable
      event_type: timer.finished
      platform: event
  condition:
    - condition: state
      entity_id: input_boolean.frigate_enabled
      state: "off"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.frigate_enabled

- alias: Cancel Frigate Timer if Frigate Manually Enabled
  id: ffdcc3a3-5cf5-4223-a26d-36c9c304bf94
  trigger:
    - platform: state
      entity_id: input_boolean.frigate_enabled
      to: "on"
  condition:
    - condition: state
      entity_id: timer.frigate_disable
      state: "active"
  action:
    - service: timer.cancel
      entity_id: timer.frigate_disable

- alias: Clean Up Temporary Camera Images
  id: f3f92f77-da0e-41e7-975d-fa66c973aba9
  trigger:
    - platform: time
      at: "00:00:00"
  action:
    - service: shell_command.clear_temp_images

- alias: Restart Frigate if Hung
  id: 689fe128-5271-49ed-9a2f-b2a08844433e
  trigger:
    - platform: state
      entity_id: sensor.frigate_processing_frame
      for: "00:05:00"
  action:
    - service: rest_command.docker_frigate_restart
    - service: notify.mobile_app_shawn_7t
      data:
        message: Frigate has been restarted due to unresponsiveness.
        title: Frigate CCTV
        data:
          ttl: 0
          priority: high

- alias: Frigate Disable Back Cameras When Shed is Open
  id: fb2c489a-f819-4d18-8a99-833b9582794a
  trigger:
    - platform: state
      entity_id: lock.shed_door
      from: locked
      to: unlocked
  condition:
    - condition: state
      entity_id: alarm_control_panel.house
      state: disarmed
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.frigate_enabled_back

- alias: Frigate Enable Back Cameras When Shed is Closed
  id: 1fede986-bf36-4488-adff-14da624fc467
  trigger:
    - platform: state
      entity_id: lock.shed_door
      from: unlocked
      to: locked
      for: "00:02:00"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.frigate_enabled_back

- alias: Cat Box Entry Alert
  id: e5cef912-167b-4bf4-ad6a-6d4c0cffa475
  trigger:
    - platform: state
      entity_id: sensor.litter_robot_short_status
      to: Timing
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.shack
        filename: /config/www/cctv/tmp/shack_{{ now ().year }}_{{ now ().month }}_{{ now ().day }}_{{ now ().hour }}_{{ now ().minute }}.jpg
    - service: notify.cctv_email
      data_template:
        title: "Litter Robot Activated - {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
        message: "The litter robot was activated at {{now().strftime('%H:%M:%S') }}."
        data:
          images:
            - /config/www/cctv/tmp/shack_{{ now ().year }}_{{ now ().month }}_{{ now ().day }}_{{ now ().hour }}_{{ now ().minute }}.jpg      