- alias: CCTV West Front Person Detected
  trigger:
    - platform: state
      entity_id: binary_sensor.west_front_person
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.frigate_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.frigate_enabled_christmas
      state: 'on'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.west_front
        filename: /config/www/cctv/west_front_full.jpg
    - service: camera.snapshot
      data:
        entity_id: camera.west_front_last_person
        filename: /config/www/cctv/west_front_person.jpg
    - service: notify.cctv_email
      data:
        title: "CCTV Alarm: West Front - Person Detected {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
        message: "A person was detected on the west front camera at {{now().strftime('%H:%M:%S') }}."
        data: 
          images:
            - /config/www/cctv/west_front_person.jpg
            - /config/www/cctv/west_front_full.jpg

- alias: CCTV East Front Person Detected
  trigger:
    - platform: state
      entity_id: binary_sensor.east_front_person
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.frigate_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.frigate_enabled_christmas
      state: 'on'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.east_front
        filename: /config/www/cctv/east_front_full.jpg
    - service: camera.snapshot
      data:
        entity_id: camera.east_front_last_person
        filename: /config/www/cctv/east_front_person.jpg
    - service: notify.cctv_email
      data:
        title: "CCTV Alarm: East Front - Person Detected {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
        message: "A person was detected on the east front camera at {{now().strftime('%H:%M:%S') }}."
        data: 
          images:
            - /config/www/cctv/east_front_person.jpg
            - /config/www/cctv/east_front_full.jpg            

- alias: CCTV West Side Person Detected
  trigger:
    - platform: state
      entity_id: binary_sensor.west_side_person
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.frigate_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.frigate_enabled_christmas
      state: 'on'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.west_side
        filename: /config/www/cctv/west_side_full.jpg
    - service: camera.snapshot
      data:
        entity_id: camera.west_side_last_person
        filename: /config/www/cctv/west_side_person.jpg
    - service: notify.cctv_email
      data:
        title: "CCTV Alarm: West Side - Person Detected {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
        message: "A person was detected on the west side camera at {{now().strftime('%H:%M:%S') }}."
        data: 
          images:
            - /config/www/cctv/west_side_person.jpg
            - /config/www/cctv/west_side_full.jpg

- alias: CCTV East Side Person Detected
  trigger:
    - platform: state
      entity_id: binary_sensor.east_side_person
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.frigate_enabled
      state: 'on'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.east_side
        filename: /config/www/cctv/east_side_full.jpg
    - service: camera.snapshot
      data:
        entity_id: camera.east_side_last_person
        filename: /config/www/cctv/east_side_person.jpg
    - service: notify.cctv_email
      data:
        title: "CCTV Alarm: East Side - Person Detected {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
        message: "A person was detected on the east side camera at {{now().strftime('%H:%M:%S') }}."
        data: 
          images:
            - /config/www/cctv/east_side_person.jpg
            - /config/www/cctv/east_side_full.jpg            

- alias: CCTV Back Yard Person Detected
  trigger:
    - platform: state
      entity_id: binary_sensor.back_yard_person
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.frigate_enabled
      state: 'on'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.back_yard
        filename: /config/www/cctv/back_yard_full.jpg
    - service: camera.snapshot
      data:
        entity_id: camera.back_yard_last_person
        filename: /config/www/cctv/back_yard_person.jpg
    - service: notify.cctv_email
      data:
        title: "CCTV Alarm: Back Yard - Person Detected {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
        message: "A person was detected on the back yard camera at {{now().strftime('%H:%M:%S') }}."
        data: 
          images:
            - /config/www/cctv/back_yard_person.jpg
            - /config/www/cctv/back_yard_full.jpg        

- alias: CCTV Back Porch Person Detected
  trigger:
    - platform: state
      entity_id: binary_sensor.back_porch_person
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.frigate_enabled
      state: 'on'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.back_porch
        filename: /config/www/cctv/back_porch_full.jpg
    - service: camera.snapshot
      data:
        entity_id: camera.back_porch_last_person
        filename: /config/www/cctv/back_porch_person.jpg
    - service: notify.cctv_email
      data:
        title: "CCTV Alarm: Back Porch - Person Detected {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
        message: "A person was detected on the back porch camera at {{now().strftime('%H:%M:%S') }}."
        data: 
          images:
            - /config/www/cctv/back_porch_person.jpg
            - /config/www/cctv/back_porch_full.jpg                    

- alias: CCTV Front Porch Person Detected
  trigger:
    - platform: state
      entity_id: binary_sensor.front_porch_person
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.frigate_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.frigate_enabled_christmas
      state: 'on'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.front_porch
        filename: /config/www/cctv/front_porch_full.jpg
    - service: camera.snapshot
      data:
        entity_id: camera.front_porch_last_person
        filename: /config/www/cctv/front_porch_person.jpg
    - service: notify.cctv_email
      data:
        title: "CCTV Alarm: Front Porch - Person Detected {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
        message: "A person was detected on the front porch camera at {{now().strftime('%H:%M:%S') }}."
        data: 
          images:
            - /config/www/cctv/front_porch_person.jpg
            - /config/www/cctv/front_porch_full.jpg   

- alias: Start Reset Timer When Frigate Disabled
  trigger:
    - platform: state
      entity_id: input_boolean.frigate_enabled
      to: 'off'
  action:
    - service: timer.start
      data_template:
        entity_id: timer.frigate_disable
        duration: "{{ states('input_number.frigate_disable_time') | int * 3600}}"

- alias: Restart Frigate When Restart Timer Expires
  trigger:
    - event_data:
        entity_id: timer.frigate_disable
      event_type: timer.finished
      platform: event
  condition:
    - condition: state
      entity_id: input_boolean.frigate_enabled
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.frigate_enabled

- alias: Cancel Frigate Timer if Frigate Manually Enabled
  trigger:
    - platform: state
      entity_id: input_boolean.frigate_enabled
      to: 'on'
  condition:
    - condition: state
      entity_id: timer.frigate_disable
      state: 'active'
  action:
    - service: timer.cancel
      entity_id: timer.frigate_disable

- alias: Clean Up Temporary Camera Images
  trigger:
    - platform: time
      at: '00:00:00'
  action:
    - service: shell_command.clear_temp_images
