- alias: Indoor Christmas On When Home
  id: cec759b6-0e2e-4d73-ada2-7b1c3ef78670
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      to: disarmed
    - platform: state
      entity_id: alarm_control_panel.house
      to: armed_home
  action:
    - service: switch.turn_on
      entity_id: switch.indoor_christmas

- alias: Indoor Christmas Off When Away or Asleep
  id: 916d3d2c-5dbc-4e6e-9c2c-2a46082f1f3c
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      from: arming
      to: armed_away
    - platform: state
      entity_id: alarm_control_panel.house
      to: armed_night
  action:
    - service: switch.turn_off
      entity_id: switch.indoor_christmas
    - service: mqtt.publish
      data:
        topic: ir/all/cmnd/irsend
        payload: '{"Protocol":"NEC","Bits":32,"Data":"0x1FE58A7"}'

- alias: MQTT Christmas Show On
  id: e2e0b58e-27e0-4e1a-857e-cbd85d015b86
  trigger:
    - platform: mqtt
      topic: christmas/show
      payload: "ON"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.christmas_show

- alias: MQTT Christmas Show Off
  id: e9c2cf8b-1ec9-494e-bbc7-bb896f27cfd9
  trigger:
    - platform: mqtt
      topic: christmas/show
      payload: "OFF"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.christmas_show

- alias: House Off For Christmas Show
  id: dc3848ec-9d7a-4f80-8c65-3cb926315859
  trigger:
    - platform: state
      entity_id: input_boolean.christmas_show
      to: "on"
  action:
    - service: switch.turn_off
      entity_id:
        - switch.outside_lights
        - switch.shed_outside_light
        - switch.office_lamps
        - group.landscape_lights
    - service: cover.close_cover
      entity_id: cover.office_blinds
    - service: input_boolean.turn_off
      entity_id: input_boolean.frigate_enabled_christmas

- alias: House On After Christmas Show
  id: 13cff086-4ed0-45a9-bdb9-79c77cca00a3
  trigger:
    - platform: state
      entity_id: input_boolean.christmas_show
      to: "off"
  action:
    - service: switch.turn_on
      entity_id:
        - switch.outside_lights
        - switch.shed_outside_light
        - group.landscape_lights
    - service: input_boolean.turn_on
      entity_id: input_boolean.frigate_enabled_christmas

- alias: Donation Box Opened
  id: f2226ed0-ef53-48b5-a2f4-5baed7f5668c
  trigger:
    - platform: state
      entity_id: sensor.elk_donation_box
      to: Violated
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 3,4
    - service: notify.mobile_app_shawn_7t
      data:
        message: The donation box has been opened.
        title: Donation Box
        data:
          ttl: 0
          priority: high
    - service: input_boolean.turn_on
      entity_id: input_boolean.donation_box

- alias: Candles On at Dark When Home
  id: 43d4c5d9-071d-4604-9297-715e0251f132
  trigger:
    - platform: sun
      event: sunset
      offset: "00:30:00"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
  action:
    - service: mqtt.publish
      data:
        topic: ir/all/cmnd/irsend
        payload: '{"Protocol":"NEC","Bits":32,"Data":"0x1FE48B7"}'

- alias: Candles On at When Returning After Dark
  id: 3f6ccd03-0d72-4e6c-bed7-0d32f338e7fb
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      from: pending
      to: disarmed
  condition:
    - condition: sun
      after: sunset
      after_offset: "00:30:00"
  action:
    - service: mqtt.publish
      data:
        topic: ir/all/cmnd/irsend
        payload: '{"Protocol":"NEC","Bits":32,"Data":"0x1FE48B7"}'
