- alias: Elk Night Mode On from Trigger
  id: e9a2b737-b23e-40a3-af50-0f4d0519a025
  trigger:
    - platform: state
      entity_id: input_boolean.elk_night_on
      to: "on"
  condition:
    - condition: template
      value_template: "{{ is_state_attr('alarm_control_panel.house', 'alarm_state', 'no_alarm_active') }}"
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.house', 'armed_away') }}"
  action:
    - service: switch.turn_on
      entity_id: switch.elk_night_mode_on
    - service: input_boolean.turn_off
      entity_id: input_boolean.elk_night_on

- alias: Elk Night Mode Off from Trigger
  id: 5be15df9-51de-49fd-a74e-686b21eaa34a
  trigger:
    - platform: state
      entity_id: input_boolean.elk_night_off
      to: "on"
  condition:
    - condition: template
      value_template: "{{ is_state_attr('alarm_control_panel.house', 'alarm_state', 'no_alarm_active') }}"
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.house', 'armed_away') }}"
  action:
    - service: switch.turn_on
      entity_id: switch.elk_night_mode_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.elk_night_off

- alias: Elk Stay Mode On from Trigger
  id: ba2d16ce-fc20-4cee-ae6c-6f1989b897fb
  trigger:
    - platform: state
      entity_id: input_boolean.elk_stay_on
      to: "on"
  condition:
    - condition: template
      value_template: "{{ is_state_attr('alarm_control_panel.house', 'alarm_state', 'no_alarm_active') }}"
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.house', 'armed_away') }}"
  action:
    - service: switch.turn_on
      entity_id: switch.elk_night_mode_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.elk_stay_on

- alias: Elk Stay Mode Off from Trigger
  id: bcc873f9-21e9-45d9-a03a-367e69db9b7f
  trigger:
    - platform: state
      entity_id: input_boolean.elk_stay_off
      to: "on"
  condition:
    - condition: template
      value_template: "{{ is_state_attr('alarm_control_panel.house', 'alarm_state', 'no_alarm_active') }}"
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.house', 'armed_away') }}"
  action:
    - service: switch.turn_on
      entity_id: switch.elk_stay_mode_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.elk_stay_off

- alias: Elk Away Mode On from Trigger
  id: df5a488a-c896-438c-83dd-0c86f1454985
  trigger:
    - platform: state
      entity_id: input_boolean.elk_away_on
      to: "on"
  condition:
    - condition: template
      value_template: "{{ is_state_attr('alarm_control_panel.house', 'alarm_state', 'no_alarm_active') }}"
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.house', 'armed_away') }}"
  action:
    - service: switch.turn_on
      entity_id: switch.elk_away_mode_on
    - service: input_boolean.turn_off
      entity_id: input_boolean.elk_away_on

- alias: Elk Clear Trigger if State Disallowed
  id: 64e00382-d3cb-4027-91ab-41c789586f62
  trigger:
    - platform: state
      entity_id: input_boolean.elk_night_on
      to: "on"
    - platform: state
      entity_id: input_boolean.elk_night_off
      to: "on"
    - platform: state
      entity_id: input_boolean.elk_stay_on
      to: "on"
    - platform: state
      entity_id: input_boolean.elk_stay_off
      to: "on"
    - platform: state
      entity_id: input_boolean.elk_away_on
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ not is_state_attr('alarm_control_panel.house', 'alarm_state', 'no_alarm_active') }}"
        - condition: template
          value_template: "{{ is_state('alarm_control_panel.house', 'armed_away') }}"
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.elk_night_on
        - input_boolean.elk_night_off
        - input_boolean.elk_stay_on
        - input_boolean.elk_stay_off
        - input_boolean.elk_away_on
