- alias: Guest Bathroom Fan Auto Off
  id: b7bc5351-8d3d-475f-a7e5-a86c730759d1
  trigger:
    - platform: state
      entity_id: light.guest_bathroom_light
      to: "off"
      for:
        minutes: 5
  action:
    - service: switch.turn_off
      entity_id: switch.guest_bathroom_fan

- alias: Master Bathroom Fan Auto Off
  id: 15bf0b1b-006b-4c80-a001-423d9cb74ce7
  trigger:
    - platform: state
      entity_id: light.master_toilet_light
      to: "off"
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: switch.shower_light_and_fan
      state: "off"
    - condition: state
      entity_id: switch.master_bath_fans
      state: "off"
  action:
    - service: switch.turn_off
      entity_id: switch.master_bathroom_fan
