- alias: Turn On Fireplace
  id: cbc71002-7634-4bbc-adf8-f3e49bff626d
  trigger:
    - platform: state
      entity_id: switch.den_fireplace
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: switch.fireplace
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.fireplace

- alias: Turn Off Fireplace
  id: daa9ac49-3d31-47f4-be44-75e535ec2562
  trigger:
    - platform: state
      entity_id: switch.den_fireplace
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: switch.fireplace
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.fireplace

- alias: Fireplace Keypad On if Fire On
  id: ec2b5822-8588-4a10-8d24-417d0c528a47
  trigger:
    - platform: state
      entity_id: switch.fireplace
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: switch.den_fireplace
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.den_fireplace

- alias: Fireplace Keypad Off if Fire Off
  id: d6e08752-0c81-472a-86d4-bfbb15db8105
  trigger:
    - platform: state
      entity_id: switch.fireplace
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: switch.den_fireplace
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.den_fireplace

- alias: Keep Fireplace Off When Away
  id: 42eb3d10-fd96-4ff4-8994-4263249c6203
  trigger:
    - platform: state
      entity_id: switch.fireplace
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_night
        - condition: state
          entity_id: alarm_control_panel.house
          state: 
            - armed_away
            - armed_vacation
  action:
    - service: switch.turn_off
      entity_id: switch.fireplace
