- alias: Master Bedroom LEDs On from Keypad
  trigger:
    - platform: state
      entity_id: switch.master_leds_power
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: light.master_bedroom_leds_rgb
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.master_bedroom_leds_rgb
    
- alias: Master Bedroom LEDs Off from Keypad
  trigger:
    - platform: state
      entity_id: switch.master_leds_power
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: light.master_bedroom_leds_rgb
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.master_bedroom_leds_rgb
      
- alias: Master Bathroom LEDs On from Keypad
  trigger:
    - platform: state
      entity_id: switch.master_bathroom_leds_power
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: light.master_bathroom_led_rgb
      state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.master_bathroom_led_rgb
    
- alias: Master Bathroom LEDs Off from Keypad
  trigger:
    - platform: state
      entity_id: switch.master_bathroom_leds_power
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: light.master_bathroom_led_rgb
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.master_bathroom_led_rgb
      
- alias: Kitchen LEDs On from Keypad
  trigger:
    - platform: state
      entity_id: switch.kitchen_leds_power
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: light.kitchen_leds_rgb
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.kitchen_leds_rgb

- alias: Kitchen LEDs Off from Keypad
  trigger:
    - platform: state
      entity_id: switch.kitchen_leds_power
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: light.kitchen_leds_rgb
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.kitchen_leds_rgb
      
- alias: Den LEDs On from Keypad
  trigger:
    - platform: state
      entity_id: switch.den_leds_power
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: light.den_leds_rgb
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.den_leds_rgb
    
- alias: Den LEDs Off from Keypad
  trigger:
    - platform: state
      entity_id: switch.den_leds_power
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: light.den_leds_rgb
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.den_leds_rgb
    
- alias: Guest Bathroom LEDs On from Keypad
  trigger:
    - platform: state
      entity_id: switch.guest_bathroom_leds_power
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: light.guest_bathroom_led_rgb
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.guest_bathroom_led_rgb
      
- alias: Guest Bathroom LEDs Off from Keypad
  trigger:
    - platform: state
      entity_id: switch.guest_bathroom_leds_power
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: light.guest_bathroom_led_rgb
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.guest_bathroom_led_rgb
      
- alias: Counter LEDs On from Keypad
  trigger:
    - platform: state
      entity_id: switch.kitchen_undercabinet_lights
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: light.kitchen_counter_leds_white
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.kitchen_counter_leds_white
      

- alias: Counter LEDs Off from Keypad
  trigger:
    - platform: state
      entity_id: switch.kitchen_undercabinet_lights
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: light.kitchen_counter_leds_white
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.kitchen_counter_leds_white
    

- alias: Master Bedroom LEDs Keypad On
  trigger:
    - entity_id: light.master_bedroom_leds_rgb
      platform: state
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.master_leds_power
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.master_leds_power

- alias: Master Bedroom LEDs Keypad Off
  trigger:
    - entity_id: light.master_bedroom_leds_rgb
      platform: state
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.master_leds_power
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.master_leds_power

- alias: Master Bathroom LEDs Keypad On
  trigger:
    - entity_id: light.master_bathroom_led_rgb
      platform: state
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.master_bathroom_leds_power
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.master_bathroom_leds_power

- alias: Master Bathroom LEDs Keypad Off
  trigger:
    - entity_id: light.master_bathroom_led_rgb
      platform: state
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.master_bathroom_leds_power
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.master_bathroom_leds_power

- alias: Kitchen LEDs Keypad On
  trigger:
    - entity_id: light.kitchen_leds_rgb
      platform: state
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.kitchen_leds_power
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.kitchen_leds_power

- alias: Kitchen LEDs Keypad Off
  trigger:
    - entity_id: light.kitchen_leds_rgb
      platform: state
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.kitchen_leds_power
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.kitchen_leds_power

- alias: Den LEDs Keypad On
  trigger:
    - entity_id: light.den_leds_rgb
      platform: state
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.den_leds_power
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.den_leds_power

- alias: Den LEDs Keypad Off
  trigger:
    - entity_id: light.den_leds_rgb
      platform: state
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.den_leds_power
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.den_leds_power

- alias: Guest Bathroom LEDs Keypad On
  trigger:
    - entity_id: light.guest_bathroom_led_rgb
      platform: state
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.guest_bathroom_leds_power
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.guest_bathroom_leds_power

- alias: Guest Bathroom LEDs Keypad Off
  trigger:
    - entity_id: light.guest_bathroom_led_rgb
      platform: state
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.guest_bathroom_leds_power
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.guest_bathroom_leds_power

- alias: White Counter LEDs Keypad On
  trigger:
    - entity_id: light.kitchen_counter_leds_white
      platform: state
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.kitchen_undercabinet_lights
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.kitchen_undercabinet_lights

- alias: White Counter LEDs Keypad Off
  trigger:
    - entity_id: light.kitchen_counter_leds_white
      platform: state
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.kitchen_undercabinet_lights
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.kitchen_undercabinet_lights

- alias: Stained Glass LEDs On from Keypad
  trigger:
    - platform: state
      entity_id: switch.stained_glass
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.den_stained_glass
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.den_stained_glass
    
- alias: Stained Glass LEDs Off from Keypad
  trigger:
    - platform: state
      entity_id: switch.stained_glass
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.den_stained_glass
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.den_stained_glass     

- alias: Stained Glass LEDs Keypad On
  trigger:
    - entity_id: switch.den_stained_glass
      platform: state
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.stained_glass
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.stained_glass

- alias: Stained Glass LEDs Keypad Off
  trigger:
    - entity_id: switch.den_stained_glass
      platform: state
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: switch.stained_glass
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.stained_glass