- alias: Master Bedroom LEDs On from Keypad
  id: 63f0a62d-e12a-4c02-8a7d-dd656c0406be
  trigger:
    - platform: state
      entity_id: switch.master_leds_power
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: light.master_bedroom_leds_rgb
      state: "off"
  action:
    - service: light.turn_on
      entity_id: light.master_bedroom_leds_rgb

- alias: Master Bedroom LEDs Off from Keypad
  id: e9f5128d-c5c9-4839-8e49-84bfa23ff0c3
  trigger:
    - platform: state
      entity_id: switch.master_leds_power
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: light.master_bedroom_leds_rgb
      state: "on"
  action:
    - service: light.turn_off
      entity_id: light.master_bedroom_leds_rgb

- alias: Master Bathroom LEDs On from Keypad
  id: db208244-e971-452c-816f-2c35d77a1705
  trigger:
    - platform: state
      entity_id: switch.master_bathroom_leds_power
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: light.master_bathroom_led_rgb
      state: "off"
  action:
    - service: light.turn_on
      entity_id: light.master_bathroom_led_rgb

- alias: Master Bathroom LEDs Off from Keypad
  id: efd698f7-84e5-4d02-ba60-0c44bdc73e06
  trigger:
    - platform: state
      entity_id: switch.master_bathroom_leds_power
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: light.master_bathroom_led_rgb
      state: "on"
  action:
    - service: light.turn_off
      entity_id: light.master_bathroom_led_rgb

- alias: Kitchen LEDs On from Keypad
  id: c4b53362-baff-49b0-bbd9-3be1f30f2816
  trigger:
    - platform: state
      entity_id: switch.kitchen_leds_power
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: light.kitchen_leds_rgb
      state: "off"
  action:
    - service: light.turn_on
      entity_id: light.kitchen_leds_rgb

- alias: Kitchen LEDs Off from Keypad
  id: 8774921d-e589-417e-a6e2-e9ba94666ca5
  trigger:
    - platform: state
      entity_id: switch.kitchen_leds_power
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: light.kitchen_leds_rgb
      state: "on"
  action:
    - service: light.turn_off
      entity_id: light.kitchen_leds_rgb

- alias: Den LEDs On from Keypad
  id: d302c0c2-dc65-4c39-8d83-4f54a1abee8c
  trigger:
    - platform: state
      entity_id: switch.den_leds_power
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: light.den_leds_rgb
      state: "off"
  action:
    - service: light.turn_on
      entity_id: light.den_leds_rgb

- alias: Den LEDs Off from Keypad
  id: 2644b7fc-9365-46ee-af0e-99f519e28349
  trigger:
    - platform: state
      entity_id: switch.den_leds_power
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: light.den_leds_rgb
      state: "on"
  action:
    - service: light.turn_off
      entity_id: light.den_leds_rgb

- alias: Guest Bathroom LEDs On from Keypad
  id: 6577d80a-9449-41b3-8d79-62e69ccba079
  trigger:
    - platform: state
      entity_id: switch.guest_bathroom_leds_power
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: light.guest_bathroom_led_rgb
      state: "off"
  action:
    - service: light.turn_on
      entity_id: light.guest_bathroom_led_rgb

- alias: Guest Bathroom LEDs Off from Keypad
  id: 4e75a0e7-0687-4fe8-8042-07e9cef0f5fa
  trigger:
    - platform: state
      entity_id: switch.guest_bathroom_leds_power
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: light.guest_bathroom_led_rgb
      state: "on"
  action:
    - service: light.turn_off
      entity_id: light.guest_bathroom_led_rgb

- alias: Counter LEDs On from Keypad
  id: 50974046-bef0-4d43-b401-5817b4c07455
  trigger:
    - platform: state
      entity_id: switch.kitchen_undercabinet_lights
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: light.kitchen_counter_leds_white
      state: "off"
  action:
    - service: light.turn_on
      entity_id: light.kitchen_counter_leds_white

- alias: Counter LEDs Off from Keypad
  id: 81f67999-5e21-4a80-ae15-20b193eb9dde
  trigger:
    - platform: state
      entity_id: switch.kitchen_undercabinet_lights
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: light.kitchen_counter_leds_white
      state: "on"
  action:
    - service: light.turn_off
      entity_id: light.kitchen_counter_leds_white

- alias: Master Bedroom LEDs Keypad On
  id: 3ffe0a71-b168-4a96-9c48-3dc7f0b5e8ee
  trigger:
    - entity_id: light.master_bedroom_leds_rgb
      platform: state
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: switch.master_leds_power
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.master_leds_power

- alias: Master Bedroom LEDs Keypad Off
  id: f3baef06-bf98-4766-9112-0522fe31228a
  trigger:
    - entity_id: light.master_bedroom_leds_rgb
      platform: state
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: switch.master_leds_power
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.master_leds_power

- alias: Master Bathroom LEDs Keypad On
  id: ba6a559d-8a1e-46b9-8388-78800ab6e3ea
  trigger:
    - entity_id: light.master_bathroom_led_rgb
      platform: state
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: switch.master_bathroom_leds_power
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.master_bathroom_leds_power

- alias: Master Bathroom LEDs Keypad Off
  id: 9744f0fe-139a-4a5a-b425-5dc2172935f1
  trigger:
    - entity_id: light.master_bathroom_led_rgb
      platform: state
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: switch.master_bathroom_leds_power
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.master_bathroom_leds_power

- alias: Kitchen LEDs Keypad On
  id: 506f5dba-ba13-40c3-9bff-a80df1ab8e58
  trigger:
    - entity_id: light.kitchen_leds_rgb
      platform: state
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: switch.kitchen_leds_power
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.kitchen_leds_power

- alias: Kitchen LEDs Keypad Off
  id: ebb428c5-2ca0-4198-a5dd-414335f7d26a
  trigger:
    - entity_id: light.kitchen_leds_rgb
      platform: state
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: switch.kitchen_leds_power
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.kitchen_leds_power

- alias: Den LEDs Keypad On
  id: 75a733cd-126b-4927-a578-b3fc54e06457
  trigger:
    - entity_id: light.den_leds_rgb
      platform: state
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: switch.den_leds_power
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.den_leds_power

- alias: Den LEDs Keypad Off
  id: 318f1a69-9ed0-46b7-b697-4a0b696231a3
  trigger:
    - entity_id: light.den_leds_rgb
      platform: state
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: switch.den_leds_power
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.den_leds_power

- alias: Guest Bathroom LEDs Keypad On
  id: 6ce141d9-212e-419e-9a5f-fbb96840dd6f
  trigger:
    - entity_id: light.guest_bathroom_led_rgb
      platform: state
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: switch.guest_bathroom_leds_power
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.guest_bathroom_leds_power

- alias: Guest Bathroom LEDs Keypad Off
  id: c54a1c16-482f-4039-a4aa-b20d3c3ae666
  trigger:
    - entity_id: light.guest_bathroom_led_rgb
      platform: state
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: switch.guest_bathroom_leds_power
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.guest_bathroom_leds_power

- alias: White Counter LEDs Keypad On
  id: 91fba5f2-5abe-4173-bd28-f4d0c8e1a59a
  trigger:
    - entity_id: light.kitchen_counter_leds_white
      platform: state
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: switch.kitchen_undercabinet_lights
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.kitchen_undercabinet_lights

- alias: White Counter LEDs Keypad Off
  id: 14d73378-7920-48dc-96ef-6e8059c66c0b
  trigger:
    - entity_id: light.kitchen_counter_leds_white
      platform: state
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: switch.kitchen_undercabinet_lights
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.kitchen_undercabinet_lights

- alias: Stained Glass LEDs On from Keypad
  id: 72dd7bb4-1f1d-4d38-a850-a94fc0ca4944
  trigger:
    - platform: state
      entity_id: switch.stained_glass
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: light.den_window_leds_cct
      state: "off"
  action:
    - service: light.turn_on
      entity_id: light.den_window_leds_cct

- alias: Stained Glass LEDs Off from Keypad
  id: c870c392-5229-4bec-b66d-b253b1266f00
  trigger:
    - platform: state
      entity_id: switch.stained_glass
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: light.den_window_leds_cct
      state: "on"
  action:
    - service: light.turn_off
      entity_id: light.den_window_leds_cct

- alias: Stained Glass LEDs Keypad On
  id: 6ab91176-1d68-4bcd-8d13-2a779fe34cdb
  trigger:
    - entity_id: light.den_window_leds_cct
      platform: state
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: switch.stained_glass
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.stained_glass

- alias: Stained Glass LEDs Keypad Off
  id: b6d2f668-f16d-4e7d-8ee1-495a9bc567a3
  trigger:
    - entity_id: light.den_window_leds_cct
      platform: state
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: switch.stained_glass
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.stained_glass
