- alias: Master Shower On
  trigger:
    - platform: state
      entity_id: switch.master_shower_light_a
      from: 'off'
      to: 'on'
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/command/set/zone/vol
        payload_template: '5,40'
    - service: cover.close_cover
      entity_id: cover.master_blinds

- alias: Master Shower Off
  trigger:
    - platform: state
      entity_id: switch.master_shower_light_a
      from: 'on'
      to: 'off'
  action:
    - service: mqtt.publish
      data:
        topic: nuvo/command/set/zone/vol
        payload_template: '5,60'
      
- alias: Master Shower Fan Timer
  trigger:
  - platform: state
    entity_id: light.master_shower_light
    to: 'off'
  condition:
  - condition: state
    entity_id: switch.master_shower_light_a
    state: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: nuvo/command/set/zone/vol
      payload_template: '5,60'
  - delay: 00:10:00
  - service: switch.turn_off
    data:
      entity_id: switch.shower_light_and_fan