- alias: Notify Alarm Tripped
  id: 6a73c789-cb0d-4d19-ac13-03d042831959
  trigger:
    - platform: state
      entity_id: switch.elk_intruder_alarm_tripped
      to: "on"
  action:
    - service: notify.mobile_app_shawn_n30
      data:
        message: The alarm has been triggered.
        title: Alarm!
        data:
          ttl: 0
          priority: high

- alias: Notify Garage Opened While Away
  id: 8965638d-9057-45fc-a070-b2bf5f9c274f
  trigger:
    - platform: state
      entity_id: sensor.elk_garage_door
      to: Violated
  condition:
    - condition: state
      entity_id: alarm_control_panel.house
      state: armed_away
  action:
    - service: notify.mobile_app_shawn_n30
      data:
        message: The garage door was opened while the alarm was armed.
        title: Garage Door
        data:
          ttl: 0
          priority: high
