- alias: Keep Popcorn Popper Off When Away
  id: 4e6b9d80-0c79-4a54-9c7e-29a52a356047
  trigger:
    - platform: state
      entity_id: switch.popper
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_night
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_away
  action:
    - service: switch.turn_off
      entity_id: switch.popper
