- alias: Count Rainfall
  id: 7da2ee73-f9b2-41a1-b75e-fed26d4de648
  trigger:
    - platform: state
      entity_id: sensor.elk_mechanical_rain
      from: Normal
      to: Violated
    - platform: state
      entity_id: sensor.elk_mechanical_rain
      from: Violated
      to: Normal
  action:
    - service: counter.increment
      entity_id:
        - counter.rain_minute
        - counter.rain_hour
        - counter.rain_day
        - counter.rain_week
        - counter.rain_month
        - counter.rain_year
        - counter.rain_total
    - service: counter.increment
      data_template:
        entity_id: >
          counter.rain_month_{{ now().month }}

    - service: input_number.set_value
      data_template:
        entity_id: >
          {% if  now().minute < 10 -%}
            input_number.rain_minute_0{{ now().minute }}
          {% else -%}
            input_number.rain_minute_{{ now().minute }}
          {% endif -%}
        value: "{{ states('sensor.rain_minute') }}"

    - service: input_text.set_value
      entity_id: input_text.last_rain
      data_template:
        value: "{{ now() }}"

- alias: Reset Minute Rain
  id: 18532267-5d0d-49da-8cb2-50440c6569ca
  trigger:
    - platform: time_pattern
      minutes: "*"
      seconds: "0"
  action:
    - service: input_number.set_value
      data_template:
        entity_id: >
          {% if now().minute == 0 -%}
            input_number.rain_minute_59
          {% elif  now().minute <= 10 -%}
            input_number.rain_minute_0{{ now().minute - 1 }}
          {% else -%}
            input_number.rain_minute_{{ now().minute - 1 }}
          {% endif -%}
        value: "{{ states('sensor.rain_minute') }}"
    - service: input_number.set_value
      entity_id: input_number.rain_last_minute
      data_template:
        value: "{{ states('counter.rain_minute') | int(0) }}"
    - service: counter.reset
      entity_id: counter.rain_minute

- alias: Reset Hour Rain
  id: 8e6db58a-4e06-4d40-81d3-d0df45583091
  trigger:
    - platform: time_pattern
      hours: "*"
      minutes: "0"
      seconds: "0"
  action:
    - service: input_number.set_value
      entity_id: input_number.rain_last_hour
      data_template:
        value: "{{ states('counter.rain_hour') | int(0) }}"
    - service: counter.reset
      entity_id: counter.rain_hour

- alias: Reset Day Rain
  id: 07cb27b8-3ec2-4da2-a348-b25ea3a265ef
  trigger:
    - platform: time
      at: "00:00:00"
  action:
    - service: input_number.set_value
      entity_id: input_number.rain_last_day
      data_template:
        value: "{{ states('counter.rain_day') | int(0) }}"
    - service: counter.reset
      entity_id: counter.rain_day

- alias: Reset Week Rain
  id: 2bb73533-17d7-49cc-b52d-8448c94ed490
  trigger:
    - platform: time
      at: "00:00:00"
  condition:
    - condition: template
      value_template: "{{ now().weekday() == 0 }}"
  action:
    - service: input_number.set_value
      entity_id: input_number.rain_last_week
      data_template:
        value: "{{ states('counter.rain_week') | int(0) }}"
    - service: counter.reset
      entity_id: counter.rain_week

- alias: Reset Month Rain
  id: bc41d281-ad03-4ebf-8dad-4a62194ee1b4
  trigger:
    - platform: time
      at: "00:00:00"
  condition:
    - condition: template
      value_template: "{{ now().day == 1 }}"
  action:
    - service: input_number.set_value
      entity_id: input_number.rain_last_month
      data_template:
        value: "{{ states('counter.rain_month') | int(0) }}"
    - service: counter.reset
      entity_id: counter.rain_month

- alias: Reset Year Rain
  id: 4e41317a-b7a9-458b-9db5-a3f374491c5d
  trigger:
    - platform: time
      at: "00:00:00"
  condition:
    - condition: template
      value_template: "{{ now().month == 1 }}"
    - condition: template
      value_template: "{{ now().day == 1 }}"
  action:
    - service: input_number.set_value
      entity_id: input_number.rain_last_year
      data_template:
        value: "{{ states('counter.rain_year') | int(0) }}"
    - service: input_number.set_value
      entity_id: input_number.rain_last_month_1
      data_template:
        value: "{{ states('counter.rain_month_1') | int(0) }}"
    - service: input_number.set_value
      entity_id: input_number.rain_last_month_2
      data_template:
        value: "{{ states('counter.rain_month_2') | int(0) }}"
    - service: input_number.set_value
      entity_id: input_number.rain_last_month_3
      data_template:
        value: "{{ states('counter.rain_month_3') | int(0) }}"
    - service: input_number.set_value
      entity_id: input_number.rain_last_month_4
      data_template:
        value: "{{ states('counter.rain_month_4') | int(0) }}"
    - service: input_number.set_value
      entity_id: input_number.rain_last_month_5
      data_template:
        value: "{{ states('counter.rain_month_5') | int(0) }}"
    - service: input_number.set_value
      entity_id: input_number.rain_last_month_6
      data_template:
        value: "{{ states('counter.rain_month_6') | int(0) }}"
    - service: input_number.set_value
      entity_id: input_number.rain_last_month_7
      data_template:
        value: "{{ states('counter.rain_month_7') | int(0) }}"
    - service: input_number.set_value
      entity_id: input_number.rain_last_month_8
      data_template:
        value: "{{ states('counter.rain_month_8') | int(0) }}"
    - service: input_number.set_value
      entity_id: input_number.rain_last_month_9
      data_template:
        value: "{{ states('counter.rain_month_9') | int(0) }}"
    - service: input_number.set_value
      entity_id: input_number.rain_last_month_10
      data_template:
        value: "{{ states('counter.rain_month_10') | int(0) }}"
    - service: input_number.set_value
      entity_id: input_number.rain_last_month_11
      data_template:
        value: "{{ states('counter.rain_month_11') | int(0) }}"
    - service: input_number.set_value
      entity_id: input_number.rain_last_month_12
      data_template:
        value: "{{ states('counter.rain_month_12') | int(0) }}"
    - service: counter.reset
      entity_id: 
        - counter.rain_year
        - counter.rain_month_1
        - counter.rain_month_2
        - counter.rain_month_3
        - counter.rain_month_4
        - counter.rain_month_5
        - counter.rain_month_6
        - counter.rain_month_7
        - counter.rain_month_8
        - counter.rain_month_9
        - counter.rain_month_10
        - counter.rain_month_11
        - counter.rain_month_12
    

- alias: Detect Rain Started
  id: 36234827-f4ba-4b2c-b68f-b27ee354d257
  trigger:
    - platform: state
      entity_id: sensor.elk_optical_rain
      to: Violated
  condition:
    - condition: state
      entity_id: input_boolean.is_raining
      state: "off"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.is_raining
    - condition: template
      value_template: "{{ not is_state('person.shawn_mccoy','home') }}"
    - service: notify.mobile_app_shawn_7t
      data:
        message: It is now raining.
        title: Weather
        data:
          ttl: 0
          priority: high
    - service: browser_mod.notification
      data:
        message: "It is now raining."
        duration: 3000

- alias: Detect Rain Stopped
  id: 9ae2b245-b303-4d59-ba85-2be41146bcdd
  trigger:
    - platform: state
      entity_id: sensor.elk_optical_rain
      to: Normal
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.is_raining
      state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.is_raining
    - condition: template
      value_template: "{{ not is_state('person.shawn_mccoy','home') }}"
    - service: notify.mobile_app_shawn_7t
      data:
        message: It has stopped raining.
        title: Weather
        data:
          ttl: 0
          priority: high
    - service: browser_mod.notification
      data:
        message: "It has stopped raining."
        duration: 3000

- alias: Display Rainfall on Elk Keypads
  id: aae69df9-96b8-4b41-aac4-ddbc2f3e37db
  trigger:
    - platform: state
      entity_id: sensor.rain_day
    - platform: state
      entity_id: alarm_control_panel.house
      to: disarmed
    - platform: state
      entity_id: alarm_control_panel.house
      from: arming
      to: armed_home
    - platform: state
      entity_id: alarm_control_panel.house
      from: arming
      to: armed_night
    - platform: state
      entity_id: alarm_control_panel.house
      from: 
        - disarmed
        - armed_night
      to: armed_home
      for: "00:01:00"
    - platform: state
      entity_id: alarm_control_panel.house
      from: 
        - disarmed
        - armed_home
      to: armed_night
      for: "00:01:00"
  condition:
    - condition: template
      value_template: "{{ states('sensor.rain_day') | float(none) > 0 }}"
  action:
    - service: elkm1.alarm_display_message
      data_template:
        entity_id: alarm_control_panel.house
        line1: 'Rain: {{ states("sensor.rain_day") }}"'

- alias: Clear Rainfall on Elk Keypads
  id: d7ec1407-ccc7-4c86-a807-382bad717c5f
  trigger:
    - platform: template
      value_template: "{{ states('sensor.rain_day') | float(none) == 0 }}"
  action:
    - service: elkm1.alarm_display_message
      data_template:
        entity_id: alarm_control_panel.house
        clear: 0
