- alias: Count Rainfall
  id: 7da2ee73-f9b2-41a1-b75e-fed26d4de648
  trigger:
    - platform: state
      entity_id: sensor.elk_mechanical_rain
      from: Normal
      to: Violated
    - platform: state
      entity_id: sensor.elk_mechanical_rain
      from: Violated
      to: Normal
  action:
    - service: counter.increment
      entity_id:
        - counter.rain_minute
        - counter.rain_hour
        - counter.rain_day
        - counter.rain_month
        - counter.rain_year
        - counter.rain_total
    - service: input_number.set_value
      data_template:
        entity_id: >
          {% if  now().minute < 10 -%}
            input_number.rain_minute_0{{ now().minute }}
          {% else -%}
            input_number.rain_minute_{{ now().minute }}
          {% endif -%}
        value: "{{ states('sensor.rain_minute') }}"

- alias: Reset Minute Rain
  id: 18532267-5d0d-49da-8cb2-50440c6569ca
  trigger:
    - platform: time_pattern
      minutes: "*"
      seconds: "0"
  action:
    - service: input_number.set_value
      data_template:
        entity_id: >
          {% if now().minute == 0 -%}
            input_number.rain_minute_59
          {% elif  now().minute <= 10 -%}
            input_number.rain_minute_0{{ now().minute - 1 }}
          {% else -%}
            input_number.rain_minute_{{ now().minute - 1 }}
          {% endif -%}
        value: "{{ states('sensor.rain_minute') }}"
    - service: counter.reset
      entity_id: counter.rain_minute

- alias: Reset Hour Rain
  id: 8e6db58a-4e06-4d40-81d3-d0df45583091
  trigger:
    - platform: time_pattern
      hours: "*"
      minutes: "0"
      seconds: "0"
  action:
    - service: counter.reset
      entity_id: counter.rain_hour

- alias: Reset Day Rain
  id: 07cb27b8-3ec2-4da2-a348-b25ea3a265ef
  trigger:
    - platform: time
      at: "00:00:00"
  action:
    - service: counter.reset
      entity_id: counter.rain_day

- alias: Reset Month Rain
  id: bc41d281-ad03-4ebf-8dad-4a62194ee1b4
  trigger:
    - platform: time
      at: "00:00:00"
  condition:
    - condition: template
      value_template: "{{ now().day == 1 }}"
  action:
    - service: counter.reset
      entity_id: counter.rain_month

- alias: Reset Year Rain
  id: 4e41317a-b7a9-458b-9db5-a3f374491c5d
  trigger:
    - platform: time
      at: "00:00:00"
  condition:
    - condition: template
      value_template: "{{ now().month == 1 }}"
    - condition: template
      value_template: "{{ now().day == 1 }}"
  action:
    - service: counter.reset
      entity_id: counter.rain_year

- alias: Detect Rain Started
  id: 36234827-f4ba-4b2c-b68f-b27ee354d257
  trigger:
    - platform: state
      entity_id: sensor.elk_optical_rain
      to: Violated
  condition:
    - condition: state
      entity_id: input_boolean.is_raining
      state: "off"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.is_raining
    - condition: template
      value_template: "{{ not is_state('device_tracker.shawn_7t','home') }}"
    - service: notify.mobile_app_shawn_7t
      data:
        message: It is now raining.
        title: Weather
        data:
          ttl: 0
          priority: high
    - service: browser_mod.toast
      data:
        message: "It is now raining."
        duration: 3000

- alias: Detect Rain Stopped
  id: 9ae2b245-b303-4d59-ba85-2be41146bcdd
  trigger:
    - platform: state
      entity_id: sensor.elk_optical_rain
      to: Normal
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.is_raining
      state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.is_raining
    - condition: template
      value_template: "{{ not is_state('device_tracker.shawn_7t','home') }}"
    - service: notify.mobile_app_shawn_7t
      data:
        message: It has stopped raining.
        title: Weather
        data:
          ttl: 0
          priority: high
    - service: browser_mod.toast
      data:
        message: "It has stopped raining."
        duration: 3000

- alias: Display Rainfall on Elk Keypads
  id: aae69df9-96b8-4b41-aac4-ddbc2f3e37db
  trigger:
    - platform: state
      entity_id: sensor.rain_day
    - platform: state
      entity_id: alarm_control_panel.house
      to: disarmed
    - platform: state
      entity_id: alarm_control_panel.house
      from: arming
      to: armed_home
    - platform: state
      entity_id: alarm_control_panel.house
      from: arming
      to: armed_night
  condition:
    - condition: template
      value_template: "{{ states('sensor.rain_day') | float > 0 }}"
  action:
    - service: elkm1.alarm_display_message
      data_template:
        entity_id: alarm_control_panel.house
        line1: 'Rain: {{ states("sensor.rain_day") }}"'

- alias: Clear Rainfall on Elk Keypads
  id: d7ec1407-ccc7-4c86-a807-382bad717c5f
  trigger:
    - platform: template
      value_template: "{{ states('sensor.rain_day') | float == 0 }}"
  action:
    - service: elkm1.alarm_display_message
      data_template:
        entity_id: alarm_control_panel.house
        clear: 0
