- alias: Start Roomba from Schedule
  id: ff865037-59b4-4162-a27e-abfd1fe70817
  trigger:
    - platform: state
      entity_id: sensor.roomba_scheduler_command
      from: stop
      to: start
  action:
    - service: vacuum.start
      entity_id: vacuum.roomba

- alias: Count Roomba Cycles
  id: a49c5f1b-a77a-4223-9364-8f510e85d6d9
  trigger:
    - platform: state
      entity_id: sensor.roomba_status
      to: "cleaning"
  action:
    - service: counter.increment
      entity_id: counter.roomba_cycles

- alias: Roomba Return if House Disarmed
  id: 6dba1760-613c-4165-8e41-b54466b7ff1d
  trigger:
    - platform: state
      entity_id: input_boolean.hvac_geofence
      to: "on"
  condition:
    - condition: state
      entity_id: sensor.roomba_status
      state: cleaning
    - condition: state
      entity_id: input_boolean.roomba_auto
      state: "on"
  action:
    - service: script.turn_on
      entity_id: script.roomba_dock

- alias: Reset Dust Bin From NFC
  id: ca947aaf-f8d3-485b-a1fe-1fe78a8eaa34
  trigger:
    - platform: event
      event_type: tag_scanned
      event_data:
        tag_id: !secret roomba_nfc
  action:
    - service: script.reset_roomba_counter
