- alias: Elk Speak Front Door
  trigger:
    - entity_id: sensor.elk_front_door
      platform: state
      to: Violated
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 1,7
    
- alias: Elk Speak Back Door
  trigger:
    - entity_id: sensor.elk_back_door
      platform: state
      to: Violated
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 1,2

- alias: Elk Speak Center Master Window
  trigger:
    - entity_id: sensor.elk_master_bed_window_center
      platform: state
      to: Violated
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 1,3

- alias: Elk Speak Center Office Window
  trigger:
    - entity_id: sensor.elk_office_window_center
      platform: state
      to: Violated
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 1,4

- alias: Elk Speak East Breakfast Room Window
  trigger:
    - entity_id: sensor.elk_dining_room_window_east
      platform: state
      to: Violated
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 1,6

- alias: Elk Speak Garage Door
  trigger:
    - entity_id: sensor.elk_garage_door
      platform: state
      to: Violated
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 1,9

- alias: Elk Speak Garage Entry
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('sensor.elk_garage_entry', 'physical_status', 'open') }}"
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 1,10

- alias: Elk Speak Guest Window
  trigger:
    - entity_id: sensor.elk_guest_bed_wildow
      platform: state
      to: Violated
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 1,12

- alias: Elk Speak Left Breakfast Room Window
  trigger:
    - entity_id: sensor.elk_dining_room_window_left
      platform: state
      to: Violated
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 1,16

- alias: Elk Speak Right Breakfast Room Window
  trigger:
    - entity_id: sensor.elk_dining_room_window_right
      platform: state
      to: Violated
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 1,19

- alias: Elk Speak Left Master Bedroom Window
  trigger:
    - entity_id: sensor.elk_master_bed_window_left
      platform: state
      to: Violated
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 1,17

- alias: Elk Speak Left Office Window
  trigger:
    - entity_id: sensor.elk_office_window_left
      platform: state
      to: Violated
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 1,18

- alias: Elk Speak Right Office Window
  trigger:
    - entity_id: sensor.elk_office_window_right
      platform: state
      to: Violated
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 1,21

- alias: Elk Speak Right Master Bedroom Window
  trigger:
    - entity_id: sensor.elk_master_bed_window_right
      platform: state
      to: Violated
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 1,20

- alias: Elk Speak Server Room Window
  trigger:
    - entity_id: sensor.elk_server_room_window
      platform: state
      to: Violated
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 1,22

- alias: Elk Speak West Master Bedroom Window
  trigger:
    - entity_id: sensor.elk_master_bed_window_west
      platform: state
      to: Violated
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 1,26

- alias: Elk Speak Air Handler Disabled
  trigger:
    - entity_id: switch.elk_ahu_disable
      platform: state
      to: 'on'
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 2,1

- alias: Elk Speak Armed Stay
  trigger:
    - entity_id: alarm_control_panel.house
      from: disarmed
      platform: state
      to: armed_home
    - entity_id: alarm_control_panel.house
      from: armed_night
      platform: state
      to: armed_home
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 2,12

- alias: Elk Speak Armed Away
  trigger:
    - entity_id: alarm_control_panel.house
      from: disarmed
      platform: state
      to: armed_away
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 2,5
    - delay: '00:00:48'
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 2,13

- alias: Elk Speak Armed Vacation
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('alarm_control_panel.house', 'armed_status', 'armed_to_vacation') }}"
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 2,14
    - delay: '00:00:48'
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 2,13      

- alias: Elk Speak Armed Night
  trigger:
    - entity_id: alarm_control_panel.house
      from: disarmed
      platform: state
      to: armed_night
    - entity_id: alarm_control_panel.house
      from: armed_home
      platform: state
      to: armed_night
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 2,8

- alias: Elk Speak Disarmed
  trigger:
    - entity_id: alarm_control_panel.house
      platform: state
      to: disarmed
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 2,2

- alias: Doorbell Alert
  trigger:
    - platform: mqtt
      topic: parrot/tele/doorbell
    - platform: state
      entity_id: sensor.elk_doorbell
      to: Violated
  action:
    - service: mqtt.publish
      data_template:
        topic: parrot/command/set/play
        payload: >
          {% if states('input_select.doorbell_tone') == "Alexa Speak" -%}
            4,1
          {% elif  states('input_select.doorbell_tone') == "Wish Upon A Star" -%}
            4,3
          {% elif  states('input_select.doorbell_tone') == "Christmas" -%}
            4,2
          {% else -%}
            4,1
          {% endif -%}
    - service: camera.snapshot
      data:
        entity_id: camera.front_porch
        filename: /config/www/cctv/tmp/front_porch_{{ now ().year }}_{{ now ().month }}_{{ now ().day }}_{{ now ().hour }}_{{ now ().minute }}.jpg
    - service: browser_mod.more_info
      entity_id: camera.front_porch
    - service: timer.start
      entity_id: timer.doorbell_popup
    - service: notify.mobile_app_shawn_7t
      data_template:
        title: Doorbell
        message: Someone is at the front door.
        data:
          image: "{{ states('sensor.external_url') }}/local/cctv/tmp/front_porch_{{ now ().year }}_{{ now ().month }}_{{ now ().day }}_{{ now ().hour }}_{{ now ().minute }}.jpg"
          data:
          actions:
            - action: URI
              title: "Open Image"
              uri: "{{ states('sensor.external_url') }}/local/cctv/tmp/front_porch_{{ now ().year }}_{{ now ().month }}_{{ now ().day }}_{{ now ().hour }}_{{ now ().minute }}.jpg"
    - service: notify.den_kodi
      data:
        title: "Doorbell"
        message: "Someone is at the front door."
        data:
          displaytime: 20000
          icon: "info"
          
    - service: browser_mod.toast
      data:
        message: "Someone is at the door."
    - service: notify.cctv_email
      data_template:
        title: "CCTV Alarm: Front Porch - Doorbell Pressed {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
        message: "The doorbell was rung at {{now().strftime('%H:%M:%S') }}."
        data: 
          images:
            - /config/www/cctv/tmp/front_porch_{{ now ().year }}_{{ now ().month }}_{{ now ().day }}_{{ now ().hour }}_{{ now ().minute }}.jpg

- alias: Close Doorbell Popup When Timer Expires
  trigger:
    - event_data:
        entity_id: timer.doorbell_popup
      event_type: timer.finished
      platform: event
  action:
    - service: browser_mod.close_popup

- alias: Timer Alert
  trigger:
    - platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: echotimer
  action:
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 3,2
    - service: switch.turn_off
      data:
        entity_id: switch.alexa_timer_end
          