- alias: Tablet Night
  id: ac3d7016-5b0f-42dd-939f-f47e7486618e
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      from: disarmed
      to: armed_night
    - platform: state
      entity_id: alarm_control_panel.house
      from: armed_home
      to: armed_night
  action:
    - service: light.turn_off
      entity_id:
        - light.den_tablet_screen
        - light.kitchen_tablet_screen
        - light.master_bedroom_tablet_screen
        - light.office_tablet_screen
        - light.shack_tablet_screen
        - light.entry_tablet_screen
        - light.server_tablet_screen

- alias: Tablet When Home
  id: ebfd2c16-e7a6-417a-b820-236884d35fe7
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      to: disarmed
    - platform: state
      entity_id: alarm_control_panel.house
      from: armed_night
      to: armed_home
  action:
    - service: light.turn_on
      entity_id:
        - light.den_tablet_screen
        - light.kitchen_tablet_screen
        - light.master_bedroom_tablet_screen
        - light.office_tablet_screen
        - light.shack_tablet_screen
        - light.entry_tablet_screen
        - light.server_tablet_screen

- alias: Tablet when Away
  id: afe3db69-fe02-4bc7-8282-0935e4976610
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      to: armed_away
  action:
    - service: light.turn_off
      entity_id:
        - light.den_tablet_screen
        - light.kitchen_tablet_screen
        - light.master_bedroom_tablet_screen
        - light.office_tablet_screen
        - light.shack_tablet_screen
        - light.entry_tablet_screen
        - light.server_tablet_screen

- alias: Reload Tablets When HA Starts
  id: 37809ea5-1069-4fb7-8a84-082d72e77732
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: button.press
      entity_id: 
        - button.den_tablet_load_start_url
        - button.kitchen_tablet_load_start_url
        - button.master_bedroom_tablet_load_start_url
        - button.office_tablet_load_start_url
        - button.shack_tablet_load_start_url
        - button.entry_tablet_load_start_url
        - button.server_tablet_load_start_url
