- alias: Tablet Night
  id: ac3d7016-5b0f-42dd-939f-f47e7486618e
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      from: disarmed
      to: armed_night
    - platform: state
      entity_id: alarm_control_panel.house
      from: armed_home
      to: armed_night
  action:
    - service: switch.turn_off
      entity_id: switch.tablet_screens
    - service: script.crestron_standby

- alias: Tablet When Home
  id: ebfd2c16-e7a6-417a-b820-236884d35fe7
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      to: disarmed
    - platform: state
      entity_id: alarm_control_panel.house
      from: armed_night
      to: armed_home
  action:
    - service: switch.turn_on
      entity_id: switch.tablet_screens
    - service: script.crestron_wake

- alias: Tablet when Away
  id: afe3db69-fe02-4bc7-8282-0935e4976610
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      from: arming
      to: 
        - armed_away
        - armed_vacation
  action:
    - service: switch.turn_off
      entity_id: switch.tablet_screens
    - service: script.crestron_standby

- alias: Reload Tablets When HA Starts
  id: 37809ea5-1069-4fb7-8a84-082d72e77732
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: button.press
      entity_id: 
        - button.den_tablet_load_start_url
        - button.kitchen_tablet_load_start_url
        - button.master_bedroom_tablet_load_start_url
        - button.office_tablet_load_start_url
        - button.shack_tablet_load_start_url
        - button.entry_tablet_load_start_url
        - button.server_tablet_load_start_url

- alias: Tablets On When Front Door Unlocked
  id: a2ab1923-ff57-440c-8e18-f65e9fe5c3f9
  trigger:
    - platform: state
      entity_id: lock.front_door_lock
      to: 
        - Unlocked
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: pending
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_away
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_vacation
  action:
    - action: switch.turn_off
      entity_id: switch.tablet_screens
    - action: light.turn_on
      data:
        entity_id: light.wall_panel_leds  
        rgb_color:
          - 255
          - 0
          - 0
        brightness_pct: 40

- alias: Tablet Backlight Show Alarmed Armed
  id: 1e7c97ce-a4af-4ee5-b0d1-6bd5253c82c1
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      from:
        - disarmed
        - armed_night
        - armed_home
        - armed_away
        - armed_vacation
      to:
        - armed_away
        - armed_night
        - armed_home
        - armed_vacation
  action:
    - action: light.turn_on
      data:
        entity_id: light.wall_panel_leds  
        rgb_color:
          - 255
          - 0
          - 0
        brightness_pct: 40

- alias: Tablet Backlight Show Alarm Disarmed
  id: 02f9a079-9075-42ce-87f6-2fd4bd713980
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      to:
        - disarmed
  action:
    - action: light.turn_on
      data:
        entity_id: light.wall_panel_leds  
        rgb_color:
          - 0
          - 255
          - 0
        brightness_pct: 40