- alias: Timer Lights On Main Weekday AM
  id: 9179c7ea-cf4b-401b-b2bc-96bf1f329c91
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.master_work_alarm', 'timestamp') | timestamp_custom('%H:%M', False, none)) }}"
  condition:
    - condition: state
      entity_id: binary_sensor.weekend_today
      state: "off"
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: binary_sensor.work_holiday_today
              state: "off"
            - condition: state
              entity_id: input_boolean.work_alarm_enabled
              state: "on"
        - condition: state
          entity_id: alarm_control_panel.house
          state: 
            - armed_away
            - armed_vacation
  action:
    - service: switch.turn_on
      continue_on_error: true
      entity_id:
        - switch.kitchen_lamp
        - switch.server_room_lamp
        - switch.office_lamps
        - switch.den_lamps
        - switch.shack_lamp
    - service: light.turn_on
      continue_on_error: true
      entity_id:
        - light.entry_lamp
        - light.house_leds
        - light.hall_lamp
        - light.den_window_leds
    - service: input_boolean.turn_on
      entity_id: 
        - input_boolean.timer_lights
        - input_boolean.timer_lights_trigger

- alias: Timer Lights On Main Evenings
  id: 623a17d8-ac58-4228-8e24-0881028a822e
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  action:
    - service: switch.turn_on
      continue_on_error: true
      entity_id:
        - switch.kitchen_lamp
        - switch.server_room_lamp
        - switch.office_lamps
        - switch.den_lamps
        - switch.shack_lamp
        - switch.guest_room_lamp
    - service: light.turn_on
      continue_on_error: true
      entity_id:
        - light.entry_lamp
        - light.house_leds
        - light.hall_lamp
        - light.den_window_leds
    - service: input_boolean.turn_on
      entity_id: 
        - input_boolean.timer_lights
        - input_boolean.timer_lights_trigger

- alias: Timer Lights On Main Weekend Holiday AM
  id: 266d66d7-59d2-4d05-92a8-5be98a3d603b
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      to: disarmed
    - platform: state
      entity_id: alarm_control_panel.house
      from: armed_night
      to: armed_home
  condition:
    - condition: and #Weekend or Holiday if up before sunrise
      conditions:
        - condition: sun
          before: sunrise
        - condition: or
          conditions:
            - condition: state
              entity_id: alarm_control_panel.house
              state: disarmed
            - condition: state
              entity_id: alarm_control_panel.house
              state: armed_home
        - condition: or
          conditions:
            - condition: state
              entity_id: binary_sensor.work_holiday
              state: "on"
            - condition: time
              weekday:
                - sat
                - sun
            - condition: state
              entity_id: input_boolean.work_alarm_enabled
              state: "off"
  action:
    - service: switch.turn_on
      continue_on_error: true
      entity_id:
        - switch.kitchen_lamp
        - switch.server_room_lamp
        - switch.office_lamps
        - switch.den_lamps
        - switch.shack_lamp
        - switch.guest_room_lamp
    - service: light.turn_on
      continue_on_error: true
      entity_id:
        - light.entry_lamp
        - light.house_leds
        - light.hall_lamp
        - light.den_window_leds
    - service: input_boolean.turn_on
      entity_id: 
        - input_boolean.timer_lights
        - input_boolean.timer_lights_trigger

- alias: Timer Lights Off Main Night Away
  id: 7b1b495b-7df2-4485-ac7e-826814a52022
  trigger:
    - platform: time
      at: "23:30:00"
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_away
        - condition: state
          entity_id: input_boolean.vacation_mode
          state: "off"
  action:
    - service: switch.turn_off
      continue_on_error: true
      entity_id:
        - switch.kitchen_lamp
        - switch.server_room_lamp
        - switch.office_lamps
        - switch.den_lamps
        - switch.shack_lamp
        - switch.guest_room_lamp
    - service: light.turn_off
      continue_on_error: true
      entity_id:
        - light.entry_lamp
        - light.house_leds
        - light.hall_lamp
        - light.den_window_leds
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.timer_lights
        - input_boolean.manual_timer_lights
        - input_boolean.timer_lights_trigger

- alias: Timer Lights Off Main Mornings
  id: 7bfd1c4d-1de6-4a4b-8243-9fd2da39fd9a
  trigger:
    - platform: sun
      event: sunrise
      offset: "+00:30:00"
  action:
    - service: switch.turn_off
      continue_on_error: true
      entity_id:
        - switch.kitchen_lamp
        - switch.server_room_lamp
        - switch.office_lamps
        - switch.den_lamps
        - switch.shack_lamp
        - switch.guest_room_lamp
    - service: light.turn_off
      continue_on_error: true
      entity_id:
        - light.entry_lamp
        - light.house_leds
        - light.hall_lamp
        - light.den_window_leds
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.timer_lights
        - input_boolean.manual_timer_lights
        - input_boolean.timer_lights_trigger

- alias: Timer Lights Off Main Night Mode
  id: aa6d3655-9af4-4b2c-a481-2ba631741cc0
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      from: disarmed
      to: armed_night
    - platform: state
      entity_id: alarm_control_panel.house
      from: armed_home
      to: armed_night
  action:
    - service: switch.turn_off
      continue_on_error: true
      entity_id:
        - switch.kitchen_lamp
        - switch.server_room_lamp
        - switch.office_lamps
        - switch.den_lamps
        - switch.shack_lamp
    - service: light.turn_off
      continue_on_error: true
      entity_id: 
        - light.entry_lamp     
        - light.kitchen_leds
        - light.denled1_light
        - light.guestbathled_light
        - light.den_window_leds
        - light.hall_lamp
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.timer_lights
        - input_boolean.timer_lights_trigger
        - input_boolean.manual_timer_lights

- alias: Timer Lights On Guest
  id: d830e8bf-54af-4ff1-a83d-f13c6c1a7e25
  trigger:
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_on_main_weekday_am
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.guest_mode
          state: "off"
        - condition: state
          entity_id: alarm_control_panel.house
          state: 
            - armed_away
            - armed_vacation
  action:
    - service: switch.turn_on
      entity_id: switch.guest_room_lamp

- alias: Timer Lights Off Guest
  id: a3275f91-7d5b-4adb-b456-945af53716ad
  trigger:
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_off_main_night_mode
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - service: switch.turn_off
      entity_id: switch.guest_room_lamp

- alias: Timer Lights On Master
  id: eb3b0cb6-84c8-4a0a-9450-533b87f71496
  trigger:
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_on_main_weekday_am
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_on_main_evenings
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_on_main_weekend_holiday_am
  condition:    
    - condition: state
      entity_id: alarm_control_panel.house
      state: 
        - disarmed
        - armed_away
        - armed_vacation
        - armed_home
  action:
    - service: switch.turn_on
      continue_on_error: true
      entity_id: switch.master_bedroom_lamps
    - service: input_boolean.turn_on
      entity_id: input_boolean.master_lamp_timer

- alias: Timer Lights Off Master
  id: 7b13c5a7-b0ce-42c4-a8ae-1eca4f620d56
  trigger:
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_off_main_night_away
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_off_main_mornings
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_off_main_night_mode
  condition:
    - condition: state
      entity_id: alarm_control_panel.house
      state: 
        - disarmed
        - armed_away
        - armed_vacation
        - armed_home
  action:
    - service: switch.turn_off
      continue_on_error: true
      entity_id: switch.master_bedroom_lamps
    - service: input_boolean.turn_off
      entity_id: input_boolean.master_lamp_timer

- alias: Timer Lights On Outside
  id: 6d6808cd-d3b4-4b63-a6eb-2f559bc57915
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.outside_timer_lights
    - service: switch.turn_on
      continue_on_error: true
      entity_id:
        - switch.outside_lights
        - switch.shed_outside_light
        - switch.flagpole
        - switch.back_landscape

- alias: Timer Lights Off Outside
  id: 72a166d5-5c49-49c3-b8ce-3c291d5a155a
  trigger:
    - platform: sun
      event: sunrise
      offset: "+00:30:00"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.outside_timer_lights
    - service: switch.turn_off
      continue_on_error: true
      entity_id:
        - switch.outside_lights
        - switch.shed_outside_light
        - switch.flagpole
        - switch.back_landscape

- alias: Master Suite Off if Sleeping
  id: f867c8e4-d417-4037-a481-688e441b0f15
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      from: arming
      to: armed_night
      for: "00:45:00"
    - platform: state
      entity_id: alarm_control_panel.house
      from: 
        - disarmed
        - armed_home
      to: armed_night
      for: "00:45:00"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: switch.master_bedroom_lamps
          state: "on"
        - condition: state
          entity_id: light.master_suite_leds
          state: "on"
  action:
    - service: light.turn_off
      continue_on_error: true
      entity_id: light.master_suite_leds
    - service: switch.turn_off
      continue_on_error: true
      entity_id:
        - switch.master_bedroom_lamps
        - switch.water_projector
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.master_lamp_timer
