- alias: Timer Lights On Main Weekday AM
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.master_work_alarm', 'timestamp') | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: or 
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: calendar.work_holidays
              state: 'off'
            - condition: state
              entity_id: input_boolean.work_alarm_enabled
              state: 'on'
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_away
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.kitchen_lamp
        - switch.server_room_lamp
        - switch.office_lamps
        - switch.den_lamps
        - switch.den_table_lamp
        - switch.shack_lamp
    - service: light.turn_on
      entity_id: light.entry_lamp
    - service: input_boolean.turn_on
      entity_id: input_boolean.timer_lights

- alias: Timer Lights On Main Evenings
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:30:00'   
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.kitchen_lamp
        - switch.server_room_lamp
        - switch.office_lamps
        - switch.den_lamps
        - switch.den_table_lamp
        - switch.shack_lamp
    - service: light.turn_on
      entity_id: light.entry_lamp
    - service: input_boolean.turn_on
      entity_id: input_boolean.timer_lights

- alias: Timer Lights On Main Weekend Holiday AM
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      to: disarmed
    - platform: state
      entity_id: alarm_control_panel.house
      from: armed_night
      to: armed_home    
  condition:
    - condition: and #Weekend or Holiday if up before sunrise
      conditions:
        - condition: sun
          before: sunrise
        - condition: or
          conditions:
            - condition: state
              entity_id: alarm_control_panel.house
              state: disarmed
            - condition: state
              entity_id: alarm_control_panel.house
              state: armed_home
        - condition: or
          conditions:
            - condition: state
              entity_id: calendar.work_holidays
              state: 'on'
            - condition: time
              weekday:
                - sat
                - sun
            - condition: state
              entity_id: input_boolean.work_alarm_enabled
              state: 'off'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.kitchen_lamp
        - switch.server_room_lamp
        - switch.office_lamps
        - switch.den_lamps
        - switch.den_table_lamp
        - switch.shack_lamp
    - service: light.turn_on
      entity_id: light.entry_lamp
    - service: input_boolean.turn_on
      entity_id: input_boolean.timer_lights

- alias: Timer Lights Off Main Night Away
  trigger:
    - platform: time
      at: '23:30:00'
  condition:
    - condition: state
      entity_id: alarm_control_panel.house
      state: armed_away
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.kitchen_lamp
        - switch.server_room_lamp
        - switch.office_lamps
        - switch.den_lamps
        - switch.den_table_lamp
        - switch.shack_lamp
    - service: light.turn_off
      entity_id: light.entry_lamp
    - service: input_boolean.turn_off
      entity_id: 
        - input_boolean.timer_lights
        - input_boolean.manual_timer_lights

- alias: Timer Lights Off Main Mornings
  trigger:
    - platform: sun
      event: sunrise
      offset: '+00:30:00'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.kitchen_lamp
        - switch.server_room_lamp
        - switch.office_lamps
        - switch.den_lamps
        - switch.den_table_lamp
        - switch.shack_lamp
    - service: light.turn_off
      entity_id: light.entry_lamp
    - service: input_boolean.turn_off
      entity_id: 
        - input_boolean.timer_lights
        - input_boolean.manual_timer_lights

- alias: Timer Lights Off Main Night Mode
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
  condition:
    - condition: state
      entity_id: alarm_control_panel.house
      state: armed_night
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.kitchen_lamp
        - switch.server_room_lamp
        - switch.office_lamps
        - switch.den_lamps
        - switch.den_table_lamp
        - switch.shack_lamp
    - service: light.turn_off
      entity_id: light.entry_lamp
    - service: input_boolean.turn_off
      entity_id: 
        - input_boolean.timer_lights
        - input_boolean.manual_timer_lights

- alias: Timer Lights On Guest
  trigger:
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_on_main_weekday_am
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_on_main_evenings
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_on_main_weekend_holiday_am
  condition:
    - condition: or
      conditions:
        - condition: sun
          after: sunset
          after_offset: "-00:30:00"
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_away
  action:
    - service: switch.turn_on
      entity_id: switch.guest_room_lamp

- alias: Timer Lights Off Guest
  trigger:
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_off_main_night_away
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_off_main_mornings
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_off_main_night_mode 
  condition:
    - condition: or
      conditions:
        - condition: sun
          after: sunrise
          after_offset: "+00:30:00"
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_away
  action:
    - service: switch.turn_off
      entity_id: switch.guest_room_lamp

- alias: Timer Lights On Master
  trigger:
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_on_main_weekday_am
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_on_main_evenings
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_on_main_weekend_holiday_am
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_away
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.master_bedroom_lamps
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.master_lamp_timer

- alias: Timer Lights Off Master
  trigger:
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_off_main_night_away
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_off_main_mornings
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_off_main_night_mode 
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_away
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
  action:
    - service: switch.turn_off
      entity_id: switch.master_bedroom_lamps
    - service: input_boolean.turn_off
      entity_id: input_boolean.master_lamp_timer

- alias: Timer Lights On Outside
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:30:00'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.outside_timer_lights
    - service: switch.turn_on
      entity_id: 
        - switch.outside_lights
        - switch.shed_outside_light

- alias: Timer Lights Off Outside
  trigger:
    - platform: sun
      event: sunrise
      offset: '+00:30:00'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.outside_timer_lights
    - service: switch.turn_off
      entity_id: 
        - switch.outside_lights
        - switch.shed_outside_light

- alias: Timer LEDs On House
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      to: disarmed
    - platform: state
      entity_id: alarm_control_panel.house
      to: armed_home
    - platform: state
      entity_id: input_boolean.timer_lights
      to: 'on'
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_on_main_weekday_am
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_on_main_evenings
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_on_main_wweekend_holiday_am
  condition:
    - condition: state
      entity_id: input_boolean.timer_lights
      state: 'on'
    - condition: state
      entity_id: light.house_leds_rgb
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
  action:
    - service: light.turn_on
      entity_id: 
        - light.house_leds_rgb
        - light.hall_lamp
  
- alias: Timer LEDs Off House Away
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      from: arming
      to: armed_away
  action:
    - service: light.turn_off
      entity_id: 
        - light.house_leds_rgb
        - light.hall_lamp

- alias: Timer LEDs Off House
  trigger:
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_off_main_night_away
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_off_main_mornings
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_off_main_night_mode 
  action:
    - service: light.turn_off
      entity_id: 
        - light.kitchen_leds_rgb
        - light.den_leds_rgb
        - light.guest_bathroom_led_rgb
        - light.den_window_leds_cct
        - light.hall_lamp

- alias: Timer LEDs Off Master
  trigger:
    - platform: state
      entity_id: input_boolean.timer_lights
      to: 'off'
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_off_main_night_away
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_off_main_mornings
    - platform: event
      event_type: automation_triggered
      event_data:
        entity_id: automation.timer_lights_off_main_night_mode
  condition:
    - condition: state
      entity_id: input_boolean.timer_lights
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
  action:
  - service: light.turn_off
    entity_id: light.master_suite_leds_rgb

- alias: Master Suite Off if Sleeping
  trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      from: arming
      to: armed_night
      for: '00:45:00'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: switch.master_bedroom_lamps
          state: 'on'
        - condition: state
          entity_id: light.master_suite_leds_rgb
          state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.master_suite_leds_rgb
    - service: switch.turn_off
      entity_id: 
        - switch.master_bedroom_lamps
        - switch.water_projector
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.master_lamp_timer