- alias: Alexa Unlock Truck
  trigger:
    - platform: state
      entity_id: input_boolean.unlock_truck
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
  action:
    - service: rest_command.unlock_truck
    - service: input_boolean.turn_off
      entity_id: input_boolean.unlock_truck

- alias: Alexa Lock Truck
  trigger:
    - platform: state
      entity_id: input_boolean.lock_truck
      to: "on"
  action:
    - service: rest_command.lock_truck
    - service: input_boolean.turn_off
      entity_id: input_boolean.lock_truck

- alias: Alexa Start Truck
  trigger:
    - platform: state
      entity_id: input_boolean.start_truck
      to: "on"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
  action:
    - service: rest_command.start_truck
    - service: input_boolean.turn_off
      entity_id: input_boolean.start_truck

- alias: Alexa Stop Truck
  trigger:
    - platform: state
      entity_id: input_boolean.stop_truck
      to: "on"
  action:
    - service: rest_command.stop_truck
    - service: input_boolean.turn_off
      entity_id: input_boolean.stop_truck

- alias: Truck Clear Trigger if State Disallowed
  trigger:
    - platform: state
      entity_id: input_boolean.start_truck
      to: "on"
    - platform: state
      entity_id: input_boolean.unlock_truck
      to: "on"
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: alarm_control_panel.house
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.house
          state: disarmed
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.start_truck
        - input_boolean.unlock_truck

- alias: Send Lock Notification When at Work
  trigger:
    - platform: state
      entity_id: person.shawn_mccoy
      to: "work"
  action:
    - service: notify.mobile_app_shawn_7t
      data:
        title: Lock Truck
        message: "You are at work.  Would you like to lock your truck?"
        data:
          ttl: 0
          priority: high
          actions:
            - action: "lock_truck" # The key you are sending for the event
              title: "Lock" # The button title

- alias: Lock Truck from Notification
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: lock_truck
  action:
    - service: rest_command.lock_truck

- alias: Send Unock or Start Notification When at Work
  trigger:
    - platform: time
      at: "15:50:00"
  condition:
    - condition: state
      entity_id: person.shawn_mccoy
      state: "work"
  action:
    - service: notify.mobile_app_shawn_7t
      data:
        title: Heading Home
        message: "It's about that time.  Would you like to start or unlock your truck?"
        data:
          ttl: 0
          priority: high
          actions:
            - action: "start_truck" # The key you are sending for the event
              title: "Start" # The button title
            - action: "unlock_truck" # The key you are sending for the event
              title: "Unlock" # The button title

- alias: Start Truck from Notification
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: start_truck
  action:
    - service: rest_command.start_truck
    - service: notify.mobile_app_shawn_7t
      data:
        title: Heading Home
        message: "The truck is running.  Would you like to unlock your truck?"
        data:
          ttl: 0
          priority: high
          actions:
            - action: "unlock_truck" # The key you are sending for the event
              title: "Unlock" # The button title

- alias: Unlock Truck from Notification
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: unlock_truck
  action:
    - service: rest_command.unlock_truck

- alias: Alexa Prompt to Start Truck When Cold
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (((state_attr('input_datetime.work_leave_time' , 'timestamp')) - (10 * 60))|timestamp_custom('%H:%M', false)) }}"
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.work_alarm_enabled
          state: "on"
        - condition: state
          entity_id: binary_sensor.work_holiday
          state: "off"
        - condition: state
          entity_id: light.kitchen_light
          state: "on"
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: numeric_state
          entity_id: sensor.acurite_outside_temperature
          below: 45
        - condition: or
          conditions:
            - condition: state
              entity_id: alarm_control_panel.house
              state: armed_home
            - condition: state
              entity_id: alarm_control_panel.house
              state: disarmed
  action:
    - service: script.activate_alexa_actionable_notification
      data_template:
        text: "The temperature is {{states('sensor.acurite_outside_temperature') | int }} degrees.  Would you like to start your truck?"
        event_id: "actionable_notification_start_truck"
        alexa_device: "media_player.alexa_den"
    - service: notify.mobile_app_shawn_7t
      data_template:
        title: Heading Home
        message: "The temperature is {{states('sensor.acurite_outside_temperature') | int }} degrees.  Would you like to start your truck?"
        data:
          ttl: 0
          priority: high
          tag: truck_start_cold
          actions:
            - action: "start_truck_cold" # The key you are sending for the event
              title: "Yes" # The button title
            - action: "no" # The key you are sending for the event
              title: "No" # The button title

- alias: Start Truck via Actionable Notificaiton
  trigger:
    - platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: actionable_notification_start_truck
        event_response: ResponseYes
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: start_truck_cold
  action:
    - service: rest_command.start_truck

- alias: Clear Truck Phone Notification if Alexa Responds
  trigger:
    - platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: actionable_notification_start_truck
        event_response: ResponseYes
    - platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: actionable_notification_start_truck
        event_response: ResponseNo
  action:
    - service: notify.mobile_app_shawn_7t
      data:
        ttl: 0
        priority: high
        message: clear_notification
        data:
          tag: truck_start_cold
