- alias: Voice Bedtime
  id: 504af65a-1574-4698-a637-136f514a96f2
  triggers:
    - trigger: conversation
      command:
        - "it's bedtime"
  action:
    - action: input_boolean.turn_on
      entity_id: input_boolean.bedtime_trigger
    - action: ai_task.generate_data
      data:
        task_name: "house shutdown comment"
        instructions: "In a whitty or funny way, tell me that you are preparing the house for bed.  This will be spoken using TTS so keep it relatively short (2 sentences or so)."
      response_variable: generated_text
    - set_conversation_response: "{{ generated_text.data }}"

- alias: Voice Good Night
  id: 18d8962a-549f-4ff4-9e94-16f75bf0ca34
  triggers:
    - trigger: conversation
      command:
        - "good night"
  action:
    - action: input_boolean.turn_on
      entity_id: input_boolean.goodnight_trigger
    - action: ai_task.generate_data
      data:
        task_name: "good night comment"
        instructions: "In a whitty or funny way, tell me good night.  This will be spoken using TTS so keep it relatively short."
      response_variable: generated_text
    - set_conversation_response: "{{ generated_text.data }}"

- alias: Voice Good Morning
  id: 98e64535-62d7-4571-b664-b93ca0f7c72b
  triggers:
    - trigger: conversation
      command:
        - "good morning"
  action:
    - action: input_boolean.turn_on
      entity_id: input_boolean.morning_trigger
    - action: ai_task.generate_data
      data:
        task_name: "good morning comment"
        instructions: |
          Based on the following conditions:
          - Outdoor temperature: {{ states('sensor.acurite_ws_temperature') }}  
          - Weather condition: {{ states('sensor.openweathermap_current_icon') }}
          - Current Rainfall: {{ states('sensor.rain_day') }}
          - Today's probablility of precipitation: {{ states('sensor.openweathermap_current_pop') }}
          - Today's predicted rainfall: {{ states('sensor.openweathermap_current_precip_forecast') }}
          - Today's high temperature: {{ states('sensor.openweathermap_current_maximum_temperature') }}
          - Today's low temperature: {{ states('sensor.openweathermap_current_minimum_temperature') }}
          In a whitty or funny way, tell me good morning.  It's likely that I have overslept and should 
          be not-so-kindly motivated to get going.   This will be read using text to speech so format 
          everything into sentences and don't make it too long (remember, I am still trying to wake up).  
          Include the current weather and daily forecast (with the same tone and humor as the rest of the response).  
          Units are in standard and rounding to whole numbers is best.  Please do not just list the current numbers in your response.  A paragraph or so is great.
      response_variable: generated_text
    - set_conversation_response: "{{ generated_text.data }}"

- alias: Voice Leaving Home
  id: 41feb6e2-e0ef-43e3-b509-861a4c95a15b
  triggers:
    - trigger: conversation
      command:
        - "I'm leaving"
  action:
    - action: input_boolean.turn_on
      entity_id: input_boolean.leaving_trigger
    - action: ai_task.generate_data
      data:
        task_name: "goodbye comment"
        instructions: "In a whitty or funny way, tell me goodbye.  This will be spoken using TTS so keep it relatively short."
      response_variable: generated_text
    - set_conversation_response: "{{ generated_text.data }}"

- alias: Voice Returning Home
  id: e8355012-d128-4969-bc00-abb78dc219f5
  triggers:
    - trigger: conversation
      command:
        - "I'm home"
  action:
    - action: input_boolean.turn_on
      entity_id: input_boolean.returning_trigger
    - action: ai_task.generate_data
      data:
        task_name: "hello comment"
        instructions: "In a whitty or funny way, welcome me back home.  This will be spoken using TTS so keep it relatively short."
      response_variable: generated_text
    - set_conversation_response: "{{ generated_text.data }}"