light:
  - platform: mqtt
    name: "House LEDs RGB"
    state_topic: "h801/all/ha/state"
    command_topic: "h801/all/command/set/rgb/power"
    brightness_state_topic: "h801/all/tele/current"
    brightness_command_topic: "h801/all/command/set/rgb/brightness"
    rgb_state_topic: "h801/all/tele/current"
    rgb_command_topic: "h801/all/command/set/rgb/color"
    brightness_value_template: "{{value_json['rgb_brightness']}}"
    rgb_value_template: "{{value_json['rgb_r']}},{{value_json['rgb_g']}},{{value_json['rgb_b']}}"
    qos: 0
    retain: false
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false

automation:
  - alias: house_gr report on
    id: 205bd136-0b4e-424e-8ddc-88f11c3f6102
    trigger:
      - platform: state
        entity_id: light.kitchen_led_1_rgb
        to: "on"
      - platform: state
        entity_id: light.kitchen_led_2_rgb
        to: "on"
      - platform: state
        entity_id: light.kitchen_led_3_rgb
        to: "on"
      - platform: state
        entity_id: light.kitchen_led_4_rgb
        to: "on"
      - platform: state
        entity_id: light.kitchen_led_5_rgb
        to: "on"
      - platform: state
        entity_id: light.kitchen_led_6_rgb
        to: "on"
      - platform: state
        entity_id: light.kitchen_led_7_rgb
        to: "on"
      - platform: state
        entity_id: light.kitchen_led_8_rgb
        to: "on"
      - platform: state
        entity_id: light.den_led_1_rgb
        to: "on"
      - platform: state
        entity_id: light.den_led_2_cct
        to: "on"
      - platform: state
        entity_id: light.den_led_3_cct
        to: "on"
      - platform: state
        entity_id: light.den_led_4_cct
        to: "on"
      - platform: state
        entity_id: light.guest_bathroom_led_rgb
        to: "on"
      - platform: state
        entity_id: light.master_bathroom_led_rgb
        to: "on"
      - platform: state
        entity_id: light.master_bedroom_led_1_rgb
        to: "on"
      - platform: state
        entity_id: light.master_bedroom_led_2_rgb
        to: "on"
    action:
      - service: mqtt.publish
        data:
          topic: h801/all/ha/state
          payload_template: "ON"
          retain: true

  - alias: house_gr report off
    id: 5d2a2f66-2f6a-4a79-9e0d-49a516127e68
    trigger:
      - platform: state
        entity_id: light.kitchen_led_1_rgb
        to: "off"
      - platform: state
        entity_id: light.kitchen_led_2_rgb
        to: "off"
      - platform: state
        entity_id: light.kitchen_led_3_rgb
        to: "off"
      - platform: state
        entity_id: light.kitchen_led_4_rgb
        to: "off"
      - platform: state
        entity_id: light.kitchen_led_5_rgb
        to: "off"
      - platform: state
        entity_id: light.kitchen_led_6_rgb
        to: "off"
      - platform: state
        entity_id: light.kitchen_led_7_rgb
        to: "off"
      - platform: state
        entity_id: light.kitchen_led_8_rgb
        to: "off"
      - platform: state
        entity_id: light.den_led_1_rgb
        to: "off"
      - platform: state
        entity_id: light.den_led_2_cct
        to: "off"
      - platform: state
        entity_id: light.den_led_3_cct
        to: "off"
      - platform: state
        entity_id: light.den_led_4_cct
        to: "off"
      - platform: state
        entity_id: light.guest_bathroom_led_rgb
        to: "off"
      - platform: state
        entity_id: light.master_bathroom_led_rgb
        to: "off"
      - platform: state
        entity_id: light.master_bedroom_led_1_rgb
        to: "off"
      - platform: state
        entity_id: light.master_bedroom_led_2_rgb
        to: "off"
    condition:
      - condition: state
        entity_id: light.kitchen_led_1_rgb
        state: "off"
      - condition: state
        entity_id: light.kitchen_led_2_rgb
        state: "off"
      - condition: state
        entity_id: light.kitchen_led_3_rgb
        state: "off"
      - condition: state
        entity_id: light.kitchen_led_4_rgb
        state: "off"
      - condition: state
        entity_id: light.kitchen_led_5_rgb
        state: "off"
      - condition: state
        entity_id: light.kitchen_led_6_rgb
        state: "off"
      - condition: state
        entity_id: light.kitchen_led_7_rgb
        state: "off"
      - condition: state
        entity_id: light.kitchen_led_8_rgb
        state: "off"
      - condition: state
        entity_id: light.den_led_1_rgb
        state: "off"
      - condition: state
        entity_id: light.den_led_2_cct
        state: "off"
      - condition: state
        entity_id: light.den_led_3_cct
        state: "off"
      - condition: state
        entity_id: light.den_led_4_cct
        state: "off"
      - condition: state
        entity_id: light.guest_bathroom_led_rgb
        state: "off"
      - condition: state
        entity_id: light.master_bathroom_led_rgb
        state: "off"
      - condition: state
        entity_id: light.master_bedroom_led_1_rgb
        state: "off"
      - condition: state
        entity_id: light.master_bedroom_led_2_rgb
        state: "off"
    action:
      - service: mqtt.publish
        data:
          topic: h801/all/ha/state
          payload_template: "OFF"
          retain: true
