light:
  - platform: mqtt
    name: "Den Window LEDs CCT"
    state_topic: "h801/d_windows/ha/state"
    command_topic: "h801/d_windows/command/set/rgb/power"
    brightness_state_topic: "h801/d_windows/tele/current"
    brightness_command_topic: "h801/d_windows/command/set/rgb/brightness"
    brightness_value_template: "{{value_json['rgb_brightness']}}"
    color_temp_command_topic: "h801/d_windows/command/set/w1/temperature"
    color_temp_state_topic: "h801/d_windows/tele/current"
    color_temp_value_template: "{{value_json['temperature']}}"
    qos: 0
    retain: false
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false

automation:
  - alias: den_window_gr report on
    id: 0dcaba68-e8ab-4dc0-9bc5-9dbf36701336
    trigger:
      - platform: state
        entity_id: light.den_led_2_cct
        to: "on"
      - platform: state
        entity_id: light.den_led_3_cct
        to: "on"
      - platform: state
        entity_id: light.den_led_4_cct
        to: "on"
    action:
      - service: mqtt.publish
        data:
          topic: h801/d_windows/ha/state
          payload_template: "ON"
          retain: true

  - alias: den_window_gr report off
    id: 0e4724a9-c2f2-4935-831f-7dbb7e0eca82
    trigger:
      - platform: state
        entity_id: light.den_led_2_cct
        to: "off"
      - platform: state
        entity_id: light.den_led_3_cct
        to: "off"
      - platform: state
        entity_id: light.den_led_4_cct
        to: "off"
    condition:
      - condition: state
        entity_id: light.den_led_2_cct
        state: "off"
      - condition: state
        entity_id: light.den_led_3_cct
        state: "off"
      - condition: state
        entity_id: light.den_led_4_cct
        state: "off"
    action:
      - service: mqtt.publish
        data:
          topic: h801/d_windows/ha/state
          payload_template: "OFF"
          retain: true
