light:
  - platform: mqtt
    name: "Den LED 3 CCT"
    state_topic: "h801/den_3/tele/current"
    command_topic: "h801/den_3/command/set/rgb/power"
    brightness_state_topic: "h801/den_3/tele/current"
    brightness_command_topic: "h801/den_3/command/set/rgb/brightness"
    color_temp_command_topic: "h801/den_3/command/set/w1/temperature"
    color_temp_state_topic: "h801/den_3/tele/current"
    color_temp_value_template: "{{value_json['temperature']}}"
    state_value_template: "{{value_json['rgb_power']}}"
    brightness_value_template: "{{value_json['rgb_brightness']}}"
    availability_topic: "h801/den_3/tele/LWT"
    qos: 0
    retain: false
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    payload_available: "Online"
    payload_not_available: "Offline"
    
sensor:
  #Driver Status Messages

  - platform: mqtt
    name: "Den LED 3 Version"
    state_topic: "h801/den_3/tele/status"
    value_template: "{{value_json['espVersion']}}"
    availability_topic: "h801/den_3/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Den LED 3 Uptime"
    state_topic: "h801/den_3/tele/status"
    value_template: "{{value_json['espUptime']}}"
    availability_topic: "h801/den_3/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Den LED 3 RSSI"
    state_topic: "h801/den_3/tele/status"
    value_template: "{{value_json['signalStrength']}}"
    availability_topic: "h801/den_3/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Den LED 3 IP"
    state_topic: "h801/den_3/tele/status"
    value_template: "{{value_json['bridgeIP']}}"
    availability_topic: "h801/den_3/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Den LED 3 Free Heap"
    state_topic: "h801/den_3/tele/status"
    value_template: "{{value_json['heapFree']}}"
    availability_topic: "h801/den_3/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Den LED 3 Heap Fragmentation"
    state_topic: "h801/den_3/tele/status"
    value_template: "{{value_json['heapFragmentation']}}"
    availability_topic: "h801/den_3/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    name: "Den LED 3 Core Version"
    state_topic: "h801/den_3/tele/status"
    value_template: "{{value_json['espCore']}}" 
    availability_topic: "h801/den_3/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
