mqtt:
  light:
    - name: "Den LEDs RGB"
      state_topic: "h801/den/ha/state"
      command_topic: "h801/den/command/set/rgb/power"
      brightness_state_topic: "h801/den/tele/current"
      brightness_command_topic: "h801/den/command/set/rgb/brightness"
      rgb_state_topic: "h801/den/tele/current"
      rgb_command_topic: "h801/den/command/set/rgb/color"
      brightness_value_template: "{{value_json['rgb_brightness']}}"
      rgb_value_template: "{{value_json['rgb_r']}},{{value_json['rgb_g']}},{{value_json['rgb_b']}}"
      qos: 0
      retain: false
      payload_on: "ON"
      payload_off: "OFF"
      optimistic: false

automation:
  - alias: den_gr report on
    id: 4ac32c82-7d4b-4ea7-9c09-77b4b58ce651
    trigger:
      - platform: state
        entity_id: light.den_led_1_rgb
        to: "on"
      - platform: state
        entity_id: light.den_led_2_cct
        to: "on"
      - platform: state
        entity_id: light.den_led_3_cct
        to: "on"
      - platform: state
        entity_id: light.den_led_4_cct
        to: "on"
    action:
      - service: mqtt.publish
        data:
          topic: h801/den/ha/state
          payload_template: "ON"
          retain: true

  - alias: den_gr report off
    id: d5d77452-d9e6-4262-a696-dfe2a9df428c
    trigger:
      - platform: state
        entity_id: light.den_led_1_rgb
        to: "off"
      - platform: state
        entity_id: light.den_led_2_cct
        to: "off"
      - platform: state
        entity_id: light.den_led_3_cct
        to: "off"
      - platform: state
        entity_id: light.den_led_4_cct
        to: "off"
    condition:
      - condition: state
        entity_id: light.den_led_1_rgb
        state: "off"
      - condition: state
        entity_id: light.den_led_2_cct
        state: "off"
      - condition: state
        entity_id: light.den_led_3_cct
        state: "off"
      - condition: state
        entity_id: light.den_led_4_cct
        state: "off"
    action:
      - service: mqtt.publish
        data:
          topic: h801/den/ha/state
          payload_template: "OFF"
          retain: true
