sensor:
  - platform: average
    name: Den Blinds Average Light Level
    entities:
      - sensor.left_den_blind_light_level
      - sensor.center_den_blind_light_level
      - sensor.right_den_blind_light_level

  - platform: average
    name: Kitchen Blinds Average Light Level
    entities:
      - sensor.left_kitchen_blind_light_level
      - sensor.east_kitchen_blind_light_level
      - sensor.right_kitchen_blind_light_level
      
  - platform: average
    name: Master Blinds Average Light Level
    entities:
      - sensor.left_master_blind_light_level
      - sensor.center_master_blind_light_level
      - sensor.right_master_blind_light_level
      - sensor.west_master_blind_light_level
      
  - platform: average
    name: Office Blinds Average Light Level
    entities:
      - sensor.left_office_blind_light_level
      - sensor.center_office_blind_light_level
      - sensor.right_office_blind_light_level
      
  - platform: average
    name: Shack Blinds Average Light Level
    entities:
      - sensor.left_shack_blind_light_level
      - sensor.center_shack_blind_light_level
      - sensor.right_shack_blind_light_level
      
  - platform: average
    name: House Blinds Average Light Level
    entities:
      - sensor.left_den_blind_light_level
      - sensor.center_den_blind_light_level
      - sensor.right_den_blind_light_level
      - sensor.left_kitchen_blind_light_level
      - sensor.east_kitchen_blind_light_level
      - sensor.right_kitchen_blind_light_level
      - sensor.left_master_blind_light_level
      - sensor.center_master_blind_light_level
      - sensor.right_master_blind_light_level
      - sensor.west_master_blind_light_level
      - sensor.left_office_blind_light_level
      - sensor.center_office_blind_light_level
      - sensor.right_office_blind_light_level
      - sensor.left_shack_blind_light_level
      - sensor.center_shack_blind_light_level
      - sensor.right_shack_blind_light_level
      - sensor.guest_blind_light_level
      - sensor.server_room_blind_light_level
