camera:
  - platform: mjpeg
    name: East Front
    still_image_url: !secret east_front_still
    mjpeg_url: !secret east_front_stream
    verify_ssl: false

  - platform: mjpeg
    name: West Front
    still_image_url: !secret west_front_still
    mjpeg_url: !secret west_front_stream
    verify_ssl: false

  - platform: mjpeg
    name: Front Porch
    still_image_url: !secret front_porch_still
    mjpeg_url: !secret front_porch_stream
    verify_ssl: false

  - platform: mjpeg
    name: Back Porch
    still_image_url: !secret back_porch_still
    mjpeg_url: !secret back_porch_stream
    verify_ssl: false

  - platform: mjpeg
    name: Back Yard
    still_image_url: !secret back_yard_still
    mjpeg_url: !secret back_yard_stream
    verify_ssl: false

  - platform: mjpeg
    name: East Side
    still_image_url: !secret east_side_still
    mjpeg_url: !secret east_side_stream
    verify_ssl: false

  - platform: mjpeg
    name: West Side
    still_image_url: !secret west_side_still
    mjpeg_url: !secret west_side_stream
    verify_ssl: false

  - platform: mjpeg
    name: Garage
    still_image_url: !secret garage_still
    mjpeg_url: !secret garage_stream
    verify_ssl: false

  - platform: mjpeg
    name: Den
    still_image_url: !secret den_still
    mjpeg_url: !secret den_stream
    verify_ssl: false

  - platform: mjpeg
    name: Kitchen
    still_image_url: !secret kitchen_still
    mjpeg_url: !secret kitchen_stream
    verify_ssl: false

  - platform: mjpeg
    name: Master
    still_image_url: !secret master_still
    mjpeg_url: !secret master_stream
    verify_ssl: false

  - platform: mjpeg
    name: Office
    still_image_url: !secret office_still
    mjpeg_url: !secret office_stream
    verify_ssl: false

  - platform: mjpeg
    name: Guest
    still_image_url: !secret guest_still
    mjpeg_url: !secret guest_stream
    verify_ssl: false

  - platform: mjpeg
    name: Hall
    still_image_url: !secret hall_still
    mjpeg_url: !secret hall_stream
    verify_ssl: false

  - platform: mqtt
    name: West Front Last Person
    topic: frigate/west_front/person/snapshot

  - platform: mqtt
    name: East Front Last Person
    topic: frigate/east_front/person/snapshot

  - platform: mqtt
    name: West Side Last Person
    topic: frigate/west_side/person/snapshot

  - platform: mqtt
    name: East Side Last Person
    topic: frigate/east_side/person/snapshot

  - platform: mqtt
    name: Back Yard Last Person
    topic: frigate/back_yard/person/snapshot

  - platform: mqtt
    name: Back Porch Last Person
    topic: frigate/back_porch/person/snapshot

  - platform: mqtt
    name: Front Porch Last Person
    topic: frigate/front_porch/person/snapshot

binary_sensor:
  - platform: mqtt
    name: West Front Person
    state_topic: frigate/west_front/person
    device_class: motion
    availability_topic: frigate/available

  - platform: mqtt
    name: East Front Person
    state_topic: frigate/east_front/person
    device_class: motion
    availability_topic: frigate/available

  - platform: mqtt
    name: West Side Person
    state_topic: frigate/west_side/person
    device_class: motion
    availability_topic: frigate/available

  - platform: mqtt
    name: East Side Person
    state_topic: frigate/east_side/person
    device_class: motion
    availability_topic: frigate/available

  - platform: mqtt
    name: Back Yard Person
    state_topic: frigate/back_yard/person
    device_class: motion
    availability_topic: frigate/available

  - platform: mqtt
    name: Back Porch Person
    state_topic: frigate/back_porch/person
    device_class: motion
    availability_topic: frigate/available

  - platform: mqtt
    name: Front Porch Person
    state_topic: frigate/front_porch/person
    device_class: motion
    availability_topic: frigate/available

sensor:
  - platform: rest
    name: Frigate Debug
    resource: !secret frigate_debug
    json_attributes:
      - west_front
      - east_front
      - west_side
      - east_side
      - back_yard
      - back_porch
      - front_porch
      - coral
    value_template: 'OK' 

  - platform: template
    sensors:
      frigate_west_front_detection_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["west_front"]["detection_fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_west_front_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["west_front"]["fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_west_front_skipped_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["west_front"]["skipped_fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_east_front_detection_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["east_front"]["detection_fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_east_front_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["east_front"]["fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_east_front_skipped_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["east_front"]["skipped_fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_west_side_detection_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["west_side"]["detection_fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_west_side_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["west_side"]["fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_west_side_skipped_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["west_side"]["skipped_fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_east_side_detection_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["east_side"]["detection_fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_east_side_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["east_side"]["fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_east_side_skipped_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["east_side"]["skipped_fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_back_yard_detection_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["back_yard"]["detection_fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_back_yard_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["back_yard"]["fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_back_yard_skipped_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["back_yard"]["skipped_fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_back_porch_detection_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["back_porch"]["detection_fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_back_porch_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["back_porch"]["fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_back_porch_skipped_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["back_porch"]["skipped_fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_front_porch_detection_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["front_porch"]["detection_fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_front_porch_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["front_porch"]["fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_front_porch_skipped_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["front_porch"]["skipped_fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_coral_fps: 
        value_template: '{{ states.sensor.frigate_debug.attributes["coral"]["fps"] }}'
        unit_of_measurement: 'FPS'
      frigate_coral_inference:
        value_template: '{{ states.sensor.frigate_debug.attributes["coral"]["inference_speed"] }}' 
        unit_of_measurement: 'ms'   
      frigate_coral_queue_length:
        value_template: '{{ states.sensor.frigate_debug.attributes["coral"]["detection_queue"] }}' 
        unit_of_measurement: 'frames'       

input_boolean:

  frigate_enabled:
    name: Enable Frigate
    icon: mdi:cctv

input_number:
  frigate_disable_time:
    name: Frigate Disable Time
    min: 1
    max: 24
    step: 1
    icon: mdi:camera-timer
    unit_of_measurement: h

timer:
  frigate_disable:
    name: Frigate Auto-restart Timer
    icon: mdi:timer
    