mqtt:
  camera:
    - name: West Front Last Person
      topic: frigate/west_front/person/snapshot

    - name: East Front Last Person
      topic: frigate/east_front/person/snapshot

    - name: West Side Last Person
      topic: frigate/west_side/person/snapshot

    - name: East Side Last Person
      topic: frigate/east_side/person/snapshot

    - name: Back Yard Last Person
      topic: frigate/back_yard/person/snapshot

    - name: Back Porch Last Person
      topic: frigate/back_porch/person/snapshot

    - name: Front Porch Last Person
      topic: frigate/front_porch/person/snapshot

  binary_sensor:
    - name: West Front Person
      state_topic: frigate/west_front/person
      device_class: motion
      availability_topic: frigate/available

    - name: East Front Person
      state_topic: frigate/east_front/person
      device_class: motion
      availability_topic: frigate/available

    - name: West Side Person
      state_topic: frigate/west_side/person
      device_class: motion
      availability_topic: frigate/available

    - name: East Side Person
      state_topic: frigate/east_side/person
      device_class: motion
      availability_topic: frigate/available

    - name: Back Yard Person
      state_topic: frigate/back_yard/person
      device_class: motion
      availability_topic: frigate/available

    - name: Back Porch Person
      state_topic: frigate/back_porch/person
      device_class: motion
      availability_topic: frigate/available

    - name: Front Porch Person
      state_topic: frigate/front_porch/person
      device_class: motion
      availability_topic: frigate/available

sensor:
  - platform: rest
    name: Frigate Debug
    resource: !secret frigate_debug
    json_attributes:
      - west_front
      - east_front
      - west_side
      - east_side
      - back_yard
      - back_porch
      - front_porch
      - coral
    value_template: "OK"

  - platform: template
    sensors:
      frigate_west_front_detection_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["west_front"]["detection_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_west_front_process_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["west_front"]["process_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_west_front_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["west_front"]["camera_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_west_front_skipped_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["west_front"]["skipped_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_east_front_detection_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["east_front"]["detection_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_east_front_process_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["east_front"]["process_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_east_front_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["east_front"]["camera_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_east_front_skipped_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["east_front"]["skipped_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_west_side_detection_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["west_side"]["detection_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_west_side_process_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["west_side"]["process_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_west_side_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["west_side"]["camera_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_west_side_skipped_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["west_side"]["skipped_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_east_side_detection_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["east_side"]["detection_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_east_side_process_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["east_side"]["process_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_east_side_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["east_side"]["camera_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_east_side_skipped_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["east_side"]["skipped_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_back_yard_detection_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["back_yard"]["detection_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_back_yard_process_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["back_yard"]["process_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_back_yard_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["back_yard"]["camera_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_back_yard_skipped_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["back_yard"]["skipped_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_back_porch_detection_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["back_porch"]["detection_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_back_porch_process_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["back_porch"]["process_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_back_porch_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["back_porch"]["camera_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_back_porch_skipped_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["back_porch"]["skipped_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_front_porch_detection_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["front_porch"]["detection_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_front_porch_process_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["front_porch"]["process_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_front_porch_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["front_porch"]["camera_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_front_porch_skipped_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["front_porch"]["skipped_fps"] }}'
        unit_of_measurement: "FPS"
      frigate_coral_fps:
        value_template: '{{ states.sensor.frigate_debug.attributes["coral"]["fps"] }}'
        unit_of_measurement: "FPS"
      frigate_coral_inference:
        value_template: '{{ states.sensor.frigate_debug.attributes["coral"]["inference_speed"] }}'
        unit_of_measurement: "ms"
      frigate_processing_frame:
        value_template: '{{ (states.sensor.frigate_debug.attributes["west_front"]["frame_info"]["read"] + states.sensor.frigate_debug.attributes["east_front"]["frame_info"]["read"] + states.sensor.frigate_debug.attributes["front_porch"]["frame_info"]["read"] + states.sensor.frigate_debug.attributes["east_side"]["frame_info"]["read"] + states.sensor.frigate_debug.attributes["west_side"]["frame_info"]["read"] + states.sensor.frigate_debug.attributes["back_yard"]["frame_info"]["read"] + states.sensor.frigate_debug.attributes["back_porch"]["frame_info"]["read"]) / 7}}'
      frigate_status:
        friendly_name: Frigate Status
        value_template: >-
          {% if is_state('input_boolean.frigate_enabled', 'on') and is_state('input_boolean.frigate_enabled_front', 'on') and is_state('input_boolean.frigate_enabled_back', 'on') -%}
            All Cameras Enabled
          {% elif  is_state('input_boolean.frigate_enabled', 'on') and is_state('input_boolean.frigate_enabled_front', 'off') and is_state('input_boolean.frigate_enabled_back', 'on') -%}
            Front Cameras Disabled
          {% elif  is_state('input_boolean.frigate_enabled', 'on') and is_state('input_boolean.frigate_enabled_front', 'on') and is_state('input_boolean.frigate_enabled_back', 'off') -%}
            Back Cameras Disabled
          {% elif  is_state('input_boolean.frigate_enabled', 'on') and is_state('input_boolean.frigate_enabled_front', 'off') and is_state('input_boolean.frigate_enabled_back', 'off') -%}
            All Cameras Disabled
          {% elif  is_state('input_boolean.frigate_enabled', 'off') -%}
            All Cameras Disabled
          {% else -%}
            Error
          {% endif -%}

input_boolean:
  frigate_enabled:
    name: Enable Frigate
    icon: mdi:cctv

  frigate_enabled_front:
    name: Frigate Enabled Front
    icon: mdi:cctv

  frigate_enabled_back:
    name: Frigate Enabled Back
    icon: mdi:cctv

input_number:
  frigate_disable_time:
    name: Frigate Disable Time
    min: 1
    max: 24
    step: 1
    icon: mdi:camera-timer
    unit_of_measurement: h

timer:
  frigate_disable:
    name: Frigate Auto-restart Timer
    icon: mdi:timer-outline

shell_command:
  clear_temp_images: bash /config/bin/clean_up_temp_images.sh
