mqtt:
  sensor:
    - state_topic: "christmas/falcon/player/Master/playlist/name/status"
      unique_id: 91398798-9cb7-4b2e-949e-fb3423c32775
      name: "FPP Master Playlist"

    - state_topic: "christmas/falcon/player/Master/playlist/section/status"
      unique_id: a4aea19f-3521-4d64-b7e8-515e7c7f04dc
      name: "FPP Master Playlist Section"

    - state_topic: "christmas/falcon/player/Master/playlist/sequence/status"
      unique_id: 519c61f9-5d3d-4531-a835-d7e55f0b59ee
      name: "FPP Master Sequence"

    - state_topic: "christmas/falcon/player/Master/version"
      unique_id: b73f5214-b5d1-42af-9503-9de0f2ad3673
      name: "FPP Master Version"

    - state_topic: "christmas/falcon/player/Master/state/status"
      unique_id: b4bee69e-3dc9-4165-aa5d-0c6d36fe2be1
      name: "FPP Master Status"
      
switch:
  - platform: template
    switches:
      indoor_christmas:
        unique_id: e330407a-7352-43da-9316-338863d7870a
        friendly_name: "Indoor Christmas Decor"
        value_template: "{{ is_state('switch.dining_room_decor', 'on') or is_state('switch.entry_hall_decor', 'on') or is_state('switch.christmas_village', 'on') or is_state('switch.snowman', 'on') or is_state('switch.christmas_tree', 'on') or is_state('switch.left_christmas_tree', 'on') or is_state('switch.kitchen_christmas_tree', 'on') or is_state('switch.christmas_garland', 'on')  or is_state('switch.master_bedroom_decor', 'on') or is_state('switch.kitchen_garland', 'on') or is_state('switch.hall_decor', 'on') or is_state('switch.office_decor', 'on') }}"
        turn_on:
          service: mqtt.publish
          data:
            topic: cmnd/decorations/power
            payload: "ON"
        turn_off:
          service: mqtt.publish
          data:
            topic: cmnd/decorations/power
            payload: "OFF"

input_boolean:
  christmas_show:
    name: Christmas Show
    icon: mdi:pine-tree

  amplifier_shutdown:
    name: Allow Amplifier Shutdown
    icon: mdi:speaker-off

  # donation_box:
  #   name: Donation Box
  #   icon: mdi:door-closed

input_datetime:
  amplifier_shutdown_time:
    name: Christmas Amplifier Shutdown Time
    has_date: false
    has_time: true

automation:
  - alias: Indoor Christmas On When Home
    id: cec759b6-0e2e-4d73-ada2-7b1c3ef78670
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        to: disarmed
      - platform: state
        entity_id: alarm_control_panel.house
        to: armed_home
    action:
      - service: switch.turn_on
        entity_id: switch.indoor_christmas

  - alias: Indoor Christmas Off When Away or Asleep
    id: 916d3d2c-5dbc-4e6e-9c2c-2a46082f1f3c
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        from: arming
        to: armed_away
      - platform: state
        entity_id: alarm_control_panel.house
        from: 
          - disarmed
          - armed_home
        to: armed_away
        for: "00:01:00"
      - platform: state
        entity_id: alarm_control_panel.house
        to: armed_night
    action:
      - service: switch.turn_off
        entity_id: switch.indoor_christmas
      - service: mqtt.publish
        data:
          topic: ir/all/cmnd/irsend
          payload: '{"Protocol":"NEC","Bits":32,"Data":"0x1FE58A7"}'

  - alias: MQTT Christmas Show On
    id: e2e0b58e-27e0-4e1a-857e-cbd85d015b86
    trigger:
      - platform: mqtt
        topic: christmas/show
        payload: "ON"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.christmas_show

  - alias: MQTT Christmas Show Off
    id: e9c2cf8b-1ec9-494e-bbc7-bb896f27cfd9
    trigger:
      - platform: mqtt
        topic: christmas/show
        payload: "OFF"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.christmas_show

  - alias: House Off For Christmas Show
    id: dc3848ec-9d7a-4f80-8c65-3cb926315859
    trigger:
      - platform: state
        entity_id: input_boolean.christmas_show
        to: "on"
    action:
      - service: switch.turn_off
        entity_id:
          - switch.outside_lights
          - switch.shed_outside_light
          - switch.office_lamps
          - group.landscape_lights
      - service: cover.close_cover
        entity_id: cover.office_blinds
      - service: input_boolean.turn_off
        entity_id: input_boolean.frigate_enabled_front

  - alias: House On After Christmas Show
    id: 13cff086-4ed0-45a9-bdb9-79c77cca00a3
    trigger:
      - platform: state
        entity_id: input_boolean.christmas_show
        to: "off"
    action:
      - service: switch.turn_on
        entity_id:
          - switch.outside_lights
          - switch.shed_outside_light
          - group.landscape_lights
      - service: input_boolean.turn_on
        entity_id: input_boolean.frigate_enabled_front

  # - alias: Donation Box Opened
  #   id: f2226ed0-ef53-48b5-a2f4-5baed7f5668c
  #   trigger:
  #     - platform: state
  #       entity_id: sensor.elk_donation_box
  #       to: Violated
  #   action:
  #     - service: mqtt.publish
  #       data:
  #         topic: parrot/command/set/play
  #         payload: 3,4
  #     - service: notify.mobile_app_shawn_7t
  #       data:
  #         message: The donation box has been opened.
  #         title: Donation Box
  #         data:
  #           ttl: 0
  #           priority: high
  #     - service: input_boolean.turn_on
  #       entity_id: input_boolean.donation_box

  - alias: Candles On at Dark When Home
    id: 43d4c5d9-071d-4604-9297-715e0251f132
    trigger:
      - platform: sun
        event: sunset
        offset: "00:30:00"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.house
            state: armed_home
          - condition: state
            entity_id: alarm_control_panel.house
            state: disarmed
    action:
      - service: mqtt.publish
        data:
          topic: ir/all/cmnd/irsend
          payload: '{"Protocol":"NEC","Bits":32,"Data":"0x1FE48B7"}'

  - alias: Candles On at When Returning After Dark
    id: 3f6ccd03-0d72-4e6c-bed7-0d32f338e7fb
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        from: pending
        to: disarmed
    condition:
      - condition: sun
        after: sunset
        after_offset: "00:30:00"
    action:
      - service: mqtt.publish
        data:
          topic: ir/all/cmnd/irsend
          payload: '{"Protocol":"NEC","Bits":32,"Data":"0x1FE48B7"}'

  - alias: Arm Christmas Amplifier Shutdown
    id: 322d4e3b-2c8e-421c-b819-d11c1c5e6ef7
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (state_attr('input_datetime.amplifier_shutdown_time', 'timestamp') | timestamp_custom('%H:%M', False, none)) }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.amplifier_shutdown

  - alias: Christmas Amplifier Shutdown
    id: 0d150ed2-030d-4348-8032-ad58f481fb50
    trigger:
      - platform: state
        entity_id: sensor.fpp_master_sequence
    condition:
      - condition: state
        entity_id: input_boolean.amplifier_shutdown
        state: "on"
    action:
      - service: switch.turn_off
        entity_id: switch.christmas_amplifier
      - service: input_boolean.turn_off
        entity_id: input_boolean.amplifier_shutdown