input_boolean:
  clock_bells_enabled:
    name: Enable Clock Bells
    icon: mdi:bell

  clock_bells_quarter_chime:
    name: Quarter Chimes
    icon: mdi:music-note

  clock_bells_hour_chime:
    name: Hourly Chimes
    icon: mdi:music-note

automation:
  - alias: Clock 15 Minute Chime
    id: 157c3888-081f-455e-96f4-e1cfafa58baa
    trigger:
      - platform: time_pattern
        minutes: 15
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.house
            state: armed_home
          - condition: state
            entity_id: alarm_control_panel.house
            state: disarmed
      - condition: state
        entity_id: input_boolean.clock_bells_enabled
        state: "on"
      - condition: state
        entity_id: input_boolean.clock_bells_quarter_chime
        state: "on"
      - condition: state
        entity_id: sensor.den_harmony_activity
        state: "PowerOff"
    action:
      - service: mqtt.publish
        data:
          topic: parrot/command/set/play
          payload: 5,1

  - alias: Clock 30 Minute Chime
    id: 3be468e4-de76-4f5c-b39b-aa959b1ebcd7
    trigger:
      - platform: time_pattern
        minutes: 30
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.house
            state: armed_home
          - condition: state
            entity_id: alarm_control_panel.house
            state: disarmed
      - condition: state
        entity_id: input_boolean.clock_bells_enabled
        state: "on"
      - condition: state
        entity_id: input_boolean.clock_bells_quarter_chime
        state: "on"
      - condition: state
        entity_id: sensor.den_harmony_activity
        state: "PowerOff"
    action:
      - service: mqtt.publish
        data:
          topic: parrot/command/set/play
          payload: 5,2

  - alias: Clock 45 Minute Chime
    id: 745ae3a8-f0e5-4790-ba0b-c02901bc13d9
    trigger:
      - platform: time_pattern
        minutes: 45
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.house
            state: armed_home
          - condition: state
            entity_id: alarm_control_panel.house
            state: disarmed
      - condition: state
        entity_id: input_boolean.clock_bells_enabled
        state: "on"
      - condition: state
        entity_id: input_boolean.clock_bells_quarter_chime
        state: "on"
      - condition: state
        entity_id: sensor.den_harmony_activity
        state: "PowerOff"
    action:
      - service: mqtt.publish
        data:
          topic: parrot/command/set/play
          payload: 5,3

  - alias: Clock Hourly Chime
    id: 08d39500-83f1-4f29-9faa-8ae57fef381a
    trigger:
      - platform: time_pattern
        minutes: "0"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.house
            state: armed_home
          - condition: state
            entity_id: alarm_control_panel.house
            state: disarmed
      - condition: state
        entity_id: input_boolean.clock_bells_enabled
        state: "on"
    action:
      - service: mqtt.publish
        data_template:
          topic: parrot/command/set/play
          payload: >
            {% if now().hour == 0 or now().hour == 12 -%}
              {% if is_state('input_boolean.clock_bells_hour_chime','on') -%}
                5,15
              {% else -%}
                5,27
              {% endif -%}  
            {% elif now().hour == 1 or now().hour == 13 -%}
              {% if is_state('input_boolean.clock_bells_hour_chime','on') -%}
                5,4
              {% else -%}
                5,16
              {% endif -%}   
            {% elif now().hour == 2 or now().hour == 14 -%}
              {% if is_state('input_boolean.clock_bells_hour_chime','on') -%}
                5,5
              {% else -%}
                5,17
              {% endif -%} 
            {% elif now().hour == 3 or now().hour == 15 -%}
              {% if is_state('input_boolean.clock_bells_hour_chime','on') -%}
                5,6
              {% else -%}
                5,18
              {% endif -%} 
            {% elif now().hour == 4 or now().hour == 16 -%}
              {% if is_state('input_boolean.clock_bells_hour_chime','on') -%}
                5,7
              {% else -%}
                5,19
              {% endif -%} 
            {% elif now().hour == 5 or now().hour == 17 -%}
              {% if is_state('input_boolean.clock_bells_hour_chime','on') -%}
                5,8
              {% else -%}
                5,20
              {% endif -%} 
            {% elif now().hour == 6 or now().hour == 18 -%}
              {% if is_state('input_boolean.clock_bells_hour_chime','on') -%}
                5,9
              {% else -%}
                5,21
              {% endif -%}
            {% elif now().hour == 7 or now().hour == 19 -%}
              {% if is_state('input_boolean.clock_bells_hour_chime','on') -%}
                5,10
              {% else -%}
                5,22
              {% endif -%}
            {% elif now().hour == 8 or now().hour == 20 -%}
              {% if is_state('input_boolean.clock_bells_hour_chime','on') -%}
                5,11
              {% else -%}
                5,23
              {% endif -%}
            {% elif now().hour == 9 or now().hour == 21 -%}
              {% if is_state('input_boolean.clock_bells_hour_chime','on') -%}
                5,12
              {% else -%}
                5,24
              {% endif -%}
            {% elif now().hour == 10 or now().hour == 22 -%}
              {% if is_state('input_boolean.clock_bells_hour_chime','on') -%}
                5,13
              {% else -%}
                5,25
              {% endif -%}
            {% elif now().hour == 11 or now().hour == 23 -%}
              {% if is_state('input_boolean.clock_bells_hour_chime','on') -%}
                5,14
              {% else -%}
                5,26
              {% endif -%}
            {% endif -%}
