sensor:
  - platform: template
    sensors:
      den_avr_url:
        unique_id: 49d3be12-2784-46ed-b844-b4080dda11b3
        value_template: !secret den_avr_url

rest_command:
  den_avr_25:
    url: "{{ states('sensor.den_avr_url') }}111VL"
    method: get

  den_avr_33:
    url: "{{ states('sensor.den_avr_url') }}095VL"
    method: get

  den_avr_40:
    url: "{{ states('sensor.den_avr_url') }}081VL"
    method: get

command_line:
  - switch:
      name: Den TV
      unique_id: 1cea3280-de25-46a2-a4d7-702c73cabcd2
      command_on: echo -n -e "\x08\x22\x00\x00\x00\x02\xD4" | nc 10.10.10.44 100
      command_off: echo -n -e "\x08\x22\x00\x00\x00\x01\xD5" | nc 10.10.10.44 100

script:
  den_avr_mute:
    mode: parallel
    sequence:
      - service: media_player.volume_mute
        target:
          entity_id: media_player.den_avr
        data:
          is_volume_muted: "{{ not state_attr('media_player.den_avr' , 'is_volume_muted') }}"
  
  den_kodi_up:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Up
  
  den_kodi_down:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Down
  
  den_kodi_left:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Left
  
  den_kodi_right:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Right
  
  den_kodi_select:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Select
  
  den_kodi_home:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Home
  
  den_kodi_back:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Back
  
  den_kodi_context:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: contextmenu
  
  den_kodi_osd:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: osd
  
  den_kodi_codec:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ShowCodec
  
  den_kodi_top:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: firstpage
  
  den_kodi_bottom:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: lastpage
  
  den_kodi_step_forward:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: stepforward
  
  den_kodi_step_back:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: stepback
  
  den_kodi_info:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: info
  
  den_kodi_tv_shows:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: GUI.ActivateWindow
          window: videos
          parameters:
            - TvshowTitles
  
  den_kodi_tv_movies:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: GUI.ActivateWindow
          window: videos
          parameters:
            - MovieTitles
  
  den_kodi_pvr:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: GUI.ActivateWindow
          window: pvr
          parameters:
            - TVChannels

  spotify_select_christian:
    mode: parallel
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.spotify_playlist
          option: "Top Christian Contemporary"
      - service: script.spotify_change_playlist

  spotify_select_country:
    mode: parallel
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.spotify_playlist
          option: "Hot Country"
      - service: script.spotify_change_playlist

  spotify_select_scores:
    mode: parallel
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.spotify_playlist
          option: "Epic Film Scores for Studying"
      - service: script.spotify_change_playlist

  spotify_select_christmas:
    mode: parallel
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.spotify_playlist
          option: "Christmas Hits"
      - service: script.spotify_change_playlist

  den_avr_activity_vol_kodi:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_25

  den_avr_activity_vol_roku:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_25

  den_avr_activity_vol_ps3:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_33

  den_avr_activity_vol_cast:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_40

  den_avr_activity_vol_wii:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_40

  den_avr_activity_vol_apple:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_40

  den_avr_activity_vol_nuvo:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_40
  
  den_roku_back:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: back
  
  den_roku_home:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: home
  
  den_roku_up:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: up
  
  den_roku_down:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: down
  
  den_roku_left:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: left
  
  den_roku_right:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: right
  
  den_roku_replay:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: replay
  
  den_roku_info:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: info
  
  den_roku_reverse:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: reverse
  
  den_roku_forward:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: forward
  
  den_roku_play:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: play