sensor:
  - platform: template
    sensors:
      den_avr_url:
        unique_id: 49d3be12-2784-46ed-b844-b4080dda11b3
        value_template: !secret den_avr_url

rest_command:
  den_avr_25:
    url: "{{ states('sensor.den_avr_url') }}111VL"
    method: get

  den_avr_33:
    url: "{{ states('sensor.den_avr_url') }}095VL"
    method: get

  den_avr_40:
    url: "{{ states('sensor.den_avr_url') }}081VL"
    method: get

switch:
  - platform: command_line
    switches:
      den_tv:
        name: Den TV
        unique_id: 1cea3280-de25-46a2-a4d7-702c73cabcd2
        command_on: echo -n -e "\x08\x22\x00\x00\x00\x02\xD4" | nc 10.10.10.44 22
        command_off: echo -n -e "\x08\x22\x00\x00\x00\x01\xD5" | nc 10.10.10.44 22

script:
  den_avr_mute:
    mode: parallel
    sequence:
      - service: media_player.volume_mute
        target:
          entity_id: media_player.den_avr
        data:
          is_volume_muted: "{{ not state_attr(media_player , 'is_volume_muted') }}"
  
  den_kodi_up:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Up
  
  den_kodi_down:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Down
  
  den_kodi_left:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Left
  
  den_kodi_right:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Right
  
  den_kodi_select:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Select
  
  den_kodi_home:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Home
  
  den_kodi_back:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Back
  
  den_kodi_context:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: contextmenu
  
  den_kodi_osd:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: osd
  
  den_kodi_codec:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ShowCodec
  
  den_kodi_top:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: firstpage
  
  den_kodi_bottom:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: lastpage
  
  den_kodi_step_forward:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: stepforward
  
  den_kodi_step_back:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: stepback
  
  den_kodi_tv_shows:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: GUI.ActivateWindow
          window: videos
          parameters:
            - TvshowTitles
  
  den_kodi_pvr:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: GUI.ActivateWindow
          window: pvr
          parameters:
            - TVChannels
