sensor:
  - platform: template
    sensors:
      den_avr_url:
        unique_id: 49d3be12-2784-46ed-b844-b4080dda11b3
        value_template: !secret den_avr_url

rest_command:
  den_avr_25:
    url: "{{ states('sensor.den_avr_url') }}111VL"
    method: get

  den_avr_33:
    url: "{{ states('sensor.den_avr_url') }}095VL"
    method: get

  den_avr_40:
    url: "{{ states('sensor.den_avr_url') }}081VL"
    method: get

  den_avr_on:
    url: "{{ states('sensor.den_avr_url') }}PO"
    method: get

  den_avr_off:
    url: "{{ states('sensor.den_avr_url') }}PF"
    method: get

  den_avr_vol_up:
    url: "{{ states('sensor.den_avr_url') }}VU"
    method: get

  den_avr_vol_dn:
    url: "{{ states('sensor.den_avr_url') }}VD"
    method: get

  den_avr_src_ps3:
    url: "{{ states('sensor.den_avr_url') }}25FN"
    method: get

  den_avr_src_wii:
    url: "{{ states('sensor.den_avr_url') }}11FN"
    method: get

  den_avr_src_apple:
    url: "{{ states('sensor.den_avr_url') }}19FN"
    method: get

  den_avr_src_roku:
    url: "{{ states('sensor.den_avr_url') }}20FN"
    method: get

  den_avr_src_cast:
    url: "{{ states('sensor.den_avr_url') }}21FN"
    method: get

  den_avr_src_kodi:
    url: "{{ states('sensor.den_avr_url') }}22FN"
    method: get

  den_avr_src_nuvo:
    url: "{{ states('sensor.den_avr_url') }}04FN"
    method: get

  den_avr_mute:
    url: "{{ states('sensor.den_avr_url') }}MO"
    method: get

command_line:
  - switch:
      name: Den TV
      unique_id: 1cea3280-de25-46a2-a4d7-702c73cabcd2
      command_on: echo -n -e "\x08\x22\x00\x00\x00\x02\xD4" | nc 10.10.10.44 100
      command_off: echo -n -e "\x08\x22\x00\x00\x00\x01\xD5" | nc 10.10.10.44 100

script:
  den_avr_mute:
    mode: parallel
    sequence:
      - service: media_player.volume_mute
        target:
          entity_id: media_player.den_avr
        data:
          is_volume_muted: "{{ not state_attr('media_player.den_avr' , 'is_volume_muted') }}"
  
  den_kodi_up:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Up
  
  den_kodi_down:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Down
  
  den_kodi_left:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Left
  
  den_kodi_right:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Right
  
  den_kodi_select:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Select
  
  den_kodi_home:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Home
  
  den_kodi_back:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.Back
  
  den_kodi_context:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: contextmenu
  
  den_kodi_osd:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: osd
  
  den_kodi_codec:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ShowCodec
  
  den_kodi_top:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: firstpage
  
  den_kodi_bottom:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: lastpage
  
  den_kodi_step_forward:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: stepforward
  
  den_kodi_step_back:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: stepback
  
  den_kodi_info:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: Input.ExecuteAction
          action: info
  
  den_kodi_tv_shows:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: GUI.ActivateWindow
          window: videos
          parameters:
            - TvshowTitles
  
  den_kodi_tv_movies:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: GUI.ActivateWindow
          window: videos
          parameters:
            - MovieTitles
  
  den_kodi_pvr:
    mode: parallel
    sequence:
      - service: kodi.call_method
        target:
          entity_id: media_player.den_kodi
        data:
          method: GUI.ActivateWindow
          window: pvr
          parameters:
            - TVChannels

  mass_select_christian:
    mode: parallel
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.mass_playlist
          option: "Top Christian Contemporary"
      - service: script.mass_change_playlist

  mass_select_country:
    mode: parallel
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.mass_playlist
          option: "Hot Country"
      - service: script.mass_change_playlist

  mass_select_scores:
    mode: parallel
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.mass_playlist
          option: "Epic Film Scores for Studying"
      - service: script.mass_change_playlist

  mass_select_christmas:
    mode: parallel
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.mass_playlist
          option: "Christmas Hits"
      - service: script.mass_change_playlist

  den_avr_activity_vol_kodi:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_25

  den_avr_activity_vol_roku:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_25

  den_avr_activity_vol_ps3:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_33

  den_avr_activity_vol_cast:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_40

  den_avr_activity_vol_wii:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_40

  den_avr_activity_vol_apple:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_40

  den_avr_activity_vol_nuvo:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_40

  den_avr_on:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_on

  den_avr_off:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_off

  den_avr_vol_up:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_vol_up

  den_avr_vol_dn:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_vol_dn

  den_avr_src_ps3:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_src_ps3

  den_avr_src_wii:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_src_wii

  den_avr_src_apple:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_src_apple

  den_avr_src_roku:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_src_roku

  den_avr_src_cast:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_src_cast

  den_avr_src_kodi:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_src_kodi

  den_avr_src_nuvo:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_src_nuvo
  
  den_roku_back:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: back
  
  den_roku_home:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: home
  
  den_roku_up:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: up
  
  den_roku_down:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: down
  
  den_roku_left:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: left
  
  den_roku_right:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: right
  
  den_roku_replay:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: replay
  
  den_roku_info:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: info
  
  den_roku_reverse:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: reverse
  
  den_roku_forward:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: forward
  
  den_roku_play:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: play
  
  den_roku_select:
    mode: parallel
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.roku_living_room
        data:
          command: select

automation:
  - alias: Den AV On With NuVo
    id: d737a132-dd7a-458e-905c-e1cfeb761bb0
    trigger:
      - platform: state
        entity_id: switch.nuvo_zone_7_power
        to: "on"
    action:
      - service: select.select_option
        data:
          entity_id: select.den_den_av
          option: "Listen to NuVo" 

  - alias: Den Mute Amp When NuVo Off
    id: d7a50b2a-e6e2-44bc-9358-71508c9097dd
    trigger:
      - platform: state
        entity_id: switch.nuvo_zone_7_power
        to: "off"
    condition:
      - condition: state
        entity_id: select.den_den_av
        state: "Listen to NuVo"
    action:
      - service: rest_command.den_avr_mute

  - alias: Den AV Off With NuVo
    id: b65d4447-c1c1-4875-9cb9-092552249790
    trigger:
      - platform: state
        entity_id: switch.nuvo_zone_7_power
        to: "off"
        for:
          seconds: 30
    condition:
      - condition: state
        entity_id: select.den_den_av
        state: "Listen to NuVo"
    action:
      - service: select.select_option
        data:
          entity_id: select.den_den_av
          option: "Power Off"          