media_player:
  - platform: custom_universal_media_player
    name: Den TV Current Status
    children: media_player.den_tv_jellyfin
    commands:
      select_source: 
        action: media_player.turn_on
        entity_id: media_player.den_tv_android
    attributes:
      state: media_player.den_tv_android
      entity_picture: sensor.den_media_cover
      media_duration: sensor.den_media_duration
      media_position: sensor.den_media_position

sensor:
  - platform: template
    sensors:
      den_avr_url:
        unique_id: 49d3be12-2784-46ed-b844-b4080dda11b3
        value_template: !secret den_avr_url

      den_media_cover:
        unique_id: 1606a2f0-f6fe-49ca-ab06-d0c430a6ea60
        value_template: >-
          {% if is_state_attr('media_player.den_tv_android', 'app_id', 'com.espn.score_center') -%}
            /local/remote_icons/channels/espn.webp
          {% elif is_state_attr('media_player.den_tv_android', 'app_id', 'com.wbd.stream') -%}
            /local/remote_icons/channels/max.webp
          {% elif is_state_attr('media_player.den_tv_android', 'app_id', 'com.netflix.ninja') -%}
            /local/remote_icons/channels/netflix.webp
          {% elif is_state_attr('media_player.den_tv_android', 'app_id', 'com.amazon.amazonvideo.livingroom') -%}
            /local/remote_icons/channels/prime.webp
          {% elif is_state_attr('media_player.den_tv_android', 'app_id', 'com.qvc.androidtv') -%}
            /local/remote_icons/channels/qvc.webp
          {% elif is_state_attr('media_player.den_tv_android', 'app_id', 'com.spotify.tv.android') -%}
            /local/remote_icons/channels/spotify.webp
          {% elif is_state_attr('media_player.den_tv_android', 'app_id', 'com.google.android.youtube.tv') -%}
            /local/remote_icons/channels/youtube.webp
          {% elif is_state_attr('media_player.den_tv_android', 'app_id', 'org.jellyfin.androidtv') -%}
            {% if is_state('media_player.den_tv_jellyfin', 'paused') or is_state('media_player.den_tv_jellyfin', 'playing') -%}
              {{ state_attr('media_player.den_tv_jellyfin', 'entity_picture') | replace("=150","=240",1) }}
            {% else -%}
              /local/remote_icons/channels/jellyfin.webp
            {% endif -%}
          {% else -%}
            /local/remote_icons/channels/googletv.webp
          {% endif -%}

      den_media_duration:
        unique_id: 6d75e32c-4904-440b-9949-844a6812516e
        value_template: >-
          {% if is_state_attr('media_player.den_tv_android', 'app_id', 'org.jellyfin.androidtv') and (is_state('media_player.den_tv_jellyfin', 'paused') or is_state('media_player.den_tv_jellyfin', 'playing')) -%}
            {{ state_attr('media_player.den_tv_jellyfin', 'media_duration') }}
          {% else -%}
            
          {% endif -%}

      den_media_position:
        unique_id: 909a55b3-104e-4322-a3c2-463ea178fbc9
        value_template: >-
          {% if is_state_attr('media_player.den_tv_android', 'app_id', 'org.jellyfin.androidtv') and (is_state('media_player.den_tv_jellyfin', 'paused') or is_state('media_player.den_tv_jellyfin', 'playing')) -%}
            {{ state_attr('media_player.den_tv_jellyfin', 'media_position') }}
          {% else -%}
            
          {% endif -%}

rest_command:
  den_avr_25:
    url: "{{ states('sensor.den_avr_url') }}111VL"
    method: get

  den_avr_33:
    url: "{{ states('sensor.den_avr_url') }}095VL"
    method: get

  den_avr_40:
    url: "{{ states('sensor.den_avr_url') }}081VL"
    method: get

  den_avr_on:
    url: "{{ states('sensor.den_avr_url') }}PO"
    method: get

  den_avr_off:
    url: "{{ states('sensor.den_avr_url') }}PF"
    method: get

  den_avr_vol_up:
    url: "{{ states('sensor.den_avr_url') }}VU"
    method: get

  den_avr_vol_dn:
    url: "{{ states('sensor.den_avr_url') }}VD"
    method: get

  den_avr_src_ps3:
    url: "{{ states('sensor.den_avr_url') }}25FN"
    method: get

  den_avr_src_wii:
    url: "{{ states('sensor.den_avr_url') }}11FN"
    method: get

  den_avr_src_apple:
    url: "{{ states('sensor.den_avr_url') }}19FN"
    method: get

  den_avr_src_roku:
    url: "{{ states('sensor.den_avr_url') }}20FN"
    method: get

  den_avr_src_cast:
    url: "{{ states('sensor.den_avr_url') }}21FN"
    method: get

  den_avr_src_kodi:
    url: "{{ states('sensor.den_avr_url') }}22FN"
    method: get

  den_avr_src_nuvo:
    url: "{{ states('sensor.den_avr_url') }}04FN"
    method: get

  den_avr_mute:
    url: "{{ states('sensor.den_avr_url') }}MO"
    method: get

command_line:
  - switch:
      name: Den TV
      unique_id: 1cea3280-de25-46a2-a4d7-702c73cabcd2
      command_on: echo -n -e "\x08\x22\x00\x00\x00\x02\xD4" | nc 10.10.10.44 100
      command_off: echo -n -e "\x08\x22\x00\x00\x00\x01\xD5" | nc 10.10.10.44 100

script:
  den_avr_mute:
    mode: parallel
    sequence:
      - service: media_player.volume_mute
        target:
          entity_id: media_player.den_avr
        data:
          is_volume_muted: "{{ not state_attr('media_player.den_avr' , 'is_volume_muted') }}"

  mass_select_christian:
    mode: parallel
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.mass_playlist
          option: "Top Christian Contemporary"
      - service: script.mass_change_playlist

  mass_select_country:
    mode: parallel
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.mass_playlist
          option: "Hot Country"
      - service: script.mass_change_playlist

  mass_select_scores:
    mode: parallel
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.mass_playlist
          option: "Epic Film Scores for Studying"
      - service: script.mass_change_playlist

  mass_select_christmas:
    mode: parallel
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.mass_playlist
          option: "Christmas Hits"
      - service: script.mass_change_playlist

  den_avr_activity_vol_kodi:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_25

  den_avr_activity_vol_roku:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_25

  den_avr_activity_vol_ps3:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_33

  den_avr_activity_vol_cast:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_40

  den_avr_activity_vol_wii:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_40

  den_avr_activity_vol_apple:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_40

  den_avr_activity_vol_nuvo:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_40

  den_avr_on:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_on

  den_avr_off:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_off

  den_avr_vol_up:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_vol_up

  den_avr_vol_dn:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_vol_dn

  den_avr_src_ps3:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_src_ps3

  den_avr_src_wii:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_src_wii

  den_avr_src_apple:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_src_apple

  den_avr_src_roku:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_src_roku

  den_avr_src_cast:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_src_cast

  den_avr_src_kodi:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_src_kodi

  den_avr_src_nuvo:
    mode: parallel
    sequence:
      - service: rest_command.den_avr_src_nuvo

  den_atv_src_espn:
    mode: parallel
    sequence:
      - action: media_player.play_media
        data:
          media_content_type: app
          media_content_id: com.espn.score_center
        target:
          entity_id: media_player.den_tv_android

  den_atv_src_jellyfin:
    mode: parallel
    sequence:
      - action: media_player.play_media
        data:
          media_content_type: app
          media_content_id: org.jellyfin.androidtv
        target:
          entity_id: media_player.den_tv_android

  den_atv_src_max:
    mode: parallel
    sequence:
      - action: media_player.play_media
        data:
          media_content_type: app
          media_content_id: com.wbd.stream
        target:
          entity_id: media_player.den_tv_android

  den_atv_src_netflix:
    mode: parallel
    sequence:
      - action: media_player.play_media
        data:
          media_content_type: app
          media_content_id: com.netflix.ninja
        target:
          entity_id: media_player.den_tv_android

  den_atv_src_prime:
    mode: parallel
    sequence:
      - action: media_player.play_media
        data:
          media_content_type: app
          media_content_id: com.amazon.amazonvideo.livingroom
        target:
          entity_id: media_player.den_tv_android

  den_atv_src_qvc:
    mode: parallel
    sequence:
      - action: media_player.play_media
        data:
          media_content_type: app
          media_content_id: com.qvc.androidtv
        target:
          entity_id: media_player.den_tv_android

  den_atv_src_spotify:
    mode: parallel
    sequence:
      - action: media_player.play_media
        data:
          media_content_type: app
          media_content_id: com.spotify.tv.android
        target:
          entity_id: media_player.den_tv_android

  den_atv_src_youtube:
    mode: parallel
    sequence:
      - action: media_player.play_media
        data:
          media_content_type: app
          media_content_id: com.google.android.youtube.tv
        target:
          entity_id: media_player.den_tv_android

  den_av_off:
    mode: parallel
    sequence:
      - action: select.select_option
        target:
          entity_id: select.den_den_av
        data:
          option: Power Off

  den_av_tv:
    mode: parallel
    sequence:
      - action: select.select_option
        target:
          entity_id: select.den_den_av
        data:
          option: Watch Android TV

  den_av_nuvo:
    mode: parallel
    sequence:
      - action: select.select_option
        target:
          entity_id: select.den_den_av
        data:
          option: Listen to NuVo