mqtt:
  sensor:
    - name: Manual Vacuum Sequence
      unique_id: 35fee3f2-65f5-48af-8ad9-21d10906a3a7
      state_topic: vacschedule/manual
    - name: Weekday 1 Vacuum Sequence
      unique_id: be38b25c-5e72-413a-a178-36121f071e35
      state_topic: vacschedule/week1
    - name: Weekday 2 Vacuum Sequence
      unique_id: 1307f0bc-74e2-46d6-8e75-7d415d930669
      state_topic: vacschedule/week2
    - name: Weekend Vacuum Sequence
      unique_id: d6696bdf-4395-4acb-8320-a2358fdae28a
      state_topic: vacschedule/weekend

input_boolean:
  vacuum_auto:
    name: Schedule Enabled
    icon: mdi:timer-outline
  vacuum_weekday_select:
    name: Vacuum Weekday Program Select
    icon: mdi:calendar-week
  vacuum_cycle_initiated:
    name: Daily Vacuum Cycle Initiated
    icon: mdi:clock-check
  vacuum_manual_entry:
    name: Entry
    icon: mdi:door-open
  vacuum_manual_hall:
    name: Hall
    icon: mdi:foot-print
  vacuum_manual_den:
    name: Den
    icon: mdi:sofa
  vacuum_manual_kitchen:
    name: Kitchen
    icon: mdi:silverware-fork-knife
  vacuum_manual_shack:
    name: Shack
    icon: mdi:radio-tower
  vacuum_manual_office:
    name: Office
    icon: mdi:laptop
  vacuum_manual_guest_bedroom:
    name: Guest Bedroom
    icon: mdi:bed-empty
  vacuum_manual_guest_bathroom:
    name: Guest Bathroom
    icon: mdi:toilet
  vacuum_manual_server_room:
    name: Server Room
    icon: mdi:server
  vacuum_manual_master_bedroom:
    name: Master Bedroom
    icon: mdi:bed-empty
  vacuum_manual_master_bathroom:
    name: Master Bathroom
    icon: mdi:toilet
  vacuum_weekday_1_entry:
    name: Entry
    icon: mdi:door-open
  vacuum_weekday_1_hall:
    name: Hall
    icon: mdi:foot-print
  vacuum_weekday_1_den:
    name: Den
    icon: mdi:sofa
  vacuum_weekday_1_kitchen:
    name: Kitchen
    icon: mdi:silverware-fork-knife
  vacuum_weekday_1_shack:
    name: Shack
    icon: mdi:radio-tower
  vacuum_weekday_1_office:
    name: Office
    icon: mdi:laptop
  vacuum_weekday_1_guest_bedroom:
    name: Guest Bedroom
    icon: mdi:bed-empty
  vacuum_weekday_1_guest_bathroom:
    name: Guest Bathroom
    icon: mdi:toilet
  vacuum_weekday_1_server_room:
    name: Server Room
    icon: mdi:server
  vacuum_weekday_1_master_bedroom:
    name: Master Bedroom
    icon: mdi:bed-empty
  vacuum_weekday_1_master_bathroom:
    name: Master Bathroom
    icon: mdi:toilet
  vacuum_weekday_2_entry:
    name: Entry
    icon: mdi:door-open
  vacuum_weekday_2_hall:
    name: Hall_1_
    icon: mdi:foot-print
  vacuum_weekday_2_den:
    name: Den
    icon: mdi:sofa
  vacuum_weekday_2_kitchen:
    name: Kitchen
    icon: mdi:silverware-fork-knife
  vacuum_weekday_2_shack:
    name: Shack
    icon: mdi:radio-tower
  vacuum_weekday_2_office:
    name: Office
    icon: mdi:laptop
  vacuum_weekday_2_guest_bedroom:
    name: Guest Bedroom
    icon: mdi:bed-empty
  vacuum_weekday_2_guest_bathroom:
    name: Guest Bathroom
    icon: mdi:toilet
  vacuum_weekday_2_server_room:
    name: Server Room
    icon: mdi:server
  vacuum_weekday_2_master_bedroom:
    name: Master Bedroom
    icon: mdi:bed-empty
  vacuum_weekday_2_master_bathroom:
    name: Master Bathroom
    icon: mdi:toilet
  vacuum_weekend_entry:
    name: Entry
    icon: mdi:door-open
  vacuum_weekend_hall:
    name: Hall
    icon: mdi:foot-print
  vacuum_weekend_den:
    name: Den
    icon: mdi:sofa
  vacuum_weekend_kitchen:
    name: Kitchen
    icon: mdi:silverware-fork-knife
  vacuum_weekend_shack:
    name: Shack
    icon: mdi:radio-tower
  vacuum_weekend_office:
    name: Office
    icon: mdi:laptop
  vacuum_weekend_guest_bedroom:
    name: Guest Bedroom
    icon: mdi:bed-empty
  vacuum_weekend_guest_bathroom:
    name: Guest Bathroom
    icon: mdi:toilet
  vacuum_weekend_server_room:
    name: Server Room
    icon: mdi:server
  vacuum_weekend_master_bedroom:
    name: Master Bedroom
    icon: mdi:bed-empty
  vacuum_weekend_master_bathroom:
    name: Master Bathroom
    icon: mdi:toilet

group:
  vacuum_manual_rooms:
    name: Vacuum Rooms
    entities:
      - input_boolean.vacuum_manual_entry
      - input_boolean.vacuum_manual_hall
      - input_boolean.vacuum_manual_office
      - input_boolean.vacuum_manual_guest_bedroom
      - input_boolean.vacuum_manual_guest_bathroom
      - input_boolean.vacuum_manual_server_room
      - input_boolean.vacuum_manual_den
      - input_boolean.vacuum_manual_master_bedroom
      - input_boolean.vacuum_manual_master_bathroom
      - input_boolean.vacuum_manual_kitchen
      - input_boolean.vacuum_manual_shack
  vacuum_weekday_1_rooms:
    name: Weekday 1 Vacuum Rooms
    entities:
      - input_boolean.vacuum_weekday_1_entry
      - input_boolean.vacuum_weekday_1_hall
      - input_boolean.vacuum_weekday_1_office
      - input_boolean.vacuum_weekday_1_guest_bedroom
      - input_boolean.vacuum_weekday_1_guest_bathroom
      - input_boolean.vacuum_weekday_1_server_room
      - input_boolean.vacuum_weekday_1_den
      - input_boolean.vacuum_weekday_1_master_bedroom
      - input_boolean.vacuum_weekday_1_master_bathroom
      - input_boolean.vacuum_weekday_1_kitchen
      - input_boolean.vacuum_weekday_1_shack
  vacuum_weekday_2_rooms:
    name: Weekday 2 Vacuum Rooms
    entities:
      - input_boolean.vacuum_weekday_2_entry
      - input_boolean.vacuum_weekday_2_hall
      - input_boolean.vacuum_weekday_2_office
      - input_boolean.vacuum_weekday_2_guest_bedroom
      - input_boolean.vacuum_weekday_2_guest_bathroom
      - input_boolean.vacuum_weekday_2_server_room
      - input_boolean.vacuum_weekday_2_den
      - input_boolean.vacuum_weekday_2_master_bedroom
      - input_boolean.vacuum_weekday_2_master_bathroom
      - input_boolean.vacuum_weekday_2_kitchen
      - input_boolean.vacuum_weekday_2_shack
  vacuum_weekend_rooms:
    name: Weekend Vacuum Rooms
    entities:
      - input_boolean.vacuum_weekday_2_entry
      - input_boolean.vacuum_weekday_2_hall
      - input_boolean.vacuum_weekday_2_office
      - input_boolean.vacuum_weekday_2_guest_bedroom
      - input_boolean.vacuum_weekday_2_guest_bathroom
      - input_boolean.vacuum_weekday_2_server_room
      - input_boolean.vacuum_weekday_2_den
      - input_boolean.vacuum_weekday_2_master_bedroom
      - input_boolean.vacuum_weekday_2_master_bathroom
      - input_boolean.vacuum_weekday_2_kitchen
      - input_boolean.vacuum_weekday_2_shack



counter:
  vacuum_cycles:
    step: 1
    
script:

  reset_vacuum_counter:
    sequence:
      - service: counter.reset
        entity_id: counter.vacuum_cycles

  vacuum_clean_segments:
    sequence:
    - service: mqtt.publish
      data:
        topic: valetudo/crookshanks/MapSegmentationCapability/clean/set
        payload_template: '{"segment_ids": {{ states("sensor.manual_vacuum_sequence")}}, "iterations": 1, "customOrder": true}'

automation:
  - alias: Start Vacuum from Schedule
    id: dd45d34f-0fb7-4ad2-88c9-788290b8ba02
    trigger:
      - platform: state
        entity_id: alarm_control_panel.house
        to: armed_away
        for: "00:10:00"
    condition:
      - condition: state
        entity_id: input_boolean.vacuum_auto
        state: "on"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
      - condition: state
        entity_id: input_boolean.vacuum_cycle_initiated
        state: "off"
    action:
      - choose:
        - conditions:
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
          sequence:
            - choose:
              - conditions:
                - condition: state
                  entity_id: input_boolean.vacuum_weekday_select
                  state: "off"
                sequence:
                  - service: mqtt.publish
                    data:
                      topic: valetudo/crookshanks/MapSegmentationCapability/clean/set
                      payload: '{"segment_ids": {{ states("sensor.weekday_1_vacuum_sequence")}}, "iterations": 1, "customOrder": true}'
                  - service: input_boolean.turn_on
                    entity_id: input_boolean.vacuum_weekday_select
              - conditions:
                - condition: state
                  entity_id: input_boolean.vacuum_weekday_select
                  state: "on"
                sequence:
                  - service: mqtt.publish
                    data:
                      topic: valetudo/crookshanks/MapSegmentationCapability/clean/set
                      payload: '{"segment_ids": {{ states("sensor.weekday_2_vacuum_sequence")}}, "iterations": 1, "customOrder": true}'
                  - service: input_boolean.turn_off
                    entity_id: input_boolean.vacuum_weekday_select
        - conditions:
          - condition: time
            weekday:
              - sat
              - sun
          sequence:
            - service: mqtt.publish
              data:
                topic: valetudo/crookshanks/MapSegmentationCapability/clean/set
                payload: '{"segment_ids": {{ states("sensor.weekend_vacuum_sequence")}}, "iterations": 1, "customOrder": true}'
      - service: input_boolean.turn_on
        entity_id: input_boolean.vacuum_cycle_initiated

  - alias: Count Vacuum Cycles
    id: 88b28362-f1cd-45ab-abce-edd5b194c0d7
    trigger:
      - platform: state
        entity_id: vacuum.valetudo_crookshanks
        to: "cleaning"
    action:
      - service: counter.increment
        entity_id: counter.vacuum_cycles
  
  - alias: Clear Daily Vacuum Run Indicator
    id: c1d1bed4-0cfb-40be-9222-ea6c0a9d52ca
    trigger:
      - platform: time
        at: "00:00:00"
    action:
      - service: input_boolean.turn_off        
        entity_id: input_boolean.vacuum_cycle_initiated
    