mqtt:
  switch:
    - name: "Garage Light 1"
      unique_id: f070fb14-8745-4265-b191-710d94ba97fe
      state_topic: "garage/t8_1/tele/current"
      command_topic: "garage/t8_1/command/set/power"
      availability_topic: "garage/t8_1/tele/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Garage Light 2"
      unique_id: b4a1a23b-778a-4798-9d03-29bb170b0930
      state_topic: "garage/t8_2/tele/current"
      command_topic: "garage/t8_2/command/set/power"
      availability_topic: "garage/t8_2/tele/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Garage Light 3"
      unique_id: 90d9a2cc-d242-4faa-b2b8-0edad7a3239c
      state_topic: "garage/t8_3/tele/current"
      command_topic: "garage/t8_3/command/set/power"
      availability_topic: "garage/t8_3/tele/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Garage Light 4"
      unique_id: 523c3ec6-e203-4e04-92a4-8f3883ce6a3e
      state_topic: "garage/t8_4/tele/current"
      command_topic: "garage/t8_4/command/set/power"
      availability_topic: "garage/t8_4/tele/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Garage Light 5"
      unique_id: a79c5fa6-3f37-4489-a2c2-d05640771ab9
      state_topic: "garage/t8_5/tele/current"
      command_topic: "garage/t8_5/command/set/power"
      availability_topic: "garage/t8_5/tele/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Garage Light 6"
      unique_id: a21b6a3f-7201-41c1-8365-ae01da761347
      state_topic: "garage/t8_6/tele/current"
      command_topic: "garage/t8_6/command/set/power"
      availability_topic: "garage/t8_6/tele/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Garage Light 7"
      unique_id: 6e1b9eb0-972a-4c6f-ae14-9897f2580579
      state_topic: "garage/t8_7/tele/current"
      command_topic: "garage/t8_7/command/set/power"
      availability_topic: "garage/t8_7/tele/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Garage Light 8"
      unique_id: c0b6fe78-cb67-4fbf-9033-6dba4a3ae0c2
      state_topic: "garage/t8_8/tele/current"
      command_topic: "garage/t8_8/command/set/power"
      availability_topic: "garage/t8_8/tele/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Garage Light 9"
      unique_id: 78a655ac-ef10-4298-bb86-abbb07eb03f7
      state_topic: "garage/t8_9/tele/current"
      command_topic: "garage/t8_9/command/set/power"
      availability_topic: "garage/t8_9/tele/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Garage Light 10"
      unique_id: d91c1d4b-07bb-4be7-8113-b37fe5a214bc
      state_topic: "garage/t8_10/tele/current"
      command_topic: "garage/t8_10/command/set/power"
      availability_topic: "garage/t8_10/tele/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Garage Light 11"
      unique_id: e475cd8e-d268-4bda-b08f-e2f6001d3184
      state_topic: "garage/t8_11/tele/current"
      command_topic: "garage/t8_11/command/set/power"
      availability_topic: "garage/t8_11/tele/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Garage Light 12"
      unique_id: 7da0debc-0d09-4d1c-82c6-da0c8834dd1f
      state_topic: "garage/t8_12/tele/current"
      command_topic: "garage/t8_12/command/set/power"
      availability_topic: "garage/t8_12/tele/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Garage Light 13"
      unique_id: eed79e02-5e4f-4f59-9867-07db8c44130d
      state_topic: "garage/t8_13/tele/current"
      command_topic: "garage/t8_13/command/set/power"
      availability_topic: "garage/t8_13/tele/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Garage Light 14"
      unique_id: 03f47b57-7157-4fef-b6a0-1fff6b2c711a
      state_topic: "garage/t8_14/tele/current"
      command_topic: "garage/t8_14/command/set/power"
      availability_topic: "garage/t8_14/tele/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"

timer:
  garage:
    name: Garage Light Timer
    duration: "00:10:00"    

group:
  garage_lights_all:
    name: All Garage Lights
    entities:
      - switch.garage_light_1
      - switch.garage_light_2
      - switch.garage_light_3
      - switch.garage_light_4
      - switch.garage_light_5
      - switch.garage_light_6
      - switch.garage_light_7
      - switch.garage_light_8
      - switch.garage_light_9
      - switch.garage_light_10
      - switch.garage_light_11
      - switch.garage_light_12
      - switch.garage_light_13
      - switch.garage_light_14

  garage_lights_low:
    name: Low Garage Lights
    entities:
      - switch.garage_light_6
      - switch.garage_light_8

  garage_lights_front:
    name: Front Garage Lights
    entities:
      - switch.garage_light_12
      - switch.garage_light_13
      - switch.garage_light_14

input_boolean:
  all_garage_lights:
    name: All Garage Lights
  low_garage_lights:
    name: Low Garage Lights

automation:
  - alias: Garage Light Auto On
    id: 5638adb3-b7d8-4af8-bd62-8e0a679ea507
    trigger:
      - platform: template
        value_template: "{{ is_state_attr('sensor.elk_garage_entry', 'physical_status', 'open') }}"
      - platform: state
        entity_id: sensor.elk_garage_motion
        from: Normal
        to: Violated
      - platform: state
        entity_id: sensor.elk_garage_door
        from: Normal
        to: Violated
    condition:
      - condition: state
        entity_id: input_boolean.low_garage_lights
        state: "off"
      - condition: state
        entity_id: input_boolean.all_garage_lights
        state: "off"
    action:
      - service: script.low_garage_lights_on

  - alias: Garage Light Timer Reset
    id: a59cfbf2-1ee1-4e47-89eb-4590f7694621
    trigger:
      - platform: template
        value_template: "{{ is_state_attr('sensor.elk_garage_entry', 'physical_status', 'open') }}"
      - platform: state
        entity_id: sensor.elk_garage_motion
        from: Normal
        to: Violated
      - platform: state
        entity_id: sensor.elk_garage_door
        from: Normal
        to: Violated
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.low_garage_lights
            state: "on"
          - condition: state
            entity_id: input_boolean.all_garage_lights
            state: "on"
    action:
      - service: timer.start
        entity_id: timer.garage_light

  - alias: Garage Light Auto Off
    id: ef137804-aff2-4e5f-80b0-b027f01fa35e
    trigger:
      - event_data:
          entity_id: timer.garage_light
        event_type: timer.finished
        platform: event
    condition:
      - condition: state
        entity_id: input_boolean.all_garage_lights
        state: "off"
    action:
      - service: script.garage_lights_off

  - alias: Front Garage Lights On With Garage Door
    id: 7ae49cef-db18-476e-bceb-f712e9ef4c36
    trigger:
      - platform: state
        entity_id: sensor.elk_garage_door
        from: Violated
        to: Normal
    condition:
      - condition: state
        entity_id: input_boolean.all_garage_lights
        state: "on"
    action:
      - service: mqtt.publish
        data:
          topic: garage/front/command/set/power
          payload: "ON"

  - alias: Front Garage Lights Off With Garage Door
    id: 7003a704-ed48-4424-b465-ce2bbd3b15ab
    trigger:
      - platform: state
        entity_id: sensor.elk_garage_door
        from: Normal
        to: Violated
    condition:
      - condition: state
        entity_id: input_boolean.all_garage_lights
        state: "on"
    action:
      - service: mqtt.publish
        data:
          topic: garage/front/command/set/power
          payload: "OFF"

  - alias: Garage Lights On From Keypad
    id: 204113bb-e7e2-4bfe-8561-b5473494aa07
    trigger:
      - platform: event
        event_type: isy994_control
        event_data:
          entity_id: switch.garage_light
          control: "DON"
      - platform: event
        event_type: isy994_control
        event_data:
          entity_id: switch.garage_light
          control: "DFON"
    condition:
      - condition: state
        entity_id: input_boolean.all_garage_lights
        state: "off"
      - condition: state
        entity_id: input_boolean.low_garage_lights
        state: "off"
    action:
      - service: script.low_garage_lights_on

  - alias: Garage Lights Change From Keypad
    id: 9f48f0ea-625a-4a00-a32d-b824cba71a55
    trigger:
      - platform: event
        event_type: isy994_control
        event_data:
          entity_id: switch.garage_light
          control: "DON"
      - platform: event
        event_type: isy994_control
        event_data:
          entity_id: switch.garage_light
          control: "DFON"
    condition:
      - condition: or
        conditions:          
        - condition: state
          entity_id: input_boolean.all_garage_lights
          state: "on"
        - condition: state
          entity_id: input_boolean.low_garage_lights
          state: "on"
    action:
      - service: script.change_garage_lights

  - alias: Garage Lights Off From Keypad
    id: ce1e3174-10e2-493d-a620-b61ca328dcf4
    trigger:
      - platform: event
        event_type: isy994_control
        event_data:
          entity_id: switch.garage_light
          control: "DOF"
    action:
      - service: script.garage_lights_off

  - alias: Garage Light Keypad On
    id: 7f285fa4-2b44-4a77-a843-6c798af2b9d1
    trigger:
      - platform: state
        entity_id: group.garage_lights_all
        to: "on"
    condition:
      - condition: state
        entity_id: switch.garage_light
        state: "off"
    action:
      - service: switch.turn_on
        entity_id: switch.garage_light

  - alias: Garage Light Keypad Off
    id: 8b9376f5-f6bd-417f-bfa9-cf06179b0f77
    trigger:
      - platform: state
        entity_id: group.garage_lights_all
        to: "off"
    condition:
      - condition: state
        entity_id: switch.garage_light
        state: "on"
    action:
      - service: switch.turn_off
        entity_id: switch.garage_light

  - alias: Garage Fan Off When Trapdoor Open
    id: 706f69f6-22fc-4a54-9bab-bea53ab000ca
    trigger:
      - platform: state
        entity_id: sensor.elk_garage_trapdoor
        to: Violated
    condition:
      - condition: state
        entity_id: switch.garage_fan
        state: "on"
    action:
      - service: switch.turn_off
        entity_id: switch.garage_fan

script:
  garage_lights_off:
    alias: Garage Lights Off
    sequence:
      - service: mqtt.publish
        data:
          topic: garage/all/command/set/power
          payload: "OFF"      
      - service: input_boolean.turn_off
        entity_id: 
          - input_boolean.all_garage_lights
          - input_boolean.low_garage_lights

  all_garage_lights_on:
    alias: All Garage Lights On
    sequence:
      - choose:
        - conditions:
          - condition: state
            entity_id: sensor.elk_garage_door
            state: Violated
          sequence:
            - service: mqtt.publish
              data:
                topic: garage/main/command/set/power
                payload: "ON"
        default: 
          - service: mqtt.publish
            data:
              topic: garage/all/command/set/power
              payload: "ON"
      - service: input_boolean.turn_on
        entity_id: input_boolean.all_garage_lights

  low_garage_lights_on:
    alias: Low Garage Lights On
    sequence:
      - service: mqtt.publish
        data:
          topic: garage/low/command/set/power
          payload: "ON"      
      - service: input_boolean.turn_on
        entity_id: input_boolean.low_garage_lights      
      - service: timer.start
        entity_id: timer.garage_light

  change_garage_lights:
    alias: Change Garage Lights
    sequence:
      - choose:
        - conditions:
          - condition: state
            entity_id: input_boolean.low_garage_lights
            state: "on"
          sequence:
            - service: input_boolean.turn_off
              entity_id: input_boolean.low_garage_lights
            - service: script.all_garage_lights_on
        default: 
          - service: input_boolean.turn_off
            entity_id: input_boolean.all_garage_lights
          - service: mqtt.publish
            data:
              topic: garage/high/command/set/power
              payload: "OFF"      
          - service: input_boolean.turn_on
            entity_id: input_boolean.low_garage_lights      
          - service: timer.start
            entity_id: timer.garage_light
