sensor:
  - platform: template
    sensors:
      den_harmony_activity:
        friendly_name: Den Harmony Activity
        value_template: "{{ state_attr('remote.harmony_den', 'current_activity') }}"

      master_harmony_activity:
        friendly_name: Master Bedroom Harmony Activity
        value_template: "{{ state_attr('remote.harmony_master_bedroom', 'current_activity') }}"