sensor:
  - platform: template
    sensors:
      den_harmony_activity:
        unique_id: a6c76263-031e-4fb4-ac3b-af868ffb2341
        friendly_name: Den Harmony Activity
        value_template: "{{ state_attr('remote.harmony_den', 'current_activity') }}"

      master_harmony_activity:
        unique_id: 69543381-332a-426e-8a4c-4ec780d31dc0
        friendly_name: Master Bedroom Harmony Activity
        value_template: "{{ state_attr('remote.harmony_master_bedroom', 'current_activity') }}"


automation:
  - alias: Set Den AVR Volume to -25
    id: 29bd4fa2-a2fc-4501-a27f-4556f6ed2f6a
    trigger:
      - platform: state
        entity_id: sensor.den_harmony_activity
        to: "Watch PVR"
      - platform: state
        entity_id: sensor.den_harmony_activity
        to: "Watch Roku"
    action:
      - service: rest_command.den_avr_25

  - alias: Set Den AVR Volume to -33
    id: c5bb3cb3-4676-4e45-91aa-5f7bfaa36f74
    trigger:
      - platform: state
        entity_id: sensor.den_harmony_activity
        to: "Play PS3"
    action:
      - service: rest_command.den_avr_33

  - alias: Set Den AVR Volume to -40
    id: c27a3e4e-f63b-43af-b978-02f9366af1d0
    trigger:
      - platform: state
        entity_id: sensor.den_harmony_activity
        to: "ChromeCast"
      - platform: state
        entity_id: sensor.den_harmony_activity
        to: "Listen to WHA"
      - platform: state
        entity_id: sensor.den_harmony_activity
        to: "Play Wii"
    action:
      - service: rest_command.den_avr_40

  - alias: Master Bedroom Harmony On With NuVo
    id: b137dfb2-ca19-4796-b28c-2d84e53768ef
    trigger:
      - platform: state
        entity_id: switch.nuvo_zone_4_power
        to: "on"
    condition:
      - condition: template
        value_template: "{{ not is_state('sensor.master_harmony_activity', 'None') }}"
    action:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_master_bedroom
          activity: "Listen to WHA"

  - alias: Master Bedroom Harmony Off With NuVo
    id: 5c62e8c7-a493-4a6d-806e-fa57f12ba0e2
    trigger:
      - platform: state
        entity_id: switch.nuvo_zone_4_power
        to: "off"
        for:
          seconds: 15
    condition:
      - condition: template
        value_template: "{{ not is_state('sensor.master_harmony_activity', 'None') }}"
      - condition: state
        entity_id: sensor.master_harmony_activity
        state: "Listen to WHA"
    action:
      - service: remote.turn_off
        entity_id: remote.harmony_master_bedroom

  - alias: Den Harmony On With NuVo
    id: d737a132-dd7a-458e-905c-e1cfeb761bb0
    trigger:
      - platform: state
        entity_id: switch.nuvo_zone_7_power
        to: "on"
    action:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_den
          activity: "Listen to WHA"

  - alias: Den Mute Amp When NuVo Off
    id: d7a50b2a-e6e2-44bc-9358-71508c9097dd
    trigger:
      - platform: state
        entity_id: switch.nuvo_zone_7_power
        to: "off"
    condition:
      - condition: state
        entity_id: sensor.den_harmony_activity
        state: "Listen to WHA"
    action:
      - service: rest_command.den_avr_mute

  - alias: Den Harmony Off With NuVo
    id: b65d4447-c1c1-4875-9cb9-092552249790
    trigger:
      - platform: state
        entity_id: switch.nuvo_zone_7_power
        to: "off"
        for:
          seconds: 15
    condition:
      - condition: state
        entity_id: sensor.den_harmony_activity
        state: "Listen to WHA"
    action:
      - service: remote.turn_off
        entity_id: remote.harmony_den

  - alias: Control Living Area Blinds from Den Harmony
    id: d3877ccb-d4f0-4159-8482-688cb7884a6a
    trigger:
      - platform: event
        event_type: roku_command
        event_data:
          source_name: Home Assistant
          type: keypress
          key: Left
    action:
      - service: cover.toggle
        entity_id:
          - cover.den_blinds
          - cover.kitchen_blinds
          - cover.shack_blinds

  - alias: Control Den Fan from Den Harmony
    id: 87f67013-61bf-4db8-95a0-82be01966996
    trigger:
      - platform: event
        event_type: roku_command
        event_data:
          source_name: Home Assistant
          type: keypress
          key: Right
    action:
      - service: switch.toggle
        entity_id: switch.den_fan
