sensor:
  - platform: template
    sensors:
      master_harmony_activity:
        unique_id: 69543381-332a-426e-8a4c-4ec780d31dc0
        friendly_name: Master Bedroom Harmony Activity
        value_template: "{{ state_attr('remote.harmony_master_bedroom', 'current_activity') }}"


automation:

  - alias: Master Bedroom Harmony On With NuVo
    id: b137dfb2-ca19-4796-b28c-2d84e53768ef
    trigger:
      - platform: state
        entity_id: switch.nuvo_zone_4_power
        to: "on"
    condition:
      - condition: template
        value_template: "{{ not is_state('sensor.master_harmony_activity', 'None') }}"
    action:
      - service: remote.turn_on
        data:
          entity_id: remote.harmony_master_bedroom
          activity: "Listen to WHA"

  - alias: Master Bedroom Harmony Off With NuVo
    id: 5c62e8c7-a493-4a6d-806e-fa57f12ba0e2
    trigger:
      - platform: state
        entity_id: switch.nuvo_zone_4_power
        to: "off"
        for:
          seconds: 15
    condition:
      - condition: template
        value_template: "{{ not is_state('sensor.master_harmony_activity', 'None') }}"
      - condition: state
        entity_id: sensor.master_harmony_activity
        state: "Listen to WHA"
    action:
      - service: remote.turn_off
        entity_id: remote.harmony_master_bedroom
