input_boolean:  
  drip_irrigation_enabled:
    name: Drip Irrigation Enabled
    icon: mdi:timer-outline
  lawn_irrigation_enabled:
    name: Lawn Irrigation Enabled
    icon: mdi:timer-outline
  lawn_irrigation_manual:
    name: Lawn Irrigation Run Next Cycle
    icon: mdi:timer-outline
  lawn_irrigation_snooze:
    name: Lawn Irrigation Snooze
    icon: mdi:timer-outline

input_number:
  drip_irrigation_duration:
    name: Drip Irrigation duration
    min: 1
    max: 60
    mode: box
    unit_of_measurement: min
  back_yard_base_runtime:
    name: Back Yard Irrigation Base Runtime
    min: 1
    max: 60
    step: 1
    mode: box
    unit_of_measurement: min
  east_front_base_runtime:
    name: East Front Irrigation Base Runtime
    min: 1
    max: 60
    step: 1
    mode: box
    unit_of_measurement: min
  east_side_base_runtime:
    name: East Side Irrigation Base Runtime
    min: 1
    max: 120
    step: 1
    mode: box
    unit_of_measurement: min
  west_front_base_runtime:
    name: West Front Irrigation Base Runtime
    min: 1
    max: 60
    step: 1
    mode: box
    unit_of_measurement: min
  west_side_base_runtime:
    name: West Side Irrigation Base Runtime
    min: 1
    max: 60
    step: 1
    mode: box
    unit_of_measurement: min
  irrigation_depletion_trigger:
    name: Minimum Irrigation Depletion to Water
    min: -1
    max: 0
    step: 0.05
    mode: box
    unit_of_measurement: in
  irrigation_delay_precip:
    name: Precipitation Rain Delay
    min: 0
    max: 1
    step: 0.05
    mode: box
    unit_of_measurement: in
  irrigation_delay_pop:
    name: Precipitation Probability Rain Delay
    min: 0
    max: 100
    step: 1
    mode: box
    unit_of_measurement: "%"

input_datetime:
  irrigation_start:
    name: Irrigation Start Time
    has_date: false
    has_time: true    

template:
  - sensor:
    - name: Program Lawn Irrigation Status
      unique_id: 3480e9ab-784f-4484-9179-9fa8aacbb115
      state: >-
        {% if  is_state('input_boolean.lawn_irrigation_enabled', 'on') and is_state('switch.main_irrigation_controller_main_irrigation_controller_main_switch', 'on') and is_state('number.main_irrigation_controller_main_irrigation_controller_multiplier', '0.25') -%}
          running
        {% elif is_state('input_boolean.lawn_irrigation_enabled', 'on')  -%}
          enabled
        {% else -%}
          disabled
        {% endif -%}

    - name: Program Drip Status
      unique_id: 697a92e1-35f7-4788-a643-d6c8f43e5568
      state: >-
        {% if is_state('input_boolean.drip_irrigation_enabled', 'on') and is_state('switch.back_drip_valve', 'off') -%}
          enabled
        {% elif  is_state('input_boolean.drip_irrigation_enabled', 'on') and is_state('switch.back_drip_valve', 'on') -%}
          running
        {% else -%}
          disabled
        {% endif -%}
      
    - name: Lawn Bucket
      unique_id: 594f7d57-f86c-4f70-b79b-9909faf075a7
      state: "{{ state_attr('sensor.smart_irrigation_lawn','bucket') | round (2,0)}}"
      unit_of_measurement: "in"
      
    - name: Lawn ET
      unique_id: b4132f9f-fb86-4fe6-afec-0632bad61d73
      state: "{{ (state_attr('sensor.smart_irrigation_lawn','et_value') / 25.4) | round (2,0)}}"
      unit_of_measurement: "in"

automation:
  - alias: Run Lawn Irrigation
    id: a85e7595-00cf-4fed-98ee-380544f75dee
    trigger:
      - platform: template
        value_template: "{{ states('sensor.time') == (state_attr('input_datetime.irrigation_start', 'timestamp') | timestamp_custom('%H:%M', False, none)) }}"
    action:
      - choose:
        - conditions:
          - condition: state
            entity_id: input_boolean.lawn_irrigation_enabled
            state: 'on'
          - condition: state
            entity_id: input_boolean.lawn_irrigation_snooze
            state: 'off'
          - condition: or
            conditions:
              - condition: state
                entity_id: input_boolean.lawn_irrigation_manual
                state: 'on'
              - condition: and
                conditions: 
                  - condition: numeric_state
                    entity_id: sensor.smart_irrigation_lawn
                    attribute: bucket
                    below: input_number.irrigation_depletion_trigger
                  - condition: numeric_state
                    entity_id: sensor.rain_day
                    below: input_number.irrigation_delay_precip
                  - condition: or
                    conditions:
                      - condition: numeric_state
                        entity_id: sensor.openweathermap_current_precip_forecast
                        below: input_number.irrigation_delay_precip
                      - condition: and
                        conditions:
                          - condition: numeric_state
                            entity_id: sensor.openweathermap_current_precip_forecast
                            above: input_number.irrigation_delay_precip
                          - condition: numeric_state
                            entity_id: sensor.openweathermap_current_pop
                            below: input_number.irrigation_delay_pop
          sequence:
            - choose:
              - conditions:          
                - condition: numeric_state
                  entity_id: sensor.smart_irrigation_lawn
                  attribute: bucket
                  below: -1.0
                sequence:
                  - action: esphome.main_irrigation_controller_sprinkler_set_divider
                    data:
                      divider: 4
                  - action: number.set_value
                    data_template:
                      entity_id: number.main_irrigation_controller_back_yard_duration
                      value: "{{ states('input_number.back_yard_base_runtime') | int * 60 }}"
                  - action: number.set_value
                    data_template:
                      entity_id: number.main_irrigation_controller_east_front_duration
                      value: "{{ states('input_number.east_front_base_runtime') | int * 60 }}"
                  - action: number.set_value
                    data_template:
                      entity_id: number.main_irrigation_controller_east_side_duration
                      value: "{{ states('input_number.east_side_base_runtime') | int * 60 }}"
                  - action: number.set_value
                    data_template:
                      entity_id: number.main_irrigation_controller_west_front_duration
                      value: "{{ states('input_number.west_front_base_runtime') | int * 60 }}"
                  - action: number.set_value
                    data_template:
                      entity_id: number.main_irrigation_controller_west_side_duration
                      value: "{{ states('input_number.west_side_base_runtime') | int * 60 }}"
                  - action: esphome.main_irrigation_controller_sprinkler_start_cycle
                  - action: smart_irrigation.set_all_buckets
                    data:
                      new_bucket_value: "{{ (state_attr('sensor.smart_irrigation_lawn','bucket') | round (2,0)) + 1}}"
              default:
                - action: esphome.main_irrigation_controller_sprinkler_set_divider
                  data:
                    divider: 2
                - action: number.set_value
                  data_template:
                    entity_id: number.main_irrigation_controller_back_yard_duration
                    value: "{{ ((state_attr('sensor.smart_irrigation_lawn','bucket') | float | abs) * (states('input_number.back_yard_base_runtime') | int) * 60) | round(0,ceil) }}"
                - action: number.set_value
                  data_template:
                    entity_id: number.main_irrigation_controller_east_front_duration
                    value: "{{ ((state_attr('sensor.smart_irrigation_lawn','bucket') | float | abs) * (states('input_number.east_front_base_runtime') | int) * 60) | round(0,ceil) }}"
                - action: number.set_value
                  data_template:
                    entity_id: number.main_irrigation_controller_east_side_duration
                    value: "{{ ((state_attr('sensor.smart_irrigation_lawn','bucket') | float | abs) * (states('input_number.east_side_base_runtime') | int) * 60) | round(0,ceil) }}"
                - action: number.set_value
                  data_template:
                    entity_id: number.main_irrigation_controller_west_front_duration
                    value: "{{ ((state_attr('sensor.smart_irrigation_lawn','bucket') | float | abs) * (states('input_number.west_front_base_runtime') | int) * 60) | round(0,ceil) }}"
                - action: number.set_value
                  data_template:
                    entity_id: number.main_irrigation_controller_west_side_duration
                    value: "{{ ((state_attr('sensor.smart_irrigation_lawn','bucket') | float | abs) * (states('input_number.west_side_base_runtime') | int) * 60) | round(0,ceil) }}"
                - action: esphome.main_irrigation_controller_sprinkler_start_cycle
                - action: smart_irrigation.reset_all_buckets
      - action: input_boolean.turn_off
        entity_id: 
          - input_boolean.lawn_irrigation_manual
          - input_boolean.lawn_irrigation_snooze

  - alias: Run Back Drip Irrigation
    id: 8fc4dd84-9231-4abc-a32b-4b6252ac7f89
    trigger:
      - platform: sun
        event: sunrise
    condition:
      - condition: state
        entity_id: input_boolean.drip_irrigation_enabled
        state: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.back_drip_valve

  - alias: Stop Back Drip Irrigation
    id: 8a752a04-9c63-49af-9643-7a3ff9e32ef7
    trigger:
      - platform: state
        entity_id: switch.back_drip_valve
        to: "on"
        for:
          minutes: "{{ states('input_number.drip_irrigation_duration')|int }}"
    action:
      - service: switch.turn_off
        entity_id: switch.back_drip_valve

script: 
  manual_water_back_yard:
    alias: Manual Water Back Yard
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: switch.main_irrigation_controller_back_yard
                state: "off"
            sequence:
              - action: esphome.main_irrigation_controller_sprinkler_set_divider
                data:
                  divider: 1
              - action: number.set_value
                data:
                  entity_id: number.main_irrigation_controller_back_yard_duration
                  value: 600
              - action: switch.turn_on
                entity_id: switch.main_irrigation_controller_back_yard
          - conditions:
              - condition: state
                entity_id: switch.main_irrigation_controller_back_yard
                state: "on"
            sequence:
              - action: switch.turn_off
                entity_id: switch.main_irrigation_controller_back_yard

  manual_water_east_front:
    alias: Manual Water East Front
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: switch.main_irrigation_controller_east_front
                state: "off"
            sequence:
              - action: esphome.main_irrigation_controller_sprinkler_set_divider
                data:
                  divider: 1
              - action: number.set_value
                data:
                  entity_id: number.main_irrigation_controller_east_front_duration
                  value: 600
              - action: switch.turn_on
                entity_id: switch.main_irrigation_controller_east_front
          - conditions:
              - condition: state
                entity_id: switch.main_irrigation_controller_east_front
                state: "on"
            sequence:
              - action: switch.turn_off
                entity_id: switch.main_irrigation_controller_east_front

  manual_water_east_side:
    alias: Manual Water East Side
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: switch.main_irrigation_controller_east_side
                state: "off"
            sequence:
              - action: esphome.main_irrigation_controller_sprinkler_set_divider
                data:
                  divider: 1
              - action: number.set_value
                data:
                  entity_id: number.main_irrigation_controller_east_side_duration
                  value: 600
              - action: switch.turn_on
                entity_id: switch.main_irrigation_controller_east_side
          - conditions:
              - condition: state
                entity_id: switch.main_irrigation_controller_east_side
                state: "on"
            sequence:
              - action: switch.turn_off
                entity_id: switch.main_irrigation_controller_east_side

  manual_water_west_front:
    alias: Manual Water West Front
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: switch.main_irrigation_controller_west_front
                state: "off"
            sequence:
              - action: esphome.main_irrigation_controller_sprinkler_set_divider
                data:
                  divider: 1
              - action: number.set_value
                data:
                  entity_id: number.main_irrigation_controller_west_front_duration
                  value: 600
              - action: switch.turn_on
                entity_id: switch.main_irrigation_controller_west_front
          - conditions:
              - condition: state
                entity_id: switch.main_irrigation_controller_west_front
                state: "on"
            sequence:
              - action: switch.turn_off
                entity_id: switch.main_irrigation_controller_west_front

  manual_water_west_side:
    alias: Manual Water West Side
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: switch.main_irrigation_controller_west_side
                state: "off"
            sequence:
              - action: esphome.main_irrigation_controller_sprinkler_set_divider
                data:
                  divider: 1
              - action: number.set_value
                data:
                  entity_id: number.main_irrigation_controller_west_side_duration
                  value: 600
              - action: switch.turn_on
                entity_id: switch.main_irrigation_controller_west_side
          - conditions:
              - condition: state
                entity_id: switch.main_irrigation_controller_west_side
                state: "on"
            sequence:
              - action: switch.turn_off
                entity_id: switch.main_irrigation_controller_west_side

  manual_water_all:
    alias: Manual Water All Zones
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: switch.main_irrigation_controller_main_irrigation_controller_main_switch
                state: "off"
            sequence:              
              - action: esphome.main_irrigation_controller_sprinkler_set_divider
                data:
                  divider: 2
              - action: number.set_value
                data_template:
                  entity_id: number.main_irrigation_controller_back_yard_duration
                  value: "{{ (states('input_number.back_yard_base_runtime') | int) * 30) | round(0,ceil) }}"
              - action: number.set_value
                data_template:
                  entity_id: number.main_irrigation_controller_east_front_duration
                  value: "{{ (states('input_number.east_front_base_runtime') | int) * 30) | round(0,ceil) }}"
              - action: number.set_value
                data_template:
                  entity_id: number.main_irrigation_controller_east_side_duration
                  value: "{{ (states('input_number.east_side_base_runtime') | int) * 30) | round(0,ceil) }}"
              - action: number.set_value
                data_template:
                  entity_id: number.main_irrigation_controller_west_front_duration
                  value: "{{ (states('input_number.west_front_base_runtime') | int) * 30) | round(0,ceil) }}"
              - action: number.set_value
                data_template:
                  entity_id: number.main_irrigation_controller_west_side_duration
                  value: "{{ (states('input_number.west_side_base_runtime') | int) * 30) | round(0,ceil) }}"
              - action: esphome.main_irrigation_controller_sprinkler_start_cycle
              - action: smart_irrigation.set_all_buckets
                data:
                  new_bucket_value: "{{ ((state_attr('sensor.smart_irrigation_lawn','bucket') | float) | round (2,0)) + 0.5}}"
          - conditions:
              - condition: state
                entity_id: switch.main_irrigation_controller_main_irrigation_controller_main_switch
                state: "on"
            sequence:
              - action: switch.turn_off
                entity_id: switch.main_irrigation_controller_main_irrigation_controller_main_switch