# Sensors
mqtt:
  sensor:
    #Sonoff Washer Monitor
    - name: "Washer State"
      unique_id: cd0ad294-4301-453e-9ac1-e12ae356cca3
      state_topic: "hass/state/washer"
      icon: mdi:washing-machine

    #Sonoff Dryer Monitor
    - name: "Dryer State"
      unique_id: 9e4b07de-7a19-4f99-ad73-3e9cfcfda4de
      state_topic: "hass/state/dryer"
      icon: mdi:tumble-dryer

sensor:
  - platform: template
    sensors:
      washer_status:
        unique_id: de9d8708-c377-40ba-a545-0ddaf5ff11fc
        value_template: >-
          {% if is_state('input_boolean.washer_end', 'on')  -%}
            Done
          {% else -%}
            {{ states('sensor.washer_state')}}
          {% endif -%}

      dryer_status:
        unique_id: 17ca6811-6cac-4a56-93ee-1c2e578d0779
        value_template: >-
          {% if is_state('input_boolean.dryer_end', 'on')  -%}
            Done
          {% else -%}
            {{ states('sensor.dryer_state')}}
          {% endif -%}

      remaining_detergent:
        unique_id: d17cc63d-4de4-46f4-88aa-f52f471592e7
        value_template: >-
          {{ (((states('counter.washer_cycles_since_refill') | float(none) - states('input_number.washer_cycle_capacity') | float(none)) / states('input_number.washer_cycle_capacity') | float(none)) * 100) | round(2, default=none) }}
        unit_of_measurement: "%"

input_boolean:
  washer_end:
    name: Washer Finished
    initial: off
    icon: mdi:stop-circle

  dryer_end:
    name: Dryer Finished
    initial: off
    icon: mdi:stop-circle

# Timers
timer:
  washer_alert:
    name: Washer Announcement Timer
    duration: "00:05:00"

  dryer_alert:
    name: Dryer Announcement Timer
    duration: "00:05:00"

#Counters
counter:
  dryer_alert:
    initial: 0
    step: 1
  washer_alert:
    initial: 0
    step: 1
  total_washer_cycles:
    step: 1
  washer_cycles_since_refill:
    step: 1

input_number:
  washer_cycle_capacity:    
    mode: box
    min: 0
    max: 1000
    unit_of_measurement: "h"

script: 
  reset_washer_detergent_counter:
    alias: Reset Detergent Counter
    sequence:
      - service: counter.reset
        entity_id: counter.washer_cycles_since_refill

automation:
  - alias: "Dryer State - Door"
    id: b20e9fcc-2cf1-4a73-b957-15c9b2a051c9
    trigger:
      - platform: numeric_state
        entity_id: sensor.dryer_energy_power
        above: 5
        below: 20
        for:
          seconds: 2
    action:
      - service: mqtt.publish
        data:
          topic: hass/state/dryer
          payload: "Door Open"
          retain: "true"

  - alias: "Dryer State - Drying"
    id: 207d3e98-175c-414d-aa88-3974301028dc
    trigger:
      - platform: numeric_state
        entity_id: sensor.dryer_energy_power
        above: 50
        for:
          seconds: 2
    action:
      - service: mqtt.publish
        data:
          topic: hass/state/dryer
          payload: "Drying"
          retain: "true"
      - service: switch.turn_on
        entity_id: switch.utility_room_vent_fan
      - service: input_boolean.turn_off
        entity_id: input_boolean.dryer_end

  - alias: "Dryer State - Idle"
    id: 5b860d55-1b30-49b0-87d7-ff953fdc4dd9
    trigger:
      - platform: numeric_state
        entity_id: sensor.dryer_energy_power
        below: 5
        for:
          seconds: 2
    action:
      - service: mqtt.publish
        data:
          topic: hass/state/dryer
          payload: "Idle"
          retain: "true"
      - service: switch.turn_off
        entity_id: switch.utility_room_vent_fan

  # -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  #  Washing Machine Start/Finish
  # -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  - alias: "Washer State - Start"
    id: f2d307d7-23bc-40c7-9626-76cc5fdedad4
    trigger:
      - platform: numeric_state
        entity_id: sensor.washer_energy_power
        above: 20
        for:
          seconds: 10
    # Make sure washer isn't already running and delaying between cycles - don't re-trigger and cause stopwatch reset
    condition:
      - condition: template
        value_template: "{{ not is_state('sensor.washer_state', 'Washing') }}"
    action:
      - service: mqtt.publish
        data:
          topic: hass/state/washer
          payload: "Washing"
          retain: "true"
      - service: input_boolean.turn_off
        entity_id: input_boolean.washer_end

  - alias: "Washer State - Idle"
    id: 51f499e7-bda1-44ec-ab06-f082bca8ce9c
    trigger:
      - platform: numeric_state
        entity_id: sensor.washer_energy_power
        below: 20
        for:
          minutes: 2
    action:
      - service: mqtt.publish
        data:
          topic: hass/state/washer
          payload: "Idle"
          retain: "true"

  - alias: "Dryer Finished"
    id: 093d5b4d-8ba6-4bf5-a16e-e16f180e76a0
    trigger:
      - platform: state
        entity_id: sensor.dryer_state
        from: "Drying"
        to: "Idle"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.dryer_end

  - alias: "Washer Finished"
    id: 727e74b5-8529-4d51-a43f-50a010567450
    trigger:
      - platform: state
        entity_id: sensor.washer_state
        from: "Washing"
        to: "Idle"
    condition:
      - condition: template
        value_template: "{{ not is_state('sensor.dryer_state', 'Drying') }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.washer_end

  # -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  #  Announcements
  # -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  - alias: "Announce Dryer Finished"
    id: 36c0668e-cdc2-4277-96ff-8934a747b48c
    trigger:
      - platform: state
        entity_id: input_boolean.dryer_end
        to: "on"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.house
            state: "disarmed"
          - condition: state
            entity_id: alarm_control_panel.house
            state: "armed_home"
    action:
      - service: mqtt.publish
        data:
          topic: parrot/command/set/play
          payload: 3,1
      - service: timer.start
        entity_id: timer.dryer_alert
      - service: notify.mobile_app_shawn_7t
        data:
          message: The dryer has stopped.
          title: Laundry Update
          data:
            ttl: 0
            priority: high
      - service: notify.den_kodi
        data:
          title: "Laundry Update"
          message: "The dryer has stopped."
          data:
            displaytime: 20000
            icon: "info"
      - service: browser_mod.notification
        data:
          message: "The dryer has stopped."
          duration: 3000

  - alias: "Repeat Announce Dryer Finished"
    id: a51c8c5c-31af-4001-b931-5125204164cc
    trigger:
      - event_data:
          entity_id: timer.dryer_alert
        event_type: timer.finished
        platform: event
    condition:
      - condition: numeric_state
        entity_id: counter.dryer_alert
        below: 7
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.house
            state: "disarmed"
          - condition: state
            entity_id: alarm_control_panel.house
            state: "armed_home"
    action:
      - service: mqtt.publish
        data:
          topic: parrot/command/set/play
          payload: 3,1
      - service: timer.start
        entity_id: timer.dryer_alert
      - service: counter.increment
        entity_id: counter.dryer_alert

  - alias: "Announce Washer Finished"
    id: b6287a47-29d5-4057-ba1f-15db05e026e2
    trigger:
      - platform: state
        entity_id: input_boolean.washer_end
        to: "on"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.house
            state: "disarmed"
          - condition: state
            entity_id: alarm_control_panel.house
            state: "armed_home"
    action:
      - service: mqtt.publish
        data:
          topic: parrot/command/set/play
          payload: 3,3
      - service: timer.start
        entity_id: timer.washer_alert
      - service: notify.mobile_app_shawn_7t
        data:
          message: The washer has stopped.
          title: Laundry Update
          data:
            ttl: 0
            priority: high
      - service: notify.den_kodi
        data:
          title: "Laundry Update"
          message: "The washer has stopped."
          data:
            displaytime: 20000
            icon: "info"
      - service: browser_mod.notification
        data:
          message: "The washer has stopped."
          duration: 3000

  - alias: "Repeat Announce Washer Finished"
    id: 7eef5299-bafb-4bbb-9da0-0d72952edb03
    trigger:
      - event_data:
          entity_id: timer.washer_alert
        event_type: timer.finished
        platform: event
    condition:
      - condition: numeric_state
        entity_id: counter.washer_alert
        below: 7
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.house
            state: "disarmed"
          - condition: state
            entity_id: alarm_control_panel.house
            state: "armed_home"
    action:
      - service: mqtt.publish
        data:
          topic: parrot/command/set/play
          payload: 3,3
      - service: timer.start
        entity_id: timer.washer_alert
      - service: counter.increment
        entity_id: counter.dryer_alert

  #Reset all timers when Laundry Room entered
  - alias: "Reset Laundry Timers on Motion"
    id: ae5d9e18-2075-493f-8a13-9927b9ece693
    trigger:
      - entity_id: sensor.elk_utility_motion
        platform: state
        to: Violated
    action:
      - service: input_boolean.turn_off
        entity_id:
          - input_boolean.dryer_end
          - input_boolean.washer_end
      - service: timer.cancel
        entity_id:
          - timer.dryer_alert
          - timer.washer_alert
      - service: counter.reset
        entity_id:
          - counter.dryer_alert
          - counter.washer_alert

  #Reset all timers when Not Awake or Home
  - alias: "Reset Laundry Timers on Alarm Status"
    id: 5d2939de-57a1-48e5-a2c5-914f5d418487
    trigger:
      - entity_id: input_boolean.dryer_end
        platform: state
        to: "on"
      - entity_id: input_boolean.washer_end
        platform: state
        to: "on"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.house
            state: "armed_away"
          - condition: state
            entity_id: alarm_control_panel.house
            state: "armed_night"
    action:
      - service: input_boolean.turn_off
        entity_id:
          - input_boolean.dryer_end
          - input_boolean.washer_end
      - service: timer.cancel
        entity_id:
          - timer.dryer_alert
          - timer.washer_alert
      - service: counter.reset
        entity_id:
          - counter.dryer_alert
          - counter.washer_alert

  - alias: dispense laundry detergent
    id: fb62b8e4-80da-447b-b5a6-fe2f341b295a
    trigger:
      - platform: state
        entity_id: sensor.detergent_button_click
        to: "single"
    action: 
      - service: switch.turn_on
        entity_id: switch.detergent_pump
      - service: counter.increment
        entity_id:
          - counter.total_washer_cycles
          - counter.washer_cycles_since_refill