# Sensors
mqtt:
  sensor:
    #Sonoff Washer Monitor
    - name: "Washer State"
      unique_id: cd0ad294-4301-453e-9ac1-e12ae356cca3
      state_topic: "hass/state/washer"
      icon: mdi:washing-machine

    #Sonoff Dryer Monitor
    - name: "Dryer State"
      unique_id: 9e4b07de-7a19-4f99-ad73-3e9cfcfda4de
      state_topic: "hass/state/dryer"
      icon: mdi:tumble-dryer

sensor:
  - platform: template
    sensors:
      washer_status:
        unique_id: de9d8708-c377-40ba-a545-0ddaf5ff11fc
        value_template: >-
          {% if is_state('input_boolean.washer_end', 'on')  -%}
            Done
          {% else -%}
            {{ states('sensor.washer_state')}}
          {% endif -%}

      dryer_status:
        unique_id: 17ca6811-6cac-4a56-93ee-1c2e578d0779
        value_template: >-
          {% if is_state('input_boolean.dryer_end', 'on')  -%}
            Done
          {% else -%}
            {{ states('sensor.dryer_state')}}
          {% endif -%}

input_boolean:
  washer_end:
    name: Washer Finished
    initial: off
    icon: mdi:stop-circle

  dryer_end:
    name: Dryer Finished
    initial: off
    icon: mdi:stop-circle

# Timers
timer:
  washer_alert:
    name: Washer Announcement Timer
    duration: "00:05:00"

  dryer_alert:
    name: Dryer Announcement Timer
    duration: "00:05:00"

#Counters
counter:
  dryer_alert:
    initial: 0
    step: 1
  washer_alert:
    initial: 0
    step: 1
