binary_sensor:
  - platform: template
    sensors:
      kitchen_leak_detectors:
        value_template: "{{ is_state('binary_sensor.kitchen_sink_leak_dry', 'on') or is_state('binary_sensor.refrigerator_leak_dry', 'on') or is_state('binary_sensor.dishwasher_leak_dry', 'on') }}"
        friendly_name: 'Kitchen Leak Detectors'  
        device_class: moisture    

      guest_bathroom_leak_detectors:
        value_template: "{{ is_state('binary_sensor.guest_sink_leak_dry', 'on') or is_state('binary_sensor.guest_toilet_leak_dry', 'on') }}"
        friendly_name: 'Guest Bathroom Leak Detectors'    
        device_class: moisture    

      master_bathroom_leak_detectors:
        value_template: "{{ is_state('binary_sensor.left_master_sink_leak_dry', 'on') or is_state('binary_sensor.right_master_sink_leak_dry', 'on') or is_state('binary_sensor.master_toilet_leak_dry', 'on') }}"
        friendly_name: 'Master Bathroom Leak Detectors'    
        device_class: moisture    

alert:
  dishwasher_leak_detected:
    name: Leak Detected!
    entity_id: binary_sensor.dishwasher_leak_dry
    state: 'on'
    repeat: 720
    can_acknowledge: true
    skip_first: false
    message: "A leak has been detected in the dishwasher."
    done_message: "The dishwasher leak has been cleared."
    notifiers:
      - mobile_app_shawn_7t
  
  dishwasher_leak_error:
    name: Leak Detector Error!
    entity_id: binary_sensor.dishwasher_leak_heartbeat
    state: 'on'
    repeat: 1440
    can_acknowledge: true
    skip_first: false
    message: "The dishwasher leak detector is not reporting."
    done_message: "The dishwasher leak detector is restored."
    notifiers:
      - mobile_app_shawn_7t

  guest_sink_leak_detected:
    name: Leak Detected!
    entity_id: binary_sensor.guest_sink_leak_dry
    state: 'on'
    repeat: 720
    can_acknowledge: true
    skip_first: false
    message: "A leak has been detected in the guest bathroom sink."
    done_message: "The guest bathroom sink leak has been cleared."
    notifiers:
      - mobile_app_shawn_7t
  
  guest_sink_leak_error:
    name: Leak Detector Error!
    entity_id: binary_sensor.guest_sink_leak_heartbeat
    state: 'on'
    repeat: 1440
    can_acknowledge: true
    skip_first: false
    message: "The guest bathroom sink leak detector is not reporting."
    done_message: "The guest bathroom sink leak detector is restored."
    notifiers:
      - mobile_app_shawn_7t
  
  guest_toilet_leak_detected:
    name: Leak Detected!
    entity_id: binary_sensor.guest_toilet_leak_dry
    state: 'on'
    repeat: 720
    can_acknowledge: true
    skip_first: false
    message: "A leak has been detected in the guest toilet."
    done_message: "The guest toilet leak has been cleared."
    notifiers:
      - mobile_app_shawn_7t
  
  guest_toilet_leak_error:
    name: Leak Detector Error!
    entity_id: binary_sensor.guest_toilet_leak_heartbeat
    state: 'on'
    repeat: 1440
    can_acknowledge: true
    skip_first: false
    message: "The guest toilet leak detector is not reporting."
    done_message: "The guest toilet leak detector is restored."
    notifiers:
      - mobile_app_shawn_7t

  kitchen_sink_leak_detected:
    name: Leak Detected!
    entity_id: binary_sensor.kitchen_sink_leak_dry
    state: 'on'
    repeat: 720
    can_acknowledge: true
    skip_first: false
    message: "A leak has been detected in the kitchen sink."
    done_message: "The kitchen sink leak has been cleared."
    notifiers:
      - mobile_app_shawn_7t
  
  kitchen_sink_leak_error:
    name: Leak Detector Error!
    entity_id: binary_sensor.kitchen_sink_leak_heartbeat
    state: 'on'
    repeat: 1440
    can_acknowledge: true
    skip_first: false
    message: "The kitchen sink leak detector is not reporting."
    done_message: "The kitchen dink leak detector is restored."
    notifiers:
      - mobile_app_shawn_7t

  left_master_sink_leak_detected:
    name: Leak Detected!
    entity_id: binary_sensor.left_master_sink_leak_dry
    state: 'on'
    repeat: 720
    can_acknowledge: true
    skip_first: false
    message: "A leak has been detected in the left master bathroom sink."
    done_message: "The left master bathroom sink leak has been cleared."
    notifiers:
      - mobile_app_shawn_7t
  
  left_master_sink_leak_error:
    name: Leak Detector Error!
    entity_id: binary_sensor.left_master_sink_leak_heartbe
    state: 'on'
    repeat: 1440
    can_acknowledge: true
    skip_first: false
    message: "The left master bathroom sink leak detector is not reporting."
    done_message: "The left master bathroom sink leak detector is restored."
    notifiers:
      - mobile_app_shawn_7t

  master_toilet_leak_detected:
    name: Leak Detected!
    entity_id: binary_sensor.master_toilet_leak_dry
    state: 'on'
    repeat: 720
    can_acknowledge: true
    skip_first: false
    message: "A leak has been detected in the master toilet."
    done_message: "The master toilet leak has been cleared."
    notifiers:
      - mobile_app_shawn_7t
  
  master_toilet_leak_error:
    name: Leak Detector Error!
    entity_id: binary_sensor.master_toilet_leak_heartbeat
    state: 'on'
    repeat: 1440
    can_acknowledge: true
    skip_first: false
    message: "The master toilet leak detector is not reporting."
    done_message: "The toilet leak detector is restored."
    notifiers:
      - mobile_app_shawn_7t

  refrigerator_sink_leak_detected:
    name: Leak Detected!
    entity_id: binary_sensor.refrigerator_leak_dry
    state: 'on'
    repeat: 720
    can_acknowledge: true
    skip_first: false
    message: "A leak has been detected in the refrigerator."
    done_message: "The refrigerator leak has been cleared."
    notifiers:
      - mobile_app_shawn_7t
  
  refrigerator_leak_error:
    name: Leak Detector Error!
    entity_id: binary_sensor.refrigerator_leak_heartbeat
    state: 'on'
    repeat: 1440
    can_acknowledge: true
    skip_first: false
    message: "The refrigerator leak detector is not reporting."
    done_message: "The refrigerator leak detector is restored."
    notifiers:
      - mobile_app_shawn_7t

  right_master_sink_leak_detected:
    name: Leak Detected!
    entity_id: binary_sensor.right_master_sink_leak_dry
    state: 'on'
    repeat: 720
    can_acknowledge: true
    skip_first: false
    message: "A leak has been detected in the right master bathroom sink."
    done_message: "The right master bathroom sink leak has been cleared."
    notifiers:
      - mobile_app_shawn_7t
  
  left_master_sink_leak_error:
    name: Leak Detector Error!
    entity_id: binary_sensor.right_master_sink_leak_heartb
    state: 'on'
    repeat: 1440
    can_acknowledge: true
    skip_first: false
    message: "The right master bathroom sink leak detector is not reporting."
    done_message: "The right master bathroom sink leak detector is restored."
    notifiers:
      - mobile_app_shawn_7t

  utility_leak_detected:
    name: Leak Detected!
    entity_id: binary_sensor.utility_leak_dry
    state: 'on'
    repeat: 720
    can_acknowledge: true
    skip_first: false
    message: "A leak has been detected in the utility room."
    done_message: "The utility room leak has been cleared."
    notifiers:
      - mobile_app_shawn_7t
  
  utility_leak_error:
    name: Leak Detector Error!
    entity_id: binary_sensor.utility_leak_heartbeat
    state: 'on'
    repeat: 1440
    can_acknowledge: true
    skip_first: false
    message: "The utility room leak detector is not reporting."
    done_message: "The utility room leak detector is restored."
    notifiers:
      - mobile_app_shawn_7t