timer:
  dishwasher_leak:
    duration: '30:00:00'
    #restore: true
    #restore_grace_period: '01:00:00'

  guest_sink_leak:
    duration: '30:00:00'
    #restore: true
    #restore_grace_period: '01:00:00'

  guest_toilet_leak:
    duration: '30:00:00'
    #restore: true
    #restore_grace_period: '01:00:00'

  kitchen_sink_leak:
    duration: '30:00:00'
    #restore: true
    #restore_grace_period: '01:00:00'

  left_master_sink_leak:
    duration: '30:00:00'
    #restore: true
    #restore_grace_period: '01:00:00'

  master_toilet_leak:
    duration: '30:00:00'
    #restore: true
    #restore_grace_period: '01:00:00'

  refrigerator_leak:
    duration: '30:00:00'
    #restore: true
    #restore_grace_period: '01:00:00'
  
  right_master_sink_leak:
    duration: '30:00:00'
    #restore: true
    #restore_grace_period: '01:00:00'

  utility_leak:
    duration: '30:00:00'
    #restore: true
    #restore_grace_period: '01:00:00'

sensor:
  - platform: template
    sensors:    
      dishwasher_leak_detector:
        friendly_name: Dishwasher Leak Detector
        value_template: >
          {% if states('binary_sensor.dishwasher_leak_dry') == "on" %}
            Wet
          {% elif states('timer.dishwasher_leak') != "active" %}      
            Error
          {% elif states('binary_sensor.dishwasher_leak_dry') == "off" %}
            Dry
          {% else %}
           Error
          {% endif %}
      
      guest_sink_leak_detector:
        friendly_name: Guest Sink Leak Detector
        value_template: >
          {% if states('binary_sensor.guest_sink_leak_dry') == "on" %}
            Wet
          {% elif states('timer.guest_sink_leak') != "active" %}      
            Error
          {% elif states('binary_sensor.guest_sink_leak_dry') == "off" %}
            Dry
          {% else %}
           Error
          {% endif %}
      
      guest_toilet_leak_detector:
        friendly_name: Guest Toilet Leak Detector
        value_template: >
          {% if states('binary_sensor.guest_toilet_leak_dry') == "on" %}
            Wet
          {% elif states('timer.guest_toilet_leak') != "active" %}      
            Error
          {% elif states('binary_sensor.guest_toilet_leak_dry') == "off" %}
            Dry
          {% else %}
           Error
          {% endif %}

      kitchen_sink_leak_detector:
        friendly_name: Kitchen Sink Leak Detector
        value_template: >
          {% if states('binary_sensor.kitchen_sink_leak_dry') == "on" %}
            Wet
          {% elif states('timer.kitchen_sink_leak') != "active" %}      
            Error
          {% elif states('binary_sensor.kitchen_sink_leak_dry') == "off" %}
            Dry
          {% else %}
           Error
          {% endif %}

      left_master_sink_leak_detector:
        friendly_name: Left Master Sink Leak Detector
        value_template: >
          {% if states('binary_sensor.left_master_sink_leak_dry') == "on" %}
            Wet
          {% elif states('timer.left_master_sink_leak') != "active" %}      
            Error
          {% elif states('binary_sensor.left_master_sink_leak_dry') == "off" %}
            Dry
          {% else %}
           Error
          {% endif %}

      master_toilet_leak_detector:
        friendly_name: Master Toilet Leak Detector
        value_template: >
          {% if states('binary_sensor.master_toilet_leak_dry') == "on" %}
            Wet
          {% elif states('timer.master_toilet_leak') != "active" %}      
            Error
          {% elif states('binary_sensor.master_toilet_leak_dry') == "off" %}
            Dry
          {% else %}
           Error
          {% endif %}
          
      refrigerator_leak_detector:
        friendly_name: Refrigerator Leak Detector
        value_template: >
          {% if states('binary_sensor.refrigerator_leak_dry') == "on" %}
            Wet
          {% elif states('timer.refrigerator_leak') != "active" %}      
            Error
          {% elif states('binary_sensor.refrigerator_leak_dry') == "off" %}
            Dry
          {% else %}
           Error
          {% endif %}

      right_master_sink_leak_detector:
        friendly_name: Right Master Sink Leak Detector
        value_template: >
          {% if states('binary_sensor.right_master_sink_leak_dry') == "on" %}
            Wet
          {% elif states('timer.right_master_sink_leak') != "active" %}      
            Error
          {% elif states('binary_sensor.right_master_sink_leak_dry') == "off" %}
            Dry
          {% else %}
           Error
          {% endif %}

      utility_leak_detector:
        friendly_name: Utility Leak Detector
        value_template: >
          {% if states('binary_sensor.utility_leak_dry') == "on" %}
            Wet
          {% elif states('timer.utility_leak') != "active" %}      
            Error
          {% elif states('binary_sensor.utility_leak_dry') == "off" %}
            Dry
          {% else %}
           Error
          {% endif %}