template:
  - sensor:
    - name: Chamber of Secrets Status Short
      unique_id: 712ed244-df40-4cbf-8c4c-a34415cdbd76
      state: >-
        {% if  is_state('binary_sensor.chamber_of_secrets_sleep_mode', 'on') -%}
          Sleep
        {% elif is_state('sensor.chamber_of_secrets_status_code', 'rdy') -%}
          Ready
        {% elif is_state('sensor.chamber_of_secrets_status_code', 'ccc') -%}
          Done
        {% elif  is_state('sensor.chamber_of_secrets_status_code', 'ccp') -%}
          Clean
        {% elif  is_state('sensor.chamber_of_secrets_status_code', 'df2') -%}
          Drawer 2
        {% elif  is_state('sensor.chamber_of_secrets_status_code', 'df1') -%}
          Drawer 1
        {% elif  is_state('sensor.chamber_of_secrets_status_code', 'csf') or is_state('sensor.chamber_of_secrets_status_code', 'csi') or is_state('sensor.chamber_of_secrets_status_code', 'scf') -%}
          Sensor
        {% elif  is_state('sensor.chamber_of_secrets_status_code', 'cst') -%}
          Timing
        {% elif  is_state('sensor.chamber_of_secrets_status_code', 'br') -%}
          Bonnet  
        {% elif  is_state('sensor.chamber_of_secrets_status_code', 'p') -%}
          Paused 
        {% elif  is_state('sensor.chamber_of_secrets_status_code', 'pd') or is_state('sensor.chamber_of_secrets_status_code', 'spf') -%}
          Pinch
        {% elif  is_state('sensor.chamber_of_secrets_status_code', 'cd') -%}
          Cat
        {% elif  is_state('sensor.chamber_of_secrets_status_code', 'ec') -%}
          Empty
        {% elif  is_state('sensor.chamber_of_secrets_status_code', 'off') -%}
          Off 
        {% elif  is_state('sensor.chamber_of_secrets_status_code', 'offline') -%}
          Offline
        {% elif  is_state('sensor.chamber_of_secrets_status_code', 'otf') -%}
          Torque 
        {% elif  is_state('sensor.chamber_of_secrets_status_code', 'dfs') or is_state('sensor.chamber_of_secrets_status_code', 'sdf') -%}
          Full
        {% elif  is_state('sensor.chamber_of_secrets_status_code', 'dhf') or is_state('sensor.chamber_of_secrets_status_code', 'dpf') or is_state('sensor.chamber_of_secrets_status_code', 'hpf') -%}
          Position
        {% elif  is_state('sensor.chamber_of_secrets_status_code', 'pwrd') or is_state('sensor.chamber_of_secrets_status_code', 'pwru') -%}
          Power
        {% else -%}
          Error
        {% endif -%}

    - name: Forbidden Forest Status Short
      unique_id: 6eb4aa56-f45c-49df-902f-f7631f18fb6e
      state: >-
        {% if  is_state('binary_sensor.forbidden_forest_sleep_mode', 'on') -%}
          Sleep
        {% elif is_state('sensor.forbidden_forest_status_code', 'rdy') -%}
          Ready
        {% elif is_state('sensor.forbidden_forest_status_code', 'ccc') -%}
          Done
        {% elif  is_state('sensor.forbidden_forest_status_code', 'ccp') -%}
          Clean
        {% elif  is_state('sensor.forbidden_forest_status_code', 'df2') -%}
          Drawer 2
        {% elif  is_state('sensor.forbidden_forest_status_code', 'df1') -%}
          Drawer 1
        {% elif  is_state('sensor.forbidden_forest_status_code', 'csf') or is_state('sensor.forbidden_forest_status_code', 'csi') or is_state('sensor.forbidden_forest_status_code', 'scf') -%}
          Sensor
        {% elif  is_state('sensor.forbidden_forest_status_code', 'cst') -%}
          Timing
        {% elif  is_state('sensor.forbidden_forest_status_code', 'br') -%}
          Bonnet  
        {% elif  is_state('sensor.forbidden_forest_status_code', 'p') -%}
          Paused 
        {% elif  is_state('sensor.forbidden_forest_status_code', 'pd') or is_state('sensor.forbidden_forest_status_code', 'spf') -%}
          Pinch
        {% elif  is_state('sensor.forbidden_forest_status_code', 'cd') -%}
          Cat
        {% elif  is_state('sensor.forbidden_forest_status_code', 'ec') -%}
          Empty
        {% elif  is_state('sensor.forbidden_forest_status_code', 'off') -%}
          Off 
        {% elif  is_state('sensor.forbidden_forest_status_code', 'offline') -%}
          Offline
        {% elif  is_state('sensor.forbidden_forest_status_code', 'otf') -%}
          Torque 
        {% elif  is_state('sensor.forbidden_forest_status_code', 'dfs') or is_state('sensor.forbidden_forest_status_code', 'sdf') -%}
          Full
        {% elif  is_state('sensor.forbidden_forest_status_code', 'dhf') or is_state('sensor.forbidden_forest_status_code', 'dpf') or is_state('sensor.forbidden_forest_status_code', 'hpf') -%}
          Position
        {% elif  is_state('sensor.forbidden_forest_status_code', 'pwrd') or is_state('sensor.forbidden_forest_status_code', 'pwru') -%}
          Power
        {% else -%}
          Error
        {% endif -%}

  - switch:
    - name: Chamber of Secrets Power
      unique_id: 1c69d41e-1d7a-4cba-82a8-d9f4230fa722
      state: "{{ not is_state('sensor.chamber_of_secrets_status_code', 'on') }}"
      turn_on:
        service: vacuum.start
        entity_id: vacuum.chamber_of_secrets_litter_box
      turn_off:
        service: vacuum.stop
        entity_id: vacuum.chamber_of_secrets_litter_box

    - name: Forbidden Forest Power
      unique_id: 088cb47f-adcb-43bf-ae93-fbecae03ad5a
      state: "{{ not is_state('sensor.forbidden_forest_status_code', 'on') }}"
      turn_on:
        service: vacuum.start
        entity_id: vacuum.forbidden_forest_litter_box
      turn_off:
        service: vacuum.stop
        entity_id: vacuum.forbidden_forest_litter_box

automation:
  - alias: Chamber of Secrets Entry Alert
    id: e5cef912-167b-4bf4-ad6a-6d4c0cffa475
    trigger:
      - platform: state
        entity_id: sensor.chamber_of_secrets_status_code
        to: "cd"
      - platform: state
        entity_id: sensor.chamber_of_secrets_status_code
        from: "rdy"
        to: "cst"
    variables:
      image_time: "{{ now ().year }}_{{ now ().month }}_{{ now ().day }}_{{ now ().hour }}_{{ now ().minute }}"
    action:
      - action: camera.snapshot
        data:
          entity_id: camera.shack
          filename: /config/media/snapshots/shack_{{ image_time }}.jpg
      - action: camera.snapshot
        data:
          entity_id: camera.chamber_of_secrets
          filename: /config/media/snapshots/chamber_of_secrets_{{ image_time }}.jpg
      - action: ai_task.generate_data      
        response_variable: llm_response
        data:
          attachments:
            - media_content_id: media-source://media_source/media/snapshots/shack_{{ image_time }}.jpg
              media_content_type: image/jpeg
            - media_content_id: media-source://media_source/media/snapshots/chamber_of_secrets_{{ image_time }}.jpg
              media_content_type: image/jpeg
          task_name: Cat ID
          instructions: >
            Identify the cat in this images by name.  One image is a room overview 
            and the other shows the inside of the Litter-Robot litterbox.  The cat 
            may not appear in both images.  There are 4 options.  Respond with only 
            that cat's name.  If there is no cat in the image respond with None.

            1) April - A black and white tuxedo cat.  She is all black except for her
            neck and legs.

            2) Luna - A smaller tabby cat.  Linear stripes with a white vest and paws. 
            She is brown with gray stripes.  She also wears a white collar.

            3) Shelby - He is the largest cat, also a tabby, but with no white except
            for his chin.  His stripes are swirled on both sides.  He is long, tall, and
            large.

            4) Junior - He is an orange tabby.  Similar in size to Luna, but varying
            shades of orange.  On infrared images, he appears nearly white while the 
            others will have more variation.
      - action: notify.cctv_email
        data_template:
          title: "Chamber of Secrets Activated by {{ llm_response.data }} - {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
          message: "The Chamber of Secrets was activated at {{now().strftime('%H:%M:%S') }}.  It was activated by {{ llm_response.data }}."
          data:
            images:
              - /config/media/snapshots/shack_{{ image_time }}.jpg    
              - /config/media/snapshots/chamber_of_secrets_{{ image_time }}.jpg     
            html: >
              The Chamber of Secrets was activated at {{now().strftime('%H:%M:%S') }}.  It was activated by {{ llm_response.data }}.
              <br>
              <img style='width: 100%; object-fit: contain' src="cid:shack_{{ image_time }}.jpg">   
              <br>
              <img style='width: 100%; object-fit: contain' src="cid:chamber_of_secrets_{{ image_time }}.jpg">   



  - alias: Forbidden Forest Entry Alert
    id: a0c3fec3-c2cc-4f3a-b190-fe19979642a3
    trigger:
      - platform: state
        entity_id: sensor.forbidden_forest_status_code
        to: "cd"
      - platform: state
        entity_id: sensor.forbidden_forest_status_code
        from: "rdy"
        to: "cst"
    variables:
      image_time: "{{ now ().year }}_{{ now ().month }}_{{ now ().day }}_{{ now ().hour }}_{{ now ().minute }}"
    action:
      - service: camera.snapshot
        data:
          entity_id: camera.entry
          filename: /config/media/snapshots/entry_{{ image_time }}.jpg
      - service: camera.snapshot
        data:
          entity_id: camera.forbidden_forest
          filename: /config/media/snapshots/forbidden_forest_{{ image_time }}.jpg
    
      - action: ai_task.generate_data      
        response_variable: llm_response
        data:
          attachments:
            - media_content_id: media-source://media_source/media/snapshots/entry_{{ image_time }}.jpg
              media_content_type: image/jpeg
            - media_content_id: media-source://media_source/media/snapshots/forbidden_forest_{{ image_time }}.jpg
              media_content_type: image/jpeg
          task_name: Cat ID
          instructions: >
            Identify the cat in this images by name.  One image is a room overview 
            and the other shows the inside of the Litter-Robot litterbox.  The cat 
            may not appear in both images.  There are 4 options.  Respond with only 
            that cat's name.  If there is no cat in the image respond with None.

            1) April - A black and white tuxedo cat.  She is all black except for her
            neck and legs.

            2) Luna - A smaller tabby cat.  Linear stripes with a white vest and paws. 
            She is brown with gray stripes.  She also wears a white collar.

            3) Shelby - He is the largest cat, also a tabby, but with no white except
            for his chin.  His stripes are swirled on both sides.  He is long, tall, and
            large.

            4) Junior - He is an orange tabby.  Similar in size to Luna, but varying
            shades of orange.  On infrared images, he appears nearly white while the 
            others will have more variation.

      - service: notify.cctv_email
        data_template:
          title: "Forbidden Forest Activated by {{ llm_response.data }} - {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
          message: "The Forbidden Forest was activated at {{now().strftime('%H:%M:%S') }}.  It was activated by {{ llm_response.data }}."
          data:
            images:
              - /config/media/snapshots/entry_{{ image_time }}.jpg    
              - /config/media/snapshots/forbidden_forest_{{ image_time }}.jpg     
            html: >
              The Forbidden Forest was activated at {{now().strftime('%H:%M:%S') }}.  It was activated by {{ llm_response.data }}.
              <br>
              <img style='width: 100%; object-fit: contain' src="cid:entry_{{ image_time }}.jpg">   
              <br>
              <img style='width: 100%; object-fit: contain' src="cid:forbidden_forest_{{ image_time }}.jpg">   

  - alias: Forbidden Forest Contents Detection
    id: 23adbc11-41bb-498d-a95b-b2e022138db7
    trigger:
      - platform: state
        entity_id: sensor.forbidden_forest_status_code
        from: "cst"
        to: "ccp"
    variables:
      image_time: "{{ now ().year }}_{{ now ().month }}_{{ now ().day }}_{{ now ().hour }}_{{ now ().minute }}"
    action:
      - service: camera.snapshot
        data:
          entity_id: camera.forbidden_forest
          filename: /config/media/snapshots/forbidden_forest_waste_{{ image_time }}.jpg
    
      - action: ai_task.generate_data      
        response_variable: llm_response
        data:
          attachments:
            - media_content_id: media-source://media_source/media/snapshots/forbidden_forest_waste_{{ image_time }}.jpg
              media_content_type: image/jpeg
          task_name: Cat ID
          instructions: >
            The image shows the inside of a litter robot cat box that has been used and is about to cycle.  
            Based on the image, identify if the previous use was urine, feces, or both.  If the litter has 
            not been used, respond with None.  Do not look at residue on the plastic.  Just return the 1-word answer.

      - service: notify.cctv_email
        data_template:
          title: "Forbidden Forest Cycling for {{ llm_response.data }} - {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
          message: "The Forbidden Forest is cycling.  The last deposit was {{ llm_response.data }}."
          data:
            images:  
              - /config/media/snapshots/forbidden_forest_waste{{ image_time }}.jpg     
            html: >
              The Forbidden Forest was activated at {{now().strftime('%H:%M:%S') }}.  It was activated by {{ llm_response.data }}.  
              <br>
              <img style='width: 100%; object-fit: contain' src="cid:forbidden_forest_waste_{{ image_time }}.jpg">   

  - alias: Chamber of Secrets Contents Detection
    id: d5c56011-7b5c-4725-9953-83321031754f
    trigger:
      - platform: state
        entity_id: sensor.chamber_of_secrets_status_code
        from: "cst"
        to: "ccp"
    variables:
      image_time: "{{ now ().year }}_{{ now ().month }}_{{ now ().day }}_{{ now ().hour }}_{{ now ().minute }}"
    action:
      - service: camera.snapshot
        data:
          entity_id: camera.chamber_of_secrets
          filename: /config/media/snapshots/chamber_of_secrets_waste_{{ image_time }}.jpg
    
      - action: ai_task.generate_data      
        response_variable: llm_response
        data:
          attachments:
            - media_content_id: media-source://media_source/media/snapshots/chamber_of_secrets_waste_{{ image_time }}.jpg
              media_content_type: image/jpeg
          task_name: Cat ID
          instructions: >
            The image shows the inside of a litter robot cat box that has been used and is about to cycle.  
            Based on the image, identify if the previous use was urine, feces, or both.  If the litter has 
            not been used, respond with None.  Do not look at residue on the plastic.  Just return the 1-word answer.

      - service: notify.cctv_email
        data_template:
          title: "Chamber of Secrets Cycling for {{ llm_response.data }} - {{now().strftime('%Y-%m-%d %H:%M:%S') }}"
          message: "The Chamber of Secrets is cycling.  The last deposit was {{ llm_response.data }}."
          data:
            images:  
              - /config/media/snapshots/chamber_of_secrets_waste{{ image_time }}.jpg     
            html: >
              The Chamber of Secrets was activated at {{now().strftime('%H:%M:%S') }}.  It was activated by {{ llm_response.data }}.  
              <br>
              <img style='width: 100%; object-fit: contain' src="cid:chamber_of_secrets_waste_{{ image_time }}.jpg">   