switch:
  - platform: template
    switches:
      manual_timer_lights:
        unique_id: f56e7e46-6f49-4287-a229-1b047ac51256
        friendly_name: "Manual Timer Lights"
        value_template: "{{ is_state('input_boolean.timer_lights', 'on') or is_state('input_boolean.manual_timer_lights', 'on') }}"
        turn_on:
          service: script.timer_lights_manual_on
        turn_off:
          service: script.timer_lights_manual_off

input_boolean:
  manual_timer_lights:
    name: Manual Timer Lights
    icon: mdi:lamp

script:
  timer_lights_manual_on:
    sequence:
      - condition: state
        entity_id: input_boolean.timer_lights
        state: "off"
      - service: switch.turn_on
        entity_id:
          - switch.kitchen_lamp
          - switch.server_room_lamp
          - switch.office_lamps
          - switch.den_lamps
          - switch.den_table_lamp
          - switch.shack_lamp
          - switch.guest_room_lamp
          - switch.master_bedroom_lamps
      - service: light.turn_on
        entity_id:
          - light.entry_lamp
          - light.house_leds
          - light.hall_lamp
          - light.den_window_leds
      - service: input_boolean.turn_on
        entity_id: input_boolean.manual_timer_lights

  timer_lights_manual_off:
    sequence:
      - condition: state
        entity_id: input_boolean.timer_lights
        state: "off"
      - service: switch.turn_off
        entity_id:
          - switch.kitchen_lamp
          - switch.server_room_lamp
          - switch.office_lamps
          - switch.den_lamps
          - switch.den_table_lamp
          - switch.shack_lamp
          - switch.guest_room_lamp
          - switch.master_bedroom_lamps
      - service: light.turn_off
        entity_id:
          - light.entry_lamp
          - light.house_leds
          - light.hall_lamp
          - light.den_window_leds
      - service: input_boolean.turn_off
        entity_id: input_boolean.manual_timer_lights

automation:
  - alias: Manual Timer Lights On from Keypad
    id: 36b9bd72-1c15-45b1-8076-984bed02b89a
    trigger:
      - platform: state
        entity_id: switch.timer_lights
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: switch.manual_timer_lights
        state: "off"
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.manual_timer_lights

  - alias: Manual Timer Lights Off from Keypad
    id: 82f2349a-ffd1-40ab-959a-12abdde9860e
    trigger:
      - platform: state
        entity_id: switch.timer_lights
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: switch.manual_timer_lights
        state: "on"
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.manual_timer_lights

  - alias: Manual Timer Lights Keypad On
    id: 928d1653-e419-4ad8-939e-4a822c06e9e0
    trigger:
      - platform: state
        entity_id: switch.manual_timer_lights
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: switch.hall_timer_lights
        state: "off"
    action:
      - service: switch.turn_on
        entity_id: switch.hall_timer_lights

  - alias: Manual Timer Lights Keypad Off
    id: 7e7673c2-75ab-4ef5-8681-c7577a128657
    trigger:
      - platform: state
        entity_id: switch.manual_timer_lights
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: switch.hall_timer_lights
        state: "on"
    action:
      - service: switch.turn_off
        entity_id: switch.hall_timer_lights
