camera:
  - platform: mjpeg
    name: Prusa MK3
    still_image_url: !secret octoprint_still
    mjpeg_url: !secret octoprint_camera

sensor:
  - platform: template
    sensors:
      nozzle_temp_actual:
        value_template: "{{ (((states.sensor.prusa_mk3_actual_tool0_temp.state | float(none)) - 32) * 5/9) | round(1, default=none) }}"

      nozzle_temp_target:
        value_template: "{{ (((states.sensor.prusa_mk3_target_tool0_temp.state | float(none)) - 32) * 5/9) | round(1, default=none) }}"

      bed_temp_actual:
        value_template: "{{ (((states.sensor.prusa_mk3_actual_bed_temp.state | float(none)) - 32) * 5/9) | round(1, default=none) }}"

      bed_temp_target:
        value_template: "{{ (((states.sensor.prusa_mk3_target_bed_temp.state | float(none)) - 32) * 5/9) | round(1, default=none) }}"

      elapsed_print_time:
        value_template: >-
          {% set time = as_timestamp(now(),0) - as_timestamp(states('sensor.prusa_mk3_start_time'),0) %}
            {% set minutes = ((time / 60) % 60) | int(none)%}
            {% set hours = (time / 3600) | int(none) %}
              {%- if time < 60-%}
                00:00
              {%- else -%}
              {%- if hours == 0 -%}
                00
              {%- endif -%}
              {%- if hours > 0 -%}
            
                {%- if hours < 10 -%}
                  0{{ hours }}
                {%- else -%}
                  {{ hours }}
                {%- endif -%}
              {%- endif -%}
              {%- if minutes == 0 -%}
                :00
              {%- endif -%}
              {%- if minutes > 0 -%}
                {%- if minutes < 10 -%}
                  :0{{ minutes }}
                {%- else -%}
                  :{{ minutes }}
                {%- endif -%}
              {%- endif -%}
              {%- endif -%}

      remaining_print_time:
        value_template: >-
          {% set time = as_timestamp(states('sensor.prusa_mk3_estimated_finish_time'),0) - as_timestamp(now(),0) %}
            {% set minutes = ((time / 60) % 60) | int(none)%}
            {% set hours = (time / 3600) | int(none) %}
              {%- if time < 60-%}
                00:00
              {%- else -%}
              {%- if hours == 0 -%}
                00
              {%- endif -%}
              {%- if hours > 0 -%}
            
                {%- if hours < 10 -%}
                  0{{ hours }}
                {%- else -%}
                  {{ hours }}
                {%- endif -%}
              {%- endif -%}
              {%- if minutes == 0 -%}
                :00
              {%- endif -%}
              {%- if minutes > 0 -%}
                {%- if minutes < 10 -%}
                  :0{{ minutes }}
                {%- else -%}
                  :{{ minutes }}
                {%- endif -%}
              {%- endif -%}
              {%- endif -%}

      total_print_time:
        value_template: >-
          {% set time = as_timestamp(states('sensor.prusa_mk3_estimated_finish_time'),0) - as_timestamp(states('sensor.prusa_mk3_start_time'),0) %}
            {% set minutes = ((time / 60) % 60) | int(none)%}
            {% set hours = (time / 3600) | int(none) %}
              {%- if time < 60-%}
                00:00
              {%- else -%}
              {%- if hours == 0 -%}
                00
              {%- endif -%}
              {%- if hours > 0 -%}
            
                {%- if hours < 10 -%}
                  0{{ hours }}
                {%- else -%}
                  {{ hours }}
                {%- endif -%}
              {%- endif -%}
              {%- if minutes == 0 -%}
                :00
              {%- endif -%}
              {%- if minutes > 0 -%}
                {%- if minutes < 10 -%}
                  :0{{ minutes }}
                {%- else -%}
                  :{{ minutes }}
                {%- endif -%}
              {%- endif -%}
              {%- endif -%}
