sensor:
  - platform: "mqtt"
    name: "Shed Temperature OWFS"
    state_topic: "owfs/temperature/shed"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  - platform: "mqtt"
    name: "Outside Temperature OWFS"
    state_topic: "owfs/temperature/outside"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  - platform: "mqtt"
    name: "Front HVAC Return Temperature OWFS"
    state_topic: "owfs/temperature/hvac_return_front"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  - platform: "mqtt"
    name: "Back HVAC Return Temperature OWFS"
    state_topic: "owfs/temperature/hvac_return_back"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  - platform: "mqtt"
    name: "Plenum HVAC Return Temperature OWFS"
    state_topic: "owfs/temperature/hvac_return_plenum"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  - platform: "mqtt"
    name: "Dryer Vent Temperature OWFS"
    state_topic: "owfs/temperature/dryer_vent"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  - platform: "mqtt"
    name: "Office Temperature OWFS"
    state_topic: "owfs/temperature/office"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  - platform: "mqtt"
    name: "Server Room HVAC Return Temperature OWFS"
    state_topic: "owfs/temperature/hvac_return_server"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  - platform: "mqtt"
    name: "Den Temperature OWFS"
    state_topic: "owfs/temperature/den"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  - platform: "mqtt"
    name: "Master Bedroom Temperature OWFS"
    state_topic: "owfs/temperature/master_bed"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  - platform: "mqtt"
    name: "garage Temperature OWFS"
    state_topic: "owfs/temperature/garage"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  - platform: "mqtt"
    name: "Dining Room Temperature OWFS"
    state_topic: "owfs/temperature/dining"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  - platform: "mqtt"
    name: "Server Room Temperature OWFS"
    state_topic: "owfs/temperature/server_room"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  - platform: "mqtt"
    name: "HVAC Supply Temperature OWFS"
    state_topic: "owfs/temperature/hvac_supply"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  - platform: "mqtt"
    name: "Work Room Temperature OWFS"
    state_topic: "owfs/temperature/work_room"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  - platform: "mqtt"
    name: "Front Hall Temperature OWFS"
    state_topic: "owfs/temperature/hall"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  - platform: "mqtt"
    name: "Guest Bedroom Temperature OWFS"
    state_topic: "owfs/temperature/guest_bed"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  - platform: "mqtt"
    name: "Attic Temperature OWFS"
    state_topic: "owfs/temperature/attic"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value | round(1) }}"
  