sensor:
  - platform: "mqtt"
    name: "Shed Temperature OWFS"
    state_topic: "ds_secondary/sensor/shed/state"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: "Outside Temperature OWFS"
    state_topic: "ds_secondary/sensor/outside/state"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: "Front HVAC Return Temperature OWFS"
    state_topic: "ds_master/sensor/hvac_return_front/state"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: "Back HVAC Return Temperature OWFS"
    state_topic: "ds_master/sensor/hvac_return_back/state"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: "Plenum HVAC Return Temperature OWFS"
    state_topic: "ds_master/sensor/hvac_return_plenum"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: "Dryer Vent Temperature OWFS"
    state_topic: "ds_secondary/sensor/dryer_vent/state"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: "Office Temperature OWFS"
    state_topic: "ds_master/sensor/office/state"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: "Server Room HVAC Return Temperature OWFS"
    state_topic: "ds_master/sensor/hvac_return_server/state"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: "Den Temperature OWFS"
    state_topic: "ds_master/sensor/den/state"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: "Master Bedroom Temperature OWFS"
    state_topic: "ds_master/sensor/master_bedroom/state"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: "garage Temperature OWFS"
    state_topic: "ds_secondary/sensor/garage/state"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: "Dining Room Temperature OWFS"
    state_topic: "ds_master/sensor/shack/state"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: "Server Room Temperature OWFS"
    state_topic: "ds_master/sensor/server_closet/state"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: "HVAC Supply Temperature OWFS"
    state_topic: "ds_master/sensor/hvac_supply/state"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: "Work Room Temperature OWFS"
    state_topic: "ds_master/sensor/work_room/state"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: "Front Hall Temperature OWFS"
    state_topic: "ds_secondary/sensor/hall/state"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: "Guest Bedroom Temperature OWFS"
    state_topic: "ds_master/sensor/guest_room/state"
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: "mqtt"
    name: "Attic Temperature OWFS"
    state_topic: "ds_master/sensor/attic/state"
    unit_of_measurement: "°C"
    device_class: "temperature"
