switch:
  - platform: template
    switches:
      irrigation_program_3_days:
        unique_id: f727faaf-4609-4493-b0a4-6fcf4d4b7552
        friendly_name: "Irrigation Schedule Every 3 Days Enabled"
        value_template: "{{ is_state('switch.program_every_3_days_enabled', 'on') }}"
        turn_on:
          service: script.rainmachine_program_1_on
        turn_off:
          service: switch.turn_off
          entity_id: switch.program_every_3_days_enabled

      irrigation_program_2_days:
        unique_id: 57178edb-ec15-4710-9ba9-f068b06fee9c
        friendly_name: "Irrigation Schedule Every 2 Days Enabled"
        value_template: "{{ is_state('switch.program_every_2_days_enabled', 'on') }}"
        turn_on:
          service: script.rainmachine_program_2_on
        turn_off:
          service: switch.turn_off
          entity_id: switch.program_every_2_days_enabled

      irrigation_run_program:
        unique_id: 710a895d-ccf7-4ff3-81f8-9419b7e05e1d
        friendly_name: "Run Irrigation Program"
        value_template: "{{ is_state('switch.every_2_days','on') or is_state('switch.every_3_days','on') or is_state('switch.drip','on') }}"
        turn_on:
          service: script.rainmachine_start_program
        turn_off:
          service: rainmachine.stop_all
          data:
            device_id: a78593b21c1f26a5cbb20983c3f47860

binary_sensor:
  - platform: template
    sensors:
      rm_zone_1_watering:
        unique_id: 9f504bd3-982c-42ba-85d1-9368b8778fb9
        friendly_name: "Zone 1 watering"
        value_template: "{{ is_state_attr('switch.east_front','status','Running') }}"

      rm_zone_2_watering:
        unique_id: 0b576ad4-d624-403e-83ac-05791938f5e2
        friendly_name: "Zone 2 watering"
        value_template: "{{ is_state_attr('switch.east_side','status','Running') }}"

      rm_zone_3_watering:
        unique_id: 67114432-dcdd-4288-968b-7ccec19ff6f8
        friendly_name: "Zone 3 watering"
        value_template: "{{ is_state_attr('switch.back_yard','status','Running') }}"

      rm_zone_4_watering:
        unique_id: bf847de9-7fbb-4710-9eef-04ba3060e6c1
        friendly_name: "Zone 4 watering"
        value_template: "{{ is_state_attr('switch.west_side','status','Running') }}"

      rm_zone_5_watering:
        unique_id: 7f802dc2-5732-42d0-bccd-85fa21b59455
        friendly_name: "Zone 5 watering"
        value_template: "{{ is_state_attr('switch.west_front','status','Running') }}"

      rm_zone_6_watering:
        unique_id: b4bbe059-767f-49f8-93a7-ffa793ca9a2e
        friendly_name: "Zone 6 watering"
        value_template: "{{ is_state_attr('switch.back_drip','status','Running') }}"

sensor:
  - platform: template
    sensors:
      program_every_3_days_status:
        unique_id: 64b4ea4a-04f1-48d7-a57c-03a64c44a409
        friendly_name: Irrigation Schedule Every 3 Days Status
        value_template: >-
          {% if is_state('switch.program_every_3_days_enabled', 'on') and is_state('switch.every_3_days', 'off') -%}
            enabled
          {% elif  is_state('switch.program_every_3_days_enabled', 'on') and is_state('switch.every_3_days', 'on') -%}
            running
          {% else -%}
            disabled
          {% endif -%}

      program_every_2_days_status:
        unique_id: c08858de-f63b-4615-b08c-a78456079502
        friendly_name: Irrigation Schedule Every 2 Days Status
        value_template: >-
          {% if is_state('switch.program_every_2_days_enabled', 'on') and is_state('switch.every_2_days', 'off') -%}
            enabled
          {% elif  is_state('switch.program_every_2_days_enabled', 'on') and is_state('switch.every_2_days', 'on') -%}
            running
          {% else -%}
            disabled
          {% endif -%}

      program_drip_status:
        unique_id: 697a92e1-35f7-4788-a643-d6c8f43e5568
        friendly_name: Irrigation Schedule Drip Status
        value_template: >-
          {% if is_state('switch.program_drip_enabled', 'on') and is_state('switch.drip', 'off') -%}
            enabled
          {% elif  is_state('switch.program_drip_enabled', 'on') and is_state('switch.drip', 'on') -%}
            running
          {% else -%}
            disabled
          {% endif -%}

automation:
  - alias: Open Back Drip Valve
    id: ecfc4d2a-3143-4c34-8b80-b1b2487893bf
    trigger:
      - platform: state
        entity_id: binary_sensor.rm_zone_6_watering
        to: "on"
    action:
      - service: switch.turn_on
        entity_id: switch.back_drip_valve

  - alias: Close Back Drip Valve
    id: 9b88277a-3a34-4419-b2bc-e4b85c9df096
    trigger:
      - platform: state
        entity_id: binary_sensor.rm_zone_6_watering
        to: "off"
    action:
      - service: switch.turn_off
        entity_id: switch.back_drip_valve

  - alias: Back Drip Valve Failsafe
    id: a644784a-13bf-4ad3-a87f-078e100db760
    trigger:
      - platform: state
        entity_id: switch.back_drip_valve
        to: "on"
        for:
          hours: 1
    action:
      - service: switch.turn_off
        entity_id: switch.back_drip_valve

script:
  rainmachine_program_1_on:
    sequence:
      - service: switch.turn_off
        entity_id: switch.program_every_2_days_enabled
      - service: switch.turn_on
        entity_id: switch.program_every_3_days_enabled

  rainmachine_program_2_on:
    sequence:
      - service: switch.turn_off
        entity_id: switch.program_every_3_days_enabled
      - service: switch.turn_on
        entity_id: switch.program_every_2_days_enabled

  rainmachine_start_program:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: switch.irrigation_program_3_days
                state: "on"
            sequence:
              - service: switch.turn_on
                entity_id: switch.every_3_days
          - conditions:
              - condition: state
                entity_id: switch.irrigation_program_2_days
                state: "on"
            sequence:
              - service: switch.turn_on
                entity_id: switch.every_2_days
      - choose:
          - conditions:
              - condition: state
                entity_id: switch.program_drip_enabled
                state: "on"
            sequence:
              - service: switch.turn_on
                entity_id: switch.drip

  rainmachine_program_1_tap:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: switch.program_every_3_days_enabled
                state: "off"
            sequence:
              - service: switch.turn_off
                entity_id: switch.program_every_2_days_enabled
              - service: switch.turn_on
                entity_id: switch.program_every_3_days_enabled
          - conditions:
              - condition: state
                entity_id: switch.program_every_3_days_enabled
                state: "on"
            sequence:
              - service: switch.turn_off
                entity_id: switch.program_every_3_days_enabled

  rainmachine_program_2_tap:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: switch.program_every_2_days_enabled
                state: "off"
            sequence:
              - service: switch.turn_off
                entity_id: switch.program_every_3_days_enabled
              - service: switch.turn_on
                entity_id: switch.program_every_2_days_enabled
          - conditions:
              - condition: state
                entity_id: switch.program_every_2_days_enabled
                state: "on"
            sequence:
              - service: switch.turn_off
                entity_id: switch.program_every_2_days_enabled