input_text:
  work_flaps_text:
    name: Work Split Flap Text
    max: 12



automation:
  - alias: Send Clock to Den Split Flap
    id: 8f115519-6602-41dd-9f38-30b804117ba4
    trigger:
      - platform: time_pattern
        minutes: "*"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.house
            state: armed_home
          - condition: state
            entity_id: alarm_control_panel.house
            state: disarmed
    action:
      - choose:
          - conditions:
            - condition: state
              entity_id: sensor.ncaaf_tamu
              state: 'IN'
            sequence:
              - service: mqtt.publish        
                data:
                  topic: denflaps/control
                  payload: >-
                    {%- if is_state('sensor.ncaaf_tamu','IN') -%}
                      {%- if is_state_attr('sensor.ncaaf_tamu','team_homeaway','home') -%}
                        {{ state_attr('sensor.ncaaf_tamu', 'opponent_abbr') }}
                        {%- if state_attr('sensor.ncaaf_tamu','possession') == state_attr('sensor.ncaaf_tamu','opponent_id') -%}
                          {{ '.' }}
                        {%- else -%}
                          {{ ' ' }}
                        {%- endif -%}
                        {{ state_attr('sensor.ncaaf_tamu', 'opponent_score') }}{{ ' ' }}{{ state_attr('sensor.ncaaf_tamu', 'team_abbr') }}
                        {%- if state_attr('sensor.ncaaf_tamu','possession') == state_attr('sensor.ncaaf_tamu','team_id') -%}
                          {{ '.' }}
                        {%- else -%}
                          {{ ' ' }}
                        {%- endif -%} 
                        {{ state_attr('sensor.ncaaf_tamu', 'team_score') }}
                      {%- else -%}
                        {{ state_attr('sensor.ncaaf_tamu', 'team_abbr') }}
                        {%- if state_attr('sensor.ncaaf_tamu','possession') == state_attr('sensor.ncaaf_tamu','team_id') -%}
                          {{ '.' }}
                        {%- else -%}
                          {{ ' ' }}
                        {%- endif -%}  
                        {{ state_attr('sensor.ncaaf_tamu', 'team_score') }}{{ ' ' }}{{ state_attr('sensor.ncaaf_tamu', 'opponent_abbr') }}
                        {%- if state_attr('sensor.ncaaf_tamu','possession') == state_attr('sensor.ncaaf_tamu','opponent_id') -%}
                          {{ '.' }}
                        {%- else -%}
                          {{ ' ' }}
                        {%- endif -%}
                        {{ state_attr('sensor.ncaaf_tamu', 'opponent_score') }}
                      {%- endif -%}  
                      {%- if state_attr('sensor.ncaaf_tamu', 'last_play')[:9] == 'Timeout #' -%}
                        {{ ' TIMEOUT' }}
                      {%- elif is_state_attr('sensor.ncaaf_tamu','clock','Halftime') -%}
                          {{ ' HALFTIME' }}
                      {%- elif is_state_attr('sensor.ncaaf_tamu','last_play','END GAME') -%}
                          {{ ' END' }}
                      {%- else -%}
                          {{ ' ' }}{{ state_attr('sensor.ncaaf_tamu', 'clock')[:-6] }}{{' '}}{{ state_attr('sensor.ncaaf_tamu', 'clock')[-3:] }}    
                      {%- endif -%} 
                    {%- else -%}
                      {{ state_attr('sensor.ncaaf_tamu', 'kickoff_in') }}
                    {%- endif -%}
          - conditions:
            - condition: state
              entity_id: sensor.nfl_hou
              state: 'IN'
            sequence:
              - service: mqtt.publish        
                data:
                  topic: denflaps/control
                  payload: >-
                    {%- if is_state('sensor.nfl_hou','IN') -%}
                      {%- if is_state_attr('sensor.nfl_hou','team_homeaway','home') -%}
                        {{ state_attr('sensor.nfl_hou', 'opponent_abbr') }}
                        {%- if state_attr('sensor.nfl_hou','possession') == state_attr('sensor.nfl_hou','opponent_id') -%}
                          {{ '.' }}
                        {%- else -%}
                          {{ ' ' }}
                        {%- endif -%}
                        {{ state_attr('sensor.nfl_hou', 'opponent_score') }}{{ ' ' }}{{ state_attr('sensor.nfl_hou', 'team_abbr') }}
                        {%- if state_attr('sensor.nfl_hou','possession') == state_attr('sensor.nfl_hou','team_id') -%}
                          {{ '.' }}
                        {%- else -%}
                          {{ ' ' }}
                        {%- endif -%} 
                        {{ state_attr('sensor.nfl_hou', 'team_score') }}
                      {%- else -%}
                        {{ state_attr('sensor.nfl_hou', 'team_abbr') }}
                        {%- if state_attr('sensor.nfl_hou','possession') == state_attr('sensor.nfl_hou','team_id') -%}
                          {{ '.' }}
                        {%- else -%}
                          {{ ' ' }}
                        {%- endif -%}  
                        {{ state_attr('sensor.nfl_hou', 'team_score') }}{{ ' ' }}{{ state_attr('sensor.nfl_hou', 'opponent_abbr') }}
                        {%- if state_attr('sensor.nfl_hou','possession') == state_attr('sensor.nfl_hou','opponent_id') -%}
                          {{ '.' }}
                        {%- else -%}
                          {{ ' ' }}
                        {%- endif -%}
                        {{ state_attr('sensor.nfl_hou', 'opponent_score') }}
                      {%- endif -%}  
                      {%- if state_attr('sensor.nfl_hou', 'last_play')[:9] == 'Timeout #' -%}
                        {{ ' TIMEOUT' }}
                      {%- elif is_state_attr('sensor.nfl_hou','clock','Halftime') -%}
                          {{ ' HALFTIME' }}
                      {%- elif is_state_attr('sensor.nfl_hou','last_play','END GAME') -%}
                          {{ ' END' }}
                      {%- else -%}
                          {{ ' ' }}{{ state_attr('sensor.nfl_hou', 'clock')[:-6] }}{{' '}}{{ state_attr('sensor.nfl_hou', 'clock')[-3:] }}    
                      {%- endif -%} 
                    {%- else -%}
                      {{ state_attr('sensor.nfl_hou', 'kickoff_in') }}
                    {%- endif -%}
          - conditions:
            - condition: state
              entity_id: sensor.mlb_ari
              state: 'IN'
            sequence:
              - service: mqtt.publish        
                data:
                  topic: denflaps/control
                  payload: >-
                    {%- if is_state('sensor.mlb_ari','IN') -%}
                      {%- if is_state_attr('sensor.mlb_ari','team_homeaway','home') -%}
                        {{ state_attr('sensor.mlb_ari', 'opponent_abbr') }}{{ ' ' }}{{ state_attr('sensor.mlb_ari', 'opponent_score') }}{{ ' ' }}{{ state_attr('sensor.mlb_ari', 'team_abbr') }}{{ ' ' }}{{ state_attr('sensor.mlb_ari', 'team_score') }}
                      {%- else -%}
                        {{ state_attr('sensor.mlb_ari', 'team_abbr') }}{{ ' ' }}{{ state_attr('sensor.mlb_ari', 'team_score') }}{{ ' ' }}{{ state_attr('sensor.mlb_ari', 'opponent_abbr') }}{{ ' ' }}{{ state_attr('sensor.mlb_ari', 'opponent_score') }}
                      {%- endif -%}
                      {%- if is_state_attr('sensor.mlb_ari','last_play','END GAME') -%}
                          {{ ' END' }}
                      {%- elif state_attr('sensor.mlb_ari','last_play')[:1] == 'M' or state_attr('sensor.mlb_ari','last_play')[:1] == 'E' -%}
                          {{ state_attr('sensor.mlb_ari', 'clock') }}
                      {%- else -%}
                          {{ ' ' }}{{ state_attr('sensor.mlb_ari', 'clock')[:1] }}{{ state_attr('sensor.mlb_ari', 'clock')[-3:-2] }}{{' O'}}{{ state_attr('sensor.mlb_ari', 'outs') }}{{' B'}}{{ state_attr('sensor.mlb_ari', 'balls') }}{{' S'}}{{ state_attr('sensor.mlb_ari', 'strikes') }}
                      {%- endif -%} 
                    {%- else -%}
                      {{ state_attr('sensor.mlb_ari', 'kickoff_in') }}
                    {%- endif -%}
        default:
          - service: mqtt.publish        
            data:
              topic: denflaps/control
              payload: >-
                {% if now().weekday() in (0,) %} 
                  MON {{ now().month }}-{{ now().day }}-{{ now().year }} {{ now().hour }}:{% if now().minute < 10 %}0{% endif %}{{ now().minute }} {{ states('sensor.acurite_ws_temperature') | round(0,default) }}F
                {% elif now().weekday() in (1,) %} 
                  TUE {{ now().month }}-{{ now().day }}-{{ now().year }} {{ now().hour }}:{% if now().minute < 10 %}0{% endif %}{{ now().minute }} {{ states('sensor.acurite_ws_temperature') | round(0,default) }}F
                {% elif now().weekday() in (2,) %} 
                  WED {{ now().month }}-{{ now().day }}-{{ now().year }} {{ now().hour }}:{% if now().minute < 10 %}0{% endif %}{{ now().minute }} {{ states('sensor.acurite_ws_temperature') | round(0,default) }}F
                {% elif now().weekday() in (3,) %} 
                  THU {{ now().month }}-{{ now().day }}-{{ now().year }} {{ now().hour }}:{% if now().minute < 10 %}0{% endif %}{{ now().minute }} {{ states('sensor.acurite_ws_temperature') | round(0,default) }}F
                {% elif now().weekday() in (4,) %} 
                  FRI {{ now().month }}-{{ now().day }}-{{ now().year }} {{ now().hour }}:{% if now().minute < 10 %}0{% endif %}{{ now().minute }} {{ states('sensor.acurite_ws_temperature') | round(0,default) }}F
                {% elif now().weekday() in (5,) %} 
                  SAT {{ now().month }}-{{ now().day }}-{{ now().year }} {{ now().hour }}:{% if now().minute < 10 %}0{% endif %}{{ now().minute }} {{ states('sensor.acurite_ws_temperature') | round(0,default) }}F
                {% elif now().weekday() in (6,) %} 
                  SUN {{ now().month }}-{{ now().day }}-{{ now().year }} {{ now().hour }}:{% if now().minute < 10 %}0{% endif %}{{ now().minute }} {{ states('sensor.acurite_ws_temperature') | round(0,default) }}F
                {% endif %}