input_text:
  work_flaps_text:
    name: Work Split Flap Text
    max: 12

Script:
  work_flaps_send_text:
    alias: Send Manual Text to Work Split Flaps
    sequence:
      - service: mqtt.publish
        data:
          topic: flaps/work/set
          payload_template: "{{ states('input_text.work_flaps_text') }}"



automation:
  - alias: Send Clock to Den Split Flap
    id: 8f115519-6602-41dd-9f38-30b804117ba4
    trigger:
      - platform: time_pattern
        minutes: "*"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.house
            state: armed_home
          - condition: state
            entity_id: alarm_control_panel.house
            state: disarmed
    action:
      - service: mqtt.publish        
        data:
          topic: denflaps/control
          payload_template: >-
            {% if now().weekday() in (0,) %} 
              MON {{ now().month }}-{{ now().day }}-{{ now().year }} {{ now().hour }}:{% if now().minute < 10 %}0{% endif %}{{ now().minute }} {{ states('sensor.acurite_ws_temperature') | round(0,default) }}F
            {% elif now().weekday() in (1,) %} 
              TUE {{ now().month }}-{{ now().day }}-{{ now().year }} {{ now().hour }}:{% if now().minute < 10 %}0{% endif %}{{ now().minute }} {{ states('sensor.acurite_ws_temperature') | round(0,default) }}F
            {% elif now().weekday() in (2,) %} 
              WED {{ now().month }}-{{ now().day }}-{{ now().year }} {{ now().hour }}:{% if now().minute < 10 %}0{% endif %}{{ now().minute }} {{ states('sensor.acurite_ws_temperature') | round(0,default) }}F
            {% elif now().weekday() in (3,) %} 
              THU {{ now().month }}-{{ now().day }}-{{ now().year }} {{ now().hour }}:{% if now().minute < 10 %}0{% endif %}{{ now().minute }} {{ states('sensor.acurite_ws_temperature') | round(0,default) }}F
            {% elif now().weekday() in (4,) %} 
              FRI {{ now().month }}-{{ now().day }}-{{ now().year }} {{ now().hour }}:{% if now().minute < 10 %}0{% endif %}{{ now().minute }} {{ states('sensor.acurite_ws_temperature') | round(0,default) }}F
            {% elif now().weekday() in (5,) %} 
              SAT {{ now().month }}-{{ now().day }}-{{ now().year }} {{ now().hour }}:{% if now().minute < 10 %}0{% endif %}{{ now().minute }} {{ states('sensor.acurite_ws_temperature') | round(0,default) }}F
            {% elif now().weekday() in (6,) %} 
              SUN {{ now().month }}-{{ now().day }}-{{ now().year }} {{ now().hour }}:{% if now().minute < 10 %}0{% endif %}{{ now().minute }} {{ states('sensor.acurite_ws_temperature') | round(0,default) }}F
            {% endif %}