media_player:
  - platform: custom_universal
    name: Spotify
    children:
      - media_player.spotify_home
    commands:
      turn_on:
        service: script.spotify_power_on
      turn_off:
        service: script.spotify_power_off
      media_play:
        service: script.spotify_play
      media_pause:
        service: script.spotify_pause
      media_next_track:
        service: script.spotify_next
      media_previous_track:
        service: script.spotify_previous
    attributes:
      state: binary_sensor.spotify_power

input_boolean:
  nuvo_spotify_in_menu:
    name: Nuvo Spotify in menu
    initial: off

binary_sensor:
  - platform: template
    sensors:
      spotify_power:
        friendly_name: Spotify Power
        value_template: "{{not is_state('media_player.spotify_home','idle') }}"

input_select:
  spotify_playlist:
    name: Playlist
    options:
      - Top Christian Contemporary
      - Top Christian
      - Christian Mix
      - WorshipNow
      - Contemporary Christian Instrumentals on Piano
      - Easter Worship
      - The Carnival Steel Drum Band
      - Epic Film Scores for Studying
      - Harry Potter Movie Soundtracks
      - Christian Christmas
      - A Soft Piano Christmas
      - Christmas Hits
      - Hot Country
      - Country Workout

  spotify_work_alarm_playlist:
    name: Playlist
    options:
      - Top Christian Contemporary
      - Top Christian
      - Christian Mix
      - WorshipNow
      - Contemporary Christian Instrumentals on Piano
      - Easter Worship
      - The Carnival Steel Drum Band
      - Epic Film Scores for Studying
      - Harry Potter Movie Soundtracks
      - Christian Christmas
      - A Soft Piano Christmas
      - Christmas Hits
      - Hot Country
      - Country Workout

  spotify_manual_alarm_playlist:
    name: Playlist
    options:
      - Top Christian Contemporary
      - Top Christian
      - Christian Mix
      - WorshipNow
      - Contemporary Christian Instrumentals on Piano
      - Easter Worship
      - The Carnival Steel Drum Band
      - Epic Film Scores for Studying
      - Harry Potter Movie Soundtracks
      - Christian Christmas
      - A Soft Piano Christmas
      - Christmas Hits
      - Hot Country
      - Country Workout

  spotify_restore_playlist:
    name: Playlist
    options:
      - Top Christian Contemporary
      - Top Christian
      - Christian Mix
      - WorshipNow
      - Contemporary Christian Instrumentals on Piano
      - Easter Worship
      - The Carnival Steel Drum Band
      - Epic Film Scores for Studying
      - Harry Potter Movie Soundtracks
      - Christian Christmas
      - A Soft Piano Christmas
      - Christmas Hits
      - Hot Country
      - Country Workout

timer:
  spotify_refresh:
    name: Spotify Refresh
    icon: mdi:spotify

script:
  spotify_play:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: media_player.spotify_home
                state: "idle"
            sequence:
              - service: script.spotify_power_on
        default:
          - service: media_player.media_play
            entity_id: media_player.spotify_home
          - service: homeassistant.update_entity
            entity_id: media_player.spotify_home

  spotify_pause:
    sequence:
      - service: media_player.media_pause
        entity_id: media_player.spotify_home
      - service: homeassistant.update_entity
        entity_id: media_player.spotify_home

  spotify_next:
    sequence:
      - service: media_player.media_next_track
        entity_id: media_player.spotify_home
      - service: homeassistant.update_entity
        entity_id: media_player.spotify_home

  spotify_previous:
    sequence:
      - service: media_player.media_previous_track
        entity_id: media_player.spotify_home
      - service: homeassistant.update_entity
        entity_id: media_player.spotify_home

  spotify_power_on:
    sequence:
      - service: media_player.select_source
        data:
          entity_id: media_player.spotify_home
          source: "Shawn's Echo Dot"
      - service: media_player.media_play
        entity_id: media_player.spotify_home
      - service: homeassistant.update_entity
        entity_id: media_player.spotify_home

  spotify_power_off:
    sequence:
      - service: media_player.media_pause
        entity_id: media_player.spotify_home
      - service: homeassistant.update_entity
        entity_id: media_player.spotify_home

  spotify_change_playlist:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.spotify_playlist
                state: "Top Christian"
            sequence:
              - service: media_player.play_media
                data:
                  entity_id: media_player.spotify_home
                  media_content_type: playlist
                  media_content_id: spotify:playlist:37i9dQZF1DXcb6CQIjdqKy
              - service: homeassistant.update_entity
                entity_id: media_player.spotify_home
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: false
              - delay:
                  seconds: 1
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: true

          - conditions:
              - condition: state
                entity_id: input_select.spotify_playlist
                state: "Christian Mix"
            sequence:
              - service: media_player.play_media
                data:
                  entity_id: media_player.spotify_home
                  media_content_type: playlist
                  media_content_id: spotify:playlist:37i9dQZF1DX5SzTPIoCKiv
              - service: homeassistant.update_entity
                entity_id: media_player.spotify_home
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: false
              - delay:
                  seconds: 1
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: true

          - conditions:
              - condition: state
                entity_id: input_select.spotify_playlist
                state: "WorshipNow"
            sequence:
              - service: media_player.play_media
                data:
                  entity_id: media_player.spotify_home
                  media_content_type: playlist
                  media_content_id: spotify:playlist:37i9dQZF1DWVYgpMbMPJMz
              - service: homeassistant.update_entity
                entity_id: media_player.spotify_home
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: false
              - delay:
                  seconds: 1
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: true

          - conditions:
              - condition: state
                entity_id: input_select.spotify_playlist
                state: "The Carnival Steel Drum Band"
            sequence:
              - service: media_player.play_media
                data:
                  entity_id: media_player.spotify_home
                  media_content_type: playlist
                  media_content_id: spotify:playlist:2BdKasaYAwvSYviEsz214Y
              - service: homeassistant.update_entity
                entity_id: media_player.spotify_home
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: false
              - delay:
                  seconds: 1
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: true

          - conditions:
              - condition: state
                entity_id: input_select.spotify_playlist
                state: "Epic Film Scores for Studying"
            sequence:
              - service: media_player.play_media
                data:
                  entity_id: media_player.spotify_home
                  media_content_type: playlist
                  media_content_id: spotify:playlist:0fObmR6AFCrJq5atFij2hj
              - service: homeassistant.update_entity
                entity_id: media_player.spotify_home
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: false
              - delay:
                  seconds: 1
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: true

          - conditions:
              - condition: state
                entity_id: input_select.spotify_playlist
                state: "Harry Potter Movie Soundtracks"
            sequence:
              - service: media_player.play_media
                data:
                  entity_id: media_player.spotify_home
                  media_content_type: playlist
                  media_content_id: spotify:playlist:0vW1PaZHXiamxAgdRD1loI
              - service: homeassistant.update_entity
                entity_id: media_player.spotify_home
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: false
              - delay:
                  seconds: 1
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: true

          - conditions:
              - condition: state
                entity_id: input_select.spotify_playlist
                state: "Christian Christmas"
            sequence:
              - service: media_player.play_media
                data:
                  entity_id: media_player.spotify_home
                  media_content_type: playlist
                  media_content_id: spotify:playlist:37i9dQZF1DWViXqZVTGO3Z
              - service: homeassistant.update_entity
                entity_id: media_player.spotify_home
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: false
              - delay:
                  seconds: 1
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: true

          - conditions:
              - condition: state
                entity_id: input_select.spotify_playlist
                state: "A Soft Piano Christmas"
            sequence:
              - service: media_player.play_media
                data:
                  entity_id: media_player.spotify_home
                  media_content_type: playlist
                  media_content_id: spotify:playlist:7J8HlMdOq82WJAU6JmhR5d
              - service: homeassistant.update_entity
                entity_id: media_player.spotify_home
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: false
              - delay:
                  seconds: 1
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: true

          - conditions:
              - condition: state
                entity_id: input_select.spotify_playlist
                state: "Hot Country"
            sequence:
              - service: media_player.play_media
                data:
                  entity_id: media_player.spotify_home
                  media_content_type: playlist
                  media_content_id: spotify:playlist:37i9dQZF1DX1lVhptIYRda
              - service: homeassistant.update_entity
                entity_id: media_player.spotify_home
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: false
              - delay:
                  seconds: 1
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: true

          - conditions:
              - condition: state
                entity_id: input_select.spotify_playlist
                state: "Country Workout"
            sequence:
              - service: media_player.play_media
                data:
                  entity_id: media_player.spotify_home
                  media_content_type: playlist
                  media_content_id: spotify:playlist:37i9dQZF1DX5OrO2Jxuvdn
              - service: homeassistant.update_entity
                entity_id: media_player.spotify_home
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: false
              - delay:
                  seconds: 1
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: true

          - conditions:
              - condition: state
                entity_id: input_select.spotify_playlist
                state: "Christmas Hits"
            sequence:
              - service: media_player.play_media
                data:
                  entity_id: media_player.spotify_home
                  media_content_type: playlist
                  media_content_id: spotify:playlist:37i9dQZF1DX0Yxoavh5qJV
              - service: homeassistant.update_entity
                entity_id: media_player.spotify_home
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: false
              - delay:
                  seconds: 1
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: true

          - conditions:
              - condition: state
                entity_id: input_select.spotify_playlist
                state: "Contemporary Christian Instrumentals on Piano"
            sequence:
              - service: media_player.play_media
                data:
                  entity_id: media_player.spotify_home
                  media_content_type: playlist
                  media_content_id: spotify:playlist:50Yv0e9mTtNO2vJqwwNfbp
              - service: homeassistant.update_entity
                entity_id: media_player.spotify_home
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: false
              - delay:
                  seconds: 1
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: true

          - conditions:
              - condition: state
                entity_id: input_select.spotify_playlist
                state: "Top Christian Contemporary"
            sequence:
              - service: media_player.play_media
                data:
                  entity_id: media_player.spotify_home
                  media_content_type: playlist
                  media_content_id: spotify:playlist:37i9dQZF1DWUileP28ODwg
              - service: homeassistant.update_entity
                entity_id: media_player.spotify_home
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: false
              - delay:
                  seconds: 1
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: true

          - conditions:
              - condition: state
                entity_id: input_select.spotify_playlist
                state: "Easter Worship"
            sequence:
              - service: media_player.play_media
                data:
                  entity_id: media_player.spotify_home
                  media_content_type: playlist
                  media_content_id: spotify:playlist:0FXVoYcT4HfkgoTjdrd65S
              - service: homeassistant.update_entity
                entity_id: media_player.spotify_home
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: false
              - delay:
                  seconds: 1
              - service: media_player.shuffle_set
                data:
                  entity_id: media_player.spotify_home
                  shuffle: true

  spotify_restore_playlist:
    sequence:
      - condition: template
        value_template: "{{ not states('input_select.spotify_playlist') == states('input_select.spotify_restore_playlist')}}"
      - service: input_select.select_option
        data_template:
          entity_id: input_select.spotify_playlist
          option: "{{ states('input_select.spotify_restore_playlist')}}"
      - service: script.spotify_change_playlist
