rest_command:
  kitchen_tablet_on:
    url: !secret kitchen_tablet_on
  kitchen_tablet_off:
    url: !secret kitchen_tablet_off
  kitchen_tablet_reload:
    url: !secret kitchen_tablet_reload
  kitchen_tablet_restart:
    url: !secret kitchen_tablet_restart
  office_tablet_on:
    url: !secret office_tablet_on
  office_tablet_off:
    url: !secret office_tablet_off
  office_tablet_reload:
    url: !secret office_tablet_reload
  office_tablet_restart:
    url: !secret office_tablet_restart
  shack_tablet_on:
    url: !secret shack_tablet_on
  shack_tablet_off:
    url: !secret shack_tablet_off
  shack_tablet_reload:
    url: !secret shack_tablet_reload
  shack_tablet_restart:
    url: !secret shack_tablet_restart

script:
  tablets_on:
    sequence:
      - service: rest_command.kitchen_tablet_on
      - service: rest_command.office_tablet_on
      - service: rest_command.shack_tablet_on

  tablets_off:
    sequence:
      - service: rest_command.kitchen_tablet_off
      - service: rest_command.office_tablet_off
      - service: rest_command.shack_tablet_off

  tablets_reload:
    sequence:
      - service: rest_command.kitchen_tablet_reload
      - service: rest_command.office_tablet_reload
      - service: rest_command.shack_tablet_reload

  tablets_restart:
    sequence:
      - service: rest_command.kitchen_tablet_restart
      - service: rest_command.office_tablet_restart
      - service: rest_command.shack_tablet_restart

sensor: 
  - platform: rest
    name: Kitchen Tablet Status
    resource: !secret kitchen_tablet_status
    json_attributes:
      - batteryLevel
      - isPlugged 

  - platform: rest
    name: Office Tablet Status
    resource: !secret office_tablet_status
    json_attributes:
      - batteryLevel
      - isPlugged 

  - platform: rest
    name: Shack Tablet Status
    resource: !secret shack_tablet_status
    json_attributes:
      - batteryLevel
      - isPlugged

  - platform: template
    sensors:
      kitchen_tablet_battery:
        value_template: '{{ states.sensor.kitchen_tablet_status.attributes["batteryLevel"] }}'
        unit_of_measurement: "%"
      kitchen_tablet_plugged:
        value_template: '{{ states.sensor.kitchen_tablet_status.attributes["isPlugged"] }}'
      office_tablet_battery:
        value_template: '{{ states.sensor.office_tablet_status.attributes["batteryLevel"] }}'
        unit_of_measurement: "%"
      office_tablet_plugged:
        value_template: '{{ states.sensor.office_tablet_status.attributes["isPlugged"] }}'
      shack_tablet_battery:
        value_template: '{{ states.sensor.shack_tablet_status.attributes["batteryLevel"] }}'
        unit_of_measurement: "%"
      shack_tablet_plugged:
        value_template: '{{ states.sensor.shack_tablet_status.attributes["isPlugged"] }}'

switch:
  - platform: mqtt
    name: "Kitchen Tablet Charger"
    state_topic: "usb1/stat/POWER"
    command_topic: "usb1/cmnd/POWER"
    availability_topic: "usb1/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Office Tablet Charger"
    state_topic: "usb2/stat/POWER"
    command_topic: "usb2/cmnd/POWER"
    availability_topic: "usb2/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Shack Tablet Charger"
    state_topic: "usb3/stat/POWER"
    command_topic: "usb3/cmnd/POWER"
    availability_topic: "usb3/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Utility Phone Charger"
    state_topic: "usb4/stat/POWER"
    command_topic: "usb4/cmnd/POWER"
    availability_topic: "usb4/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"

automation:
  - alias: Kitchen Tablet Start Charging
    id: 10aca3b5-cd37-4844-aceb-695910d24692
    trigger:
      - platform: numeric_state
        entity_id: sensor.kitchen_tablet_battery
        below: 40
    action:
      - service: switch.turn_on
        entity_id: switch.kitchen_tablet_charger

  - alias: Kitchen Tablet Stop Charging
    id: c08d1431-445d-4b83-b972-ee6225c9d737
    trigger:
      - platform: numeric_state
        entity_id: sensor.kitchen_tablet_battery
        above: 80
    action:
      - service: switch.turn_off
        entity_id: switch.kitchen_tablet_charger

  - alias: Office Tablet Start Charging
    id: 2b05fcf6-98ef-406f-887e-f92e891f64e8
    trigger:
      - platform: numeric_state
        entity_id: sensor.office_tablet_battery
        below: 40
    action:
      - service: switch.turn_on
        entity_id: switch.office_tablet_charger

  - alias: Office Tablet Stop Charging
    id: 14c8b11c-e1b4-4f2f-a541-7c66028a0489
    trigger:
      - platform: numeric_state
        entity_id: sensor.office_tablet_battery
        above: 80
    action:
      - service: switch.turn_off
        entity_id: switch.office_tablet_charger

  - alias: Shack Tablet Start Charging
    id: 09a0b988-c547-4f6f-aef3-b0cbff488fa5
    trigger:
      - platform: numeric_state
        entity_id: sensor.shack_tablet_battery
        below: 40
    action:
      - service: switch.turn_on
        entity_id: switch.shack_tablet_charger

  - alias: Shack Tablet Stop Charging
    id: 0d7555dc-aed7-474e-963c-05692c70c731
    trigger:
      - platform: numeric_state
        entity_id: sensor.shack_tablet_battery
        above: 80
    action:
      - service: switch.turn_off
        entity_id: switch.shack_tablet_charger

  - alias: Utility Phone Start Charging
    id: 413081c8-b18e-48ed-9805-0e07f4bbfabe
    trigger:
      - platform: numeric_state
        entity_id: sensor.shawn_g5_battery_level
        below: 40
    action:
      - service: switch.turn_on
        entity_id: switch.utility_phone_charger

  - alias: Utility Phone Stop Charging
    id: 3ef6b619-a30d-4bb8-871b-e29858940836
    trigger:
      - platform: numeric_state
        entity_id: sensor.shawn_g5_battery_level
        above: 80
    action:
      - service: switch.turn_off
        entity_id: switch.utility_phone_charger