#Device Tracking
device_tracker:
  - platform: aprs
    username: !secret my_callsign
    callsigns:
      - !secret truck_callsign

sensor:
  - platform: torque
    email: ram@ram.com

  - platform: template
    sensors:
      truck_oil_life:
        unique_id: 3db01971-8b78-4259-a531-21376fe3f290
        friendly_name: Truck Oil Remaining Life
        unit_of_measurement: "%"
        value_template: "{{ (((states('input_number.truck_oil_threshold') | int(0) - states('sensor.truck_oil_distance') | int(0)) / states('input_number.truck_oil_threshold') | int(0)) * 100) | round (0, default=none)}}"

      truck_tire_life:
        unique_id: c86cb17e-6e8a-46e1-a9ba-1f24903af35f
        friendly_name: Truck Tire Rotation Remaining Life
        unit_of_measurement: "%"
        value_template: "{{ (((states('input_number.truck_tire_threshold') | int(0) - states('sensor.truck_tire_distance') | int(0)) / states('input_number.truck_tire_threshold') | int(0)) * 100) | round (0, default=none)}}"

      truck_mileage_yesterday:
        unique_id: 95f28a61-3902-42a2-8b32-962a950456a8
        friendly_name: Truck Mileage Yesterday
        unit_of_measurement: "mi"
        value_template: "{{ state_attr('sensor.truck_mileage_daily','last_period') | round (0, default=none) }}"

      truck_mileage_last_week:
        unique_id: 18727a1e-bc3b-48b8-8707-a8e5f7463324
        friendly_name: Truck Mileage Last Week
        unit_of_measurement: "mi"
        value_template: "{{ state_attr('sensor.truck_mileage_weekly','last_period') | round (0, default=none) }}"
        
      truck_mileage_last_month:
        unique_id: 03a9c94f-9fbb-47ee-a10f-74d058a273af
        friendly_name: Truck Mileage Last month
        unit_of_measurement: "mi"
        value_template: "{{ state_attr('sensor.truck_mileage_monthly','last_period') | round (0, default=none) }}"

      truck_mileage_last_year:      
        unique_id: 449c3861-4253-4028-abd5-95fe2d53e965
        friendly_name: Truck Mileage Last year
        unit_of_measurement: "mi"
        value_template: "{{ state_attr('sensor.truck_mileage_yearly','last_period') | round (0, default=none) }}"

template:
  - sensor:
      - name: Truck Fuel Level Dirty
        unique_id: 9a476a5c-c64c-46fb-8760-3303b4aff5e4
        unit_of_measurement: "%"
        state: "{{ states('sensor.vehicle_fuel_level_from_engine_ecu') | round (0, default=none) }}"

      - name: Truck Odometer
        unique_id: 0b67e40a-21b8-47f1-b71d-302da11ccd5e
        unit_of_measurement: "mi"
        state: "{{ (states('sensor.vehicle_distance_travelled_since_codes_cleared') | int(0) * 0.621371) | round (0, default=none) + states('input_number.truck_odometer_offset') | int(0)}}"

      - name: Truck Oil Distance
        unique_id: b468aa25-e458-41e4-8426-9c65990145bd
        unit_of_measurement: "mi"
        state: "{{ (states('sensor.truck_odometer_clean') | int(0) - states('input_number.truck_last_oil') | int(0)) | round (0, default=none)}}"

      - name: Truck Tire Distance
        unique_id: c21e18b3-a208-4d29-b0c5-8f251816f2af
        unit_of_measurement: "mi"
        state: "{{ (states('sensor.truck_odometer_clean') | int(0) - states('input_number.truck_last_tire') | int(0)) | round (0, default=none)}}"

      - name: Truck Trip Distance Dirty
        unique_id: d290cd5f-5a4d-4ec5-ab13-5377deef911f
        unit_of_measurement: "mi"
        state: "{{ (states('sensor.vehicle_trip_distance') | float(0) * 0.621371) | round (0, default=none) }}"

      - name: Truck Trip Cost
        unique_id: c18dcf11-5384-4b7f-adfd-e846f3690a5c
        state: "${{ states('sensor.vehicle_fuel_cost_trip') | round (2, default=none) }}"

      - name: Truck Trip MPG Dirty
        unique_id: c86921f2-5c25-4d72-959f-4320417ad8e6
        unit_of_measurement: "mpg"
        state: "{{ states('sensor.vehicle_trip_average_mpg') | round (0, default=none) }}"

      - name: Truck Trip Fuel Dirty
        unique_id: 99733930-50b5-481f-9887-85d73bdc07ec
        unit_of_measurement: "gal"
        state: "{{ (states('sensor.vehicle_fuel_used_trip') | float(0) * 0.264172) | round (1, default=none) }}"

      - name: Truck Trip DTE Dirty
        unique_id: 485c87dc-ae69-45c7-81b3-600cc2a6f507
        unit_of_measurement: "mi"
        state: "{{ states('sensor.vehicle_distance_to_empty_estimated') | round (0, default=none) }}"

      - name: Truck Odometer Clean
        unique_id: cc29c857-8a95-48e0-8057-376d335ca624
        unit_of_measurement: mi
        state: "{{ states('input_number.truck_odometer') | int(0) }}"

      - name: Truck Trip Distance
        unique_id: a29fc1b7-0817-4bbb-9292-a120f436354f
        unit_of_measurement: "mi"
        state: "{{ states('input_number.truck_trip_distance') | int(0) }}"

      - name: Truck Trip MPG
        unique_id: be88216a-6a32-4f52-aabd-5310dd55d8fe
        unit_of_measurement: "mpg"
        state: "{{ states('input_number.truck_trip_mpg') | int(0) }}"

      - name: Truck Trip Fuel
        unique_id: 60542401-e4df-4460-a0d3-0af2db96d7e2
        unit_of_measurement: "gal"
        state: "{{ states('input_number.truck_trip_fuel') | float(0) }}"

      - name: Truck Fuel Level
        unique_id: 6c172773-cf30-486e-8500-d929989f3261
        unit_of_measurement: "%"
        state: "{{ states('input_number.truck_fuel_level') | int(0) }}"

      - name: Truck Trip DTE
        unique_id: 18a18c2c-1e5e-4404-a5a9-3b6c2f863e77
        unit_of_measurement: "mi"
        state: "{{ states('input_number.truck_dte') | int(0) }}"

input_number:
  truck_last_oil:
    name: Last Oil Change Mileage
    min: 0
    max: 200000
    unit_of_measurement: mi
  truck_last_tire:
    name: Last Tire Rotation Mileage
    min: 0
    max: 200000
    unit_of_measurement: mi
  truck_oil_threshold:
    name: Oil Change Threshold
    min: 0
    max: 20000
    unit_of_measurement: mi
  truck_tire_threshold:
    name: Tire Rotation Threshold
    min: 0
    max: 20000
    unit_of_measurement: mi
  truck_odometer_offset:
    name: Truck Odometer Offset
    min: 0
    max: 200000
    unit_of_measurement: mi
  truck_odometer:
    name: Truck Odometer Total
    min: 0
    max: 250000
    unit_of_measurement: mi
  truck_trip_distance:
    name: Truck Distance Last Trip
    min: 0
    max: 10000
    unit_of_measurement: mi
  truck_trip_mpg:
    name: Truck MPG Last Trip
    min: 0
    max: 50
    unit_of_measurement: mpg
  truck_trip_fuel:
    name: Truck Fuel Last Trip
    min: 0
    max: 500
    unit_of_measurement: gal
  truck_fuel_level:
    name: Truck Fuel Level
    min: 0
    max: 100
    unit_of_measurement: "%"
  truck_dte:
    name: Truck Fuel Level
    min: 0
    max: 500
    unit_of_measurement: "mi"


input_text:
  truck_last_oil:
    name: Last Oil Change Date
  truck_last_tire:
    name: Last Tire Rotation Date

utility_meter:
  truck_mileage_daily:
    source: sensor.truck_odometer_clean
    cycle: daily

  truck_mileage_weekly:
    source: sensor.truck_odometer_clean
    cycle: weekly

  truck_mileage_monthly:
    source: sensor.truck_odometer_clean
    cycle: monthly

  truck_mileage_yearly:
    source: sensor.truck_odometer_clean
    cycle: yearly

automation:
  - alias: Update Truck Odometer
    id: 7ca37d55-8890-48f5-b9bf-7abc069e18d2
    trigger:
      - platform: state
        entity_id: sensor.truck_odometer
    condition:
      condition: numeric_state
      entity_id: sensor.truck_odometer
      above: input_number.truck_odometer
    action:
      - service: input_number.set_value
        entity_id: input_number.truck_odometer
        data_template:
          value: "{{ (states('sensor.truck_odometer') | int(0)) }}"

  - alias: Update Truck Trip Mileage
    id: 5eb69860-55fb-4762-ae18-397277538f8a
    trigger:
      - platform: state
        entity_id: sensor.truck_trip_distance_dirty
    condition:
      condition: numeric_state
      entity_id: sensor.truck_trip_distance_dirty
      above: 0
    action:
      - service: input_number.set_value
        entity_id: input_number.truck_trip_distance
        data_template:
          value: "{{ (states('sensor.truck_trip_distance_dirty') | int(0)) }}"

  - alias: Update Truck Trip Fuel Economy
    id: 13a45a50-b33f-4aef-9c72-4a04a1a6a1b4
    trigger:
      - platform: state
        entity_id: sensor.truck_trip_mpg_dirty
    condition:
      condition: numeric_state
      entity_id: sensor.truck_trip_mpg_dirty
      above: 0
    action:
      - service: input_number.set_value
        entity_id: input_number.truck_trip_mpg
        data_template:
          value: "{{ (states('sensor.truck_trip_mpg_dirty') | int(0)) }}"

  - alias: Update Truck Trip Fuel
    id: cd5b2ff2-dbb5-4b31-abaf-89def15d0f61
    trigger:
      - platform: state
        entity_id: sensor.truck_trip_fuel_dirty
    condition:
      condition: numeric_state
      entity_id: sensor.truck_trip_fuel_dirty
      above: 0
    action:
      - service: input_number.set_value
        entity_id: input_number.truck_trip_fuel
        data_template:
          value: "{{ (states('sensor.truck_trip_fuel_dirty') | float(0)) }}"

  - alias: Update Truck Fuel Level
    id: 0e5a0c80-1396-4519-9ff6-82a4555bf78b
    trigger:
      - platform: state
        entity_id: sensor.truck_fuel_level_dirty
    condition:
      condition: numeric_state
      entity_id: sensor.truck_fuel_level_dirty
      above: 0
    action:
      - service: input_number.set_value
        entity_id: input_number.truck_fuel_level
        data_template:
          value: "{{ (states('sensor.truck_fuel_level_dirty') | float(0)) }}"

  - alias: Update Truck DTE
    id: e957831d-85a1-4b68-971a-622b68130d2c
    trigger:
      - platform: state
        entity_id: sensor.truck_trip_dte_dirty
    condition:
      condition: numeric_state
      entity_id: sensor.truck_trip_dte_dirty
      above: 0
    action:
      - service: input_number.set_value
        entity_id: input_number.truck_dte
        data_template:
          value: "{{ (states('sensor.truck_trip_dte_dirty') | float(0)) }}"