#Device Tracking
device_tracker:
  - platform: aprs
    username: !secret my_callsign
    callsigns:
      - !secret truck_callsign

sensor:
  - platform: torque
    email: ram@ram.com

  - platform: template
    sensors:
      truck_oil_life:
        friendly_name: Truck Oil Remaining Life
        unit_of_measurement: "%"
        value_template: "{{ (((states('input_number.truck_oil_threshold') | int(0) - states('sensor.truck_oil_distance') | int(0)) / states('input_number.truck_oil_threshold') | int(0)) * 100) | round (0, default=none)}}"
      truck_tire_life:
        friendly_name: Truck Tire Rotation Remaining Life
        unit_of_measurement: "%"
        value_template: "{{ (((states('input_number.truck_tire_threshold') | int(0) - states('sensor.truck_tire_distance') | int(0)) / states('input_number.truck_tire_threshold') | int(0)) * 100) | round (0, default=none)}}"
      truck_mileage_yesterday:
        friendly_name: Truck Mileage Yesterday
        unit_of_measurement: "mi"
        value_template: "{{ state_attr('sensor.truck_mileage_daily','last_period') | round (0, default=none) }}"
      truck_mileage_last_week:
        friendly_name: Truck Mileage Last Week
        unit_of_measurement: "mi"
        value_template: "{{ state_attr('sensor.truck_mileage_weekly','last_period') | round (0, default=none) }}"
      truck_mileage_last_month:
        friendly_name: Truck Mileage Last month
        unit_of_measurement: "mi"
        value_template: "{{ state_attr('sensor.truck_mileage_monthly','last_period') | round (0, default=none) }}"
      truck_mileage_last_year:
        friendly_name: Truck Mileage Last year
        unit_of_measurement: "mi"
        value_template: "{{ state_attr('sensor.truck_mileage_yearly','last_period') | round (0, default=none) }}"

template:
  - sensor:
      - name: Truck Fuel Level Dirty
        unit_of_measurement: "%"
        state: "{{ states('sensor.vehicle_fuel_level_from_engine_ecu') | round (0, default=none) }}"
      - name: Truck Odometer
        unit_of_measurement: "mi"
        state: "{{ (states('sensor.vehicle_distance_travelled_since_codes_cleared') | int(0) * 0.621371) | round (0, default=none) + states('input_number.truck_odometer_offset') | int(0)}}"
      - name: Truck Oil Distance
        unit_of_measurement: "mi"
        state: "{{ (states('sensor.truck_odometer_clean') | int(0) - states('input_number.truck_last_oil') | int(0)) | round (0, default=none)}}"
      - name: Truck Tire Distance
        unit_of_measurement: "mi"
        state: "{{ (states('sensor.truck_odometer_clean') | int(0) - states('input_number.truck_last_tire') | int(0)) | round (0, default=none)}}"
      - name: Truck Trip Distance Dirty
        unit_of_measurement: "mi"
        state: "{{ (states('sensor.vehicle_trip_distance') | float(0) * 0.621371) | round (0, default=none) }}"
      - name: Truck Trip Cost
        state: "${{ states('sensor.vehicle_fuel_cost_trip') | round (2, default=none) }}"
      - name: Truck Trip MPG Dirty
        unit_of_measurement: "mpg"
        state: "{{ states('sensor.vehicle_trip_average_mpg') | round (0, default=none) }}"
      - name: Truck Trip Fuel Dirty
        unit_of_measurement: "gal"
        state: "{{ (states('sensor.vehicle_fuel_used_trip') | float(0) * 0.264172) | round (1, default=none) }}"
      - name: Truck Trip DTE Dirty
        unit_of_measurement: "mi"
        state: "{{ states('sensor.vehicle_distance_to_empty_estimated') | round (0, default=none) }}"
      - name: Truck Odometer Clean
        unit_of_measurement: mi
        state: "{{ states('input_number.truck_odometer') | int(0) }}"
      - name: Truck Trip Distance
        unit_of_measurement: "mi"
        state: "{{ states('input_number.truck_trip_distance') | int(0) }}"
      - name: Truck Trip MPG
        unit_of_measurement: "mpg"
        state: "{{ states('input_number.truck_trip_mpg') | int(0) }}"
      - name: Truck Trip Fuel
        unit_of_measurement: "gal"
        state: "{{ states('input_number.truck_trip_fuel') | float(0) }}"
      - name: Truck Fuel Level
        unit_of_measurement: "%"
        state: "{{ states('input_number.truck_fuel_level') | int(0) }}"
      - name: Truck Trip DTE
        unit_of_measurement: "mi"
        state: "{{ states('input_number.truck_dte') | int(0) }}"

input_number:
  truck_last_oil:
    name: Last Oil Change Mileage
    min: 0
    max: 200000
    unit_of_measurement: mi
  truck_last_tire:
    name: Last Tire Rotation Mileage
    min: 0
    max: 200000
    unit_of_measurement: mi
  truck_oil_threshold:
    name: Oil Change Threshold
    min: 0
    max: 20000
    unit_of_measurement: mi
  truck_tire_threshold:
    name: Tire Rotation Threshold
    min: 0
    max: 20000
    unit_of_measurement: mi
  truck_odometer_offset:
    name: Truck Odometer Offset
    min: 0
    max: 200000
    unit_of_measurement: mi
  truck_odometer:
    name: Truck Odometer Total
    min: 0
    max: 250000
    unit_of_measurement: mi
  truck_trip_distance:
    name: Truck Distance Last Trip
    min: 0
    max: 10000
    unit_of_measurement: mi
  truck_trip_mpg:
    name: Truck MPG Last Trip
    min: 0
    max: 50
    unit_of_measurement: mpg
  truck_trip_fuel:
    name: Truck Fuel Last Trip
    min: 0
    max: 500
    unit_of_measurement: gal
  truck_fuel_level:
    name: Truck Fuel Level
    min: 0
    max: 100
    unit_of_measurement: "%"
  truck_dte:
    name: Truck Fuel Level
    min: 0
    max: 500
    unit_of_measurement: "mi"


input_text:
  truck_last_oil:
    name: Last Oil Change Date
  truck_last_tire:
    name: Last Tire Rotation Date

utility_meter:
  truck_mileage_daily:
    source: sensor.truck_odometer_clean
    cycle: daily

  truck_mileage_weekly:
    source: sensor.truck_odometer_clean
    cycle: weekly

  truck_mileage_monthly:
    source: sensor.truck_odometer_clean
    cycle: monthly

  truck_mileage_yearly:
    source: sensor.truck_odometer_clean
    cycle: yearly

automation:
  - alias: Update Truck Odometer
    id: 7ca37d55-8890-48f5-b9bf-7abc069e18d2
    trigger:
      - platform: state
        entity_id: sensor.truck_odometer
    condition:
      condition: numeric_state
      entity_id: sensor.truck_odometer
      above: input_number.truck_odometer
    action:
      - service: input_number.set_value
        entity_id: input_number.truck_odometer
        data_template:
          value: "{{ (states('sensor.truck_odometer') | int(0)) }}"

  - alias: Update Truck Trip Mileage
    id: 5eb69860-55fb-4762-ae18-397277538f8a
    trigger:
      - platform: state
        entity_id: sensor.truck_trip_distance_dirty
    condition:
      condition: numeric_state
      entity_id: sensor.truck_trip_distance_dirty
      above: 0
    action:
      - service: input_number.set_value
        entity_id: input_number.truck_trip_distance
        data_template:
          value: "{{ (states('sensor.truck_trip_distance_dirty') | int(0)) }}"

  - alias: Update Truck Trip Fuel Economy
    id: 13a45a50-b33f-4aef-9c72-4a04a1a6a1b4
    trigger:
      - platform: state
        entity_id: sensor.truck_trip_mpg_dirty
    condition:
      condition: numeric_state
      entity_id: sensor.truck_trip_mpg_dirty
      above: 0
    action:
      - service: input_number.set_value
        entity_id: input_number.truck_trip_mpg
        data_template:
          value: "{{ (states('sensor.truck_trip_mpg_dirty') | int(0)) }}"

  - alias: Update Truck Trip Fuel
    id: cd5b2ff2-dbb5-4b31-abaf-89def15d0f61
    trigger:
      - platform: state
        entity_id: sensor.truck_trip_fuel_dirty
    condition:
      condition: numeric_state
      entity_id: sensor.truck_trip_fuel_dirty
      above: 0
    action:
      - service: input_number.set_value
        entity_id: input_number.truck_trip_fuel
        data_template:
          value: "{{ (states('sensor.truck_trip_fuel_dirty') | float(0)) }}"

  - alias: Update Truck Fuel Level
    id: 0e5a0c80-1396-4519-9ff6-82a4555bf78b
    trigger:
      - platform: state
        entity_id: sensor.truck_fuel_level_dirty
    condition:
      condition: numeric_state
      entity_id: sensor.truck_fuel_level_dirty
      above: 0
    action:
      - service: input_number.set_value
        entity_id: input_number.truck_fuel_level
        data_template:
          value: "{{ (states('sensor.truck_fuel_level_dirty') | float(0)) }}"

  - alias: Update Truck DTE
    id: e957831d-85a1-4b68-971a-622b68130d2c
    trigger:
      - platform: state
        entity_id: sensor.truck_trip_dte_dirty
    condition:
      condition: numeric_state
      entity_id: sensor.truck_trip_dte_dirty
      above: 0
    action:
      - service: input_number.set_value
        entity_id: input_number.truck_dte
        data_template:
          value: "{{ (states('sensor.truck_trip_dte_dirty') | float(0)) }}"