input_boolean:

  vacation_mode:
    name: Vacation Mode
    icon: mdi:airplane

sensor:
  - platform: history_stats
    name: Replay Back Porch Light
    entity_id: switch.back_porch_light
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

  - platform: history_stats
    name: Replay Office Light
    entity_id: light.office_light
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

  - platform: history_stats
    name: Replay Server Room Light
    entity_id: light.server_room_light
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

  - platform: history_stats
    name: Replay Hall Light
    entity_id: light.hallway_light
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

  - platform: history_stats
    name: Replay Kitchen Light
    entity_id: light.kitchen_light
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

  - platform: history_stats
    name: Replay Kitchen Sink Light
    entity_id: light.kitchen_sink_light
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

  - platform: history_stats
    name: Replay Dining Room Light
    entity_id: light.dining_room_light
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

  - platform: history_stats
    name: Replay Guest Bathroom Light
    entity_id: light.guest_bathroom_light
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

  - platform: history_stats
    name: Replay Entry Light
    entity_id: light.entry_light
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

  - platform: history_stats
    name: Replay Foyer Light
    entity_id: light.foyer_light
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

  - platform: history_stats
    name: Replay Den Light
    entity_id: light.den_light
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

  - platform: history_stats
    name: Replay Master Bedroom Light
    entity_id: light.master_bedroom_light
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

  - platform: history_stats
    name: Replay Shack Light
    entity_id: switch.shack_light
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

  - platform: history_stats
    name: Replay Guest Bedroom Light
    entity_id: light.guest_bedroom_light
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

  - platform: history_stats
    name: Replay Master Sink Light
    entity_id: switch.master_bathroom_lights
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

  - platform: history_stats
    name: Replay Master Shower Light
    entity_id: light.master_shower_light
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

  - platform: history_stats
    name: Replay Master Toilet Light
    entity_id: light.master_toilet_light
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

  - platform: history_stats
    name: Replay Timer Lamps
    entity_id: input_boolean.timer_lights
    state: 'on'
    type: count
    start: >
      {{ as_timestamp(now()) - (7*86400) }}
    duration: 00:00:30

automation:
  - alias: Vacation Replay Lights Off in Morning
    trigger:
      - platform: state
        entity_id: input_boolean.outside_timer_lights
        from: 'on'
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'on'
    action:
      - service: light.turn_off
        entity_id:
          - light.den_light
          - light.dining_room_light
          - light.entry_light
          - light.foyer_light
          - light.guest_bathroom_light
          - light.guest_bedroom_light
          - light.hallway_light
          - light.kitchen_light
          - light.kitchen_sink_light
          - light.master_bedroom_light
          - light.master_shower_light
          - light.master_toilet_light
          - light.office_light
          - light.server_room_light
      - service: switch.turn_off
        entity_id:
          - switch.back_porch_light
          - switch.master_bathroom_lights
          - switch.shack_light