input_boolean:
  vacation_mode:
    name: Vacation Mode
    icon: mdi:airplane
  timer_lights_trigger:
    name: Timer Light trigger
    icon: mdi:timer-alert

automation:

  - alias: Vacation Mode On
    id: 196cf690-72dd-4494-bfbf-64027e27e44f
    trigger:
      - platform: template
        value_template: "{{ is_state_attr('alarm_control_panel.house', 'armed_status', 'armed_to_vacation') }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.vacation_mode
      - service: button.press
        entity_id: button.docker_vm_frigate_away

  - alias: Vacation Mode Off
    id: cf1edc36-5820-4cf3-8c4f-7db5ffb55245
    trigger:
      - platform: state
        entity_id: input_boolean.hvac_geofence
        to: "on"
      - platform: state
        entity_id: device_tracker.shawn_n30
        to: "home"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.vacation_mode
      - service: switch.turn_off
        entity_id:
          - switch.presence_simulation
      - service: button.press
        entity_id: button.docker_vm_frigate_home

  - alias: Notify Alarm Disarmed
    id: 47c99c56-602a-4695-9219-f8ecc9c3f0aa
    trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      to: disarmed
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.house
            attribute: changed_by
            state: "Sayaka"
          - condition: state
            entity_id: alarm_control_panel.house
            attribute: changed_by
            state: "Gary"
    action:
      service: notify.mobile_app_shawn_n30
      data:
        title: Alarm Disarmed
        message: The alarm has been disarmed.

  - alias: Notify Alarm Armed in Vacation Mode
    id: 426c952b-9cfd-48d7-9dc7-eb95c2de7c20
    trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      from: arming
      to: armed_vacation
    action:
      service: notify.mobile_app_shawn_n30
      data:
        title: Alarm Armed
        message: The alarm has been armed.

  - alias: Vacation Notification Heartbeat
    id: 8a4f83b8-1b3f-4757-80e4-c0fecdf6d433
    trigger:
    - platform: time
      at: "08:00:00"
    - platform: time
      at: "20:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
    action:
      service: notify.mobile_app_shawn_n30
      data:
        title: Notification Test
        message: Notification test -  {{now().strftime('%Y-%m-%d %H:%M:%S') }}

  - alias: Vacation Replay Lights Off in Morning
    id: 8757403b-1145-471c-be4d-bc48a9bbb12d
    trigger:
      - platform: state
        entity_id: input_boolean.outside_timer_lights
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
    action:
      - service: switch.turn_off
        entity_id:
          - switch.presence_simulation
      - service: light.turn_off
        continue_on_error: true
        entity_id:
          - light.den_light
          - light.dining_room_light
          - light.entry_light
          - light.foyer_light
          - light.guest_bathroom_light
          - light.guest_bedroom_light
          - light.hallway_light
          - light.kitchen_light
          - light.kitchen_sink_light
          - light.master_bedroom_light
          - light.master_shower_light
          - light.master_toilet_light
          - light.office_light
          - light.server_room_light
      - service: switch.turn_off
        continue_on_error: true
        entity_id:
          - switch.back_porch_light
          - switch.master_bathroom_lights
          - switch.shack_light
      - service: script.turn_on
        entity_id: script.timer_lights_off

  - alias: Enable presence Simulation at Night
    id: fd7e5115-06c6-416a-aa08-0de1ad988b22
    trigger:
      - platform: state
        entity_id: input_boolean.outside_timer_lights
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
    action:
      - service: switch.turn_on
        entity_id:
          - switch.presence_simulation

  - alias: Trigger Timer Light Shutdown
    id: 41bd9105-e59a-4f8e-81b6-807a7d786f2e
    trigger:
      - platform: state
        entity_id: input_boolean.timer_lights_trigger
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
    action:
      - service: script.turn_on
        entity_id: script.timer_lights_off

script:
  timer_lights_off:
    sequence:
      - service: switch.turn_off
        continue_on_error: true
        entity_id:
          - switch.kitchen_lamp
          - switch.server_room_lamp
          - switch.office_lamps
          - switch.den_lamps
          - switch.shack_lamp
          - switch.guest_room_lamp
          - switch.master_bedroom_lamps
      - service: light.turn_off
        continue_on_error: true
        entity_id:
          - light.entry_lamp
          - light.house_leds
          - light.hall_lamp
          - light.den_window_leds
      - service: input_boolean.turn_off
        entity_id:
          - input_boolean.timer_lights
          - input_boolean.manual_timer_lights
          - input_boolean.timer_lights_trigger