wake_on_lan:

switch:
  - platform: wake_on_lan
    name: Office PC
    mac: !secret office_pc_mac
    host: !secret office_pc_ip
    turn_off:
      service: button.press
      entity_id: button.shawn_desktop_hibernate

automation:
  - alias: Office PC on With Desk
    id: 8afcbc9d-ce6f-4629-8f50-aa74333d277c
    trigger:
      - platform: state
        entity_id: switch.office_desk
        from: "off"
        to: "on"
    action:
      - service: switch.turn_on
        entity_id: switch.office_pc

  - alias: Office PC off With Desk
    id: ec21334c-e550-4710-98fe-22bcaccbf608
    trigger:
      - platform: state
        entity_id: switch.office_desk
        from: "on"
        to: "off"
    action:
      - service: switch.turn_off
        entity_id: switch.office_pc