sensor:
  - platform: template
    sensors:
      water_heater_status:
        unique_id: 27a058f0-d528-4fc7-b58d-d92d90c8b96c
        friendly_name: "Water Heater Status"
        value_template: >-
          {% if states('sensor.thermopile_voltage') | float(none) > 0.13-%} 
            Idle
          {% elif states('sensor.thermopile_voltage') | float(none) > 0.10-%}
            Heating
          {% elif  states('sensor.thermopile_voltage') | float(none) < 0.10-%}
            Pilot Fail
          {% else -%}
            Error
          {% endif -%}
  - platform: history_stats
    name: Water Heater Runtime
    entity_id: sensor.water_heater_status
    state: "Heating"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

alert:
  water_heater_pilot_fail:
    name: Water Heater Fault
    entity_id: sensor.water_heater_status
    state: "Pilot Fail"
    repeat: 360
    can_acknowledge: true
    skip_first: false
    title: "Water Heater Fault"
    message: "The water heater pilot light has failed."
    done_message: "The water heater pilot light has been re-lit."
    notifiers:
      - mobile_app_shawn_7t

automation:
  - alias: Water Heater Pilot Alert
    id: dd2bc8e5-2cba-44cd-952d-8fda01e93ba9
    trigger:
      - platform: state
        entity_id: sensor.water_heater_status
        to: "Pilot Fail"
    action:
      - service: persistent_notification.create
        data:
          title: Water Heater Fault!
          message: The water heater pilot light has failed.