sensor:
- platform: waze_travel_time
  name: "Shawn to Home"
  origin: sensor.shawn_position
  destination: zone.home
  region: 'US'
- platform: waze_travel_time
  name: "Shawn to Work"
  origin: sensor.shawn_position
  destination: zone.work
  region: 'US'
- platform: template
  sensors:
    shawn_position:
      friendly_name: 'Shawn Positioin'
      value_template: "{{ state_attr('device_tracker.shawn_n6', 'latitude') }}, {{ state_attr('device_tracker.shawn_n6', 'longitude') }}"