sensor:
  - platform: template
    sensors:
      shawn_position:
        friendly_name: "Shawn Positioin"
        value_template: "{{ state_attr('device_tracker.shawn_n6', 'latitude') }}, {{ state_attr('device_tracker.shawn_n6', 'longitude') }}"
