sensor:
  - platform: "mqtt"
    name: "Aquara Server Closet Temperature"
    state_topic: "zigbee2mqtt/aquara_env_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value_json.temperature }}"
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/aquara_env_1"
    name: "Aquara Server Closet Humidity"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "humidity"
    value_template: "{{ value_json.humidity }}"
  - platform: "mqtt"
    name: "Aquara Server Closet Pressure"
    state_topic: "zigbee2mqtt/aquara_env_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "hPa"
    device_class: "pressure"
    value_template: "{{ value_json.pressure }}"
  - platform: "mqtt"
    name: "Aquara Server Closet Battery"
    state_topic: "zigbee2mqtt/aquara_env_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
  - platform: "mqtt"
    name: "Aquara Server Closet Link Quality"
    state_topic: "zigbee2mqtt/aquara_env_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"
  - platform: "mqtt"
    name: "Aquara Outside Temperature"
    state_topic: "zigbee2mqtt/aquara_env_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value_json.temperature }}"
  - platform: "mqtt"
    name: "Aquara Outside Humidity"
    state_topic: "zigbee2mqtt/aquara_env_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "humidity"
    value_template: "{{ value_json.humidity }}"
  - platform: "mqtt"
    name: "Aquara Outside Pressure"
    state_topic: "zigbee2mqtt/aquara_env_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "hPa"
    device_class: "pressure"
    value_template: "{{ value_json.pressure }}"
  - platform: "mqtt"
    name: "Aquara Outside Battery"
    state_topic: "zigbee2mqtt/aquara_env_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
  - platform: "mqtt"
    name: "Aquara Outside Link Quality"
    state_topic: "zigbee2mqtt/aquara_env_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"
  - platform: "mqtt"
    name: "Aquara Office Temperature"
    state_topic: "zigbee2mqtt/aquara_env_3"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value_json.temperature }}"
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/aquara_env_3"
    name: "Aquara Office Humidity"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "humidity"
    value_template: "{{ value_json.humidity }}"
  - platform: "mqtt"
    name: "Aquara Office Pressure"
    state_topic: "zigbee2mqtt/aquara_env_3"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "hPa"
    device_class: "pressure"
    value_template: "{{ value_json.pressure }}"
  - platform: "mqtt"
    name: "Aquara Office Battery"
    state_topic: "zigbee2mqtt/aquara_env_3"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
  - platform: "mqtt"
    name: "Aquara Office Link Quality"
    state_topic: "zigbee2mqtt/aquara_env_3"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"
  - platform: "mqtt"
    name: "Aquara Den Temperature"
    state_topic: "zigbee2mqtt/aquara_env_4"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value_json.temperature }}"
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/aquara_env_4"
    name: "Aquara Den Humidity"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "humidity"
    value_template: "{{ value_json.humidity }}"
  - platform: "mqtt"
    name: "Aquara Den Pressure"
    state_topic: "zigbee2mqtt/aquara_env_4"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "hPa"
    device_class: "pressure"
    value_template: "{{ value_json.pressure }}"
  - platform: "mqtt"
    name: "Aquara Den Battery"
    state_topic: "zigbee2mqtt/aquara_env_4"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
  - platform: "mqtt"
    name: "Aquara Den Link Quality"
    state_topic: "zigbee2mqtt/aquara_env_4"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"
  - platform: "mqtt"
    name: "Aquara Master Bedroom Temperature"
    state_topic: "zigbee2mqtt/aquara_env_5"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value_json.temperature }}"
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/aquara_env_5"
    name: "Aquara Master Bedroom Humidity"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "humidity"
    value_template: "{{ value_json.humidity }}"
  - platform: "mqtt"
    name: "Aquara Master Bedroom Pressure"
    state_topic: "zigbee2mqtt/aquara_env_5"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "hPa"
    device_class: "pressure"
    value_template: "{{ value_json.pressure }}"
  - platform: "mqtt"
    name: "Aquara Master Bedroom Battery"
    state_topic: "zigbee2mqtt/aquara_env_5"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
  - platform: "mqtt"
    name: "Aquara Master Bedroom Link Quality"
    state_topic: "zigbee2mqtt/aquara_env_5"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"
  - platform: "mqtt"
    name: "Button 1 Press"
    state_topic: "zigbee2mqtt/snooze_button_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:toggle-switch"
    value_template: "{{ value_json.click }}"
  - platform: "mqtt"
    name: "Button 1 Battery"
    state_topic: "zigbee2mqtt/snooze_button_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
  - platform: "mqtt"
    name: "Button 1 link Quality"
    state_topic: "zigbee2mqtt/snooze_button_1"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"
  - platform: "mqtt"
    name: "Button 2 Press"
    state_topic: "zigbee2mqtt/snooze_button_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    icon: "mdi:toggle-switch"
    value_template: "{{ value_json.click }}"
  - platform: "mqtt"
    name: "Button 2 Battery"
    state_topic: "zigbee2mqtt/snooze_button_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
  - platform: "mqtt"
    name: "Button 2 link Quality"
    state_topic: "zigbee2mqtt/snooze_button_2"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"