input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600 # Updated this to the number of seconds you wish

mqtt:
  sensor:
    - name: Bridge state
      state_topic: "zigbee2mqtt/bridge/state"
      icon: mdi:router-wireless

automation:
  - id: enable_zigbee_join
    alias: Enable Zigbee joining
    trigger:
      - platform: state
        entity_id: input_boolean.zigbee_permit_join
        to: "on"
    action:
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/bridge/config/permit_join
          payload: "true"
      - service: timer.start
        entity_id: timer.zigbee_permit_join

  - id: disable_zigbee_join
    alias: Disable Zigbee joining
    trigger:
      - platform: state
        entity_id: input_boolean.zigbee_permit_join
        to: "off"
    action:
      - service: mqtt.publish
        data:
          payload: "false"
          topic: zigbee2mqtt/bridge/config/permit_join
      - service: timer.cancel
        entity_id: timer.zigbee_permit_join

  - id: disable_zigbee_join_timer
    alias: Disable Zigbee joining by timer
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.zigbee_permit_join
    action:
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/bridge/config/permit_join
          payload: "false"
      - service: input_boolean.turn_off
        entity_id: input_boolean.zigbee_permit_join
