- alias: Entry Lamp On from Keypad
  id: 83b0f4f4-d8cb-467f-9ce8-012584d4c015
  trigger:
    - platform: state
      entity_id: switch.entry_lamp
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: light.entry_lamp
      state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.entry_lamp
        brightness: 128

- alias: Entry Lamp Off from Keypad
  id: f2b1cb87-6f2c-4253-9eb1-07d88657012b
  trigger:
    - platform: state
      entity_id: switch.entry_lamp
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: light.entry_lamp
      state: "on"
  action:
    - service: light.turn_off
      entity_id: light.entry_lamp

- alias: Entry Lamp Keypad On
  id: 7e1a0bec-ff77-4c61-a572-6f23b35d2fd9
  trigger:
    - platform: state
      entity_id: light.entry_lamp
      to: "on"
  condition:
    - condition: state
      entity_id: switch.entry_lamp
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.entry_lamp

- alias: Entry Lamp Keypad Off
  id: da59e9b1-ef47-43cb-8577-6c26254ac01c
  trigger:
    - platform: state
      entity_id: light.entry_lamp
      to: "off"
  condition:
    - condition: state
      entity_id: switch.entry_lamp
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.entry_lamp
