- alias: Office Desk Light On from Keypad
  id: 9b58716a-3c08-4e2a-be7a-2e8cd205a7f5
  trigger:
    - platform: state
      entity_id: switch.office_desk_light
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: light.office_desk_light
      state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.office_desk_light

- alias: Office Desk Light Off from Keypad
  id: 6acb799f-596c-439b-8f78-7882d8bec786
  trigger:
    - platform: state
      entity_id: switch.office_desk_light
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: light.office_desk_light
      state: "on"
  action:
    - service: light.turn_off
      entity_id: light.office_desk_light

- alias: Office Desk Light Keypad On
  id: af503ac8-ddba-490b-8de9-684a1077532e
  trigger:
    - platform: state
      entity_id: light.office_desk_light
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: switch.office_desk_light
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.office_desk_light

- alias: Office Desk Light Keypad Off
  id: 82504963-eaf4-4f74-a5d2-c0dc877559e4
  trigger:
    - platform: state
      entity_id: light.office_desk_light
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: switch.office_desk_light
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.office_desk_light
