- alias: Office Desk Light On from Keypad
  trigger:
    - platform: state
      entity_id: switch.office_desk_light
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: light.office_desk_light
      state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.office_desk_light

- alias: Office Desk Light Off from Keypad
  trigger:
    - platform: state
      entity_id: switch.office_desk_light
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: light.office_desk_light
      state: "on"
  action:
    - service: light.turn_off
      entity_id: light.office_desk_light

- alias: Office Desk Light Keypad On
  trigger:
    - platform: state
      entity_id: light.office_desk_light
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: switch.office_desk_light
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.office_desk_light

- alias: Office Desk Light Keypad Off
  trigger:
    - platform: state
      entity_id: light.office_desk_light
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: switch.office_desk_light
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.office_desk_light
