- alias: Shack Desk Light On from Keypad
  id: f65af43a-d090-4652-bf31-9749aab8c1cc
  trigger:
    - platform: state
      entity_id: switch.shack_desk_light
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: light.shack_desk_light
      state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.shack_desk_light

- alias: Shack Desk Light Off from Keypad
  id: a595df5c-0bd7-4bbf-9974-ccaf99c6bbfc
  trigger:
    - platform: state
      entity_id: switch.shack_desk_light
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: light.shack_desk_light
      state: "on"
  action:
    - service: light.turn_off
      entity_id: light.shack_desk_light

- alias: Shack Desk Light Keypad On
  id: 16c1d619-6b7e-4f07-9a68-f1030343b07b
  trigger:
    - platform: state
      entity_id: light.shack_desk_light
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: switch.shack_desk_light
      state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.shack_desk_light

- alias: Shack Desk Light Keypad Off
  id: 96636f12-49b5-4a22-ad87-c0f409aaa485
  trigger:
    - platform: state
      entity_id: light.shack_desk_light
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: switch.shack_desk_light
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.shack_desk_light
